### ISSUE TITLE
Banner in wrong position after Rewarded Video watched

### ISSUE THREAD

**Issue by rotter** [googleads/googleads-mobile-unity#646] opened 2018-04-02 20:31 UTC
If I have a banner showing on the bottom of the screen, then start a rewarded video with the device correctly oriented (portrait), then during the beginning of the video I rotate the device so it's upside-down and then cancel the video (to avoid the reward), once the video closes the banner is on the wrong side of the screen. I always load banners as "bottom" and when I do this they show up at the top after the video, and never returns to the correct position (only if I close/reopen the app).

It seems to happen also if I start the video while already upside down, but not always it seems. In both scenarios this problem happens either every time or almost every time, so it's pretty easy to reproduce.

My app doesnt allow rotation, so turning the device upside down has no effect at all on the screen (the app doesnt turn, nor does the rewarded video), only the banner changes its position after closing the video.

Im testing on a Nexus 4, so I dont think this is device specific.

**Comment by rotter** [comment] 2018-04-03 15:08
This seems like a bizarre situation that would never happen "naturally", but the first time it occurred to me it was indeed naturally. I was testing the rewarded video with the device on a flat table but the device was slightly angled due to a cable passing below it, and then after the video the banner was on top of the screen. It took me some 30 minutes to figure out the reason was the rotation (since my app has rotation locked it didnt occur to me quickly).

**Comment by rampara** [comment] 2018-04-04 18:49
@rotter can't seem to reproduce this on my end. Steps I followed:

1. Request and display smart banner at bottom of screen
2. Request and show rewarded video.
3. Rotate phone 180 degrees
4. Close rewarded video before reward is granted.

At this phone the entire UI is upside down, but the banner is still rendered correctly at the bottom.

**Comment by rotter** [comment] 2018-04-04 18:52
@rampara try to disable "auto rotation" on the app. On my app the rotation is fully locked on "portrait".

Build Settings window -> Android -> Player Settings -> Resolution and Presentation -> Default Orientation = Portrait

**Comment by rotter** [comment] 2018-04-04 18:53
btw, I've had this issue happen with Interstitial as well today, so I believe this issue is not only reward-video related, but anything full-screen.

**Comment by rampara** [comment] 2018-04-04 19:02
@rotter do you have rotation disabled in-app but enabled on a OS level?

**Comment by rampara** [comment] 2018-04-05 00:05
@rotter still unable to repro this on my end. Does your video rotate?

**Comment by rotter** [comment] 2018-04-05 00:35
@rampara I just tried on a different device (a Samsung tablet), and the behavior is different, so let me make the distinction:

1) Nexus 4 phone, OS rotation is enabled. I have the game with a banner on the bottom and the phone on regular portrait orientation (not upside down), I start the rewarded video (or interstitial), turn the phone upside down, the video stays upside down, I close the video, the game screen shows upside down with the banner on the top of the screen. After I rotate back to the original portrait orientation the banner stays on the top.

2) Samsung tablet, OS rotation enabled. I have the game with a banner on the bottom and the tablet on regular portrait orientation (not upside down), I start the rewarded video (or interstitial), turn the phone upside down, the video ROTATES so that it is NOT UPSIDE DOWN to me, I close the video, the game screen quickly animates back to upside down, and the banner is on the correct position (bottom of the screen).

It happens with my game in production if you want to try, I just tried now and it happened on the first try on both devices.

**Comment by fzdravko** [comment] 2018-04-08 20:38
I have this problem too. It happens when I load Rewarded Video and then cancel it, banner ad change position from bottom to top. I have multiple devices and this happens only on one - Motorola Moto G (XT1032) - Android v5.1.

**Comment by rotter** [comment] 2018-04-10 13:36
@rampara @fzdravko I forgot to check Android version on my case (Nexus 4), and it is the same exact API version (Android 5.1.1 in fact), so that may be the culprit.

**Comment by rotter** [comment] 2018-04-12 13:58
@rampara I have just got an email from a player complaining about this same problem. His Android is 5.0.2 and the banner moves to the top of the screen after an interstitial ad:

"My version of Android is 5.02.  And yes, the banner moves to the top right after closing a full-screen ad."

**Comment by rampara** [comment] 2018-04-12 21:50
@rotter was finally able to reproduce the issue on my end. Putting together a workaround that should be pushed out shortly.

**Comment by rampara** [comment] 2018-04-12 22:09
Closing as duplicate of #629.

**Closed by rampara** 2018-04-12 22:09 UTC
Labels: P2, support question

**Comment by rampara** [comment] 2018-04-18 22:25
@rotter have you tried to reproduce the issue on the latest version of the plugin (v3.13.1) ?

**Comment by rotter** [comment] 2018-04-18 22:37
Im on vacation this week, I have no access to any devices, sorry. I will test it next Monday.

**Comment by rotter** [comment] 2018-04-23 19:27
I have just tried and on the first 2 rewarded videos the banner was OK (bottom), then after the 3rd rewarded video the banner moved to the top.

Some comments:
- I didnt update the AdMob SDK bundled on the game, I was expecting that the update would already be on the device due to the automatic updates on Google modules, if I should have downloaded the newest SDK let me know and I will re-test
- But I dont know which version of the AdMob SDK is running on the device, I dont know how to check. Google play services version on the device is 12.5.29
- I'm not 100% sure but I think it was the same banner during the whole test, so the problem didnt happen during a banner switch
