### ISSUE TITLE
Unity3d Cloud Build 

### ISSUE THREAD

**Issue by theneken** [googleads/googleads-mobile-unity#195] opened 2016-03-24 15:32 UTC
Hello,

There is any way to successfull build GoogleAds for iOS with Unity Cloud Build? I think that Unity servers didn't have cocopods installed on they build agents. I got error:

10930:        [xcode] /BUILD_PATH/piotr-zygadlo.galaxy-of-trian.default-ios/Unity/temp.M41Hjm/Frameworks/Plugins/IOS/GoogleMobileAds.framework/Modules/module.modulemap:2:19: error: umbrella header 'GoogleMobileAds.h' not found
10931:        [xcode]   umbrella header "GoogleMobileAds.h"
10932:        [xcode] 1 error generated.
10933:        [xcode] In file included from /BUILD_PATH/piotr-zygadlo.galaxy-of-trian.default-ios/Unity/temp.M41Hjm/Libraries/Plugins/IOS/GADUInterface.m:6:
10934:        [xcode] /BUILD_PATH/piotr-zygadlo.galaxy-of-trian.default-ios/Unity/temp.M41Hjm/Libraries/Plugins/IOS/GADURequest.h:4:9: fatal error: could not build module 'GoogleMobileAds'
10935:        [xcode] @import GoogleMobileAds;
10936:        [xcode] 2 errors generated.
10937:        [xcode] CompileC build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/GADURequest.o Libraries/Plugins/IOS/GADURequest.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
10938:        [xcode]     cd /BUILD_PATH/piotr-zygadlo.galaxy-of-trian.default-ios/Unity/temp.M41Hjm
10939:        [xcode] /BUILD_PATH/piotr-zygadlo.galaxy-of-trian.default-ios/Unity/temp.M41Hjm/Frameworks/Plugins/IOS/GoogleMobileAds.framework/Modules/module.modulemap:2:19: error: umbrella header 'GoogleMobileAds.h' not found
10940:        [xcode]   umbrella header "GoogleMobileAds.h"
10941:        [xcode] 1 error generated.
10942:        [xcode] /BUILD_PATH/piotr-zygadlo.galaxy-of-trian.default-ios/Unity/temp.M41Hjm/Libraries/Plugins/IOS/GADURequest.m:4:9: fatal error: could not build module 'GoogleMobileAds'
10943:        [xcode] @import GoogleMobileAds;
10944:        [xcode] 2 errors generated.

**Comment by rampara** [comment] 2016-03-28 17:49
Have you included the Google Mobile Ads iOS Framework and any other necessary mediation files within the 'Assets/Plugins/iOS' directory of your Unity project?

**Comment by 11Sheep** [comment] 2016-04-17 14:28
HI rampara,

I have a similar issue. If i'm using windows, how do i include the Google Mobile Ads iOS Framework? is it a single file? from were can i download it?

**Comment by rampara** [comment] 2016-04-18 17:52
@11Sheep you can download the Google Mobile Ads iOS framework from our [developer docs](https://developers.google.com/admob/ios/download) page.

**Comment by 11Sheep** [comment] 2016-04-19 03:04
The package contains two directories ('GoogleMobileAds.framework' and 'Mediation Adapters'). Do i need to add both to the 'Assets/Plugin/iOS' directory? (or just the content of 'GoogleMobileAds.framework')

**Comment by rampara** [comment] 2016-04-19 16:08
Including the 'Mediation Adapters' directory is only required if you are using mediation.

**Comment by 11Sheep** [comment] 2016-04-19 17:17
Ok, I added the files and got error that .h file is missing.
Can you please try help me see what did i miss?

210:        [xcode] extern const methodPointerType* native_delegate_wrapper_BannerClient_AdViewDidFailToReceiveAdWithErrorCallback_m63959831_indirect = (const methodPointerType*)&native_delegate_wrapper_BannerClient_AdViewDidFailToReceiveAdWithErrorCallback_m63959831;
211:        [xcode] extern const methodPointerType* native_delegate_wrapper_InterstitialClient_InterstitialDidFailToReceiveAdWithErrorCallback_m2030413979_indirect = (const methodPointerType*)&native_delegate_wrapper_InterstitialClient_InterstitialDidFailToReceiveAdWithErrorCallback_m2030413979;
212:        [xcode] extern const methodPointerType* native_delegate_wrapper_RewardBasedVideoAdClient_RewardBasedVideoAdDidFailToReceiveAdWithErrorCallback_m2391022519_indirect = (const methodPointerType*)&native_delegate_wrapper_RewardBasedVideoAdClient_RewardBasedVideoAdDidFailToReceiveAdWithErrorCallback_m2391022519;
213:        [xcode] /BUILD_PATH/11sheep.sheeppuzzle.sheepuzzle-ios-production/PuzzleGame/temp.Z87PVm/Frameworks/Plugins/iOS/GoogleMobileAds.framework/Modules/module.modulemap:2:19: error: umbrella header 'GoogleMobileAds.h' not found
214:        [xcode] 1 error generated.
215:        [xcode] /BUILD_PATH/11sheep.sheeppuzzle.sheepuzzle-ios-production/PuzzleGame/temp.Z87PVm/Libraries/Plugins/iOS/GADURequest.m:4:9: fatal error: could not build module 'GoogleMobileAds'
216:        [xcode] 2 errors generated.
217:        [xcode] ** BUILD FAILED **

**Comment by rampara** [comment] 2016-04-22 19:37
I am able to create a successful Unity cloud build with the following setup:

- [Sample Unity project](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld)
- Import latest version of Google Mobile Ads Unity plugin package
- Copy Google Mobile Ads iOS SDK to 'Assets/Plugins/iOS' of Unity project

Can you ensure you're using a stand zip tool to unzip the mobile ads SDK and that you're not modifying the SDK in any other way. If you're still running into issues, you can link a project where you're able to reproduce the problem and I can investigate further.

**Comment by 11Sheep** [comment] 2016-04-23 03:26
Hi @rampara ,

I verified it again:
- All the google mobile ads unity plugin is imported as they should be
- All the google mobile ads ios sdk files are imported and I also checked GitHub to see that they are there
- I even checked that the specific file that the error say is missing (GoogleMobileAds.h) is there.

And I still get this error.

How do I send you the project link in private message?

**Comment by rampara** [comment] 2016-04-25 18:13
GitHub no longer provides a private messaging system. Can you can reproduce the error in a project you're will to share publicly, such as our [sample project](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld)?

**Comment by rampara** [comment] 2016-08-16 18:44
Closing issue due to non-response. If this issue persists, please re-open.

**Closed by rampara** 2016-08-16 18:44 UTC
Labels: support question

**Comment by lizistorm** [comment] 2017-06-30 06:31
The problem is the "Headers" and "GoogleMobileAds" link lost when unzip googlemobileadssdkios.zip on windows. 
Unzip on Mac will resolve the problem.
Or delete the link files and move real Version/A/Headers and GoogleMobileAds files to root path.
