### ISSUE TITLE
ANR with com.google.android.gms.internal

### ISSUE THREAD

**Issue by obaidahmed234** [googleads/googleads-mobile-unity#688] opened 2018-06-06 11:31 UTC
Hi, We're receiving ANR Report from our games using Admob made with Unity 2018.1.1. I have attached ANR Report below and this is the only information we have regarding ANR since we're unable to reproduce this.

"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x76206f90 self=0xab8dcf00
  | sysTid=20094 nice=-4 cgrp=apps sched=0/0 handle=0xf7019ec8
  | state=S schedstat=( 1504449839 4029105848 2598 ) utm=95 stm=55 core=4 HZ=100
  | stack=0xff1fb000-0xff1fd000 stackSize=8MB
  | held mutexes=
 
  #00  pc 000000000000f620  /system/lib/libc.so (syscall+28)
 
  #01  pc 00000000000a8f07  /system/lib/libart.so (_ZN3art17ConditionVariable4WaitEPNS_6ThreadE+82)
 
  #02  pc 000000000027b385  /system/lib/libart.so (_ZN3artL12GoToRunnableEPNS_6ThreadE+772)
 
  #03  pc 00000000000860d9  /system/lib/libart.so (_ZN3art12JniMethodEndEjPNS_6ThreadE+8)
 
  #04  pc 00000000000714af  /data/dalvik-cache/arm/system@framework@boot.oat (Java_java_lang_Thread_nativeCreate__Ljava_lang_Thread_2JZ+142)
 
  at java.lang.Thread.nativeCreate (Native method)
 
  at java.lang.Thread.start (Thread.java:1063)
- locked <@addr=0x13301c80> (a android.os.HandlerThread)
 
  at android.net.ConnectivityManager.incCallbackHandlerRefCount (ConnectivityManager.java:2365)
- locked <@addr=0x71a9d410> (a java.util.concurrent.atomic.AtomicInteger)
 
  at android.net.ConnectivityManager.sendRequestForNetwork (ConnectivityManager.java:2397)
 
  at android.net.ConnectivityManager.registerNetworkCallback (ConnectivityManager.java:2529)
 
  at org.chromium.android_webview.AwNetworkChangeNotifierRegistrationPolicy.onFirstWebViewCreated (AwNetworkChangeNotifierRegistrationPolicy.java:31)
 
  at org.chromium.android_webview.AwContentsLifecycleNotifier.onWebViewCreated (AwContentsLifecycleNotifier.java:7)
 
  at org.chromium.android_webview.AwContents.nativeInit (Native method)
 
  at org.chromium.android_webview.AwContents.<init> (AwContents.java:80)
 
  at com.android.webview.chromium.WebViewChromium$1.run (WebViewChromium.java:12)
 
  at com.android.webview.chromium.WebViewChromiumFactoryProvider$WebViewChromiumRunQueue.drainQueue (WebViewChromiumFactoryProvider.java:14)
 
  at com.android.webview.chromium.WebViewChromiumFactoryProvider$WebViewChromiumRunQueue$1.run (WebViewChromiumFactoryProvider.java:2)
 
  at org.chromium.base.ThreadUtils.runOnUiThread (ThreadUtils.java:30)
 
  at com.android.webview.chromium.WebViewChromiumFactoryProvider$WebViewChromiumRunQueue.addTask (WebViewChromiumFactoryProvider.java:8)
 
  at com.android.webview.chromium.WebViewChromiumFactoryProvider.addTask (WebViewChromiumFactoryProvider.java:16)
 
  at com.android.webview.chromium.WebViewChromium.init (WebViewChromium.java:65)
 
  at android.webkit.WebView.<init> (WebView.java:548)
 
  at android.webkit.WebView.<init> (WebView.java:483)
 
  at android.webkit.WebView.<init> (WebView.java:466)
 
  at android.webkit.WebView.<init> (WebView.java:453)
 
  at android.webkit.WebView.<init> (WebView.java:443)
 
  at com.google.android.gms.internal.zzaor.<init> (unavailable)
 
  at com.google.android.gms.internal.zzaor.zzb (unavailable)
 
  at com.google.android.gms.internal.zzaoo.call (unavailable)
 
  at com.google.android.gms.internal.zzakg.zzb (unavailable)
 
  at com.google.android.gms.internal.zzaol.zza (unavailable)
 
  at com.google.android.gms.ads.internal.js.zze.<init> (unavailable)
 
  at com.google.android.gms.ads.internal.js.zzn.zza (unavailable)
 
  at com.google.android.gms.ads.internal.js.zzo.run (unavailable)
 
  at com.google.android.gms.internal.zzalz.execute (unavailable)
 
  at com.google.android.gms.ads.internal.js.zzn.zza (unavailable)
 
  at com.google.android.gms.ads.internal.js.zzn.zzb (unavailable)
- locked <@addr=0x12ea3710> (a java.lang.Object)
 
  at com.google.android.gms.internal.zzvi.zzf (unavailable)
 
  at com.google.android.gms.ads.internal.zzac.zza (unavailable)
 
  at com.google.android.gms.ads.internal.zzac.zza (unavailable)
 
  at com.google.android.gms.ads.internal.zzax.zza (unavailable)
 
  at com.google.android.gms.internal.zzmz.zza (unavailable)
- locked <@addr=0x12efe0c0> (a java.lang.Object)
 
  at com.google.android.gms.ads.MobileAds.initialize (unavailable)
 
  at com.google.android.gms.ads.MobileAds.initialize (unavailable)
 
  at com.heyzap.sdk.mediation.adapter.AdmobAdapter.onStart (AdmobAdapter.java:138)
 
  at com.heyzap.mediation.abstr.NetworkAdapter$1.run (NetworkAdapter.java:105)
 
  at com.heyzap.common.concurrency.WrappedRunnable.run (WrappedRunnable.java:26)
 
  at com.heyzap.common.concurrency.HandlerExecutorService$2.run (HandlerExecutorService.java:59)
 
  at android.os.Handler.handleCallback (Handler.java:739)
 
  at android.os.Handler.dispatchMessage (Handler.java:95)
 
  at android.os.Looper.loop (Looper.java:135)
 
  at android.app.ActivityThread.main (ActivityThread.java:5253)
 
  at java.lang.reflect.Method.invoke! (Native method)
 
  at java.lang.reflect.Method.invoke (Method.java:372)
 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:913)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:708)

**Comment by rampara** [comment] 2018-06-25 10:33
@obaidahmed234 closing this issue as the ANR is caused by WebView and not this plugin.

**Closed** 2018-06-25 10:33 UTC
Labels: P2, support question

**Comment by Jack6Wolf** [comment] 2020-07-03 05:44
> @obaidahmed234 closing this issue as the ANR is caused by WebView and not this plugin.

Hello, Excuse me, how do you solve this ANR？
