### ISSUE TITLE
il2cpp.exe did not run properly! error Unity 2017.4.38f1 LTS

### ISSUE THREAD

**Issue by waqasbhattii** [googleads/googleads-mobile-unity#1252] opened 2020-04-12 15:47 UTC
Hello @stowy ,

I hope you are doing well. I am getting an error while building my app in Unity 2017.4.38f1 using the latest GoogleMobileAds package. I have attached screenshot of the error. Please have a look and help.

Thanks,

Waqas
<img width="432" alt="Screen Shot 2020-04-12 at 8 38 17 PM" src="https://user-images.githubusercontent.com/43206618/79073177-8994f700-7cfe-11ea-836c-8a61bdcb5354.png">
<img width="437" alt="Screen Shot 2020-04-12 at 8 45 06 PM" src="https://user-images.githubusercontent.com/43206618/79073181-8dc11480-7cfe-11ea-8d54-029fddc7343d.png">

**Comment by stowy** [comment] 2020-04-13 16:46
Thanks @waqasbhattii - I think this is a duplicate of #1208. It will be resolved in the next release due this month.

**Comment by waqasbhattii** [comment] 2020-04-14 08:45
Thanks for your reply @stowy :)

**Closed** 2020-04-14 08:45 UTC
