### ISSUE TITLE
Sound's level and mute functions don't work

### ISSUE THREAD

**Issue by egorovsa** [googleads/googleads-mobile-unity#1898] opened 2022-01-13 10:35 UTC
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.2.7
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: IOS (iOS, Android, Unity Editor)
  * Platform OS version: iOS (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

set SetApplicationVolume or SetApplicationMuted into your code
start app and rewarder or interstitial ad
sound level is not changed
in case of SetApplicationMuted(true) ad's sound is not muted

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
MobileAds.SetApplicationVolume(0.5f);
MobileAds.SetApplicationMuted(true);
```

**Comment by shefich** [comment] 2022-01-17 22:28
I have the same issue.
Btw they told us several years ago, that everythin is fixed: https://groups.google.com/g/google-admob-ads-sdk/c/IADqLj5FJAU/m/2BYOuH46BgAJ

**Comment by shefich** [comment] 2022-01-17 23:09
Tried on Google Mobile Ads Unity Plugin Version 6.1.2

**Comment by shefich** [comment] 2022-01-18 15:21
Upd: Sound can't be turned off by default for all Mediated Ad providers (Ex. Ironsource, Applovin, Unity etc.) coming through Admob Mediation. Admob videos volume can be controlled.
@egorovsa do you have the same experince?

**Comment by egorovsa** [comment] 2022-01-18 15:26
Admob videos volume is not changing..Sounds for 100% and it's  very annoying my users... 
I would't like to turn it off totally, however, turning off does't work as well.

**Comment by egorovsa** [comment] 2022-01-18 15:43
I've been trying to set different values.  If I get right the value 0.5f is a half of the current phone volume. Therefor I've tried to set less than 0.5f too. Nevertheless nothing changed.
SetApplicationMuted.. two years ago I used this, It worked perfect.

**Comment by NVentimiglia** [comment] 2022-04-08 06:46
Unable to replicate on the hello world app. I'm going to assume that this may be a bug from content from a mediation partner.

Can someone provide me with information on what mediation partners are being used and perhaps a logcat of this bug.

**Comment by shefich** [comment] 2022-04-10 15:09
No need to use or include the mediation partners. The mute function just doesn't work on any Admob video.
Already sent sample project to the Admob team here: https://groups.google.com/g/google-admob-ads-sdk/c/IADqLj5FJAU/m/2BYOuH46BgAJ
But it was private message, however they told me that engineer team is investigating the problem.

**Comment by ariok** [comment] 2022-04-28 16:48
I'm reproducing the same exact issue. I'm trying to turn off audio during ads with both SetApplicationVolume and SetApplicationMuted, but the volume is always at 100%. I'm experiencing the issue on a device that has been added in the "Test device" list using the Admob dashboard. Not sure if the info is a useful.

**Comment by ariok** [comment] 2022-04-28 17:29
A quick update about my previous comment. Using a device that is not been added as "Test device" I can correctly mute the audio. In my case the issue is just triggered on "Test devices".

**Comment by kunny** [comment] 2023-02-06 15:06
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.

**Closed by kunny** 2023-02-06 15:06 UTC
Labels: wontfix, P2, Integration Issue, SDK Issue
