### ISSUE TITLE
Automatic activation banner

### ISSUE THREAD

**Issue by KVinS** [googleads/googleads-mobile-unity#498] opened 2017-09-07 13:28 UTC
Hello. I have a problem.
If you make a request for a banner, and then display a rewarded video, after the video is closed, a banner is activated.
(Android, Unity5, 3.6.3)
Repeated in the [example](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld/):
1) Request banner
2) Destroy banner
3) Request rewarded
4) Show rewarded
My English is terrible, [I create a video](https://drive.google.com/file/d/0B2L9VKgjo49HbjhiSENBV2QtS1U/view?usp=sharing).

**Comment by rampara** [comment] 2017-11-15 02:22
@KVinS I'm having trouble reproducing this behavior. Is this issue still present for you on the latest version of this plugin?

**Comment by rampara** [comment] 2017-12-15 00:36
Closing due to non-response.

**Closed** 2017-12-15 00:37 UTC
Labels: support question
