### ISSUE TITLE
GAD 3.15.1 RewardBasedVideoAd.Instance issue [ClassNotFoundException]

### ISSUE THREAD

**Issue by rchallenger** [googleads/googleads-mobile-unity#876] opened 2019-03-15 11:01 UTC
Hello,
I'm getting this error in Android application built with Unity3D 5.4.0, 5.4.2, 5.5.0. 
And Only Unity2018.+ works fine.

To clear up all the questiuons I've tried to make an empty project with GAD 3.15.1, where in `MonBehavior.Start()` I've chached RewardBasedVideoAd.Instance to a temporary variable. RIght after application starts I get this error `Exception: No such proxy method: UnityEngine.AndroidJavaRunnableProxy.toString()`.
Later, after Start is triggered CogCat shows next error: `AndroidJavaException: java.lang.ClassNotFoundException: com.google.unity.ads.UnityRewardBasedVideoAdListener`.

Application, built with Unity 2018, has no such errors.

Can you help me figuring out what is wrong here?

PS: unity-plugin-library.jas is present in Plugins folder, Resolver imported all libraries sucessfully, using jdk1.8.0_202.

[LogCat snapshot](https://github.com/googleads/googleads-mobile-unity/files/2970664/GAD3.15.1_rewarded.instance.log.txt)

**Comment by mmvlad** [comment] 2019-05-02 10:46
Having the same issue with Unity 5.4, 5.6.5

Looks like the lib is not even tested now on previous versions though support is stated 4.6+.

**Comment by UragayalaDeepika** [comment] 2019-08-01 00:59
@rchallenger Can you please confirm that you are still seeing this issue with the latest version?

**Comment by UragayalaDeepika** [comment] 2019-09-30 21:24
@rchallenger Closing this for now as we are not able to reproduce the issue on our end. Feel free to reopen and provide us an update for us to take a look.

**Closed by UragayalaDeepika** 2019-09-30 21:24 UTC
Labels: support question
