### ISSUE TITLE
Banner ad position changes after viewing interstitial ad.

### ISSUE THREAD

**Issue by MushoodMunir** [googleads/googleads-mobile-unity#753] opened 2018-08-27 07:31 UTC
![issue](https://user-images.githubusercontent.com/10167077/44646888-e80c4500-a9f5-11e8-883f-29f7376f6af3.png)
![sample](https://user-images.githubusercontent.com/10167077/44646889-e80c4500-a9f5-11e8-8aec-bf30ae997581.png)

I'm using unity 2017.2.1 and Google Mobile Ads Unity Plugin v3.13.0
Issue: The Smart Banner Position move up after the soft keys appeared on interstitial ad. Sometimes the banner back to bottom position but sometimes the banner stuck to that position that is adjust according to soft keys of the mobile. @rampara closed this issue but i faced the same issue with the above specified plugin.

https://github.com/googleads/googleads-mobile-unity/issues/687#issue-329687638

**Comment by devingDev** [comment] 2018-08-31 05:58
As a temporary solution you could recreate the bannerview after an interstitial

**Comment by rampara** [comment] 2018-09-06 22:39
Closing as duplicate of #687 as that's still an open issue.

**Closed** 2018-09-06 22:39 UTC
Labels: P2, duplicate, plugin bug
