### ISSUE TITLE
Smart banner displaced on Galaxy S5 SCL23

### ISSUE THREAD

**Issue by hieunp8x** [googleads/googleads-mobile-unity#611] opened 2018-02-05 09:28 UTC
Hi, 
I am using original sample of Admob HelloWorld Sample for test (include in plugin 3.11.0)
But banner still displaced (see image attach)
My device: Samsung Galaxy S5, Model SCL23 (NTT Docomo)
OS: 6.0.1
![27745097_1999728963607282_481306669_o](https://user-images.githubusercontent.com/13539845/35797162-669e92d8-0a91-11e8-9906-ef1da67ba4fb.png)

Thanks.

**Comment by AibNihan** [comment] 2018-02-05 18:56
Maybe You Should Check this Unity Answers [Unity Answer](https://answers.unity.com/questions/1264156/change-position-of-admob-banner-when-opening-new-s.html) 
Hope It's Helping You

**Comment by rampara** [comment] 2018-02-06 23:57
@hieunp8x have you modified the HelloWorld sample app in any way? Are you able to reproduce this issue on any other device or only the Samsung Galaxy S5?

**Comment by hieunp8x** [comment] 2018-02-07 03:27
Hi Rampara,
>>>have you modified the HelloWorld sample app in any way? 
No, i don't 

>>>Are you able to reproduce this issue on any other device or only the Samsung Galaxy S5?
Only bug on Galaxy S5, S6 (NTT-Docomo)

Thanks.

**Comment by hieunp8x** [comment] 2018-02-07 03:32
Hi AibNihan,

Thanks you for reply
Solution is ok

Best regards.

**Comment by rampara** [comment] 2018-02-12 22:25
@hieunp8x on a Samsung S5 running 4.4.2, smart banners are positioned as expected for mewhen using the `AdPosition.Top` ad position constant.

![image](https://user-images.githubusercontent.com/11047881/36123101-8064fd14-1000-11e8-9fa8-4782460aa2b6.png)

**Comment by hieunp8x** [comment] 2018-02-13 13:58
@rampara Error on Samsung **Galaxy S5 Model SCL23 (Device of NTT-Docomo in Japan)**

**Comment by rampara** [comment] 2018-02-14 19:17
@hieunp8x I don't have access to that particular device. Were you able to repo the issue on any other devices?

**Comment by rampara** [comment] 2018-04-11 19:54
Closing due to non-response.

**Closed** 2018-04-11 19:54 UTC
Labels: P2, support question
