### ISSUE TITLE
Admob banner doesn't show after adding IAP through Unity services

### ISSUE THREAD

**Issue by galloperx** [googleads/googleads-mobile-unity#696] opened 2018-06-14 12:35 UTC
Hello,
I was using this plugin and it was working fine (showing one banner) in my app. Without any changes to the banner script code which is almost identical to the example one here, I added IAP through Unity Services, it works fine, but now the banner is gone.
While trying to trace the problem to its root I added try {..} catch {...} blocks to the banner creating code and the line 
bannerAd = new BannerView(adID, AdSize.SmartBanner, AdPosition.Top);
throws this exception:
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.unity.ads.UnityAdListener" 

I also ran the Resolver and if I select "Resolve" it says everything's fine, but if I try "Force resolve" resolution fails.

Also note that despite all this the project builds with no errors.

**Comment by Hexa566** [comment] 2018-06-15 09:43
Unity Version ? Build Type ? (Internal or Gradle) ?

**Comment by galloperx** [comment] 2018-06-15 09:56
Unity 2017.4.4f1 and building with Gradle

**Comment by Hexa566** [comment] 2018-06-15 17:55
Trying using internal if gradle is not necessary , i think it is mostly happening due to gradle.
See your debugs , is admob initializing or not ? & paste your logcat.

**Comment by rampara** [comment] 2018-06-25 09:30
@galloperx is the `unity-plugin-library.jar` still present in your project under the `Assets/Plugins/Android/GoogleMobileAdsPlugin/libs` directory?

**Comment by galloperx** [comment] 2018-06-28 12:57
Yes it's there, sorry for late reply.
Currently the exact error with showing the banner pops up after this line of code:
`bannerAd = new BannerView(adID, AdSize.SmartBanner, AdPosition.Top);`
and the exception is the class not found: com.google.unity.ads.adlistener
I've tried different ways to solve this, including reinstalling the Android SDK, clearing Gradle cache, updating Java to the latest SDK with changing the java_home to reflect the update (everything works fine there) etc. Most of this is unrelated to the current problem, but I did it anyway just to be sure.

**Comment by galloperx** [comment] 2018-06-28 13:52
Additionally, I tried to use the Resolver's option "Prebuild with Gradle" which led to this error:

Error somewhere in the process of creating the gradle build, executing it, and copying the outputs.
This will break dependency resolution and your build will not run.
See the output below for possible gradle build errors. The most likely cases are: an invalid bundleID (which you can correct in the Android Player Settings), or a failure to determine the Android SDK platform and build tools verison (you can verify that you have a valid android SDK path in the Unity preferences.
If you're not able to diagnose the error, please report a bug at: https://github.com/googlesamples/unity-jar-resolver/issuesA possible work-around is to turn off the "Gradle Prebuild" from the Jar Resolver Settings.

```
Error (-1):
Traceback (most recent call last):
  File "<string>", line 475, in <module>
  File "<string>", line 467, in main
  File "<string>", line 214, in generate_gradle_build
  File "<string>", line 75, in merge_dir_tree
WindowsError: [Error 123] �������������� ������ � ����� �����,: u'https://maven.google.com/*.*'
generate_gradle_prebuild returned -1

UnityEngine.Debug:LogError(Object)
GooglePlayServices.<RunGenGradleScript>c__AnonStoreyE:<>m__11(Result)
GooglePlayServices.ProgressReporter:Update(CommandLineDialog)
GooglePlayServices.CommandLineDialog:Update()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

Windows error 123 is the one that says "The filename, directory name, or volume label syntax is incorrect"

**Comment by rampara** [comment] 2018-07-20 20:38
@galloperx can you provide a test Unity project that reproduces this issue?

**Comment by rampara** [comment] 2018-09-06 22:45
Closing issue due to non-response.

**Closed by rampara** 2018-09-06 22:45 UTC
Labels: P2, support question
