### ISSUE TITLE
FATAL EXCEPTION on RewardedVideoAdListener.onRewardedVideoCompleted()

### ISSUE THREAD

**Issue by useless-id** [googleads/googleads-mobile-unity#655] opened 2018-04-11 16:09 UTC
Hello, I found a issue when trying to finish the RewardAd in Android 7.
After the RewardVideo has finished (and I don't even have the time to close the RewardVideo with X) the game crashes and I have this logcat with FATAL EXCEPTION[main]

`04-11 17:55:01.729 19107 19107 D AndroidRuntime: Shutting down VM
04-11 17:55:01.731 19107 19206 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-11 17:55:01.731 19107 19206 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-11 17:55:01.737 19107 19107 E AndroidRuntime: FATAL EXCEPTION: main
04-11 17:55:01.737 19107 19107 E AndroidRuntime: Process: com.unity3d.GlitterMayo, PID: 19107
04-11 17:55:01.737 19107 19107 E AndroidRuntime: java.lang.Error: FATAL EXCEPTION [main]
04-11 17:55:01.737 19107 19107 E AndroidRuntime: Unity version     : 2017.3.1f1
04-11 17:55:01.737 19107 19107 E AndroidRuntime: Device model      : samsung SM-G925F
04-11 17:55:01.737 19107 19107 E AndroidRuntime: Device fingerprint: samsung/zeroltexx/zerolte:7.0/NRD90M/G925FXXS5ERBC:user/release-keys
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 
04-11 17:55:01.737 19107 19107 E AndroidRuntime: Caused by: java.lang.AbstractMethodError: abstract method "void com.google.android.gms.ads.reward.RewardedVideoAdListener.onRewardedVideoCompleted()"
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.google.android.gms.internal.zzafh.onRewardedVideoCompleted(Unknown Source)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.google.android.gms.internal.zzafd.onTransact(Unknown Source)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at android.os.Binder.transact(Binder.java:507)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at hl.b(:com.google.android.gms.dynamite_dynamitemodulesa@12521021@12.5.21 (040400-189987672):20)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.google.android.gms.ads.internal.reward.client.l.f(:com.google.android.gms.dynamite_dynamitemodulesa@12521021@12.5.21 (040400-189987672):27)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.google.android.gms.ads.internal.a.u(:com.google.android.gms.dynamite_dynamitemodulesa@12521021@12.5.21 (040400-189987672):471)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.google.android.gms.ads.internal.reward.d.f_(:com.google.android.gms.dynamite_dynamitemodulesa@12521021@12.5.21 (040400-189987672):87)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.google.android.gms.ads.internal.reward.mediation.h.h(:com.google.android.gms.dynamite_dynamitemodulesa@12521021@12.5.21 (040400-189987672):37)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.google.android.gms.ads.internal.reward.client.n.f(:com.google.android.gms.dynamite_dynamitemodulesa@12521021@12.5.21 (040400-189987672):96)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.google.android.gms.ads.internal.a.u(:com.google.android.gms.dynamite_dynamitemodulesa@12521021@12.5.21 (040400-189987672):471)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.google.android.gms.ads.internal.ak.Z(:com.google.android.gms.dynamite_dynamitemodulesa@12521021@12.5.21 (040400-189987672):277)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.google.android.gms.ads.internal.gmsg.am.a(:com.google.android.gms.dynamite_dynamitemodulesa@12521021@12.5.21 (040400-189987672):28)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.google.android.gms.ads.internal.webview.j.b(:com.google.android.gms.dynamite_dynamitemodulesa@12521021@12.5.21 (040400-189987672):356)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.google.android.gms.ads.internal.webview.ab.run(Unknown Source)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.google.android.gms.ads.internal.util.f.dispatchMessage(:com.google.android.gms.dynamite_dynamitemodulesa@12521021@12.5.21 (040400-189987672):9)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
04-11 17:55:01.737 19107 19107 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
04-11 17:55:01.788  3620  3633 D InputDispatcher: Focus left window: 19107
`

I tried testing on Android 6.xx and there is no problem with RewardVideo, after it has completed the listener give me what I want and I have the reward.
Thanks for the attention, any suggestion/tips on how to fix it?

**Comment by rampara** [comment] 2018-04-11 17:38
Closing as duplicate of #653.

**Closed** 2018-04-11 17:39 UTC
Labels: P1, plugin bug
