### ISSUE TITLE
Rewarded Video Callbacks not gets called after error in SDK

### ISSUE THREAD

**Issue by cometa93** [googleads/googleads-mobile-unity#742] opened 2018-08-03 21:18 UTC
`W Ads     : Unable to append parameter to URL: https://googleads.g.doubleclick.net/aclk?sa=L&ai=CN-VsxLxkW-RkwviAB4_1hDiQuKncUqPBz9e1B-Sr6eW4ARABIIqQwDZg6cTGhdQaoAHJ--jQA6kC-ALl_vVzsz6oAwHIAwiqBOgBT9A37PM-IejDpAv8jpjllsKiH5C2gvp0ry6xEKvIqmb25sOlnqGBeZGENHo_H0IS-YqBMG2Ix7MJMbC2Y9JoPq03TRRc-tuVlwni8FOT9ekDwiGDg4Yk1H4Nk_k38lZ79ElrnJlHeKMPLHyCZTRoS77Q5FNy6b7UM62Dk-zbY02hEH9Zukw20uyTaG8XvNdBs9JJ-u6WVhcRIqJlwuEYQ1xTuNQI8zEihDMvemak1MI4UE8lk-WWeXX9J8KrHMe0GNIpCTlz8tWsSGiMshS4nCSpFbbVf5b8A7HkZ6i1GGQfuiTY0MEk_MAEpOuT-OUBiAX90ZChBcAFcZAGAaAGHLAGAYAHsbrcMpgHAagHpr4bqAfVyRuoB6EBqAetyhuoB67NG6gH2csbqAfPzBu4B4v6rZmdlsxuwAeN1QPAB-jUA9gHAfoHGGNvbS5pbm5vZ2FtZXMuZm9lYW5kcm9pZJgIAaAIp909qAgBsAgCuAgB0ggJCIDhgBAQARgCsQmz2Ef4z7HNI7gTsQOCFCgaJm1vYmlsZWFwcDo6Mi1ldS5mdW52ZW50dXJlLkNvc21vc1F1ZXN0&num=1&cid=CAASUeRoMS8uagmqqtppnqo7yyyg1gh_vf6ASaJ4LXWOtKE2qZPnHLd3k4vkuemqCHEFWgjbkqBy41DrXmEJOdppiFfIKAHnvKg3VNi1CtBHkdXWMw&sig=AOD64_3LKdQ-wwYmsmbRgLn0x_QRrm8h2w&ms=CoACCvYS4VgiiMLnXSc3LkLxuu3lodwE5hKgVNUUc6iMI8n0bFMd9LQKxEiO3MzVt5rpAwWwInvghXK23k07cM0foeA25FQ0rLdm0n-gYuRdYzKnWHqhsI7OJhOewpU7fGqjem4Gge6Hnve7m74oPM9tANe86VrbCZuA9SYRhwI1Fk7MKUWjgKfEr-5IQ-W0Qpr1gLiWGrN3o4nsglGyLJrWrHNQl3mkpqubcrX3gWWNeeRYAJP6ZhoCUGqLkMijuITkl0kbuwEUJGxwzjvzMBp1lVdaywKKOeWVyuLNnYeeSwVJzk1ZvPK379w4Yd2wsVgC70h47Kr07bVViBJnvEdwtAqAApcGVQXxK9utNH95wwQNFrc9wPxvLCJv3QNL_8dXA4hs13Z1HPH-wTtx-bhNekCrMCMUnMxVy8E9f3tCbddM-bnmuUmoub52UWSteLdP6WX1fkeSJsD6-sjvHy7hVqT5-2pBUL2pBUeyz2N1PMJ7HgkZuWyeC9wwJyw91EsMZpznOTH23BM97adA5bouP9ir5IQDGzcnlEFvVtvlVFO89ZcYgF_oz0mq0TAJy_CNGdsoUPLHe24cWIawuo65xOuCpZz1Ag_tTOj9Hv5Cbv0LDrHdHhi9LmTK4zS6E_N7R_qGtVQletBoWQRTvHNkJFIhCdDOXeJE_bdC2rYEjZeODF0SEIu2nwveTPhZUpmVcDloOKg&adurl=market://details%3Fid%3Dcom.innogames.foeandroid%26referrer%3Dcampaigntype%253Da%2526network%253Dd%2526campaignid%253D1411655933%2526loc_physical_ms%253D%26inline%3Dtrue%26enifd%3DABCzQSO4U67aBBxJGyW2zxnfxNUeF6ClMKndmkwDv6Ks_GDapQPxyPV1bCGl48ymac8LNbS_RkdZa4c5GG_9ACJRRDwfC9SczajUpqGtujd-eDGmY0-zdXkH48eYSDAc0W1RYN1k0BKTP4y0JmKY9HwVPT5FGLlFZRjR9QBPqlqF1n37L5U-cvU64g&label=video_10s_engaged_view
`

I've pasted logcat error, after which i didn't get callback. I'd to reproduce the issue on NOT TESTING enviroment. Test ads were working perfectly 100% times! I've received a lot of feedback from players not getting rewarded.

**Comment by rampara** [comment] 2018-08-07 21:12
@cometa93 is this issue present for AdMob ads or for mediated ads? Are you able to consistently reproduce the problem?

**Comment by rampara** [comment] 2019-01-23 03:49
Closing due to non-response.

**Closed by rampara** 2019-01-23 03:49 UTC
Labels: P2, support question
