### ISSUE TITLE
Banner ad spams messages once it shows the first time and never stops. Not even when the app is minimized.

### ISSUE THREAD

**Issue by wallaby3** [googleads/googleads-mobile-unity#671] opened 2018-05-13 12:15 UTC
I get this message every frame as soon as the first banner ad shows:

"05-13 21:59:40.840 5748-5748/{my app's bundle identifier} D/ViewRootImpl@de2377[PopupWindow:55a6438]: Relayout returned: oldFrame=[0,1655][864,1775] newFrame=[0,1655][864,1775] result=0x1 surface={isValid=true -1511204864} surfaceGenerationChanged=false"

It never stops until the app is manually closed.

It also happens using Test ads.

I've tried SmartBanner and Banner types and the both do the same thing.

It's not showing as an error, just a log message that slows down the app printing to the console every frame.

 Interstitial and Reward ads don't appear to have this issue.

**Comment by Mitnainartinarian** [comment] 2018-05-23 01:34
I get this too. It causes performance problems with my app.

**Comment by rampara** [comment] 2018-07-24 20:01
@wallaby3 @Mitnainartinarian is this issue only reproducible on certain devices for you or across all devices ?

**Comment by rampara** [comment] 2018-07-24 21:57
Closing as this issue seems to be resolved on the latest version of the plugin.

**Closed by rampara** 2018-07-24 21:57 UTC
Labels: P2, support question
