### ISSUE TITLE
CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.

### ISSUE THREAD

**Issue by renanpc** [googleads/googleads-mobile-unity#222] opened 2016-05-21 11:36 UTC
I am trying to generate an apk from my project and unity keep showing me this error, someone know how to solve this problem?

Log:
CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:/Program Files/Java/jdk1.8.0_91\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="E:/Android/android-sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznm;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznn;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzno;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzno$zza;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznp;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznq;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqi;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqi$zza;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqj;
9 errors; aborting
]
stdout[
processing archive E:\MarvinTheVolcano\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\libs\.\unity-plugin-library.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/unity/
processing com/google/unity/BuildConfig.class...
ignored resource com/google/unity/ads/
processing com/google/unity/ads/Banner.class...
processing com/google/unity/ads/Banner$1.class...
processing com/google/unity/ads/Banner$1$1.class...
processing com/google/unity/ads/Banner$2.class...
processing com/google/unity/ads/Banner$3.class...
processing com/google/unity/ads/Banner$4.class...
processing com/google/unity/ads/Banner$5.class...
processing com/google/unity/ads/Interstitial.class...
processing com/google/unity/ads/Interstitial$1.class...
processing com/google/unity/ads/Interstitial$1$1.class...
processing com/google/unity/ads/Interstitial$2.class...
processing com/google/unity/ads/Interstitial$3.class...
processing com/google/unity/ads/Interstitial$4.class...
processing com/google/unity/ads/Interstitial$5.class...
processing com/google/unity/ads/PluginUtils.class...
processing com/google/unity/ads/RewardBasedVideo.class...
processing com/google/unity/ads/RewardBasedVideo$1.class...
processing com/google/unity/ads/RewardBasedVideo$1$1.class...
processing com/google/unity/ads/RewardBasedVideo$2.class...
processing com/google/unity/ads/RewardBasedVideo$3.class...
processing com/google/unity/ads/UnityBannerAdListener.class...
processing com/google/unity/ads/UnityInterstitialAdListener.class...
processing com/google/unity/ads/UnityRewardBasedVideoAdListener.class...
processing archive E:\MarvinTheVolcano\Temp\StagingArea\android-libraries\MainLibProj\libs\.\play-games-plugin-support.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/games/
ignored resource com/google/games/bridge/
processing com/google/games/bridge/BuildConfig.class...
processing com/google/games/bridge/NativeBridgeActivity.class...
processing com/google/games/bridge/TokenFragment.class...
processing com/google/games/bridge/TokenFragment$1.class...
processing com/google/games/bridge/TokenFragment$TokenRequest.class...
processing com/google/games/bridge/TokenPendingResult.class...
processing com/google/games/bridge/TokenResult.class...
processing archive E:\MarvinTheVolcano\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\bin\classes.jar...
ignored resource .readme
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource android/
ignored resource android/support/
ignored resource android/support/v7/
ignored resource android/support/v7/app/
processing android/support/v7/app/ActionBar.class...
processing android/support/v7/app/ActionBar$DisplayOptions.class...
processing android/support/v7/app/ActionBar$LayoutParams.class...
processing android/support/v7/app/ActionBar$NavigationMode.class...
processing android/support/v7/app/ActionBar$OnMenuVisibilityListener.class...
processing android/support/v7/app/ActionBar$OnNavigationListener.class...
processing android/support/v7/app/ActionBar$Tab.class...
processing android/support/v7/app/ActionBar$TabListener.class...
processing android/support/v7/app/ActionBarActivity.class...
processing android/support/v7/app/ActionBarDrawerToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$1.class...
processing android/support/v7/app/ActionBarDrawerToggle$Delegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$DelegateProvider.class...
processing android/support/v7/app/ActionBarDrawerToggle$DrawerArrowDrawableToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$DrawerToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$DummyDelegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$HoneycombDelegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$JellybeanMr2Delegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$ToolbarCompatDelegate.class...
processing android/support/v7/app/ActionBarDrawerToggleHoneycomb.class...
processing android/support/v7/app/ActionBarDrawerToggleHoneycomb$SetIndicatorInfo.class...
processing android/support/v7/app/AlertController.class...
processing android/support/v7/app/AlertController$1.class...
processing android/support/v7/app/AlertController$2.class...
processing android/support/v7/app/AlertController$3.class...
processing android/support/v7/app/AlertController$4.class...
processing android/support/v7/app/AlertController$5.class...
processing android/support/v7/app/AlertController$AlertParams.class...
processing android/support/v7/app/AlertController$AlertParams$1.class...
processing android/support/v7/app/AlertController$AlertParams$2.class...
processing android/support/v7/app/AlertController$AlertParams$3.class...
processing android/support/v7/app/AlertController$AlertParams$4.class...
processing android/support/v7/app/AlertController$AlertParams$OnPrepareListViewListener.class...
processing android/support/v7/app/AlertController$ButtonHandler.class...
processing android/support/v7/app/AlertController$CheckedItemAdapter.class...
processing android/support/v7/app/AlertDialog.class...
processing android/support/v7/app/AlertDialog$Builder.class...
processing android/support/v7/app/AppCompatActivity.class...
processing android/support/v7/app/AppCompatCallback.class...
processing android/support/v7/app/AppCompatDelegate.class...
processing android/support/v7/app/AppCompatDelegateImplBase.class...
processing android/support/v7/app/AppCompatDelegateImplBase$1.class...
processing android/support/v7/app/AppCompatDelegateImplBase$ActionBarDrawableToggleImpl.class...
processing android/support/v7/app/AppCompatDelegateImplBase$AppCompatWindowCallbackBase.class...
processing android/support/v7/app/AppCompatDelegateImplV11.class...
processing android/support/v7/app/AppCompatDelegateImplV14.class...
processing android/support/v7/app/AppCompatDelegateImplV14$AppCompatWindowCallbackV14.class...
processing android/support/v7/app/AppCompatDelegateImplV23.class...
processing android/support/v7/app/AppCompatDelegateImplV23$AppCompatWindowCallbackV23.class...
processing android/support/v7/app/AppCompatDelegateImplV7.class...
processing android/support/v7/app/AppCompatDelegateImplV7$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$2.class...
processing android/support/v7/app/AppCompatDelegateImplV7$3.class...
processing android/support/v7/app/AppCompatDelegateImplV7$4.class...
processing android/support/v7/app/AppCompatDelegateImplV7$5.class...
processing android/support/v7/app/AppCompatDelegateImplV7$5$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$6.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ActionMenuPresenterCallback.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ActionModeCallbackWrapperV7.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ActionModeCallbackWrapperV7$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ListMenuDecorView.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelFeatureState.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelFeatureState$SavedState.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelFeatureState$SavedState$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelMenuPresenterCallback.class...
processing android/support/v7/app/AppCompatDialog.class...
processing android/support/v7/app/AppCompatDialogFragment.class...
processing android/support/v7/app/AppCompatViewInflater.class...
processing android/support/v7/app/AppCompatViewInflater$DeclaredOnClickListener.class...
processing android/support/v7/app/NavItemSelectedListener.class...
processing android/support/v7/app/NotificationCompat.class...
processing android/support/v7/app/NotificationCompat$1.class...
processing android/support/v7/app/NotificationCompat$Builder.class...
processing android/support/v7/app/NotificationCompat$IceCreamSandwichExtender.class...
processing android/support/v7/app/NotificationCompat$JellybeanExtender.class...
processing android/support/v7/app/NotificationCompat$LollipopExtender.class...
processing android/support/v7/app/NotificationCompat$MediaStyle.class...
processing android/support/v7/app/NotificationCompatImpl21.class...
processing android/support/v7/app/NotificationCompatImplBase.class...
processing android/support/v7/app/ToolbarActionBar.class...
processing android/support/v7/app/ToolbarActionBar$1.class...
processing android/support/v7/app/ToolbarActionBar$2.class...
processing android/support/v7/app/ToolbarActionBar$ActionMenuPresenterCallback.class...
processing android/support/v7/app/ToolbarActionBar$MenuBuilderCallback.class...
processing android/support/v7/app/ToolbarActionBar$PanelMenuPresenterCallback.class...
processing android/support/v7/app/ToolbarActionBar$ToolbarCallbackWrapper.class...
processing android/support/v7/app/TwilightCalculator.class...
processing android/support/v7/app/TwilightManager.class...
processing android/support/v7/app/TwilightManager$1.class...
processing android/support/v7/app/TwilightManager$TwilightState.class...
processing android/support/v7/app/WindowDecorActionBar.class...
processing android/support/v7/app/WindowDecorActionBar$1.class...
processing android/support/v7/app/WindowDecorActionBar$2.class...
processing android/support/v7/app/WindowDecorActionBar$3.class...
processing android/support/v7/app/WindowDecorActionBar$ActionModeImpl.class...
processing android/support/v7/app/WindowDecorActionBar$TabImpl.class...
ignored resource android/support/v7/appcompat/
processing android/support/v7/appcompat/BuildConfig.class...
ignored resource android/support/v7/graphics/
ignored resource android/support/v7/graphics/drawable/
processing android/support/v7/graphics/drawable/DrawableUtils.class...
processing android/support/v7/graphics/drawable/DrawableWrapper.class...
processing android/support/v7/graphics/drawable/DrawerArrowDrawable.class...
processing android/support/v7/graphics/drawable/DrawerArrowDrawable$ArrowDirection.class...
ignored resource android/support/v7/text/
processing android/support/v7/text/AllCapsTransformationMethod.class...
ignored resource android/support/v7/transition/
processing android/support/v7/transition/ActionBarTransition.class...
ignored resource android/support/v7/view/
processing android/support/v7/view/ActionBarPolicy.class...
processing android/support/v7/view/ActionMode.class...
processing android/support/v7/view/ActionMode$Callback.class...
processing android/support/v7/view/CollapsibleActionView.class...
processing android/support/v7/view/ContextThemeWrapper.class...
processing android/support/v7/view/StandaloneActionMode.class...
processing android/support/v7/view/SupportActionModeWrapper.class...
processing android/support/v7/view/SupportActionModeWrapper$CallbackWrapper.class...
processing android/support/v7/view/SupportMenuInflater.class...
processing android/support/v7/view/SupportMenuInflater$InflatedOnMenuItemClickListener.class...
processing android/support/v7/view/SupportMenuInflater$MenuState.class...
processing android/support/v7/view/ViewPropertyAnimatorCompatSet.class...
processing android/support/v7/view/ViewPropertyAnimatorCompatSet$1.class...
processing android/support/v7/view/WindowCallbackWrapper.class...
ignored resource android/support/v7/view/menu/
processing android/support/v7/view/menu/ActionMenuItem.class...
processing android/support/v7/view/menu/ActionMenuItemView.class...
processing android/support/v7/view/menu/ActionMenuItemView$ActionMenuItemForwardingListener.class...
processing android/support/v7/view/menu/ActionMenuItemView$PopupCallback.class...
processing android/support/v7/view/menu/BaseMenuPresenter.class...
processing android/support/v7/view/menu/BaseMenuWrapper.class...
processing android/support/v7/view/menu/BaseWrapper.class...
processing android/support/v7/view/menu/ExpandedMenuView.class...
processing android/support/v7/view/menu/ListMenuItemView.class...
processing android/support/v7/view/menu/ListMenuPresenter.class...
processing android/support/v7/view/menu/ListMenuPresenter$MenuAdapter.class...
processing android/support/v7/view/menu/MenuBuilder.class...
processing android/support/v7/view/menu/MenuBuilder$Callback.class...
processing android/support/v7/view/menu/MenuBuilder$ItemInvoker.class...
processing android/support/v7/view/menu/MenuDialogHelper.class...
processing android/support/v7/view/menu/MenuItemImpl.class...
processing android/support/v7/view/menu/MenuItemImpl$1.class...
processing android/support/v7/view/menu/MenuItemWrapperICS.class...
processing android/support/v7/view/menu/MenuItemWrapperICS$ActionProviderWrapper.class...
processing android/support/v7/view/menu/MenuItemWrapperICS$CollapsibleActionViewWrapper.class...
processing android/support/v7/view/menu/MenuItemWrapperICS$OnActionExpandListenerWrapper.class...
processing android/support/v7/view/menu/MenuItemWrapperICS$OnMenuItemClickListenerWrapper.class...
processing android/support/v7/view/menu/MenuItemWrapperJB.class...
processing android/support/v7/view/menu/MenuItemWrapperJB$ActionProviderWrapperJB.class...
processing android/support/v7/view/menu/MenuPopupHelper.class...
processing android/support/v7/view/menu/MenuPopupHelper$MenuAdapter.class...
processing android/support/v7/view/menu/MenuPresenter.class...
processing android/support/v7/view/menu/MenuPresenter$Callback.class...
processing android/support/v7/view/menu/MenuView.class...
processing android/support/v7/view/menu/MenuView$ItemView.class...
processing android/support/v7/view/menu/MenuWrapperFactory.class...
processing android/support/v7/view/menu/MenuWrapperICS.class...
processing android/support/v7/view/menu/SubMenuBuilder.class...
processing android/support/v7/view/menu/SubMenuWrapperICS.class...
ignored resource android/support/v7/widget/
processing android/support/v7/widget/AbsActionBarView.class...
processing android/support/v7/widget/AbsActionBarView$1.class...
processing android/support/v7/widget/AbsActionBarView$VisibilityAnimListener.class...
processing android/support/v7/widget/ActionBarBackgroundDrawable.class...
processing android/support/v7/widget/ActionBarBackgroundDrawableV21.class...
processing android/support/v7/widget/ActionBarContainer.class...
processing android/support/v7/widget/ActionBarContextView.class...
processing android/support/v7/widget/ActionBarContextView$1.class...
processing android/support/v7/widget/ActionBarOverlayLayout.class...
processing android/support/v7/widget/ActionBarOverlayLayout$1.class...
processing android/support/v7/wid<message truncated>

**Comment by renanpc** [comment] 2016-05-22 18:47
Could compile disabling all jar files from version 8.4.0, below:

![image](https://cloud.githubusercontent.com/assets/6960326/15455744/11884634-2034-11e6-8ed1-eff80a1dfa7b.png)

**Comment by dogancaufuk** [comment] 2016-05-24 15:36
This solution is compiling without error but not working only ads working not play games

**Comment by renanpc** [comment] 2016-05-24 16:22
Yes, that is another problem, i've created a post here [http://forum.unity3d.com/threads/invalidoperationexception-there-was-an-error-creating-a-gameservices-object-check-for-log-errors-f.405980/](url), take a look to know if is the same problem you have.

**Comment by dogancaufuk** [comment] 2016-05-24 16:48
Yes same but you got "InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK" this error because of unchecking play services.. when you unchecked them compiling okey but there then is no play service on build so you got a different error

**Comment by renanpc** [comment] 2016-05-24 17:04
Checking Play-Services-Games and Play-Services-Plus i can compile correctly, i have unchecked only Play-Services-Nearby and Play-Services-Drive.

**Comment by dogancaufuk** [comment] 2016-05-24 17:13
Did you tried to sign in google play on your project? and did you send any score? Not working for me without Play-Services-Nearby and Play-Services-Drive

**Comment by renanpc** [comment] 2016-05-24 17:28
I've tried everything, and keep getting the same error. When i enable Play-Services-Nearby and Play-Services-Drive i can't compile because of the dex conversion error.

**Comment by rampara** [comment] 2016-05-24 22:51
@renanpc the issue is you're running into is likely caused by you trying to use inconsistent versions of play services together (play-services-games 8.4.0 and play-services-base 9.0.0). Can you update your dependencies to use the latest version available. Dependencies should be declared within the `Assets/PlayServicesResolver/Editor/` directory of your Unity project.

**Comment by renanpc** [comment] 2016-05-25 00:32
@rampara what files i need to edit in that folder ? SampleDependencies.cs ?

Thx...

**Comment by dogancaufuk** [comment] 2016-05-25 11:32
I think this error is about google play plugin not admob;

Assets/PlayServicesResolver/Editor/Admobdependencies.cs
svcSupport.DependOn("com.google.android.gms", "play-services-ads", "9.0.0");

Assets/GooglePlayGames/PluginVersion.cs
public const string PlayServicesVersionConstraint = "9.0.0";

ProjectSettings/GoogleDependencyGooglePlayGames.xml
Change all versions to 9.0.0

ProjectSettings/GoogleDependencyAdMobUnity.xml
Change all versions to 9.0.0

After them "Window / Google Play Games / Setup /Android Setup" and accept all changes

**Compile success without any errors**

But its calling another project id not my id that i was saved maybe it can be my problem with google play account i couldn't find 608941808256 id anywhere its not mine..

Access Not Configured. Google Play Game Services API has not been used in project 608941808256 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/games/overview?project=608941808256 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by alternativerichie** [comment] 2016-05-26 15:46
I am at a loss with this. Game Play Services was working fine until I added Admob recently.  
I thought I'd fix it by adding latest Game Play Services.  @dogancaufuk tried your dependency settings and managed to get it to build with all versions of play-services saying 9.0.0.  Thanks for that.

But now when I go to login on the game it just comes up with the Create a Gamer ID screen and doesn't log me in.

Is there no fix for this, which version combination of Game Play Services and Admob do I need to go back to, to get this working again?

How are people getting around this?

Thanks

**Comment by rampara** [comment] 2016-05-29 02:24
As @dogancaufuk mentioned, AdMob dependencies are declared in the `AdMobDependencies` file within the `Assets/PlayServicesResolver/Editor` directory of your Unity project. Google Play Games dependencies should be declared in the `GPGPDependencies` files within the `Assets\GooglePlayGames\Editor` directory of your Unity project.

**Comment by rampara** [comment] 2016-10-10 21:04
The latest version of the plugin (v.3.1.0) resolves issues caused by declaring different versions of Google Play services dependencies from separate plugins (ie. Admob and Google Play Games).

**Closed by rampara** 2016-10-10 21:04 UTC
Labels: plugin bug

**Comment by vin223** [comment] 2016-11-29 17:58
Can anybody help me?? i really need your helpp..
any of you know how to fix this problem ??

CommandInvokationFailure: Unable to convert classes into dex format.
D:/Ervina/Java/jdk1.7.0_79\bin\java.exe -Xmx1024M -Dcom.android.sdkmanager.toolsdir="D:/Ervina/andoidsdk\tools" -Dfile.encoding=UTF8 -jar "D:\Ervina\tugas TIK\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at SDKMain.main(SDKMain.java:127)
]
stdout[

]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.HostView:OnGUI()

**Comment by rampara** [comment] 2016-11-29 19:39
I would recommend opening a new issue rather than following up on one that's already been closed (especially since your issue seems to be different). Can you try updating the version of JDK used to Unity to Java 8.
