### ISSUE TITLE
UnityMediationAdapter: An ad is already loading for placement ID

### ISSUE THREAD

**Issue by madTeddy** [googleads/googleads-mobile-unity#1234] opened 2020-04-03 11:16 UTC
I'm using **Unity Ads mediation**, and often I cannot get the ads. In the logcat every time I see these messages: 

> E/UnityMediationAdapter( 4651): An ad is already loading for placement ID: interstitial
> E/UnityMediationAdapter( 4651): Failed to load Interstitial ad from Unity Ads: INTERNAL_ERROR

After waiting some time, IsLoaded still equals to false, and when I trying to load new ad, I see this message again. Only resetting the Google Ads ID in device Google settings helps, but not for long.

_In mediation test suite all is fine with loading ads._

**Comment by nvtuan96** [comment] 2020-04-10 07:28
same issue

**Comment by stowy** [comment] 2020-04-10 15:23
This is expected behavior, I believe you are hitting [this bit of code](https://github.com/googleads/googleads-mobile-android-mediation/blob/4548c1f91afa2f72469bce62c866f4028cd9e299/ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java#L125).

Placements [are untracked](https://github.com/googleads/googleads-mobile-android-mediation/blob/4548c1f91afa2f72469bce62c866f4028cd9e299/ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java#L245) when loading is completed from the Unity side. Can you confirm that the Unity ad loading completes when you see this error?

**Comment by madTeddy** [comment] 2020-04-12 11:53
> This is expected behavior, I believe you are hitting [this bit of code](https://github.com/googleads/googleads-mobile-android-mediation/blob/4548c1f91afa2f72469bce62c866f4028cd9e299/ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java#L125).
> 
> Placements [are untracked](https://github.com/googleads/googleads-mobile-android-mediation/blob/4548c1f91afa2f72469bce62c866f4028cd9e299/ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java#L245) when loading is completed from the Unity side. Can you confirm that the Unity ad loading completes when you see this error?

I can't confirm, because how I said "IsLoaded" is equal to false all the time and I see message about "ad is already loading". That is some kind of "No Fill" or what?

**Comment by stowy** [comment] 2020-04-13 16:49
It sounds to me like the request is not completing in the first instance. What do your logs look like after making the first request? Have you tried recording a Charles proxy session to inspect the network traffic?

**Comment by kunny** [comment] 2023-01-09 15:00
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!

**Closed by kunny** 2023-01-09 15:00 UTC
Labels: obsolete
