### ISSUE TITLE
AdMob IOS Issue getting NSURLSession/NSURLConnection HTTP (kCFStreamErrorDomainSSL, -9814)

### ISSUE THREAD

**Issue by usamaB** [googleads/googleads-mobile-unity#260] opened 2016-08-17 07:27 UTC
I don't have CocoaPods installed but I have added GoogleMobileAds.framework manually. The build runs, but on AdRequest Call NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9814) is shown in the console and nothing happens thereafter.
I'm using unity 5.3.4f1 and Xcode 7.3.1.

**Comment by rampara** [comment] 2016-08-17 17:27
Have you set an ATS exception in your app, as described in your [developer docs](https://firebase.google.com/docs/admob/ios/ios9)?

**Comment by usamaB** [comment] 2016-08-17 21:03
what is there to set? ATS is set to true automatically. Should I add 

> <key>NSAppTransportSecurity</key>
> <dict>
>     <key>NSAllowsArbitraryLoads</key>
>     <true/>
> </dict>
 keys to the plist manually. 
P.S. I have tested on IOS 9 and on IOS 8 device both showing the same results.

**Comment by rampara** [comment] 2016-08-17 23:07
Yes, the ATS exception should be added to your info.plist manually as described in the link from my post above. However, this shouldn't be an issue on iOS 8 devices. Is there anything running on the device or on your network that my be blocking ad traffic?

**Comment by usamaB** [comment] 2016-08-18 06:42
Hey Rampara,
ATS is enabled by default. I mean NSAppTransportSecurity  is already there in the plist. If I view the plist source code <key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
Its already there which the doc asks to do essentially. A screen shot is also attached in propertylist form. 
![screen shot 2016-08-18 at 11 35 17 am](https://cloud.githubusercontent.com/assets/13015524/17764314/e5b4ef5a-6537-11e6-8d8a-44c6bee7691a.png)

And If we try to add NSAppTransportSecurity manually xcode automatically converts it to App Transport Security Settings. 

I get NSURLSession/NSURLConnection HTTP load failed  erorr with 2 different error codes first 9814 and second 9802.

**Comment by rampara** [comment] 2016-08-18 07:54
Is there anything running on the device or on your network that may be blocking ad traffic? Are you able to reproduce this issue both over WiFi and a mobile data connection?

**Comment by usamaB** [comment] 2016-08-18 07:56
I have integrated multiple ad networks and all are working fine but the issue only exists here. I want to use its mediation. Till now i have just tested Wifi I can test on data though.

**Comment by usamaB** [comment] 2016-08-18 07:58
ATM Im trying to make in it work in a sample project with just admob and Unity added nothing else.

**Comment by usamaB** [comment] 2016-08-18 11:41
Its strange the same build worked on Iphone5 with 81.1 but had the above error on ipod5 with 8.1.1 and both running on the same network. Any idea whats wrong?

**Comment by rampara** [comment] 2016-08-18 17:48
On 5th gen iPod running iOS 8.2 (closest I could get to 8.1.1), I'm able to request and display ads without issue using the sample app from this repository. Are you seeing this issue using our sample app to request test ads?

**Comment by rampara** [comment] 2016-11-30 00:55
Closing this issue due to it's age and non-response. If this issue persists for you, please re-open the issue.

**Closed by rampara** 2016-11-30 00:55 UTC
Labels: support question
