### ISSUE TITLE
Debug.Log doesn't work on handler

### ISSUE THREAD

**Issue by duchanhleo** [googleads/googleads-mobile-unity#311] opened 2016-11-21 06:09 UTC
Hello,
I'm getting a strange issue. Debug.Log doesn't show the log if I put it on handler method. But it show up on other places. I haven't never seen that issue before. Please explain to me why the logs don't show up on handler method and how to show them up.
Thanks

**Comment by trtuanpham** [comment] 2016-11-21 06:17
Me too

**Comment by duchanhleo** [comment] 2016-11-21 07:06
Hard to debug without log. do you have any idea, @trtuanpham ?

**Comment by trtuanpham** [comment] 2016-11-21 07:18
I think you need use old version and wait. @duchanhleo

**Comment by duchanhleo** [comment] 2016-11-21 07:34
Thank you so much. I'm switching to Unity Plugin v3.1.1.

**Comment by duchanhleo** [comment] 2016-11-21 07:54
@trtuanpham hey man, do you know which version work without that issue? I tried 3.1.1, it still there

**Comment by trtuanpham** [comment] 2016-11-21 15:55
@duchanhleo sr im working on 312

**Comment by rampara** [comment] 2016-11-29 22:32
@trtuanpham @duchanhleo in the [sample application]() from this repo, the Monobehavior.print commands (which should be identical to Debug.log) work without issue for me on both Android and iOS. Are you able to reproduce your issue with this sample app?

**Comment by trtuanpham** [comment] 2016-12-06 00:50
@rampara i tried in the simple, it still there

**Comment by rampara** [comment] 2016-12-07 19:47
With the HelloWorld sample app, you're not seeing ad event information under the `Unity` tag in logcat for Android or in the Xcode console for iOS?

**Comment by trtuanpham** [comment] 2016-12-15 01:04
@rampara i use print of unity

**Comment by trtuanpham** [comment] 2016-12-15 01:10
@rampara I don't see it in editor and debug in android

**Comment by rampara** [comment] 2016-12-16 00:04
@trtuanpham I'm having trouble reproducing this behavior. Can you provide me a link to a Unity project (preferably a stripped down sample app similar to the one included in this repo) that exhibits this issue to help me debug.

**Comment by rampara** [comment] 2017-01-23 22:08
Closing this issue due to non-response. Please re-open if this issue persists for you.

**Closed by rampara** 2017-01-23 22:08 UTC
Labels: support question
