### ISSUE TITLE
Ad Closed Events not working

### ISSUE THREAD

**Issue by albus702** [googleads/googleads-mobile-unity#124] opened 2015-09-18 16:03 UTC
Code: 
Interstitial.LoadAd(request);
Interstitial.AdClosed+=delegate{ Application.Quit(); };

The above code works with older versions of this package but does not work with the latest version and Unity 5.

**Comment by rampara** [comment] 2015-10-07 21:44
In our sample application linked [here](https://github.com/googleads/googleads-mobile-unity/tree/master/unity/samples/HelloWorld), I am able to receive the ad closing and ad closed events for interstitials. Are you able to reproduce your problem in our sample application?

- Ram

**Comment by rampara** [comment] 2016-01-04 17:24
Closing issue due to non-response. If this issue persists, please re-open.

- Ram

**Closed by rampara** 2016-01-04 17:24 UTC
