### ISSUE TITLE
Support of Native Ads Advanced?

### ISSUE THREAD

**Issue by litemesa** [googleads/googleads-mobile-unity#617] opened 2018-02-17 16:02 UTC
Hi, as Native Express Ad format is being discontinued, do you have any plans to support Native Advanced Ad format?

**Comment by rampara** [comment] 2018-03-01 01:21
@litemesa extending this plugin to support Native Ads advanced is currently being investigated.

**Comment by rampara** [comment] 2018-03-01 01:22
Closing as duplicate of #146

**Closed by rampara** 2018-03-01 01:22 UTC
Labels: P3, duplicate, feature request
