### ISSUE TITLE
Interstitial error but banner can load normal

### ISSUE THREAD

**Issue by Fuatnow** [googleads/googleads-mobile-unity#171] opened 2016-02-17 17:11 UTC
02-17 17:07:21.737: I/Unity(17537): AndroidJavaException: java.lang.NoSuchMethodError: no method with name='loadAd' signature='(Lcom.google.android.gms.ads.AdRequest;)V' in class Lcom/google/unity/ads/Interstitial;
02-17 17:07:21.737: I/Unity(17537): java.lang.NoSuchMethodError: no method with name='loadAd' signature='(Lcom.google.android.gms.ads.AdRequest;)V' in class Lcom/google/unity/ads/Interstitial;
02-17 17:07:21.737: I/Unity(17537): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
02-17 17:07:21.737: I/Unity(17537): 	at com.unity3d.player.UnityPlayer.a(Unknown Source)
02-17 17:07:21.737: I/Unity(17537): 	at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
02-17 17:07:21.737: I/Unity(17537):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0

**Comment by rampara** [comment] 2016-02-17 21:09
Are you using the latest version of the plugin (3.0.1)? If you can link to a project where the problem is reproducible I can investigate further.

**Comment by Fuatnow** [comment] 2016-02-20 20:27
the other developer‘s application  in my device can display normal.

**Comment by Fuatnow** [comment] 2016-02-22 05:07
Today,I come to my company find a same device (Samsung-S4 android version) but the systme version is 5.0.1,it can load success.
Now, I'm so confuse.

**Comment by rampara** [comment] 2016-02-23 01:47
The log you provided doesn't include any information on why interstitials failed and I am unable to reproduce the issue. If you can provide a link to a project that exhibits the issue, I can investigate further.

**Comment by rampara** [comment] 2016-08-17 17:46
Closing issue due to non-response. If this issue persists, please re-open.

**Closed by rampara** 2016-08-17 17:46 UTC
Labels: support question

**Comment by MarouaneIdd** [comment] 2017-10-05 10:18
I'm using the last GoogleAds plugin ,Update the Sdk to lasts version 
Rewarded video is working fine , but the interstitial / banner  not working properly 
sometimes it actually works (interstitial) the first call , after the first show it dosnot shows again 
The problem become clearer when I add Firebase (Analytics) and OnsSignal plugin 
i think its related to (Google.Handler version)

**Comment by rampara** [comment] 2017-10-06 00:14
@MarouaneIdd can you open a new issue with more information. Do you receive an error code when you attempt to load and ad? Are you deploying to Android or iOS? Do you see anything in the log that may indicate the cause of the ad failing to load/display? What made your this the problem is related to Google Version Handler?
