### ISSUE TITLE
AdMob banner in a Unity Android game shows up on the top with AdPosition.Bottom

### ISSUE THREAD

**Issue by RobertRybaric** [googleads/googleads-mobile-unity#639] opened 2018-03-25 09:07 UTC
Hi, I am now testing a new Unity game for Android on 3 different devices, a Redmi 4A smartphone, a Samsung Galaxy Tab 8 tablet and a Huawei MediaPad 2 tablet. The game has portrait orientation only and I am showing an AdMob banner (for now just test ad) from the very beginning of the game using  1 single call of the appropriate method:

`bannerView = new BannerView(adUnitId, AdSize.SmartBanner, AdPosition.Bottom);`

While on the first 2 devices, the banner is showing up correctly at the bottom of the screen, on the Huawei MediaPad 2 it is showing up on the top covering my status information and navigation button. Any idea, why is this happening and how to fix it?

Unity: 2017.3.1f1
AdMob PlugIn for Unity: 3.12

Thanks, Robert

**Comment by Hardik-Nadiyapara** [comment] 2018-03-28 09:11
Hello, Admob team 
@RobertRybaric i am facing same problem , banner stick to top of the screen,despite of set Adposition to bottom

**Comment by robertry** [comment] 2018-03-28 09:16
Hi @Hardik-Nadiyapara I have submitted this also into the Google Group for AdMob: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/google-admob-ads-sdk/I3oelAmkUXc/yhkdgbrwBAAJ
They are investigating and I have also figured out using their sample HelloWorld test project, that the issue happens on the device in question always after an interstitial or rewarded video is showed over an existing banner. In such case the banner just move from the bottom to the top and you see this happening when you close the interstitial or rewarded video. Suggest you try the sample as well, if it behaves the same way for you.

**Comment by rampara** [comment] 2018-03-28 19:27
@RobertRybaric @Hardik-Nadiyapara are you also only experiencing this issue after an interstitial or rewarded video is shown over the banner? Or is this issue consistently reproducible on certain devices for you?

**Comment by Hardik-Nadiyapara** [comment] 2018-03-29 03:59
hello @rampara  
i am facing the issue when i load banner after destroying it.
let me explain it by test case 
at game start load banner showing perfectly in the bottom of the screen
now when i am trying to destroy banner and load again then problem start means banner showing at the top of the screen.

**Comment by rampara** [comment] 2018-04-02 17:58
@Hardik-Nadiyapara I'm still unable to reproduce this issue as it seems device specific. Marking this as a duplicate of #572.

**Closed by rampara** 2018-04-02 17:58 UTC
Labels: P2, plugin bug
