### ISSUE TITLE
Banner position for 18:9 devices

### ISSUE THREAD

**Issue by msureka** [googleads/googleads-mobile-unity#584] opened 2017-12-15 06:41 UTC
Hello,

We are testing our game on Mi Mix 2 (actual screen size : 1080 x 2160), but in the game it gives us 1080 x 2030. This is one problem, but not related to Admob.

Our issue is the banner is not shown at the bottom of the screen. It is shown around 100-200 pixels above the bottom. This is much above the safe area (if any). 

On other Android devices it shows up fine.

Any ideas?

Thanks!

**Comment by rampara** [comment] 2017-12-15 19:10
@msureka this issue seems specific to the device rather than 18:9 devices as I did a quick test on a Pixel XL 2 and the banner is being positioned correctly. Currently, don't have access to a Mi Mix 2. Were you able to reproduce the issue on any other devices?

**Comment by rampara** [comment] 2018-01-30 20:55
Closing issue due to non-response. Please re-open if your issue persists.

**Closed by rampara** 2018-01-30 20:55 UTC
Labels: support question
