### ISSUE TITLE
Crash on Reward Video Completed on Android

### ISSUE THREAD

**Issue by msureka** [googleads/googleads-mobile-unity#682] opened 2018-06-01 06:19 UTC
Hello,

We just updated our game and added Firebase Cloud Messaging and Firebase Analytics packages, and now the game is crashing whenever a rewarded video completed callback is called.

Is there some conflict issue as a similar problem was reported a year back but was supposedly fixed?

Can you please check as our game is currently live but crashing whenever a rewarded video is played.

A snapshot of logcat is below:

06-01 11:22:04.973 15388-15388/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.spiel.manvsmissiles, PID: 15388
                                                   java.lang.Error: FATAL EXCEPTION [main]
                                                   Unity version     : 5.6.5p3
                                                   Device model      : Xiaomi MI MAX
                                                   Device fingerprint: Xiaomi/hydrogen/hydrogen:6.0.1/MMB29M/V7.5.6.0.MBCMIDE:user/release-keys
                                                   
                                                   Caused by: java.lang.AbstractMethodError: abstract method "void com.google.android.gms.ads.reward.RewardedVideoAdListener.onRewardedVideoCompleted()"
                                                       at com.google.android.gms.internal.zzafh.onRewardedVideoCompleted(Unknown Source)
                                                       at com.google.android.gms.internal.zzafd.onTransact(Unknown Source)
                                                       at android.os.Binder.transact(Binder.java:387)
                                                       at nx.b(:com.google.android.gms.dynamite_dynamitemodulesa@12688023@12.6.88 (040400-197970725):20)
                                                       at com.google.android.gms.ads.internal.reward.client.l.f(:com.google.android.gms.dynamite_dynamitemodulesa@12688023@12.6.88 (040400-197970725):27)
                                                       at com.google.android.gms.ads.internal.a.u(:com.google.android.gms.dynamite_dynamitemodulesa@12688023@12.6.88 (040400-197970725):471)
                                                       at com.google.android.gms.ads.internal.reward.d.i_(:com.google.android.gms.dynamite_dynamitemodulesa@12688023@12.6.88 (040400-197970725):88)
                                                       at com.google.android.gms.ads.internal.reward.mediation.h.h(:com.google.android.gms.dynamite_dynamitemodulesa@12688023@12.6.88 (040400-197970725):37)
                                                       at com.google.android.gms.ads.internal.reward.client.n.f(:com.google.android.gms.dynamite_dynamitemodulesa@12688023@12.6.88 (040400-197970725):96)
                                                       at com.google.android.gms.ads.internal.a.u(:com.google.android.gms.dynamite_dynamitemodulesa@12688023@12.6.88 (040400-197970725):471)
                                                       at com.google.android.gms.ads.internal.ak.Z(:com.google.android.gms.dynamite_dynamitemodulesa@12688023@12.6.88 (040400-197970725):261)
                                                       at com.google.android.gms.ads.internal.gmsg.am.a(:com.google.android.gms.dynamite_dynamitemodulesa@12688023@12.6.88 (040400-197970725):27)
                                                       at com.google.android.gms.ads.internal.webview.j.b(:com.google.android.gms.dynamite_dynamitemodulesa@12688023@12.6.88 (040400-197970725):346)
                                                       at com.google.android.gms.ads.internal.webview.ab.run(Unknown Source)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.google.android.gms.ads.internal.util.f.dispatchMessage(:com.google.android.gms.dynamite_dynamitemodulesa@12688023@12.6.88 (040400-197970725):9)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5442)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by rampara** [comment] 2018-06-25 09:46
Closing at duplicate of #695.

**Closed by rampara** 2018-06-25 09:46 UTC
Labels: P2, plugin bug

**Comment by Ruco** [comment] 2018-10-02 15:28
I have the exact same issue. (see also: #771 ) But the dependencies file already uses the correct version (15.0.1). So that's not the solution (in my case). Please advice.

**Comment by Ruco** [comment] 2018-10-03 07:50
I had been using the latest version of the plugin.
But was (finally and) actually able to solve it by downgrading to plugin version 3.13.0
