### ISSUE TITLE
Crash when showing Interstitial 

### ISSUE THREAD

**Issue by tienhagioi** [googleads/googleads-mobile-unity#449] opened 2017-06-20 04:49 UTC
Sometimes , my game crash while showing Interstitlal .This is debug log : 

`
I/WindowState(  446): WIN DEATH: Window{2207bc50 u0 com.sg.bubblepopstory/com.google.android.gms.ads.AdActivity}

I/WindowState(  446): WIN DEATH: Window{21ef1a88 u0 SurfaceView}

I/WindowManager(  446): Screenshot Window{2207bc50 u0 com.sg.bubblepopstory/com.google.android.gms.ads.AdActivity EXITING} was all black! mSurfaceLayer=21030 minLayer=21030 maxLayer=21030

I/WindowState(  446): WIN DEATH: Window{21eab208 u0 com.sg.bubblepopstory/com.google.firebase.MessagingUnityPlayerActivity}

D/dalvikvm(  446): GC_FOR_ALLOC freed 1105K, 22% free 24805K/31540K, paused 45ms, total 45ms

W/ActivityManager(  446): Exception thrown during pause

W/ActivityManager(  446): android.os.DeadObjectException

W/ActivityManager(  446): 	at android.os.BinderProxy.transact(Native Method)

W/ActivityManager(  446): 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:685)

W/ActivityManager(  446): 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1243)

W/ActivityManager(  446): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:4410)

W/ActivityManager(  446): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:4342)

W/ActivityManager(  446): 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9496)

W/ActivityManager(  446): 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9284)

W/ActivityManager(  446): 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10078)

W/ActivityManager(  446): 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9607)

W/ActivityManager(  446): 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

D/WindowManager(  446): adjustConfigurationLw, config:{1.3 ?mcc?mnc ?locale ?layoutDir sw360dp w360dp h615dp 320dpi nrml long port ?uimode ?night finger -keyb/v/h -nav/v} mLidState:1 mHasDockFeature:false mHasKeyboardFeature:false mHasHallSensorFeature:true config.hardKeyboardHidden:2

I/ActivityManager(  446): Restarting because process died: ActivityRecord{222911e8 u0 com.sg.bubblepopstory/com.google.firebase.MessagingUnityPlayerActivity}

W/ActivityManager(  446): Exception when starting activity com.sg.bubblepopstory/com.google.firebase.MessagingUnityPlayerActivity

W/ActivityManager(  446): android.os.DeadObjectException

W/ActivityManager(  446): 	at android.os.BinderProxy.transact(Native Method)

W/ActivityManager(  446): 	at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:773)

W/ActivityManager(  446): 	at com.android.server.am.ActivityStack.realStartActivityLocked(ActivityStack.java:942)

W/ActivityManager(  446): 	at com.android.server.am.ActivityStack.startSpecificActivityLocked(ActivityStack.java:1054)

W/ActivityManager(  446): 	at com.android.server.am.ActivityStack.resumeTopActivityLocked(ActivityStack.java:2095)

W/ActivityManager(  446): 	at com.android.server.am.ActivityStack.resumeTopActivityLocked(ActivityStack.java:1703)

W/ActivityManager(  446): 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1294)

W/ActivityManager(  446): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:4410)

W/ActivityManager(  446): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:4342)

W/ActivityManager(  446): 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9496)

W/ActivityManager(  446): 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9284)

W/ActivityManager(  446): 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10078)

W/ActivityManager(  446): 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9607)

W/ActivityManager(  446): 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

V/ActivityManager(  446): Cleanup Regular Process. app=ProcessRecord{224471c0 13331:com.sg.bubblepopstory/u0a10044}

I/ActivityManager(  446): Start proc com.sg.bubblepopstory for activity com.sg.bubblepopstory/com.google.firebase.MessagingUnityPlayerActivity: pid=13679 uid=10044 gids={50044, 3003, 1028}

W/AppLockService(13591): topActivity = com.sg.bubblepopstory PreviosActivity = com.google.android.gms.ads.AdActivity

I/ActivityManager(  446): Process com.sg.bubblepopstory (pid 13331) has died and restarted (pid 13679).
`

**Comment by rampara** [comment] 2017-06-20 18:29
@tienhagioi would you be able to provide a full log for this crash. Also, is this crash consistently reproducible for you or did you see the crash is a crash report?

**Comment by rampara** [comment] 2017-07-14 21:00
Closing due to age of issue. Please re-open if this issue persists for you.

**Closed by rampara** 2017-07-14 21:00 UTC
Labels: support question
