### ISSUE TITLE
AdmobDependencies.cs Error

### ISSUE THREAD

**Issue by malisasmaz** [googleads/googleads-mobile-unity#349] opened 2017-02-12 15:43 UTC
Assets/googleads-mobile-unity-master/source/plugin/Assets/GoogleMobileAds/Editor/AdMobDependencies.cs(30,36): error CS0103: The name `Google' does not exist in the current context

**Comment by rampara** [comment] 2017-02-13 20:28
Are you using the latest version of this plugin? Does the `Assets/PlayServicesResolver/Editor` directory of your Unity project include the files listed in the screenshot below?

<img width="474" alt="screen shot 2017-02-13 at 12 27 03 pm" src="https://cloud.githubusercontent.com/assets/11047881/22901827/d7c8ca96-f1e7-11e6-9f98-264f86645192.png">

**Comment by rampara** [comment] 2017-03-20 22:00
As this sounds like Unity Cloud Build support issue, I'm closing this as a duplicate of #333. If your issue is unrelated to Unity Cloud Build, please re-open the issue.

**Closed by rampara** 2017-03-20 22:00 UTC
Labels: support question
