### ISSUE TITLE
v6.0.0 add weird permission

### ISSUE THREAD

**Issue by hoainam1593** [googleads/googleads-mobile-unity#1620] opened 2021-05-21 03:26 UTC
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.22
  * Google Mobile Ads Unity plugin version: 6.0.0
  * Platform: android (iOS, Android, Unity Editor)
  * Platform OS version: all (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: all
  * Mediation ad networks used, and their versions: none

#### Steps to reproduce:

use admob v6.0.0 when I build, it yields 3 weird permissions: 
- android.permission.READ_EXTERNAL_STORAGE
- android.permission.READ_PHONE_STATE
- android.permission.WRITE_EXTERNAL_STORAGE
how can I get rid of those permissions?

**Comment by hoainam1593** [comment] 2021-05-21 08:53
I found the reason: in manifest file in `Assets\Plugins\Android\googlemobileads-unity.aar` missing `android:minSdkVersion` so it include permission `READ_EXTERNAL_STORAGE` & `READ_PHONE_STATE`


Solution: add `android:minSdkVersion` to that manifest by:
- unzip `googlemobileads-unity.aar` to folder `tempFolder`
- in manifest file, add `<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="29" />` inside `<manifest>` tag
- re-zip aar file by command: `jar cvf googlemobileads-unity.aar -C tempFolder/ .`

**Comment by mdobele** [comment] 2021-05-21 23:56
Just as an alternative solution, since I've had other plugins do the same is you can add these to your main manifest file and it should remove them in the final merged version.

`<uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove" />
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />
 <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="remove" />`

**Comment by EpicMark98** [comment] 2021-06-05 21:17
I was really struggling to fix this problem. Using the jar command as described above was not working and I was struggling to find the right place to put the three lines listed by mdobele. Finally, I solved the problem by adding an Android Manifest to Assets/Plugins/Android.
[AndroidManifest.txt](https://github.com/googleads/googleads-mobile-unity/files/6603247/AndroidManifest.txt)

**Comment by bankel** [comment] 2021-07-05 15:47
**manifest-merger-debug-report.txt**

`uses-permission#android.permission.WRITE_EXTERNAL_STORAGE
IMPLIED from /Users/lyf/Documents/merge fruit/MergeFruitAndroidProject/launcher/src/main/AndroidManifest.xml:3:1-10:12 reason: com.google.unity.ads has a targetSdkVersion < 4
uses-permission#android.permission.READ_PHONE_STATE
IMPLIED from /Users/lyf/Documents/merge fruit/MergeFruitAndroidProject/launcher/src/main/AndroidManifest.xml:3:1-10:12 reason: com.google.unity.ads has a targetSdkVersion < 4
uses-permission#android.permission.READ_EXTERNAL_STORAGE`

Why does Unity Admob add these Permissions that I never use? Please fix the bug

**Comment by chicotx56** [comment] 2021-07-19 22:16
when will the solution be released?

**Comment by rotter** [comment] 2021-07-24 18:19
This is a major problem, I just updated to 6.0.X and had this same problem, luckily I noticed Google Play warning of new permissions when I uploaded, or we would face major customer service problems (tons of emails, bad reviews, users not updating and not getting new fixes, etc)

**Comment by Radu6** [comment] 2021-07-29 20:55
Hello,
Why doesn't the library take the min sdk version specified in player settings?
Thanks

**Comment by ericleich** [comment] 2021-07-29 22:15
The library would have its own minSdkVersion requirements that should be the minimum of code it writes and any of its dependencies (e.g. Google Mobile Ads Android SDK). So it won't be your min version. v6.0.0 changed the build process and it looks like the version was unspecified. We'll aim to fix this before the next release.

**Comment by ddadkhah** [comment] 2021-09-20 03:40
> * jar cvf googlemobileads-unity.aar -C tempFolder/

Where should tempFolder be? And where the new .arr file will be created?

**Comment by chicotx56** [comment] 2021-09-20 10:52
> > * jar cvf googlemobileads-unity.aar -C tempFolder/
> 
> Where should tempFolder be? And where the new .arr file will be created?

The issue is fixed in latest plugin version https://github.com/googleads/googleads-mobile-unity/releases/tag/v6.1.0

**Comment by ddadkhah** [comment] 2021-09-21 06:05
> > > * jar cvf googlemobileads-unity.aar -C tempFolder/
> > 
> > 
> > Where should tempFolder be? And where the new .arr file will be created?
> 
> The issue is fixed in latest plugin version https://github.com/googleads/googleads-mobile-unity/releases/tag/v6.1.0

I found my answer. 
But new plugin has other issues. I submitted an issue.

**Comment by mopsicus** [comment] 2022-03-17 12:00
Now in version 7, plugin remove permissions:
```
android.permission.READ_EXTERNAL_STORAGE
android.permission.WRITE_EXTERNAL_STORAGE
```
from main manifest

**Comment by MarciOscura** [comment] 2022-03-25 06:10
I need read and write permissions but admob removes them from my manifest it's really annoying, fix that error, there are people who need read and write permissions

**Comment by githubsoooh** [comment] 2022-03-26 02:24
Permission is still added in version 7.0.0.

**Comment by MayisGM** [comment] 2022-03-31 10:35
> I need read and write permissions but admob removes them from my manifest it's really annoying, fix that error, there are people who need read and write permissions

Hi did you find a solution for this issue?

**Comment by mopsicus** [comment] 2022-03-31 11:24
> > I need read and write permissions but admob removes them from my manifest it's really annoying, fix that error, there are people who need read and write permissions
> 
> Hi did you find a solution for this issue?

Rollback to 6.1.2

**Comment by MayisGM** [comment] 2022-03-31 11:26
> > > I need read and write permissions but admob removes them from my manifest it's really annoying, fix that error, there are people who need read and write permissions
> > 
> > 
> > Hi did you find a solution for this issue?
> 
> Rollback to 6.1.2

Thank you for your fast response.

**Comment by lahmidi-developer** [comment] 2022-05-07 15:50
On player settings > Publishing Settings : Active Custom Main Manifest and add this 2 line 
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace"/>
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="replace" />

**Comment by brunomikoski** [comment] 2022-05-18 06:36
> Now in version 7, plugin remove permissions:
> 
> ```
> android.permission.READ_EXTERNAL_STORAGE
> android.permission.WRITE_EXTERNAL_STORAGE
> ```
> 
> from main manifest

Any news about this? I also need those permissions and now AdMob removes it.

**Comment by lahmidi-developer** [comment] 2022-05-19 17:32
@brunomikoski add this to AndroidManifest 

<uses-permission tools:node="replace" android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission tools:node="replace" android:name="android.permission.READ_EXTERNAL_STORAGE"/>

**Comment by lahmidi-developer** [comment] 2022-05-19 17:32
@brunomikoski add this to AndroidManifest
`<uses-permission tools:node="replace" android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission tools:node="replace" android:name="android.permission.READ_EXTERNAL_STORAGE"/>
-<application>`

**Comment by brunomikoski** [comment] 2022-05-21 17:37
> @brunomikoski add this to AndroidManifest `<uses-permission tools:node="replace" android:name="android.permission.WRITE_EXTERNAL_STORAGE"/> <uses-permission tools:node="replace" android:name="android.permission.READ_EXTERNAL_STORAGE"/>`

Cheers this fixed the issue! <3

**Comment by NVentimiglia** [comment] 2022-05-26 16:41
Fixed, please update.

**Closed by NVentimiglia** 2022-05-26 16:41 UTC

**Comment by Thinkershut** [comment] 2022-07-17 19:06
Using below mentioned package adding storage and phone permissions to app,

    Google Mobile Ads Unity Plugin v7.1.0
    native ads add-on

Unity Version : 2021.3.2f1
Build Platform : Android

Is the issue came again @NVentimiglia ? Tested with empty project too.
