### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by openxcellstudio** [googleads/googleads-mobile-unity#203] opened 2016-04-15 09:52 UTC
i get video load event and video start event but i dont get video complete means OnAdRewarded event after video watch sucessfully

after i close the ads i get event Videoclosed

**Comment by rampara** [comment] 2016-04-15 17:09
Which ad network and platform (iOS or Android) are you seeing this issue with? Are you using the latest adapters and SDKs as listed on our [mediation partners](https://developers.google.com/admob/android/mediation-networks) page?

**Comment by openxcellstudio** [comment] 2016-04-18 10:45
I am using Version 3.0.3 of Unity which is latest by date.
Platform is Unity - Android.

**Comment by rampara** [comment] 2016-04-18 17:49
The OnAdRewarded ad event will only be fired for [mediated rewarded video ads](https://developers.google.com/admob/android/rewarded-video). Video interstitials do not have rewards and will not fire the corresponding OnAdRewarded ad event. Is this issue you're having for mediated rewarded video? If so, which ad network are you mediating?

**Comment by openxcellstudio** [comment] 2016-04-19 05:38
04-19 10:58:23.533: I/Unity(11143): HandleRewardBasedVideoOpened event received
04-19 10:58:23.533:
 I/Unity(11143):  
04-19 10:58:23.533: I/Unity(11143): 
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
04-19 10:58:23.565: 
D/OpenGLRenderer(11143): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-19 10:58:23.611: I/OpenGLRenderer(11143): 
Initialized EGL, version 1.4
04-19 10:58:23.699: W/Ads(11143): Precache abort but no preload task running.
04-19 10:58:23.709:
 W/MediaPlayer(11143): Couldn't open file on client side; trying server side: java.io.FileNotFoundException:
 No content provider: https://www.youtube.com/get_video?video_id=zRtPUIumXcY&ts=1461043307&t=OTXUg_xcAHU3f1vK1H8FyNpdXRc&gad=1
04-19 10:58:23.714:
 W/MediaPlayer(11143): setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
04-19 10:58:23.822: W/cr_BindingManager(11143):
 Cannot call determinedVisibility() - never saw a connection for the pid: 11143



THIS IS LOG FILE CONTENT when reward video is playing..

**Comment by openxcellstudio** [comment] 2016-04-19 05:51
https://developers.google.com/admob/android/games#helpful_primers

we are following this instruction and we use the GoogleMobileAdsDemoScript that is also given in the package

**Comment by openxcellstudio** [comment] 2016-04-20 05:49
any help please

**Comment by openxcellstudio** [comment] 2016-04-20 10:22
W/MediaPlayer(32188): setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder

error..!!!

**Comment by rampara** [comment] 2016-04-21 00:43
Which ad network are you mediating rewarded video ads from?

**Comment by openxcellstudio** [comment] 2016-04-21 05:12
admob reward video

**Comment by openxcellstudio** [comment] 2016-04-22 09:37
04-22 14:44:05.527: I/Ads(19365): Ad opening.

04-22 14:44:05.527: I/Ads(19365): Ad opening.

04-22 14:44:05.544: I/Unity(19365): HandleRewardBasedVideoOpened event received

04-22 14:44:05.544: I/Unity(19365):  

04-22 14:44:05.544: I/Unity(19365): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

04-22 14:44:06.404: W/MediaPlayer(19365): Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /data/user/0/com.oxll.adsjk/cache/admobVideoStreams/44C799CC39176495425A310D1BE59762

04-22 14:44:06.408: W/MediaPlayer(19365): setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder

04-22 14:44:06.459: D/MediaPlayer(19365): setSubtitleAnchor in MediaPlayer

04-22 14:44:06.462: I/Ads(19365): AdMediaPlayerView stream dimensions: 640 x 360

04-22 14:44:06.938: W/MediaPlayer(19365): info/warning (3, 0)

**Comment by openxcellstudio** [comment] 2016-04-22 10:34
i solved media player problem but still get this log and plugin not call method OnRewarded()
04-22 16:01:30.225: V/MediaPlayer-JNI(17782): getCurrentPosition: 9958 (msec)
04-22 16:01:30.255: V/MediaPlayer-JNI(17782): getCurrentPosition: 9958 (msec)
04-22 16:01:30.355: V/MediaPlayer(17782): message received msg=2, ext1=0, ext2=0
04-22 16:01:30.355: V/MediaPlayer(17782): playback complete
04-22 16:01:30.355: V/MediaPlayer(17782): callback application
04-22 16:01:30.355: V/MediaPlayer(17782): back from callback
04-22 16:01:30.355: V/MediaPlayer(17782): message received msg=7, ext1=0, ext2=0
04-22 16:01:30.355: V/MediaPlayer(17782): unrecognized message: (7, 0, 0)
04-22 16:01:30.355: V/MediaPlayer(17782): callback application
04-22 16:01:30.355: V/MediaPlayer(17782): back from callback
04-22 16:01:30.395: V/MediaPlayer-JNI(17782): getCurrentPosition: 10063 (msec)
04-22 16:01:30.395: V/MediaPlayer-JNI(17782): isPlaying: 0
04-22 16:01:30.395: V/MediaPlayer-JNI(17782): getCurrentPosition: 10063 (msec)
04-22 16:01:30.650: V/MediaPlayer-JNI(17782): getCurrentPosition: 10063 (msec)

**Comment by rampara** [comment] 2016-04-22 17:40
Currently AdMob only supports rewarded video ads through mediation. Can you provide a Charles log of your rewarded video ad request and response?

**Comment by openxcellstudio** [comment] 2016-04-25 06:16
we add the unity as third part reward ads but how many thing we have to import in unity project?

i added unityadpater.jar in to unity project but it fail to load video this is error in log

is there any thing that we have to add in unity project ?

when i add unity-ads.aar file of frame work than it give error command invocation failuer 

CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:/Program Files/Java/jdk1.8.0_71\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="E:/android-sdk-windows\tools" -Dfile.encoding=UTF8 -jar "E:\InstalledUnity\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/BuildConfig;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/IUnityAdsListener;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/UnityAds;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/UnityAds$1;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/UnityAds$2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/UnityAds$3;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/UnityAdsDeviceLog;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/UnityAdsDeviceLog$1;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/UnityAdsDeviceLog$UnityAdsLogLevel;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
	... 9 more
]

**Comment by rampara** [comment] 2016-04-25 18:25
The build error you posted in your latest response is because you're including duplicate files in your Unity project. Can you ensure you don't have duplicate Unity Ads JARs or AARs.

**Comment by openxcellstudio** [comment] 2016-04-28 12:10
there is no duplicate jar file or aar file if i remove that 2 file than i can build and interstitial and banner works fine but if i add this 2 file for reward video ads than it not allow me to build 

i am using unity reward video ads as third party in admob reward video so i have to add this 2 file in plugin folder 

UnityAdsAdapter.jar   and   unity-ads.aar


please try your self
import this plugin https://github.com/googleads/googleads-mobile-unity/releases/tag/v3.0.3
and than import this plugin https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/current-build

now set admob interstital banner and reward id 

add unity as reward ads third party in admob 

and add this 2 file => UnityAdsAdapter.jar   and   unity-ads.aar
from https://dl.google.com/googleadmobadssdk/adapterunityandroid.zip
and https://github.com/Applifier/unity-ads-sdk

and try to build that's it check reward video is loading and if it give rewarded event after complete video

if you solve this issue ,many developer can use it 

thanks in advance

**Comment by openxcellstudio** [comment] 2016-05-03 05:03
no one can reply??

**Comment by openxcellstudio** [comment] 2016-05-04 10:55
when we just not import 
https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/current-build

this plugin than reward video works perfectly

**Comment by rampara** [comment] 2016-05-04 20:53
Using the sample application from this repo, the Google Mobile Ad Unity plugin, the Google Play Games Unity plugin, the Unity Android SDK and the Unity Adapter, I'm able to successfully request and display rewarded video ads with the expected ad events. I've attached the project [here](https://drive.google.com/file/d/0B2oE3iOknPmMVHFfSHcyZy1zR2s/view?usp=sharing).

**Comment by openxcellstudio** [comment] 2016-05-05 09:46
05-05 15:15:52.791: I/Unity(16848): HandleRewardBasedVideoFailedToLoad event received with message: No fill

with your project i not changed any thing even id also same

**Comment by openxcellstudio** [comment] 2016-05-05 12:34
i copy your folder from your project and i put that folder in another project than it gives again same error

**Comment by rampara** [comment] 2016-05-05 17:45
None of the plugins, SDKs or adapters included in the project I linked were modified. If you can link to a Unity project where you're able to reproduce the error it would help me investigate what's happening.

**Comment by rampara** [comment] 2016-08-16 18:44
Closing issue due to non-response. If this issue persists, please re-open.

**Closed by rampara** 2016-08-16 18:44 UTC
Labels: support question
