### ISSUE TITLE
Crash game at the begining (3.15.1)

### ISSUE THREAD

**Issue by mohammadmahdi123** [googleads/googleads-mobile-unity#811] opened 2018-12-03 08:53 UTC
Hi. I imported google ad 3.15.1 to my unity project and then resolve it successfully.
I added app id in manifest correctly according to the developer guide.

`12-03 08:49:15.753  3284  3300 D Unity   : -------------------------RequestRewardBasedVideo---------------------------: 0 at ./Runtime/Export/Debug.bindings.h:43 (17408, 0, 0)
12-03 08:49:15.754  3284  3300 I Unity   : -------------------------RequestRewardBasedVideo---------------------------
12-03 08:49:15.754  3284  3300 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
12-03 08:49:15.754  3284  3300 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
12-03 08:49:15.754  3284  3300 I Unity   : UnityEngine.Logger:Log(LogType, Object)
12-03 08:49:15.754  3284  3300 I Unity   : UnityEngine.Debug:Log(Object)
12-03 08:49:15.754  3284  3300 I Unity   : RewardBasedVideoAdProvider:RequestRewardBasedVideo() (at F:\Game Projects\Looper\Assets\RewardBasedVideoAdProvider.cs:100)
12-03 08:49:15.754  3284  3300 I Unity   :
12-03 08:49:15.754  3284  3300 I Unity   : (Filename: F Line: 0)
12-03 08:49:15.754  3284  3300 I Unity   :
12-03 08:49:15.763  3284  3300 D Unity   : java.lang.ClassNotFoundException: com.google.android.gms.ads.AdRequest$Builder: 0 at ./Runtime/Export/Debug.bindings.h:43 (17408, 0, 0)
12-03 08:49:15.782  3284  3300 I Unity   : java.lang.ClassNotFoundException: com.google.android.gms.ads.AdRequest$Builder
12-03 08:49:15.782  3284  3300 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
12-03 08:49:15.782  3284  3300 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
12-03 08:49:15.782  3284  3300 I Unity   : UnityEngine.Logger:Log(LogType, Object)
12-03 08:49:15.782  3284  3300 I Unity   : UnityEngine.Debug:Log(Object)
12-03 08:49:15.782  3284  3300 I Unity   : RewardBasedVideoAdProvider:RequestRewardBasedVideo() (at F:\Game Projects\Looper\Assets\RewardBasedVideoAdProvider.cs:111)
12-03 08:49:15.782  3284  3300 I Unity   :
12-03 08:49:15.782  3284  3300 I Unity   : (Filename: F Line: 0)
12-03 08:49:15.782  3284  3300 I Unity   :
12-03 08:49:15.789  3284  3308 E mono    :
12-03 08:49:15.789  3284  3308 E mono    : Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object
12-03 08:49:15.789  3284  3308 E mono    :   at UnityEngine.AndroidJavaObject.Dispose (Boolean disposing) [0x00007] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:230
12-03 08:49:15.789  3284  3308 E mono    :   at UnityEngine.AndroidJavaObject.Finalize () [0x00003] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:225
`

**Comment by rampara** [comment] 2018-12-05 20:30
@mohammadmahdi123 have you correctly included the required Google Play dependencies into your project? Can you post the contents of you `Assets/Plugins/Android` directory?

**Comment by mohammadmahdi123** [comment] 2018-12-08 16:09
I can not resolve with new resolver (force resolve: resolution failed) but can resolve with old one (resolve client jar). When my app is started, it crashes. (class not found com.google.android.gms.ads).
I can sign in and leaderboards are displaying.

**Comment by rampara** [comment] 2019-01-23 03:32
Closing as duplicate of #814.

**Closed by rampara** 2019-01-23 03:32 UTC
Labels: P2, support question
