### ISSUE TITLE
reward video callback not working in iOS build

### ISSUE THREAD

**Issue by hkk007** [googleads/googleads-mobile-unity#769] opened 2018-09-28 07:18 UTC
In iOS build
when reward video is playing game not automatically paused. so i used 
MobileAds.SetiOSAppPauseOnBackground(true);

Then game paused 
but problem is when i resume game.

    HandleRewardBasedVideoRewarded(object sender, Reward args)    is called when video is completed not closed.

HandleRewardBasedVideoClosed(object sender, EventArgs args)  this method is called only when user closed before video watching completely.  This method not calling if user close the video after completing video and rewarded.

please help as soon as possible.

**Comment by sahujaunpuri** [comment] 2018-09-28 07:55
Where u get reward placement id?
Kya aap mujhe reward placement id generate krne ka link de sakte hai bhaee?

**Comment by hkk007** [comment] 2018-09-28 08:08
> Where u get reward placement id?
> Kya aap mujhe reward placement id generate krne ka link de sakte hai bhaee?

Go to admob -> Apps -> Add Ad unit -> select reward video and follow steps

If you know interstitial and banner ads then it is near to it.

**Comment by hkk007** [comment] 2018-09-28 09:35
please reply to my problem here

**Comment by rampara** [comment] 2018-10-03 01:12
@hkk007 i'm not able to reproduce the behavior you described in your original post. Are you using mediation?

**Comment by rampara** [comment] 2018-10-26 17:46
@hkk007 can you provide a test or sample project that reproduces this issue?

**Comment by rampara** [comment] 2019-01-23 03:43
Closing due to non-response.

**Closed by rampara** 2019-01-23 03:43 UTC
Labels: P2, support question
