### ISSUE TITLE
Crash on iOS: rewardedAd:didFailToPresentWithError throws

### ISSUE THREAD

**Issue by mohammaddabiri** [googleads/googleads-mobile-unity#1169] opened 2020-02-12 11:57 UTC
Observed through Crashlytics on live. 

Fatal Exception: NSInvalidArgumentException
-[__NSCFString localizedFailureReason]: unrecognized selector sent to instance 

![image](https://user-images.githubusercontent.com/5851479/74332508-c2136580-4d8d-11ea-9add-6e8716a1da46.png)

We can't reproduce it locally easily but it happens intermittently to live users.
We handle the OnAdFailedToShow case in client code but the event never reaches us due to this underlying exception.

**Comment by SebaDudzic** [comment] 2020-02-13 09:58
Same here for me. Huge spike in crashes

**Comment by SebaDudzic** [comment] 2020-02-13 10:00
Most of them are from iOS 13.3.0 or 13.3.1.
Some from 9.3.5
And only few from iOS 12

**Comment by SebaDudzic** [comment] 2020-02-13 10:24
It seems it started crashing after upgrading Firebase SDK from 6.6 to 6.9

**Comment by stowy** [comment] 2020-02-13 13:22
Hi, thanks for this report. Can you provide more information, this crash report doesn't seem to give enough info to determine the cause. Do we know what selector is not recognized?

Are you all using mediation, if so, what networks?

**Comment by mohammaddabiri** [comment] 2020-02-13 13:27
Afraid we don't since the log is generated by Crashlytics and we have no means of reproing the issue manually. We are using the Unity Plugin and not the iOS layer directly. 

We do use mediation with AdMob and currently support Facebook Audience Network and Unity Ads which seem to be functioning normally otherwise and without issue on Android.

**Comment by SebaDudzic** [comment] 2020-02-13 13:56
Also cannot give you any more information due to crashlytics. We use AdMob mediation with facebook provider.

**Comment by stowy** [comment] 2020-02-14 15:05
I've determined that this is an issue with the iOS SDK, version 7.54.0 and 7.55.0.
You resolve by changing [this line of code](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml#L11) to:

```
<iosPod name="Google-Mobile-Ads-SDK" version="= 7.53.1">
```

Alternatively you can change the Podfile of the built iOS project to the following:

```
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Unity-iPhone' do
  pod 'Google-Mobile-Ads-SDK', '= 7.53.1'
end

```

There will be an updated iOS release with a fix for this.  Thanks for reporting.

**Comment by stowy** [comment] 2020-02-15 00:35
Note that this is now fixed, we released [iOS SDK version 7.55.1](https://developers.google.com/admob/ios/download) - so you can disregard the above fix and just do a clean build or run `pod update` on your iOS build to get the fix.

**Comment by SebaDudzic** [comment] 2020-02-17 08:21
Thanks for such a quick response and fix. We are building a fixed app right now. I will let you know if it helped in a couple of days.

**Comment by howeyang-gh** [comment] 2020-02-18 22:29
> I've determined that this is an issue with the iOS SDK, version 7.54.0 and 7.55.0.
> You resolve by changing [this line of code](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml#L11) to:
> 
> ```
> <iosPod name="Google-Mobile-Ads-SDK" version="= 7.53.1">
> ```
> 
> Alternatively you can change the Podfile of the built iOS project:
> 
> ```
> target 'Unity-iPhone' do
>   pod 'Google-Mobile-Ads-SDK', '= 7.53.1'
> #  other pods as needed
> end
> ```
> 
> There will be an updated iOS release with a fix for this. Thanks for reporting.

@stowy 
Thanks for looking into this issue.
If you could clarify some confusion on my end, is this issue on version 7.53 because I am seeing this issue on this version. ( You mentioned that it was on 7.54 and 7.55 )

**Comment by SebaDudzic** [comment] 2020-02-20 07:23
It helped :) I think you can close this issue.

**Closed** 2020-02-20 13:05 UTC

**Comment by mohammaddabiri** [comment] 2020-02-24 11:28
Thanks for resolving the issue so quickly. Should the fix automatically propagate to the [Unity Plugin](https://github.com/googleads/googleads-mobile-unity/releases)? or do we need to await an update to that separately?

**Comment by stowy** [comment] 2020-02-24 18:48
The plugin doesn't need updating except to perhaps specify a new minimum
version of the SDK, however as long as you clear the previous iOS build or
build to a new location, or if you want to keep an existing build, go to
the iOS project / podfile directory and run 'pod update' then you will
receive the latest version of the iOS SDK and the issue will be resolved.
