### ISSUE TITLE
EntryPointNotFoundException with all ads type

### ISSUE THREAD

**Issue by QuanHuynhM** [googleads/googleads-mobile-unity#1308] opened 2020-05-16 13:02 UTC
* Unity version: 2019.2.21
  * Google Mobile Ads Unity plugin version: 5.1.0
  * Platform: Unity Editor

Currently when I update to admob 5.1.0, when I make a request to the banner I get an error

EntryPointNotFoundException: GADUCreateAnchoredAdaptiveBannerView

This happens similarly when requesting interstitial and rewarded ad.

When I downgrade to 5.0.1 everything is normal.

Is there any way to fix this?

**Comment by stowy** [comment] 2020-05-18 17:51
I think this is a duplicate of https://github.com/googleads/googleads-mobile-unity/issues/1296. In short, if you want to use Unity editor, you should select a different platform for the build target, eg Android or Standalone.

**Closed by stowy** 2020-05-18 17:51 UTC
