### ISSUE TITLE
Admob ANR Input dispatching timed out

### ISSUE THREAD

**Issue by songhojung** [googleads/googleads-mobile-unity#775] opened 2018-10-08 01:13 UTC
We are using Unity 5.6.3, and integrated Google Mobile Ads for Interstitial and Rewarded Ads

We are using Google Mobile Ads Unity Plugin v3.15.1

We have been receiving several ANRs and Crash. 

there are many other anr issue relate to admob, but i show below main issue.

 On discussing with the Unity Plugin team, they have asked me to contact you as the issue seems to be of the GMA SDK.

"main" tid=1 Native 
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x7267c610 self=0xefdb1000
  | sysTid=26320 nice=-4 cgrp=default sched=0/0 handle=0xf621d4a8
  | state=S schedstat=( 20008128819 11151478023 45757 ) utm=1420 stm=580 core=7 HZ=100
  | stack=0xff795000-0xff797000 stackSize=8MB
  | held mutexes=
  #00  pc 00000000000190e8  /system/lib/libc.so (syscall+28)
  #01  pc 00000000000b375d  /system/lib/libart.so (_ZN3art17ConditionVariable16WaitHoldingLocksEPNS_6ThreadE+88)
  #02  pc 00000000003bb8b3  /system/lib/libart.so (_ZN3artL12GoToRunnableEPNS_6ThreadE+306)
  #03  pc 00000000003bb751  /system/lib/libart.so (_ZN3art12JniMethodEndEjPNS_6ThreadE+8)
  #04  pc 00000000007d21b9  /system/framework/arm/boot-framework.oat (Java_android_os_BinderProxy_transactNative__ILandroid_os_Parcel_2Landroid_os_Parcel_2I+144)
  at android.os.BinderProxy.transactNative (Native method)
  at android.os.BinderProxy.transact (Binder.java:750)
  at android.app.IActivityManager$Stub$Proxy.refContentProvider (IActivityManager.java:4852)
  at android.app.ActivityThread.incProviderRefLocked (ActivityThread.java:5952)
  at android.app.ActivityThread.acquireExistingProvider (ActivityThread.java:6015)
- locked <0x0da251d5> (a android.util.ArrayMap)
  at android.app.ActivityThread.acquireProvider (ActivityThread.java:5893)
  at android.app.ContextImpl$ApplicationContentResolver.acquireProvider (ContextImpl.java:2479)
  at android.content.ContentResolver.acquireProvider (ContentResolver.java:1736)
  at android.content.ContentResolver.query (ContentResolver.java:781)
  at android.content.ContentResolver.query (ContentResolver.java:705)
  at android.content.ContentResolver.query (ContentResolver.java:663)
  at android.os.Binder.transact (Binder.java:604)
  at com.google.android.gms.internal.zzeu.zzb (unavailable)
  at com.google.android.gms.internal.zzadm.zza (unavailable)
  at com.google.android.gms.internal.zzadx.zza (unavailable)
- locked <0x0373c8db> (a java.lang.Object)
  at com.google.android.gms.internal.zzadx.loadAd (unavailable)
  at com.google.unity.ads.RewardBasedVideo$2.run (RewardBasedVideo.java:196)
  at android.os.Handler.handleCallback (Handler.java:789)
  at android.os.Handler.dispatchMessage (Handler.java:98)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:6565)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)

**Comment by rotter** [comment] 2018-10-22 03:23
I'm having this exact same issue, or very similar. I was gonna open another issue but found this one instead.

I've got many players complaining of game closing out of nowhere, and am having several stacktraces similar to these on Play Console, so I believe admob is the culprit.

Stacktrace A:
(...)
  at com.google.android.gms.dynamite.DynamiteModule.zzc (unavailable:122)
  at com.google.android.gms.dynamite.DynamiteModule.zza (unavailable:96)
  at com.google.android.gms.dynamite.DynamiteModule.getRemoteVersion (unavailable:149)
  at com.google.android.gms.internal.ads.zzkc.zzc (unavailable:31)
  at com.google.android.gms.internal.ads.zzmi.zza (unavailable:98)
  at com.google.android.gms.ads.BaseAdView.loadAd (unavailable:15)
  at com.google.android.gms.ads.AdView.loadAd (unavailable:18)
(...)

Stacktrace B:
 (...) 
  at com.google.android.gms.dynamite.DynamiteModule.zzc (unavailable:122) 
  at com.google.android.gms.dynamite.DynamiteModule.zza (unavailable:96) 
  at com.google.android.gms.dynamite.DynamiteModule.getRemoteVersion (unavailable:149) 
  at com.google.android.gms.internal.ads.zzkc.zzc (unavailable:31) 
  at com.google.android.gms.internal.ads.zzmk.zza (unavailable:40)
  at com.google.android.gms.ads.InterstitialAd.loadAd (unavailable:9)
 (...)

**Comment by rotter** [comment] 2018-10-22 03:23
I'm having this exact same issue, or very similar. I was gonna open another issue but found this one instead.

I've got many players complaining of game closing out of nowhere, and am having several stacktraces similar to these on Play Console, so I believe admob is the culprit.

Stacktrace A:
(...)
  at com.google.android.gms.dynamite.DynamiteModule.zzc (unavailable:122)
  at com.google.android.gms.dynamite.DynamiteModule.zza (unavailable:96)
  at com.google.android.gms.dynamite.DynamiteModule.getRemoteVersion (unavailable:149)
  at com.google.android.gms.internal.ads.zzkc.zzc (unavailable:31)
  at com.google.android.gms.internal.ads.zzmi.zza (unavailable:98)
  at com.google.android.gms.ads.BaseAdView.loadAd (unavailable:15)
  at com.google.android.gms.ads.AdView.loadAd (unavailable:18)
(...)

Stacktrace B:
 (...) 
  at com.google.android.gms.dynamite.DynamiteModule.zzc (unavailable:122) 
  at com.google.android.gms.dynamite.DynamiteModule.zza (unavailable:96) 
  at com.google.android.gms.dynamite.DynamiteModule.getRemoteVersion (unavailable:149) 
  at com.google.android.gms.internal.ads.zzkc.zzc (unavailable:31) 
  at com.google.android.gms.internal.ads.zzmk.zza (unavailable:40)
  at com.google.android.gms.ads.InterstitialAd.loadAd (unavailable:9)
 (...)

**Comment by rotter** [comment] 2018-10-22 03:24
I'm having this exact same issue, or very similar. I was gonna open another issue but found this one instead.

I've got many players complaining of game closing out of nowhere, and am having several stacktraces similar to these on Play Console, so I believe admob is the culprit.

Stacktrace A:
(...)
  at com.google.android.gms.dynamite.DynamiteModule.zzc (unavailable:122)
  at com.google.android.gms.dynamite.DynamiteModule.zza (unavailable:96)
  at com.google.android.gms.dynamite.DynamiteModule.getRemoteVersion (unavailable:149)
  at com.google.android.gms.internal.ads.zzkc.zzc (unavailable:31)
  at com.google.android.gms.internal.ads.zzmi.zza (unavailable:98)
  at com.google.android.gms.ads.BaseAdView.loadAd (unavailable:15)
  at com.google.android.gms.ads.AdView.loadAd (unavailable:18)
(...)

Stacktrace B:
 (...) 
  at com.google.android.gms.dynamite.DynamiteModule.zzc (unavailable:122) 
  at com.google.android.gms.dynamite.DynamiteModule.zza (unavailable:96) 
  at com.google.android.gms.dynamite.DynamiteModule.getRemoteVersion (unavailable:149) 
  at com.google.android.gms.internal.ads.zzkc.zzc (unavailable:31) 
  at com.google.android.gms.internal.ads.zzmk.zza (unavailable:40)
  at com.google.android.gms.ads.InterstitialAd.loadAd (unavailable:9)
 (...)

**Comment by rampara** [comment] 2018-10-26 17:33
@songhojung @rotter For ANR issues not directly caused by the plugin (caused by Google Play services instead) can you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) with ANR logs and the version of Google Play services used to build your app.

**Closed** 2018-10-26 17:33 UTC
Labels: P2, support question
