### ISSUE TITLE
iOS 7.1 issue after clicking on interstitial 

### ISSUE THREAD

**Issue by arbuznikov** [googleads/googleads-mobile-unity#121] opened 2015-09-10 05:17 UTC
Hi!
There is a problem on iOS 7.1 You can see it in the example project. The issue presents on device and in the simulator also.
Start example project. Click on interstitial, app store will open.
Go back to app and try to close interstitial. It hangs and doesn't close.
If you press home button and go back to app, interstitial closes. But next interstitial doesn't show up. 
If you press home button again and go back to app interstitial shows up, but it is not clickable and you can not close it.
On iOS 8.1 and above everything is working fine.

**Comment by rampara** [comment] 2015-10-07 21:47
Can you please try reproducing this problem with your latest Google Mobile Ads iOS SDK release.

- Ram

**Comment by arbuznikov** [comment] 2015-10-08 05:46
Hi! 
Just tried on simulator. Issue is still there.

**Comment by moistrue** [comment] 2016-01-12 08:28
I have the same problem on iOS 7.1.2 with sdk version7.6.0

**Comment by rampara** [comment] 2016-10-10 21:22
Closing this issue due to its age and it being specific to the Google Mobile Ads SDK and not this plugin. GMA SDK issues can be reported at our [product forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).

**Closed by rampara** 2016-10-10 21:22 UTC
