### ISSUE TITLE
Reward Ad complete or rewarded event not working.

### ISSUE THREAD

**Issue by ms25** [googleads/googleads-mobile-unity#448] opened 2017-06-14 10:09 UTC
I am trying to do some custom thing when user complete the full reward ad for that I am using 
 user rewarded event but it is not working. I am using Unity 5.5.1. I tried to put debug in native event code but even that debug is not showing.

**Comment by rampara** [comment] 2017-06-14 17:28
@ms25 are you able to reproduce this issue with the sample app from this repo? Are you using mediation. If so, do you know which network the ad is from?

**Comment by keroxp** [comment] 2017-06-15 03:52
I got same problem above. I'm using Unity 5.6.1f1 and network which it occurred was **Unity Ads**. Not only `OnAdRewarded` but also `OnAdClosed` method hadn't been called.

When playing Ads by AdMob, Those were called correctly.

OS: iOS
Pod's Dependencies versions:
  - Google-Mobile-Ads-SDK (7.20.0)
  - GoogleMobileAdsMediationAdColony (3.1.1.0):
    - AdColony (= 3.1.1)
    - Google-Mobile-Ads-SDK (>= 7.10.1)
  - GoogleMobileAdsMediationUnity (2.1.0.0):
    - Google-Mobile-Ads-SDK (>= 7.10.1)
    - GoogleMobileAdsMediationUnityAdsSDK (= 2.1.0)
  - GoogleMobileAdsMediationUnityAdsSDK (2.1.0)

**Comment by rampara** [comment] 2017-06-15 18:46
@keroxp as your issue doesn't seem specific to this plugin (seems like either an adapter or Unity Ads SDK issue) I would recommend you reach out on the [Google Mobile Ads support forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).

**Comment by Pacifist94** [comment] 2017-06-28 22:15
Same issue here ... not using Mediation , just the adds from Admob, and the new Rewarded videos from Google....
Have the same issue though  .. OnAdRewarded and also OnAdClosed method hadn't been called.
(They just work on the first time,, the second ad you request wont trigger any method)

**Comment by rampara** [comment] 2017-06-29 18:28
@Pacifist94 I'm unable to reproduce this behavior on both iOS and Android using the sample app from this repo. Are you able to reproduce the issue witht the HelloWorld sample app?

**Comment by gayoso** [comment] 2017-07-02 07:21
I have the same issue, using Mediation with AdMob and UnityAds. Rewarded videos from adMob work fine and do all callbacks. However, when I get a video from UnityAds only the "opening" callback is done. In logcat, I can see this log which only happens when I get a UnityAds ad:

> 07-02 04:16:22.168  4691  4728 I ActivityManager: Config changes=480 {1.0 722mcc310mnc [en_US,es_AR] ldltr sw411dp w683dp h387dp 420dpi nrml land finger -keyb/v/h -nav/h s.621}
07-02 04:16:47.347 15739 15739 I Unity   : rewarded ad opening
07-02 04:16:47.347 15739 15739 I Unity   :
07-02 04:16:47.347 15739 15739 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
07-02 04:16:47.347 15739 15739 I Unity   :
07-02 04:16:47.482  4691  2993 I ActivityManager: START u0 {flg=0x10010000 cmp=com.Cockbear.Cuboid/com.unity3d.ads.adunit.AdUnitActivity (has extras)} from uid 10208 on display 0
07-02 04:16:47.558  4691  6477 I ActivityManager: Config changes=480 {1.0 722mcc310mnc [en_US,es_AR] ldltr sw411dp w411dp h659dp 420dpi nrml port finger -keyb/v/h -nav/h s.622}
07-02 04:16:47.811  4691  4728 I ActivityManager: Displayed com.Cockbear.Cuboid/com.unity3d.ads.adunit.AdUnitActivity: +280ms

Could this extra activtiy have anything to do with the problem? Maybe since my app was already integrated with UnityAds, the ad shown is handled by Unity instead of AdMob?

**Comment by rampara** [comment] 2017-07-05 19:13
@gayoso are you using the latest version of the Unity Ads adapter and SDK?

**Comment by gayoso** [comment] 2017-07-05 22:04
Hi, I believe I was. I got all the links from the official Google tutorials on how to set up Mediation with UnityAds. I've abandoned this project for now, thanks!

**Comment by rampara** [comment] 2017-07-10 23:37
@gayoso as mentioned earlier, your issue doesn't seem specific to this plugin (seems like either an adapter or Unity Ads SDK issue) I would recommend you reach out on the Google Mobile Ads support forum.

**Comment by rampara** [comment] 2017-07-14 20:59
Closing issue due to non-response from original poster. Please re-open if you're still experiencing this issue.

**Closed by rampara** 2017-07-14 20:59 UTC
Labels: support question
