### ISSUE TITLE
Imposible to re-packege resources

### ISSUE THREAD

**Issue by chaky31** [googleads/googleads-mobile-unity#244] opened 2016-07-01 17:54 UTC
Hi, I've tried to compile de example, but it's imposible, I get the next error always:

```
stderr[

]
stdout[

]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.PostProcessAndroidPlayer.Exec (System.String command, System.String args, System.String workingdir, System.String[] progress_strings, Single progress_value, System.String errorMsg)
UnityEditor.Android.PostProcessAndroidPlayer.CompileResources (System.String stagingArea, System.String packageName, UnityEditor.Android.AndroidLibraries androidLibraries)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcessInternal (System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
```

But stderr is empty so... I don't know what is the error. If someone can help me...

Thanks

**Comment by rampara** [comment] 2016-07-06 18:32
Did you follow the instructions from our [developer docs](https://firebase.google.com/docs/admob/android/games#unity)?

**Comment by Universalerror** [comment] 2016-07-15 08:00
I've had the same issue when trying to build an empty project with this plugin in it without any other code. Upon building first time and after resolving the jar files I get the same error as above. After reloading the project file I get this error message instead:
Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
```
C:\Android\build-tools\24.0.0\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Android\platforms\android-24\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.google.unity:com.google.android.gms.ads.impl:com.google.android.gms.ads:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.clearcut:com.google.android.gms:com.google.android.gms.tasks:android.support.v4 -S "C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res" -S "C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\play-services-ads-9.2.0\res" -S "C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\play-services-ads-lite-9.2.0\res" -S "C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\play-services-base-9.2.0\res" -S "C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\play-services-basement-9.2.0\res" -S "C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\play-services-clearcut-9.2.0\res" -S "C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\play-services-gass-9.2.0\res" -S "C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\play-services-tasks-9.2.0\res" -S "C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\support-v4-23.1.1\res"

stderr[

]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: C:\Android\platforms\android-24\android.jar
applyFileOverlay for drawable
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_icon_light.xml
trying overlaySet Key=common_google_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_google_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_light_pressed.9.png
trying overlaySet Key=common_ic_googleplayservices.png
trying overlaySet Key=common_plus_signin_btn_icon_dark.xml
trying overlaySet Key=common_plus_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light.xml
trying overlaySet Key=common_plus_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark.xml
trying overlaySet Key=common_plus_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_light.xml
trying overlaySet Key=common_plus_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_pressed.9.png
trying overlaySet Key=abc_ab_share_pack_mtrl_alpha.9.png
trying overlaySet Key=abc_action_bar_item_background_material.xml
trying overlaySet Key=abc_btn_borderless_material.xml
trying overlaySet Key=abc_btn_check_material.xml
trying overlaySet Key=abc_btn_check_to_on_mtrl_000.png
trying overlaySet Key=abc_btn_check_to_on_mtrl_015.png
trying overlaySet Key=abc_btn_colored_material.xml
trying overlaySet Key=abc_btn_default_mtrl_shape.xml
trying overlaySet Key=abc_btn_radio_material.xml
trying overlaySet Key=abc_btn_radio_to_on_mtrl_000.png
trying overlaySet Key=abc_btn_radio_to_on_mtrl_015.png
trying overlaySet Key=abc_btn_rating_star_off_mtrl_alpha.png
trying overlaySet Key=abc_btn_rating_star_on_mtrl_alpha.png
trying overlaySet Key=abc_btn_switch_to_on_mtrl_00001.9.png
trying overlaySet Key=abc_btn_switch_to_on_mtrl_00012.9.png
trying overlaySet Key=abc_cab_background_internal_bg.xml
trying overlaySet Key=abc_cab_background_top_material.xml
trying overlaySet Key=abc_cab_background_top_mtrl_alpha.9.png
trying overlaySet Key=abc_control_background_material.xml
trying overlaySet Key=abc_dialog_material_background_dark.xml
trying overlaySet Key=abc_dialog_material_background_light.xml
trying overlaySet Key=abc_edit_text_material.xml
trying overlaySet Key=abc_ic_ab_back_mtrl_am_alpha.png
trying overlaySet Key=abc_ic_clear_mtrl_alpha.png
trying overlaySet Key=abc_ic_commit_search_api_mtrl_alpha.png
trying overlaySet Key=abc_ic_go_search_api_mtrl_alpha.png
trying overlaySet Key=abc_ic_menu_copy_mtrl_am_alpha.png
trying overlaySet Key=abc_ic_menu_cut_mtrl_alpha.png
trying overlaySet Key=abc_ic_menu_moreoverflow_mtrl_alpha.png
trying overlaySet Key=abc_ic_menu_paste_mtrl_am_alpha.png
trying overlaySet Key=abc_ic_menu_selectall_mtrl_alpha.png
trying overlaySet Key=abc_ic_menu_share_mtrl_alpha.png
trying overlaySet Key=abc_ic_search_api_mtrl_alpha.png
trying overlaySet Key=abc_ic_voice_search_api_mtrl_alpha.png
trying overlaySet Key=abc_item_background_holo_dark.xml
trying overlaySet Key=abc_item_background_holo_light.xml
trying overlaySet Key=abc_list_divider_mtrl_alpha.9.png
trying overlaySet Key=abc_list_focused_holo.9.png
trying overlaySet Key=abc_list_longpressed_holo.9.png
trying overlaySet Key=abc_list_pressed_holo_dark.9.png
trying overlaySet Key=abc_list_pressed_holo_light.9.png
trying overlaySet Key=abc_list_selector_background_transition_holo_dark.xml
trying overlaySet Key=abc_list_selector_background_transition_holo_light.xml
trying overlaySet Key=abc_list_selector_disabled_holo_dark.9.png
trying overlaySet Key=abc_list_selector_disabled_holo_light.9.png
trying overlaySet Key=abc_list_selector_holo_dark.xml
trying overlaySet Key=abc_list_selector_holo_light.xml
trying overlaySet Key=abc_menu_hardkey_panel_mtrl_mult.9.png
trying overlaySet Key=abc_popup_background_mtrl_mult.9.png
trying overlaySet Key=abc_ratingbar_full_material.xml
trying overlaySet Key=abc_scrubber_control_off_mtrl_alpha.png
trying overlaySet Key=abc_scrubber_control_to_pressed_mtrl_000.png
trying overlaySet Key=abc_scrubber_control_to_pressed_mtrl_005.png
trying overlaySet Key=abc_scrubber_primary_mtrl_alpha.9.png
trying overlaySet Key=abc_scrubber_track_mtrl_alpha.9.png
trying overlaySet Key=abc_seekbar_thumb_material.xml
trying overlaySet Key=abc_seekbar_track_material.xml
trying overlaySet Key=abc_spinner_mtrl_am_alpha.9.png
trying overlaySet Key=abc_spinner_textfield_background_material.xml
trying overlaySet Key=abc_switch_thumb_material.xml
trying overlaySet Key=abc_switch_track_mtrl_alpha.9.png
trying overlaySet Key=abc_tab_indicator_material.xml
trying overlaySet Key=abc_tab_indicator_mtrl_alpha.9.png
trying overlaySet Key=abc_text_cursor_material.xml
trying overlaySet Key=abc_textfield_activated_mtrl_alpha.9.png
trying overlaySet Key=abc_textfield_default_mtrl_alpha.9.png
trying overlaySet Key=abc_textfield_search_activated_mtrl_alpha.9.png
trying overlaySet Key=abc_textfield_search_default_mtrl_alpha.9.png
trying overlaySet Key=abc_textfield_search_material.xml
trying overlaySet Key=app_banner.png
trying overlaySet Key=app_icon.png
applyFileOverlay for layout
trying overlaySet Key=abc_action_bar_title_item.xml
trying overlaySet Key=abc_action_bar_up_container.xml
trying overlaySet Key=abc_action_bar_view_list_nav_layout.xml
trying overlaySet Key=abc_action_menu_item_layout.xml
trying overlaySet Key=abc_action_menu_layout.xml
trying overlaySet Key=abc_action_mode_bar.xml
trying overlaySet Key=abc_action_mode_close_item_material.xml
trying overlaySet Key=abc_activity_chooser_view.xml
trying overlaySet Key=abc_activity_chooser_view_list_item.xml
trying overlaySet Key=abc_alert_dialog_button_bar_material.xml
trying overlaySet Key=abc_alert_dialog_material.xml
trying overlaySet Key=abc_dialog_title_material.xml
trying overlaySet Key=abc_expanded_menu_layout.xml
trying overlaySet Key=abc_list_menu_item_checkbox.xml
trying overlaySet Key=abc_list_menu_item_icon.xml
trying overlaySet Key=abc_list_menu_item_layout.xml
trying overlaySet Key=abc_list_menu_item_radio.xml
trying overlaySet Key=abc_popup_menu_item_layout.xml
trying overlaySet Key=abc_screen_content_include.xml
trying overlaySet Key=abc_screen_simple.xml
trying overlaySet Key=abc_screen_simple_overlay_action_mode.xml
trying overlaySet Key=abc_screen_toolbar.xml
trying overlaySet Key=abc_search_dropdown_item_icons_2line.xml
trying overlaySet Key=abc_search_view.xml
trying overlaySet Key=abc_select_dialog_material.xml
trying overlaySet Key=notification_media_action.xml
trying overlaySet Key=notification_media_cancel_action.xml
trying overlaySet Key=notification_template_big_media.xml
trying overlaySet Key=notification_template_big_media_narrow.xml
trying overlaySet Key=notification_template_lines.xml
trying overlaySet Key=notification_template_media.xml
trying overlaySet Key=notification_template_part_chronometer.xml
trying overlaySet Key=notification_template_part_time.xml
trying overlaySet Key=select_dialog_item_material.xml
trying overlaySet Key=select_dialog_multichoice_material.xml
trying overlaySet Key=select_dialog_singlechoice_material.xml
trying overlaySet Key=support_simple_spinner_dropdown_item.xml
applyFileOverlay for anim
trying overlaySet Key=abc_fade_in.xml
trying overlaySet Key=abc_fade_out.xml
trying overlaySet Key=abc_grow_fade_in_from_bottom.xml
trying overlaySet Key=abc_popup_enter.xml
trying overlaySet Key=abc_popup_exit.xml
trying overlaySet Key=abc_shrink_fade_out_from_bottom.xml
trying overlaySet Key=abc_slide_in_bottom.xml
trying overlaySet Key=abc_slide_in_top.xml
trying overlaySet Key=abc_slide_out_bottom.xml
trying overlaySet Key=abc_slide_out_top.xml
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_plus_signin_btn_text_dark.xml
trying overlaySet Key=common_plus_signin_btn_text_light.xml
trying overlaySet Key=abc_background_cache_hint_selector_material_dark.xml
trying overlaySet Key=abc_background_cache_hint_selector_material_light.xml
trying overlaySet Key=abc_color_highlight_material.xml
trying overlaySet Key=abc_primary_text_disable_only_material_dark.xml
trying overlaySet Key=abc_primary_text_disable_only_material_light.xml
trying overlaySet Key=abc_primary_text_material_dark.xml
trying overlaySet Key=abc_primary_text_material_light.xml
trying overlaySet Key=abc_search_url_text.xml
trying overlaySet Key=abc_secondary_text_material_dark.xml
trying overlaySet Key=abc_secondary_text_material_light.xml
trying overlaySet Key=switch_thumb_material_dark.xml
trying overlaySet Key=switch_thumb_material_light.xml
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: C:\Users\Admin\Desktop\Test Google\Temp\StagingAreProcessing image: aC:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-hdpi\abc_ab_share_pack_mtrl_alpha.9.png
\android-libraries\appcompat-v7-23.1.1\res\drawable-mdpi\abc_ab_share_pack_mtrl_alpha.9.png
Processing image: C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xhdpi\abc_ab_share_pack_mtrl_alpha.9.png
Processing image: C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xxhdpi\abc_ab_share_pack_mtrl_alpha.9.png
    (processed image C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-mdpi\abc_ab_share_pack_mtrl_alpha.9.png: 253% size of source)
Processing image: C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-mdpi    (pr\abc_btn_check_to_on_mtrl_000.png
ocessed image C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-hdpi\abc_ab_share_pack_mtrl_alpha.9.png: 256% size of source)
    (processed image C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xhdpi\abc_ab_share_pack_mtrl_alpha.9.png: 253% size of source)
Processing image: C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-hdpi\abc_btn_check_to_on_mtrl_000.png
Processing image: C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xhdpi\abc_btn_check_to_on_mtrl_000.png
    (processed image C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xxhdpi\abc_ab_share_pack_mtrl_alpha.9.png: 236% size of source)
Processing image: C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xxhdpi\abc_btn_check_to_on_mtrl_000.png
    (processed image C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-mdpi\abc_btn_check_to_on_mtrl_000.png: 134% size of source)
    (processed image C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-hdpi\abc_btn_check_to_on_mtrl_000.png: 134% size of source)
    (processed image C:\Users\AdmProcessinin\Desktop\Testg  Google\Temp\StagiimagngAreae: \andrC:\Useoid-librrs\Aaries\appcompat-vdmi7-23.1.n\1\res\drProceawablDesktop\sse-xhdpi\abc_btn_check_to_oingn_mtrl_000.png: Te12 ima5st Google\ge: T% size oCf :\Uemp\ssStagource)
ers\AdmiingArea\andron\Desktopid-libra\Test riGooglees\Temp\StagingArea\\appcompat-vandroid-libra7-ries\app23compat-v7-23.1.1\r.1.1es\draw\ablres\e-mdpi\abc_btn_check_to_dron_awmtrl_015.png
able-xxxhdpi\abc_btn_check_to_on_mtrl_000.png
Processing image: C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-hdpi\abc_btn_check_to_on_mtrl_015.png
    (processed image C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xxhdpi\abc_btn_check_to_on_mtrl_000.png: 119% size of source)
    (processed image C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-mdpi\abc_btn_check_to_on_mtrl_015.png: 132% size of source)
Processing image: C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xhdpi\abc_btn_check_to_on_mtrl_015.png
Processing image: C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xxhdpi\abc_btn_check_to_on_mtrl_015.png
    (processed image C:\Users\Admin\Desktop\Test Google\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawab<message truncated>
```
I am using the latest version of Unity, the AdMob plugin and the Android SDK.

**Comment by rampara** [comment] 2016-07-15 22:43
@Universalerror is the console error you posted complete? It doesn't indicate the cause of the error.

**Comment by Universalerror** [comment] 2016-07-18 07:39
@rampara I have copied the entirety of the message in the Unity error window.

**Comment by rampara** [comment] 2016-07-18 18:42
@Universalerror I'm able to build without issue using version 24.0.1 of Android build tools.

**Comment by Universalerror** [comment] 2016-07-21 10:20
@rampara I'm not sure where the issue lies then. I've heard many issues from other developers regarding build tools 24 and each one of their issues were resolved by backdating to 23.

**Comment by rampara** [comment] 2016-10-10 21:27
Updates to the latest version of the plugin (v.3.1.0) should resolve problems with Google Play services resolution. If this problem persists for you, can you re-open the issue and attach a Unity project where the problem is reproducible.

**Closed by rampara** 2016-10-10 21:27 UTC
Labels: support question
