### ISSUE TITLE
Build process stuck at building scene 0

### ISSUE THREAD

**Issue by MidiSmallYue** [googleads/googleads-mobile-unity#1417] opened 2020-08-18 16:00 UTC
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.3.6
  * Google Mobile Ads Unity plugin version: 5.3.0
  * Platform: Android
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem

unity stuck in build process stuck at building scene 0
no errr and no warning，I suspect that Android Resolver> Resolve is invalid，Also 'Forse Resovle' feature doesn't work with this version. Tried reimport with no luck. No errors when importing. Similar to this issue, link: https://github.com/playgameservices/play-games-plugin-for-unity/issues/2790
My English is only a little bit, I don’t know if you understand what I mean
![1597766413(1)](https://user-images.githubusercontent.com/21123359/90536713-02292a00-e1af-11ea-87a4-e1bbf90b0e81.png)

**Comment by MidiSmallYue** [comment] 2020-08-18 16:06
target api level to API 29 in Unity will have this problem

**Comment by MidiSmallYue** [comment] 2020-08-18 16:14
The unity jar resolve version is too low will cause this problem, Google Mobile Ads Unity plugins version: 5.3.0, unity jar resolve version 1.2.135, need to be upgraded to 1.2.138, will solve this problem

**Comment by andrey-melnikov** [comment] 2022-06-11 21:16
1) Try Force Resolve, if nothing appears on the screen then it means that play services resolver is broken and this is the cause of the problem.
2) Download the latest external resolver unitypackage from here: https://github.com/googlesamples/unity-jar-resolver/
3) import into unity
4) if unity says that there are duplicates of dll files then delete the one in the play services folder
5) restart unity
6) do force resolve

Now everything works.

**Comment by kunny** [comment] 2023-01-09 14:44
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones.

Thanks for your contribution again!

**Closed by kunny** 2023-01-09 14:44 UTC
Labels: obsolete

**Comment by TheHeadphonesAreNeeded** [comment] 2024-11-21 13:40
remove unity ads
