### ISSUE TITLE
Support for iOS 14 & AdMob SDK 7.64.0 [URGENT]

### ISSUE THREAD

**Issue by eduardocoelho** [googleads/googleads-mobile-unity#1421] opened 2020-08-20 14:06 UTC
Hi guys,
I apologize if here isn't the appropriate place for this request.
I'm in a hurry to update my Unity3D game to work with iOS 14's new App Tracking Transparency SDK and IDFA access.
I'm currently using v5.3.0 of this plugin, which was tested with the iOS SDK 7.63.0.

If I update the Cocoapods / Xcode project to use the iOS SDK 7.64.0, will the this plugin still work? I hope you guys help us with this, as mentioned in Google AdMob's dashboard:

**"Prepare your apps for iOS 14 Apple announced the new AppTrackingTransparency framework, which requires changes to your iOS apps. Implement the GMA SDK 7.64.0 (or later) and set up consent messaging to help prevent a significant loss in ad revenue."**

Thanks in advance,

**Comment by ChaserKnight** [comment] 2020-08-20 14:22
Yes, this is really urgent, we need official info and documentation about how this Unity AdMob plugin will work on iOS 14.

**Comment by AllanRW** [comment] 2020-08-20 18:07
Waiting for this update too!

**Comment by PaulNaylor** [comment] 2020-08-21 02:57
Waiting for this update too!

**Comment by AndyQZL** [comment] 2020-08-21 06:37
Waiting for this update too!

**Comment by gimoneto** [comment] 2020-08-21 07:02
Waiting for this update too!

**Comment by mdobele** [comment] 2020-08-25 01:42
@stowy  Thanks, Is there any timeline on when your solution would be available?  I'd rather use that then another third-party plugin if possible.

**Comment by rotter** [comment] 2020-08-25 22:33
Im also waiting for this update!

**Comment by lionkingsiro** [comment] 2020-08-26 02:17
waiting.. im also need for my unity games on ios!

**Comment by p0w1nd** [comment] 2020-08-27 08:45
I'm also waiting for this. Thank you.

**Comment by hanrock** [comment] 2020-08-28 17:50
I'm also waiting for this update!

**Comment by IShix-g** [comment] 2020-08-31 04:46
I'm also waiting for this upgrade.

**Comment by pelevinma** [comment] 2020-08-31 08:25
I'm also waiting for this update.

**Comment by arslanaligamesgear** [comment] 2020-08-31 10:36
Waiting for this Update.
Moreover anyone tried using Plugin with 7.63 and manually adding iOS 7.64 Frameworks ?
Any Success?

**Comment by mdobele** [comment] 2020-08-31 12:27
> Waiting for this Update.
> Moreover anyone tried using Plugin with 7.63 and manually adding iOS 7.64 Frameworks ?
> Any Success?

Yes, whilst waiting I've gone ahead and used the 3rd party App Transparency plugin stowy linked (It's actually very easy to use) and am using Admob Unity plugin v5.3.0 which used the iOS 7.63 framework, and then just changed the podfile GoogleMobileAdsDependencies.xml to use the iOS 7.64 framework and gotten everything working ok on iOS14.

**Comment by arslanaligamesgear** [comment] 2020-09-01 13:01
> > Waiting for this Update.
> > Moreover anyone tried using Plugin with 7.63 and manually adding iOS 7.64 Frameworks ?
> > Any Success?
> 
> Yes, whilst waiting I've gone ahead and used the 3rd party App Transparency plugin stowy linked (It's actually very easy to use) and am using latest Admob Unity plugin v5.3.0 which used the iOS 7.63 framework, and then just changed the podfile GoogleMobileAdsDependencies.xml to use the iOS 7.64 framework and gotten everything working ok on iOS14.

Can you guide me where to get this plugin "App Transparency plugin stowy linked"

**Comment by nhtai2004** [comment] 2020-09-02 04:08
I'm waiting for this update

**Comment by ChaserKnight** [comment] 2020-09-03 15:56
There is a new release (v5.4.0) some hours ago, does it contain support for iOS 14? It is not mentioned in the released notes.

**Comment by ericleich** [comment] 2020-09-03 17:54
v5.4.0 builds against/has a dependency on iOS 7.64.0 SDK, which is the official Google Mobile Ads release version for iOS 14.

- For [enabling SKAdNetwork](https://developers.google.com/admob/ios/ios14#skadnetwork), v5.4.0 does not automatically include the plist key today, but this can be done manually after building a Unity project into Xcode. We'll be looking to add this in a future update.
- For AppTrackingTransparency updates, please see https://developer.apple.com/news/?id=hx9s63c5.

**Comment by ericleich** [comment] 2020-09-04 02:25
Due to #1437, 5.4.0 release was reverted. recommendation for now is back to using v5.3.0 and bump GoogleMobileAdsDependencies.xml to 7.64 as @mdobele suggested.

**Comment by nicolasgramlich** [comment] 2020-09-17 00:17
iOS 14 is now officially out and it would be great if it could be properly supported.

**Comment by KATUNATOR** [comment] 2020-09-21 12:19
With all needed steps ads (specifically Native Ad Banner) are working on iPhone OS14, but not on iPad OS14. Searched the internet, but hasn't found even a question with the same problem!

Project info:
- AdMob SDK (Unity) - 3.18.3
- AdMob SDK (iOS) - 7.64
- IronSourceAdMobAdapter (iOS) - 4.3.16.0

Important note: didn't make a request for AppTrackingTransparency, just added SkAdNetworks and updated native AdMob SDK (iOS) through GoogleMobileAdsDependencies.xml.

**Comment by stowy** [comment] 2020-09-21 13:47
@KATUNATOR this may not be an iOS14 problem. Can you ask on our [developer forum](https://groups.google.com/g/google-admob-ads-sdk) and they will help triage your issue with loading ads on an iPad.  If it is confirmed to be an iOS14 issue we will ensure to address it.

**Comment by KATUNATOR** [comment] 2020-09-22 11:03
Thanx for answer, will try!

**Comment by adibacco** [comment] 2020-09-24 17:35
Hope that AdMob SDK (iOS) - 7.64 will be in next release.

**Comment by zivandar** [comment] 2020-10-03 15:01
Any progress?Now when I install SDK 5.3.0. If I don't upgrade to 7.64, no ads will be shown on iOS 14, I get it right?

**Comment by xjjon** [comment] 2020-10-05 05:30
bump

**Comment by claudio-tezzin-playkids** [comment] 2020-10-14 16:12
+1

**Comment by rockylimandauw** [comment] 2020-10-15 03:03
+1

**Comment by MarlonColhado** [comment] 2020-10-18 15:22
Any progress?

**Comment by ChaserKnight** [comment] 2020-10-21 07:28
Is there any update on this? Or this plugin is abandoned now?

**Comment by arslanaligamesgear** [comment] 2020-10-26 11:45
If anyone has tried the v5.3 official unity plugin and manually upgrading Xcode project framework via pods and has success please do comment, Moreover dont mention any thirdparty paid plugins please

**Comment by ChaserKnight** [comment] 2020-11-03 09:39
It's been 3 months since the last release, in early 2021 iOS 14 will stop showing ads if this is not supported by the plugin. So please give us some update on the situation. We want support for iOS 14 in this official plugin. Hello!!! is anybody here? Or is this plugin abandoned? Hello...!!!!

**Comment by stowy** [comment] 2020-11-03 21:21
@ChaserKnight you are right to be concerned, please be assured we are aware of this, however we need to ensure that our solution works for future changes as well and takes into account offerings from the Unity SDK itself.

That said we anticipate a release with improved iOS 14 support by end of next week latest. In the mean time it is possible to support iOS 14 with the existing plugin as per my [above comment](https://github.com/googleads/googleads-mobile-unity/issues/1421#issuecomment-678782799).

**Comment by ChaserKnight** [comment] 2020-11-04 07:22
@stowy thank you for the info, it's great to know that the plugin is coming.

**Comment by arslanaligamesgear** [comment] 2020-11-04 07:26
> @ChaserKnight  He is talking about his paid commercial plugin! Sad but not news about official plugin

**Comment by arslanaligamesgear** [comment] 2020-11-04 07:28
> @ChaserKnight you are right to be concerned, please be assured we are aware of this, however we need to ensure that our solution works for future changes as well and takes into account offerings from the Unity SDK itself.
> 
> That said we anticipate a release with improved iOS 14 support by end of next week latest. In the mean time it is possible to support iOS 14 with the existing plugin as per my [above comment](https://github.com/googleads/googleads-mobile-unity/issues/1421#issuecomment-678782799).

Are you talking about the previous paid plugin or the official google plugin?

**Comment by ChaserKnight** [comment] 2020-11-04 07:29
@arslanaligamesgear he said that the official plugin is anticipated to be released next week, so I think that's good news, along with that he mentioned the third party paid plugin, I am not sure if that's his plugin.

**Comment by arslanaligamesgear** [comment] 2020-11-04 07:32
@ChaserKnight If official then sure, A reason to cheer

**Comment by stowy** [comment] 2020-11-04 22:46
I only work on the Google AdMob plugin (this repo). The original reference to the paid ATT plugin was just a note that it was available and is not officially recommended by Google. I also have no affiliation with it.

At this stage there are no plans to add an ATT consent flow to this plugin as it is something that is likely to be needed by multiple ad networks and hence support from Unity seems a more logical solution.  However support for adding the `SKAdNetwork` IDs will be provided, including automatically adding the current Google `SKAdNetwork` ID(s).

**Comment by stowy** [comment] 2020-11-12 22:41
All please try out [release version 5.4.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/v5.4.0) which has the inclusion of Google's `SKAdNetwork` IDs in the **Info.plist**.

**Closed** 2020-11-19 19:54 UTC
