### ISSUE TITLE
Release 11.7.0 crashes the iOS game during startup

### ISSUE THREAD

**Issue by arcv** [googleads/googleads-mobile-unity#3489] opened 2024-07-28 13:02 UTC
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.39f1
  * Google Mobile Ads Unity plugin version: 9.2.0
  * Plugin installation method: .unitypackage (Unity package manager, .unitypackage import)
  * Platform: Mac Mini / iOS
  * Platform OS version: iOS 17.4
  * Any specific devices issue occurs on: None
  * Mediation ad networks used, and their versions: UnityAds

#### Steps to reproduce:

Install Google Admob SDK 9.2.0 from Unitypackage then install UnityAds 3.12.1 mediation adapter.
Build XCode project with Pods enabled. Default Pod versions for Google-Mobile-Ads-SDK cause crash during game start-up.

Built the game on Mac Mini M2 Sonomo 14.5. Crashes happen in both Mac Mini and iPhone 12. When built with **Google-Mobile-Ads-SDK 11.7.0**, it causes the error below. I thought this was caused by InApp integration and disabled the InApps but it didn't solve the issue. Manually editing version of **Google-Mobile-Ads-SDK** to **11.1.0** in Podfile fixed though.

> UnityIAP UnityEarlyTransactionObserver: Added to the payment queue
-> applicationDidBecomeActive()
Failed to look up symbolic reference at 0x124552381 - offset 1072551 - symbol symbolic _____Sg 14MarketplaceKit14AppDistributorO in /private/var/folders/18/yccyv73n1lx3r1zf_88t10_c0000gn/X/44E90429-D410-5C1F-AA2B-40C21D8FCE79/d/Wrapper/<REMOVED>.app/Frameworks/UnityFramework.framework/UnityFramework

#### Relevant Code:

```
target 'UnityFramework' do
  pod 'GoogleMobileAdsMediationUnity', '4.12.1.0'
  pod 'Google-Mobile-Ads-SDK', '11.7.0' <- fixing version to 11.1.0 resolves the crash
end
```

**Comment by TvaroshFlyboys** [comment] 2024-07-30 07:48
We have maybe an similar issue with our app. We have a mobile iOS app, which players download from the store to their MacBooks and started to report the crash on app start.

Users found out that if they delete Settings file located here: ~/library/containers/appName/data/Library/Application Support/GoogleMobileAds/Settings they run the app normally and can play. But the Settings file is automatically created again, which means that the next app start is a crash again... So they have to delete that Settings file before each app start.

**Comment by TvaroshFlyboys** [comment] 2024-07-30 08:43
seems like the same issue

UnityIAP UnityEarlyTransactionObserver: Added to the payment queue
-> applicationDidBecomeActive()
Failed to look up symbolic reference at 0x114e4da59 - offset 1813919 - symbol symbolic _____Sg 14MarketplaceKit14AppDistributorO in /private/var/folders/g6/qglkwqm17qz6t76_x2gr8tr40000gn/X/EEB239EC-9F00-5E5A-8A38-F83E9F3B6639/d/Wrapper/[appName.app/Frameworks/UnityFramework.framework/UnityFramework](http://appName.app/Frameworks/UnityFramework.framework/UnityFramework)

**Comment by arcv** [comment] 2024-07-30 09:21
@TvaroshFlyboys Could be an issue with Apple-side, not sure. [MarketplaceKit](https://developer.apple.com/documentation/marketplacekit) seems to be a framework for alternative market provider.

**Comment by TvaroshFlyboys** [comment] 2024-07-30 10:08
based on the release log of google mobile ads version 11.6.0, they've added dependency on the MarketplaceKit:

11.6.0 | 2024-06-17 | Added a dependency on MarketplaceKit. This requires apps to build with Xcode 15.3 or above.MarketplaceKit is Swift-only, so a Swift placeholder file has been added to the distribution so Swift standard libraries are included in apps even if they don't contain other Swift files.

but how I wrote in above post, the game starts if user deletes the Settings file, so looks like some issue with reading that file?

**Comment by NVentimiglia** [comment] 2024-08-01 01:53
I was able to confirm this issue. I will let everyone know when we have a fix.

**Comment by NVentimiglia** [comment] 2024-08-01 02:18
@arcv 

I was not able to replicate this issue. Please confirm I should experience this crash when I run the XCode project on an iOS device.

- UnityEditor 2023
- XCode 16
-  'GoogleMobileAdsMediationUnity', '4.12.1.0'
-  'Google-Mobile-Ads-SDK', '11.7.0' <- fixing version to 11.1.0 resolves the crash

**Comment by TvaroshFlyboys** [comment] 2024-08-01 05:35
for us it is happening if you run iOS game on MacBook (design for iPad). First run is OK, but after the Settings file is created the second and next runs crashes.

**Comment by ikitae** [comment] 2024-08-20 05:17
crash on silicon mac

**Comment by TvaroshFlyboys** [comment] 2024-08-20 06:22
is there any progress? or do you need more info?

**Comment by Str4tos** [comment] 2024-08-20 06:29
My steps to reproduce the crash:
- Unity any version
- XCode 15.4
- Mac OS 14.5 (Apple silicon)

The first launch of iOS App on My Mac (Designed for iPhone) works without any issues.
**The second identical launch causes a crash.**

The following actions do not resolve the issue:
- Clean Build folder
- Deleting `~/Library/Containers/AppName`
- Deleting `/private/var/folders/z_/..../AppName`
- Changing Application bundle identifier (for tests)

My logs:
```
LSPrefs: could not find untranslocated node for <FSNode 0x6000039bc200> { isDir = ?, path = '/private/var/folders/z_/7gzbzjl96tvc953lz9c6rz740000gn/X/E6D65E5B-1C37-52A5-B741-E5A8FDFB15F0/d/Wrapper/TestApp.app' }, proceeding on the assumption it is not translocated: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"
Type: Error | Timestamp: 2024-08-20 09:16:42.552740+03:00 | Process: TestApp | Library: LaunchServices | Subsystem: com.apple.launchservices | Category: default | TID: 0x80ec

Failed to look up symbolic reference at 0x10735d8cf - offset 4264569 - symbol symbolic _____Sg 14MarketplaceKit14AppDistributorO in /private/var/folders/z_/7gzbzjl96tvc953lz9c6rz740000gn/X/E6D65E5B-1C37-52A5-B741-E5A8FDFB15F0/d/Wrapper/TestApp.app/TestApp
Type: stdio
```

**Comment by MuhammadWaqasOfficial** [comment] 2024-08-29 05:06
Experiencing Same Crash:
 1- Crash is not related to mediation, as tagged for mediation.
 2- No crash observed on actual iphone device
 3- Crashed when build and run for
-  My Mac (Designed for iPad)
- iOS Simulator ( iPhone 15 Pro Max )

4- Temp solution deleting Settings file as mentioned by @TvaroshFlyboys [here](https://github.com/googleads/googleads-mobile-unity/issues/3489#issuecomment-2257697483)
5- First time it won't crash, after that its keep crashing on launch.

<img width="1144" alt="Crash" src="https://github.com/user-attachments/assets/b8411318-8a67-4368-b034-3fd2ea564a5d">

**Comment by ezefranca** [comment] 2024-09-05 13:07
The crash started in July, It's September and no Answers? The crashes particularly happens on iPad / macOS running iPad versions.

**Comment by Str4tos** [comment] 2024-09-05 13:27
I found the answer from Google here: https://groups.google.com/g/google-admob-ads-sdk/c/VgOZsuGOI3w

> Your concern is currently under investigation and we have no updates to provide at this time. However, our team is actively working on it. We appreciate your understanding and patience.

**Comment by NVentimiglia** [comment] 2024-09-09 18:24
Hi Everyone,

We have verified the issue and recommend using iOS SDK version 11.5.0 or below. This can be done by modifying `GoogleMobileAdsDependencies.xml`.

We are working on a fix.

**Comment by NVentimiglia** [comment] 2024-09-13 16:28
This issue will be fixed in the next release.

In the mean time you can update your ios dependency to version `11.9.0`.

The Google Mobile Ads Unity plugin dependencies are listed in Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml.

**Closed by NVentimiglia** 2024-09-13 16:28 UTC
Labels: SDK, Mediation

**Comment by facingsun** [comment] 2024-09-15 04:07
xcode Version 15.4 
'Google-Mobile-Ads-SDK', '~> 11.9.0'
iphone15 17.6.1（Other equipment unknown）
Simulator is running properly
An error occurs when the IOS device starts：
“Failed to look up symbolic reference at 0x102e15a9f - offset 76833 - symbol symbolic _____Sg ScP in /private/var/containers/Bundle/Application/4A43XXA8-5D0B-48D5-8VV9-2CEC7E0B80FE/XX.app/XXXX”
Versions 11.4.0 and above have this problem

**Comment by facingsun** [comment] 2024-09-15 04:08
xcode Version 15.4
'Google-Mobile-Ads-SDK', '~> 11.9.0'
iphone15 17.6.1（Other equipment unknown）
Simulator is running properly
An error occurs when the IOS device starts：
“Failed to look up symbolic reference at 0x102e15a9f - offset 76833 - symbol symbolic _____Sg ScP in /private/var/containers/Bundle/Application/4A43XXA8-5D0B-48D5-8VV9-2CEC7E0B80FE/XX.app/XXXX”
Versions 11.5.0 and above have this problem

**Comment by sametguzeldev** [comment] 2024-11-04 12:42
@NVentimiglia  This issue is still not fixed for me.
I am using Google-Mobile-Ads-SDK 11.10.0 and having the same error. Crash on startup.

I added an empty swift file into the project and crashes stopped. But then when I tried to upload that app to TestFlight, I got this error.

` Asset validation failed (90206)
Invalid Bundle. The bundle at 'AppName.app/Frameworks/UnityFramework.framework' contains disallowed file 'Frameworks'. (ID: a3b2b44f-df27-4a84-9891-da308e67d582) `

Then I checked the ipa myself and saw that there is a library called `libswift_Concurrency.dylib` under `AppName.app/Frameworks/UnityFramework.framework`

**Comment by sidepelican** [comment] 2024-12-30 12:36
Same. This issue is not fixed.
Xcode 16.2 and iOS 18.1.1 (iPhone 15)
Google-Mobile-Ads-SDK 11.13.0, installed via cocoapods 1.16.2

`Failed to look up symbolic reference at 0x1052d4b31 - offset 261839 - symbol symbolic _____Sg ScP in /private/var/containers/Bundle/Application/3822F393-1D3B-454E-B5E3-A200EBA267D3/xxxx.app/xxxx`

**Comment by enisshelbaya** [comment] 2025-01-09 14:30
@sidepelican did you find a solution ?

**Comment by chenilim** [comment] 2025-01-10 19:12
Adding the dummy swift file worked. Thanks jksmx!

**Comment by pratishshr** [comment] 2025-01-26 10:37
+1 seeing this issue in 11.13.0

```
Failed to look up symbolic reference at 0x10eaf819f - offset 720569 - symbol symbolic _____Sg ScP in /private/var/containers/Bundle/Application/686B5118-446E-4EB3-B67F-749CF01A4BEB/{APP_NAME}.app/Frameworks/UnityFramework.framework/UnityFramework
```
