### ISSUE TITLE
Rewarded Ads Issue

### ISSUE THREAD

**Issue by haydin20** [googleads/googleads-mobile-unity#460] opened 2017-07-11 13:46 UTC
Hi, 

i am trying use rewarded video. Im working on demo scene. For first time, request and show working good. But if i want to show a rewarded ad second time request and show not working. i can not get and ad.

i m using rewarded ads 2 different type. Watch for earn free coins, watch and continue. requested ads working for only one. 

Also when i request a ads. i m waiting 2-3 seconds for watch. Video ads comes very late. 

Any solution about this ? 

i m using default example codes and trying on default example scene.

**Comment by rampara** [comment] 2017-07-13 01:24
@haydin20 what error code do you receive when you attempt to request a second ad? Is this error reproducible for you with the sample app in this repo? Can you provide the ad unit you are using to request rewarded video ads?

**Comment by rampara** [comment] 2017-08-16 00:41
Closing due to non-response. Please re-open if this issue persists for you.

**Closed by rampara** 2017-08-16 00:41 UTC
Labels: support question
