### ISSUE TITLE
Google admob with socket.Io unity

### ISSUE THREAD

**Issue by fabpranav** [googleads/googleads-mobile-unity#595] opened 2018-01-02 13:32 UTC
Assets/GoogleMobileAds/Api/AdLoader.cs(70,35): error CS0433: The imported type `System.Action<T1,T2>' is defined multiple times

**Comment by rampara** [comment] 2018-01-30 23:17
@fabpranav closing as this issue is caused by the socket.io library and not this plugin.

**Closed by rampara** 2018-01-30 23:17 UTC
Labels: P2, support question
