### ISSUE TITLE
Converting managed assmblies to C++ (After installing plugin)

### ISSUE THREAD

**Issue by husher** [googleads/googleads-mobile-unity#418] opened 2017-05-15 23:26 UTC
Unity freezes when building for iOS after installing plugin.
I have Unity personal edition 5.6.0 and I installed the last version of the plugin.
Is there anything I can do to prevent freeze Unity when building?

**Comment by rampara** [comment] 2017-05-16 18:08
@husher do you see any output in the Unity console that might indicate the cause of the issue? If not, can you try switching the scripting backend form IL2CPP to Mono2x and trying to build? You might see additional information logged to the console with this scripting backend.

**Comment by rampara** [comment] 2017-07-13 21:05
Closing issue due to it's age. Please re-open if this issue persists for you.

**Closed by rampara** 2017-07-13 21:05 UTC
Labels: support question
