### ISSUE TITLE
Banner or Interstitial "not ready"

### ISSUE THREAD

**Issue by AppAdvisory** [googleads/googleads-mobile-unity#215] opened 2016-05-04 13:20 UTC
Hi,

How can I check if it's ready .. or not ? 

Thanks !

**Comment by Wolfos2** [comment] 2016-05-04 13:33
Add a callback to bannerView.OnAdLoaded, this will be called when the ad has finished loading.

So...
`
void Start()
{
    // Admob initialization
    bannerView.OnAdLoaded += OnAdLoaded;
}

void OnAdLoaded()
{
    // Ad has finished loading
}
`

**Comment by rampara** [comment] 2016-05-04 18:50
+1 to @Wolfos2's response. Interstitials also have an `IsLoaded()` method.

**Comment by aaaaaa55555** [comment] 2016-06-08 15:30
@Wolfos2

ok thanks a lot!

But there is always "not ready" after showing 1 interstitial ... 

Thanks for the help!

**Comment by Wolfos2** [comment] 2016-06-08 16:44
Hi,

Maybe the problem is in your settings on Admob.com? It allows you to limit
the amount of interstitials shown to a single user. I think the default
setting is once per 5 minutes but I"m not sure.

2016-06-08 17:31 GMT+02:00 Anthony Barouch <notifications@github.com>:

**Comment by aaaaaa55555** [comment] 2016-06-08 16:47
@Wolfos2  thanks for your wuick answer. 

Limitation? Is it new? I don't see where I can change it..

Thanks!

**Comment by aaaaaa55555** [comment] 2016-06-08 16:50
I find it .. but there is no imitation on my side 
![admob](https://cloud.githubusercontent.com/assets/5120751/15902748/d1610536-2da9-11e6-8f6e-c912ed0717a2.png)

**Comment by aaaaaa55555** [comment] 2016-06-09 10:29
still have this message : 

2016-06-09 12:28:23.374 colorballz[4685:724655] GoogleMobileAdsPlugin: Interstitial is not ready to be shown.


the interstitial is shown just at start and after nothing ...

**Comment by rampara** [comment] 2016-06-13 22:47
Are seeing this issue on iOS? On iOS, GADInterstitial is a one time use object. Since the Google Mobile Ads Unity plugin is a wrapper for the Google Mobile Ads Unity SDK, the same limitations apply. You can find more information on our [developer docs](https://developers.google.com/admob/ios/interstitial#only_load_gadinterstitial_once). Every time you make a interstitial ad request, you should use a new interstitial object. Our [sample project](https://github.com/googleads/googleads-mobile-unity/blob/master/samples/HelloWorld/Assets/GoogleMobileAdsDemoScript.cs) is a good example for what best practice should be.

**Comment by rampara** [comment] 2016-08-17 17:46
Closing issue due to non-response. If this issue persists, please re-open.

**Closed by rampara** 2016-08-17 17:46 UTC
Labels: support question

**Comment by erperejildo** [comment] 2017-10-31 11:48
same error here. In my case using Ionic but I think is not relevant
