### ISSUE TITLE
JarResolver error last release

### ISSUE THREAD

**Issue by ceceomer** [googleads/googleads-mobile-unity#313] opened 2016-11-28 15:02 UTC
What can I do?
![untitled](https://cloud.githubusercontent.com/assets/10334894/20673104/6a402916-b58c-11e6-938b-2b46578eb6aa.png)

**Comment by rampara** [comment] 2016-12-01 21:35
Do you have any other warnings or errors in the console output from Play Services resolver that might indicate the cause of your error? Which versions are declaring as dependencies for AdMob and Analytics?

**Comment by chuakc92** [comment] 2016-12-16 03:02
Try removing Google.JarResolver.dll.

**Comment by rampara** [comment] 2017-01-26 00:21
Closing this issue due to non-response. Please re-open if this issue persists for you.

**Closed by rampara** 2017-01-26 00:21 UTC
Labels: support question
