### ISSUE TITLE
native ads on wrong position on s6

### ISSUE THREAD

**Issue by epicapps0** [googleads/googleads-mobile-unity#457] opened 2017-07-07 05:19 UTC
First time opening it works and the native large shows in the bottom center of the screen.
after closing and reopening the game it reappears slightly below on right corner  screen (Samsung s6).

![device-2017-07-07-101401](https://user-images.githubusercontent.com/29197040/27944077-b609f3a8-62fd-11e7-9497-98f5e26652e6.png)

**Comment by rampara** [comment] 2017-07-08 00:30
@epicapps0 are you able to reproduce the issue with the sample app from this repo? If so, can you break down the steps to reproduce the issue?

**Comment by rampara** [comment] 2017-08-16 00:36
Closing due to non-response. Please re-open if this issue persists for you.

**Closed by rampara** 2017-08-16 00:36 UTC
Labels: support question
