### ISSUE TITLE
java.lang.Error  $Proxy12.onAdFailedToLoad

### ISSUE THREAD

**Issue by UnityKR** [googleads/googleads-mobile-unity#842] opened 2019-02-07 07:40 UTC
Device summary:
* samsung SM-G965N
* Android 8.0

Software summary:
* Unity 2018.3.3f1
* Resolver play-services-resolver_v1.2.98.0
* GooglePlayGamesPlugin_v0.9.58

Error Log
java.lang.Error: FATAL EXCEPTION [Thread-5544]
Unity version     : 2018.3.3f1
Device model      : samsung SM-G965N
Device fingerprint: samsung/star2lteks/star2lteks:8.0.0/R16NW/G965NKSU1ARJ2:user/release-keys
Caused by
  at com.unity3d.player.ReflectionHelper.nativeProxyInvoke (Native Method)
  at com.unity3d.player.ReflectionHelper.a (Unknown Source)
  at com.unity3d.player.ReflectionHelper$1.invoke (Unknown Source:6)
  at java.lang.reflect.Proxy.invoke (Proxy.java:913)
  at $Proxy12.onAdFailedToLoad (Unknown Source)
  at com.google.unity.ads.Interstitial$1$1$2.run (Interstitial.java:89)
  at java.lang.Thread.run (Thread.java:764)

**Comment by mkud** [comment] 2019-02-25 08:29
The same problem

java.lang.Error: FATAL EXCEPTION [Thread-45]
Unity version     : 2018.3.6f1
Device model      : LGE LGMS550
Device fingerprint: MetroPCS/ph2n_mpcs_us/ph2n:7.0/NRD90U/180402143b640:user/release-keys
Caused by
  at com.unity3d.player.ReflectionHelper.nativeProxyInvoke (Native Method)
  at com.unity3d.player.ReflectionHelper.a (Unknown Source)
  at com.unity3d.player.ReflectionHelper$1.invoke (Unknown Source)
  at java.lang.reflect.Proxy.invoke (Proxy.java:813)
  at $Proxy10.onAdFailedToLoad (Unknown Source)
  at com.google.unity.ads.RewardBasedVideo$1$1$2.run (RewardBasedVideo.java:89)
  at java.lang.Thread.run (Thread.java:761)

**Comment by chechulinYuri** [comment] 2019-03-16 08:56
the same, very high crash rate in google play due to this
unity 2018.3.*

**Comment by chechulinYuri** [comment] 2019-03-18 07:01
any updates? I had to delete admob from my project due to that error. Unity 2018.3.*
Crash rate is very high with google ads plugn, around 3-5%!

**Comment by mkud** [comment] 2019-03-18 07:07
Downgrade to Unity 2018.2.x helps you. I use 2018.2.18f1

**Comment by chechulinYuri** [comment] 2019-03-18 07:10
yeh, but 2018.3 and 2018.2 versions are not compatible, due to lots of changes with prefabs and scenes.

**Comment by mkud** [comment] 2019-03-18 07:17
Yes, you are completely right. But it helped me - I used 2017.3 before. so I went back to the previous version, and then upgraded to 2018.2 and made the same changes.

**Comment by Zohaib-Saleem** [comment] 2019-05-06 06:30
this issue is fixed in unity 2018.3.13

**Comment by UragayalaDeepika** [comment] 2019-06-28 15:35
Closing this issue. Please comment if you would want us to take a look into this again.

**Closed by UragayalaDeepika** 2019-06-28 15:35 UTC
