### ISSUE TITLE
Delegate events problem

### ISSUE THREAD

**Issue by MadeForThisCommment** [googleads/googleads-mobile-unity#494] opened 2017-09-07 03:01 UTC
I dont whats causing the problem but there are a lot of errors

> Assets/GoogleMobileAds/Platforms/Android/InterstitialClient.cs(42,46): error CS0066: `GoogleMobileAds.Android.InterstitialClient.OnAdOpening': event must be of a delegate type

**Comment by rampara** [comment] 2017-09-07 08:20
@MadeForThisCommment have you modified the source code for this plugin in any way?

**Comment by MadeForThisCommment** [comment] 2017-09-07 13:08
I didnt delete the plug-in and other folders from the old plug-in that I installed.

**Comment by rampara** [comment] 2017-09-26 23:58
@MadeForThisCommment updating from an older version of this plugin shouldn't cause this issue. If you link me to a Unity project that reproduces this issue, I can dig into what is causing it.

**Comment by rampara** [comment] 2017-11-15 02:11
Closing due to non-response.

**Closed by rampara** 2017-11-15 02:11 UTC
Labels: support question
