### ISSUE TITLE
Banner Bottom Does Not Appear Correct

### ISSUE THREAD

**Issue by ceyhuntasci** [googleads/googleads-mobile-unity#430] opened 2017-05-25 11:58 UTC
It behaves like navigation bar is not hidden on Xperia Z3 compact. So banner appears at a higher position from where it should be. I've tried v3.1.3, banner didn't show up at all but it was clickable. And on v3.2 problem is still there. Currently using v3.5

**Comment by rampara** [comment] 2017-05-30 23:49
@ceyhuntasci are you able to reproduce the issue on any other devices? I currently don't have a Z3 compact to test against.

**Comment by zhouzhanglin** [comment] 2017-06-02 01:06
UnityPlayerActivity -> onCreate
Add `((SurfaceView)mUnityPlayer.getChildAt(0)).setZOrderOnTop(false);`

**Comment by rampara** [comment] 2017-06-13 20:31
Closing as duplicate of #447.

**Closed by rampara** 2017-06-13 20:31 UTC
Labels: support question
