### ISSUE TITLE
Mediation example

### ISSUE THREAD

**Issue by boris-741** [googleads/googleads-mobile-unity#426] opened 2017-05-23 06:10 UTC
1. I can not connect with unity ads Mediation. Please show an example. 
2. With admobn I have a problem. 15% of my users receive a response from the server [no fill] on rewarded video. Why is this happening?

**Comment by rampara** [comment] 2017-05-23 22:53
Did you follow the instructions listed on the [Mediation developer docs](https://developers.google.com/admob/unity/mediation) to setup mediation? As for your no fill issue, are you running into this issue on Android or iOS? Once you have mediation set up, it should help with your fill rate.

**Comment by rampara** [comment] 2017-05-24 21:12
closing as duplicate of #427

**Closed by rampara** 2017-05-24 21:12 UTC
Labels: duplicate, support question
