### ISSUE TITLE
In-App interstitial flow

### ISSUE THREAD

**Issue by FedericoLaGreca** [googleads/googleads-mobile-unity#191] opened 2016-03-22 18:10 UTC
Hello,

we are implementing in-app interstitial ads starting with Android, and we use Unity's built-in In-App Purchasing service. We have encountered two issues using the suggested testing method (https://support.google.com/admob/answer/6170649?hl=en&ref_topic=6145802)

1) If we use IDefaultInAppPurchaseProcessor as a purchase listener, we have a crash with this message:
`Class not found when unmarshalling: com.google.android.finsky.billing.lightpurchase.PurchaseParams`

2) We solved issue 1) by using a ICustomInAppPurchaseProcessor instead of the default one, and implementing our own purchase flow (as we did in other parts of our app). The purchase works as intended using this method, but we noticed a behavior that we're not sure it's normal: our implementation of ICustomInAppPurchaseProcessor is correctly called when the user presses the buy button in the interstitial, but the callback from our flow, inside of which we call
`purchase.RecordResolution(PurchaseResolutionType.Success); `
is only called after the user closes the interstital. I guess this happens because Unity is in background while the interstitial is shown, but shouldn't the ad automatically close when the user completes a purchase?

**Comment by rampara** [comment] 2016-03-23 03:00
For the default purchase flow, I'm unable to reproduce the class not found error following the steps from the link you provided. I used our [sample application](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld), the GoogleMobileAdsDemoHandler, and ad unit id ca-app-pub-2412876219430673/6669260544. 

Also, it is not expected behavior for the interstitial to close automatically when a user completes a purchase. It is up to the user to close the interstitial. This is consistent with the default purchase flow as well. Our sample app linked above also demonstrates best practice for requesting interstitials.

**Comment by rampara** [comment] 2016-10-10 21:31
Closing this issue to due it's age and non-response. Please re-open if this issue persists for you.

**Closed by rampara** 2016-10-10 21:31 UTC
Labels: support question
