### ISSUE TITLE
HandleRewardBasedVideoFailedToLoad event received with message: Internal error

### ISSUE THREAD

**Issue by Thornus** [googleads/googleads-mobile-unity#287] opened 2016-10-16 21:31 UTC
Hi guys, when I try to load the reward based video nothing happens and this is what I get in logcat:

> HandleRewardBasedVideoFailedToLoad event received with message: Internal error

I use Vungle for the AdMob mediation, the ad should be set correctly (although it's saying "pending" next to its eCPM in the mediation window).
I tried to use a banner in the game to see if it's a general problem with the plugin but the banner works fine. I'm using version 3.0.7 of the plugin.

**Comment by rampara** [comment] 2016-10-21 21:38
In logcat, do you see any other messages that might indicate the cause of the error under the "Ads", "Unity" or vungle specific tags? Are you using the latest version of the Vungle SDK and and adapter?

**Comment by ForestJungle** [comment] 2016-10-22 08:25
Hi rampara. I use two ad networks is Unity ads and Vungle.They are still pending.... should I add more sdk for each seperate ad network?So why don't I use plugins of Unity ads and Vungle without should use Admob?
P/S: Although I added Unity services in project(Include ID Ads for both android and ios).On Admob account I set ad network Unity with full Game ID,Place ID ,API key .Now it's still pending and I can't show video on Android.

**Comment by rampara** [comment] 2016-10-24 20:08
@ForestJungle I responded to your comment in the issue you created at #293.

**Comment by siddharth3322** [comment] 2016-12-15 18:51
@rampara At present I was facing same issue when I try to load rewarded video.
I was using Unity ad network for 3rd party mediation purpose. 

![screen shot 2016-12-16 at 12 15 04 am]

Also attaching image for admob settings:

![screen shot 2016-12-16 at 12 20 06 am]

I have already integrate Unity Ads SDK into project using Asset Store.
Please give me some help into this.

(https://cloud.githubusercontent.com/assets/3082151/21237563/873d5d4e-c325-11e6-9a7f-a551b11ddca7.png)

(https://cloud.githubusercontent.com/assets/3082151/21237510/58d644de-c325-11e6-9ecf-5b92e0afb041.png)

**Comment by rampara** [comment] 2016-12-16 00:02
@siddharth3322 is this error always reproducible or are you able to successfully request and display ads from Unity Ads sometimes? Do you see any other output in logcat that may indicate the cause of the error? Can you try integrating the Unity Ads SDK available in their [public repo](https://github.com/Unity-Technologies/unity-ads-android) rather than the one distributed through the asset store.

**Comment by rampara** [comment] 2017-01-23 22:07
Closing this issue due to non-response. Please re-open if this issue persists for you.

**Closed by rampara** 2017-01-23 22:07 UTC
Labels: support question

**Comment by MrSharpp** [comment] 2021-04-30 20:26
this issue is still persists
