### ISSUE TITLE
Crash on OnePlus devices

### ISSUE THREAD

**Issue by AnnKryvenko** [googleads/googleads-mobile-unity#612] opened 2018-02-06 20:29 UTC
![screen shot 2018-02-06 at 22 19 12](https://user-images.githubusercontent.com/16333229/35882202-09d37b08-0b8c-11e8-8761-6812f3e9b1a2.png)
Unity version: 2017.3.0p2
googleads-mobile-unity version: 3.10.0

Caused by java.lang.IllegalStateException: Only fullscreen activities can request orientation
       at android.os.Parcel.readException(Parcel.java:1950)
       at android.os.Parcel.readException(Parcel.java:1888)
       at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5927)
       at android.app.Activity.setRequestedOrientation(Activity.java:5762)
       at com.google.android.gms.ads.internal.overlay.d.a(:com.google.android.gms.DynamiteModulesA@11975440:182)
       at com.google.android.gms.ads.internal.overlay.d.b(:com.google.android.gms.DynamiteModulesA@11975440:216)
       at com.google.android.gms.ads.internal.overlay.d.a(:com.google.android.gms.DynamiteModulesA@11975440:76)
       at com.google.android.gms.ads.internal.overlay.client.c.onTransact(:com.google.android.gms.DynamiteModulesA@11975440:8)
       at android.os.Binder.transact(Binder.java:622)
       at com.google.android.gms.internal.zzeu.zzb(Unknown Source:7)
       at com.google.android.gms.internal.zzxg.onCreate(Unknown Source:8)
       at com.google.android.gms.ads.AdActivity.onCreate(Unknown Source:28)
       at android.app.Activity.performCreate(Activity.java:6998)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6809)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by AibNihan** [comment] 2018-02-06 21:01
Hello There, 
You Need To Check The First Line 

> java.lang.IllegalStateException: Only fullscreen activities can request orientation

you need to orientate your screen when you call the full screen activities (in admob full screen ativities mean interstitial ad)

**Comment by rampara** [comment] 2018-02-06 23:47
This issue is a duplicate of #553 and isn't caused by this plugin but rather the GMA Android SDK. The fix for the issue will be included in the next release of the GMA Android SDK. As a workaround, you can target an API < 27.

**Closed by rampara** 2018-02-06 23:47 UTC
Labels: MAD SDK issue, duplicate
