### ISSUE TITLE
GooglePlayGames + GoogleMobileAds ( cannot post on #226 )

### ISSUE THREAD

**Issue by SoulessSerpent** [googleads/googleads-mobile-unity#228] opened 2016-05-31 03:35 UTC
After importing GooglePlayGames v09.34 and then GoogleMobileAds v3.0.3, when I attempt to build the application my aapt.exe crashes then I get a error message "Failed to re-package resources. See the Console for the details".

![](https://cloud.githubusercontent.com/assets/9650299/15638009/c063c9a0-265e-11e6-95f0-d35fb22c71af.PNG)

@rampara Sorry unity was truncating the log and yes I am using the latest version v3.0.4
Here is a full log of the error
http://pastebin.com/CvtB5Eyu

Also for some reason I cannot touch/edit the other issue post I created so sorry again for creating a new issue post

**Comment by rampara** [comment] 2016-06-01 19:04
I'm having trouble finding the cause of the error based on the log output you provided. Can you provide a link to a Unity project where you can reproduce this error? Our [sample application](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) or any other project were the issue is reproducible would work.

**Comment by rampara** [comment] 2016-08-17 17:50
Closing issue due to non-response. If this issue persists, please re-open.

**Closed by rampara** 2016-08-17 17:50 UTC
Labels: support question
