### ISSUE TITLE
Banner issue with soft keyboard

### ISSUE THREAD

**Issue by neogreco** [googleads/googleads-mobile-unity#774] opened 2018-10-05 21:24 UTC
Hello, i have a problem displaying the banner in particular with some sony devices with soft keys.
When i show the banner at the button of the screen, no matter if the keyboard is up or gone, the smart banner is showed as a little line.
If i press the task button on the soft keyboard, the app go to background and then i take it to foreground again the banner blinks with a correct size and inmediatly later it looks like a line again.
I tested in this two devices with the issue

- Sony Xperia F3113
- Sony Xperia 5221

And the problem does not happen in a 

- Motorola G3.
- Samsung Galaxy S8

I try some configuration in the android manifest but no luck.
I have this at the moment: 
```
  <activity android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" 
    	android:label="@string/app_name" 
    	android:screenOrientation="portrait" 
    	android:launchMode="singleTask" 
    	android:name="com.unity3d.player.UnityPlayerNativeActivity"
    	android:windowSoftInputMode="stateAlwaysHidden|adjustPan">
```

**Comment by rampara** [comment] 2018-10-26 17:45
@neogreco were you able to reproduce the issue on any other devices. I was unable to reproduce the issue on the Xperia devices I have access to.

**Comment by neogreco** [comment] 2018-10-29 13:22
It happened in a motorola G5 too but not always. Some times after go background or showing an interstitial ad and go back.

**Comment by neogreco** [comment] 2018-10-29 13:29
@rampara, For now, we solve the issue by cleaning up the project and re installing firebase and admob again. We remove several plugins that we do not use anymore, and i suspect that one of them affected the manifest merge causing that the banner activity remains with a non full screen theme or something like that.
It would be nice if in some way the admob configuration is not affected by another unity plugin or there is a sure way to force it.

**Comment by neogreco** [comment] 2018-10-29 13:30
I think this is related to [#576](https://github.com/googleads/googleads-mobile-unity/issues/576)

**Comment by rampara** [comment] 2018-10-31 00:44
@neogreco if you're able to reproduce the issue in the future, sharing the final merged manifest for the app would help greatly with our investigation. For now I'm closing the issue.

**Closed by rampara** 2018-10-31 00:44 UTC
Labels: P2, support question
