### ISSUE TITLE
Property 'userIdentifier' not found on object of type 'GADRewardBasedVideoAd *'

### ISSUE THREAD

**Issue by Hassurunous** [googleads/googleads-mobile-unity#632] opened 2018-03-16 15:27 UTC
Just downloaded and installed this yesterday and was trying to test it out with iOS. I was getting some other errors that I was able to resolve by changing the build target, and I've still got about 500 "Warnings" in Xcode about Deprecation and code that will never be executed, but this is the only true error I am left with. I'm not really sure what to even try here at the moment. Any tips would be greatly appreciated!

**Comment by rampara** [comment] 2018-03-16 16:15
@Hassurunous it looks like your project may be referencing an older version of the iOS GMA SDK. Can you run the `pod repo update ` command and try to rebuild your iOS project.

**Comment by Hassurunous** [comment] 2018-03-16 20:43
Still no luck. I notice in the podfile Unity generated it had the version set to 7.0, so I deleted that bit and ran update again and rebuilt but same error.

**Comment by rampara** [comment] 2018-03-19 17:32
@Hassurunous the specified version is the podfile should be `~> 7.0` which should resolve to the newest `7.x` release of the SDK. Is the latest SDK not pulled in if you try building a new iOS project (instead of appending or replacing an existing one) ?

**Comment by fkkcloud** [comment] 2018-03-23 06:42
having the same issue here - any updates?

**Comment by fkkcloud** [comment] 2018-03-28 02:14
@rampara I am having exactly same problem and using previous version seems to getting rid of this issue. btw my versions:
GMA:3.8.0
Unity:2017.3.1f1
Xcode: 9.3 beta2

**Comment by rampara** [comment] 2018-03-28 21:27
@fkkcloud can you check what version of the iOS GMA SDK is being included in your generated Xcode project. The easiest way to do this would be to turn on verbose logging (select `Assets-> Play Services Resolver -> iOS Resolver -> Settings` and check `verbose logging`). You should see a message in the console that starts with `'/usr/local/bin/pod install' completed with code 0`, which lists the version of the iOS GMA SDK was included in the generated Xcode project.

**Comment by sysads** [comment] 2018-04-02 08:30
Any fix to this issue? Having same issue now.

**Comment by rampara** [comment] 2018-04-02 17:48
@sysads can you try following the instructions in my previous comment to check which version of the GMA SDK is used in your Xcode project?

**Comment by koniu699** [comment] 2018-04-04 06:32
Hello, I'm having the same issue. From logs I've got this:

> Using Google-Mobile-Ads-SDK (7.24.1)

and the error is the same:

> Property 'userIdentifier' not found on object of type 'GADRewardBasedVideoAd *'

I'm using Unity 2017.1.2f1

**Comment by fkkcloud** [comment] 2018-04-04 06:39
@sysads @koniu699  try to remove the latest plugin from Unity project and installing [old version](https://github.com/googleads/googleads-mobile-unity/releases/tag/v3.8.0)

**Comment by koniu699** [comment] 2018-04-04 06:54
@fkkcloud yeah, I just did that and it works as expected. However it's a bug in newest version (and it's the version "promoted" on main download page), so it should be noted.

**Comment by rampara** [comment] 2018-04-04 18:35
@fkkcloud @koniu699 the issue is caused because your Xcode project doesn't include the latest version of the iOS GMA SDK. Can you trying running `pod repo update` in the terminal and then building a new Xcode project (instead of appending to an existing build)?

**Comment by fkkcloud** [comment] 2018-04-04 18:36
@rampara Created new xcode project from scratch but has same issue.

**Comment by rampara** [comment] 2018-04-04 19:09
@fkkcloud have you run `pod repo update` ? Did you check if you're pulling in an older version of the iOS GMA SDK into your generated Xcode project?

**Comment by zogster** [comment] 2018-05-15 07:10
Hi, had the same issue.
Running `pod repo update` didnt work for me. Got a connection/repo not found error.
What helped:
```
pod repo remove master
pod setup
```
And then a fresh Unity export.

**Comment by MorganMoon** [comment] 2018-05-17 01:09
Encountering this same issue in Unity 2018.1.0f2

**Comment by htsoft** [comment] 2018-06-21 18:06
Same issue in Unity 2018.1.5f1 I've updated repo using:  
```
pod repo remove master
pod setup
```
But the problem still persists

**Comment by rampara** [comment] 2018-06-25 10:42
Closing issue as generating a new iOS project that includes the latest version of the iOS SDK resolves this issue.

**Closed by rampara** 2018-06-25 10:42 UTC
Labels: P2, support question
