### ISSUE TITLE
Crash Rate Drastically Increase From v 3.16 To Onward

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#928] opened 2019-05-30 05:17 UTC
So we replace admob sdk with v3.16, v3.17 and crash rate increase. Its like horizontal line in google play dashboard. Lot of other developers experience same issue.
Everything is implemented correctly.
Also game crashes when interstitial ad is closed. (Tested on multiple android devices).
Game also wont run sometimes when interstitial ad won't appear.

**Comment by stowy** [comment] 2019-06-03 09:01
Hello, can you please provide more details about crashes - ie stack traces, any specific android API version, and specific devices?  When you say a lot of other developers experience this issue, please can you provide more detail - where else are you seeing this reported?

**Comment by matie** [comment] 2019-06-03 09:04
Facing same problems here. 

Since last week, jar resolver update, it is a huge issue. I haven't changed code related to advertising. Both are banner related.

Calling .Hide() on a banner causes a hard app crash. It says something about that ad size and unity id must be set first, but they are set. The banner is visible.  

![Screenshot 2019-06-03 at 10 52 13](https://user-images.githubusercontent.com/3448261/58789318-26223f00-85ee-11e9-86f7-dc4aa0632705.png)

When preventing .Hide() to be executed, it get this error (google play crash report), but I can't figure out when this is happening. Maybe after returning from a banner click?

![Screenshot 2019-06-03 at 10 53 54](https://user-images.githubusercontent.com/3448261/58789338-31756a80-85ee-11e9-86f0-d7c39557631c.png)


Regards,
Mt

**Comment by stowy** [comment] 2019-06-03 10:06
This is odd. Can you please provide a sample reproducing the crash - also what version of the plugin and versions of Android, etc are you using? I've have not seen this crash in testing.

**Comment by matie** [comment] 2019-06-03 11:26
Found the issue. I occasionally initialised the banner with an empty (null) unit ID string. Before, the banner load failed callback solved the issue, but now it crashes the app.  My fault, but maybe you could log a warning/exception or something when creating the BannerView object, in stead of the current crash which occurs when running .loadAd

**Comment by UragayalaDeepika** [comment] 2019-06-06 15:52
@matie Closing this. Feel free to reopen if you still have any issues.

**Closed by UragayalaDeepika** 2019-06-06 15:52 UTC
