### ISSUE TITLE
Crash on oreo device with Only fullscreen activities can request orientation Error

### ISSUE THREAD

**Issue by storybell** [googleads/googleads-mobile-unity#608] opened 2018-02-03 08:24 UTC
Hello,

my game continuously crash while showing ads both intertitial and reward(banner not tested) on android oreo device for platform 26 and 27.

here is my logcat
[Logcat.txt](https://github.com/googleads/googleads-mobile-unity/files/1691528/Logcat.txt)

**Comment by rampara** [comment] 2018-02-06 23:48
This issue is a duplicate of #553 and isn't caused by this plugin but rather the GMA Android SDK. The fix for the issue will be included in the next release of the GMA Android SDK. As a workaround, you can target an API < 27.

**Closed** 2018-02-06 23:49 UTC
Labels: MAD SDK issue, duplicate
