### ISSUE TITLE
Position ad programatically

### ISSUE THREAD

**Issue by brinca** [googleads/googleads-mobile-unity#573] opened 2017-11-23 04:53 UTC
Once deployed, we should be able to reposition the ad through script, to any arbitrary position, including off screen.
This could be used, among other things, to fake ads embedded in scroll views (we could move the ad in sync with the scroll view so that to the user it would appear that it was included in the content being scrolled).

My actual use case is a level select screen, where each level is stacked vertically, styled like direction signs on a post.
Every so often I want to display a sign containing an ad instead of a level, so that it could blend in better with the content (same as native ads on blogs and other web-based content).

I realise that having the ad view as a child of a game object is tricky, given that this seems to be a view overlaid on top of the Unity view, but the next best thing is to be able to control movement of the ad(s), so that, while the Unity view below would show an empty sign, when moved in sync with the banner view it would look like if they were one.

This would be great for native ads, but if possible for banners too, even better! ;)

Related to #146 and #563

**Comment by rampara** [comment] 2017-11-30 19:23
Closing as a duplicate of #563.

**Closed** 2017-11-30 19:23 UTC
Labels: feature request
