### ISSUE TITLE
Unity Cloud Build iOS: GoogleMobileAds.h file not found

### ISSUE THREAD

**Issue by craftyfirefox** [googleads/googleads-mobile-unity#528] opened 2017-10-05 07:03 UTC
Since Issue #524 is already closed I'll open my own: I have the same problem as described there, but mine isn't resolved - Unity Cloud Build for IOs still fails when trying to compile with this plugin added. I believe I got the latest versions of all plugins, imported the necessary framework, but the issue persists. Please find attached my full log from the latest build using the Hello World app to avoid unnecessary cluttering with unrelated stuff.

[developer buildlog.txt](https://github.com/googleads/googleads-mobile-unity/files/1358274/developer.buildlog.txt)

**Comment by rampara** [comment] 2017-10-13 00:45
@craftyfirefox I'm having trouble reproducing this. I used the HelloWorld sample project from this repo and the only steps required on my part was importing the Unity package for this plugin and adding `MainScene` to list of scenes in the build. Can you try with the latest version of this plugin which includes a newer version of Play Services Resolver than what was used in your build.

**Comment by lambdor** [comment] 2017-10-17 10:18
I get this error ever since I updated to XCode 9.0.1 see #544.

**Comment by craftyfirefox** [comment] 2017-10-25 10:48
Still no luck fixing this, I tried to delete everything and reimport the plugin in Version 3.8.0. Still the same, I attached the project as I uploaded it to unity services, to check and compare:

https://www.dropbox.com/s/u8t55go98v38laj/GoogleAdsHelloWorld.zip?dl=0

**Comment by lambdor** [comment] 2017-10-25 12:19
Another thing I noticed. I usually used to open the Xcode project with the .xproj file. But there is also a .xworkspace file generated. Try to open the project with .xworkspace.

**Comment by lambdor** [comment] 2017-10-25 12:22
Oh, and another crazy Apple black magic weirdness. When I add the framework from a subdirectory of my project folder it doesn't work. But when I add it from the Downloads folder it does. Makes now sense, but I can reproduce this error. It's almost as if some folders on Mac can get cursed...

**Comment by rampara** [comment] 2017-10-25 19:28
@lambdor the default behavior of the GMA Unity plugin is to generate a xcworkspace that includes all the required dependencies of the plugin. If you would like the required dependencies to be added to a standard Xcode project instead, you can toggle the option at `Assets -> Play Services Resolver -> iOS Resolver -> Settings -> Cocoapods Integration`.

**Comment by craftyfirefox** [comment] 2017-10-29 21:48
Any updates on this? I don't really want to build locally, Cloud Build is so much easier and faster.

**Comment by rampara** [comment] 2017-11-10 01:20
@craftyfirefox are you still running into this issue after updating the the latest version of the plugin and performing version resolution (select `Assets -> Play Services Resolver ->Version Handler -> Update` in the Unity editor) ?

**Comment by rampara** [comment] 2017-12-06 16:31
Closing this issue due to non-response. Please re-open if this issue persists for you.

**Closed by rampara** 2017-12-06 16:31 UTC
Labels: support question
