### ISSUE TITLE
Banner view positioned on top of the screen shows cut (partially) on Android device with notch

### ISSUE THREAD

**Issue by mariome17** [googleads/googleads-mobile-unity#823] opened 2018-12-28 10:05 UTC
I'm testing this on Oneplus 6T. But I assume the issue is similar on other Android devices with a notch.
On iPhone with notch the banner ad looks ok(same app).
I'm on the latest version of the Google Mobile Ads.
This is how I'm creating the banner:
[](url)
`banner1 = new BannerView(AndroidbannerAdId, AdSize.Banner, AdPosition.Top);`

And below, in the printscreen, it's an illustration of the problem. The banner is cut, partially.

![screenshot_20181226-110059](https://user-images.githubusercontent.com/46218616/50512054-53435200-0a90-11e9-87a3-4a4673a8d5ec.jpg)

On Android devices without a notch, the banner shows up ok.
My Unity version is the latest, 2018.3.0.

**Comment by itayganor** [comment] 2019-01-09 22:48
Yeah, seems like there are some serious problems with the vertical positioning system. The notch confuses it and you can't really use hardcoded position because the height of the notch is not the same across all devices of course.
My issue is #792 , I wish they've answered me. I hope this could be get fixed soon.

**Comment by rampara** [comment] 2019-01-23 03:52
Closing as duplicate of #792.

**Closed** 2019-01-23 03:52 UTC
Labels: P1, duplicate, feature request
