### ISSUE TITLE
play-services-ads:22.4.0 issue

### ISSUE THREAD

**Issue by dcosmin-97** [googleads/googleads-mobile-unity#2930] opened 2023-09-14 09:57 UTC
### [REQUIRED] Step 1: Describe your environment

  * Unity version:  2021.3.30f1
  * Google Mobile Ads Unity plugin version:  8.5.2
  * Platform: Android - Unity Editor
  * Mediation ad networks used, and their versions: Applovin 6.9.0, Liftoff 4.0.0, Meta 3.11.0, Mintegral 1.2.1, Pangle 2.3.0

#### Steps to reproduce:

If you force resolve, you will get 
<file>Assets/Plugins/Android/com.google.android.gms.play-services-ads-22.4.0.aar</file>
<file>Assets/Plugins/Android/com.google.android.gms.play-services-ads-base-22.4.0.aar</file>
<file>Assets/Plugins/Android/com.google.android.gms.play-services-ads-identifier-18.0.0.aar</file>
<file>Assets/Plugins/Android/com.google.android.gms.play-services-ads-lite-22.4.0.aar</file>
<file>Assets/Plugins/Android/com.google.android.gms.play-services-appset-16.0.1.aar</file>
<file>Assets/Plugins/Android/com.google.android.gms.play-services-base-18.2.0.aar</file>
<file>Assets/Plugins/Android/com.google.android.gms.play-services-basement-18.1.0.aar</file>
<file>Assets/Plugins/Android/com.google.android.gms.play-services-measurement-21.3.0.aar</file>
<file>Assets/Plugins/Android/com.google.android.gms.play-services-measurement-api-21.3.0.aar</file>
<file>Assets/Plugins/Android/com.google.android.gms.play-services-measurement-base-21.3.0.aar</file>
<file>Assets/Plugins/Android/com.google.android.gms.play-services-measurement-impl-21.3.0.aar</file>
<file>Assets/Plugins/Android/com.google.android.gms.play-services-measurement-sdk-21.3.0.aar</file>
<file>Assets/Plugins/Android/com.google.android.gms.play-services-measurement-sdk-api-21.3.0.aar</file>

The resolve will complete without errors.

The issue when you try to build:
FAILURE: Build completed with 2 failures.

```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Admin\.gradle\caches\transforms-2\files-2.1\00277a26865588baf0041d38a0cce91f\com.google.android.gms.play-services-ads-lite-22.4.0\AndroidManifest.xml:48:5-117: AAPT: error: unexpected element <property> found in <manifest><application>.
```

How to fix:
Assets\GoogleMobileAds\Editor\GoogleMobileAdsDependencies.xml
Change to: 
androidPackage spec="com.google.android.gms:play-services-ads:[22.3.0]"

**Comment by NVentimiglia** [comment] 2023-09-15 21:50
Hi @dcosmin-97 

Confirmed the issue, thank you.

**Comment by xmx77** [comment] 2023-09-17 17:52
Not work with me, untiy Unity version: 2021.3.29.
I try to change to :com.google.android.gms:play-services-ads:[22.3.0]
And to com.google.android.gms:play-services-ads:[22.4.0]
both of them not work.

**Comment by dcosmin-97** [comment] 2023-09-17 17:56
> Not work with me, untiy Unity version: 2021.3.29. I try to change to :com.google.android.gms:play-services-ads:[22.3.0] And to com.google.android.gms:play-services-ads:[22.4.0] both of them not work.

I can try to help you, what other SDK and mediations do you have in the game? 
Also, delete all the resolved libraries and check for the remaining ones to exist in the main AndroidManifest.xml.

**Comment by xmx77** [comment] 2023-09-17 18:08
I have those 
- Firebase sdk 
- facebook SDK 
- Unity ADS 
And the issue it was 
`/Users/mahmoudabualamrien/.gradle/caches/transforms-2/files-2.1/b786d6b8050a9adf09aae2d746c9c69e/com.google.android.gms.play-services-ads-lite-22.4.0/AndroidManifest.xml:48:5-117: AAPT: error: unexpected element <property> found in <manifest><application>.`

**Comment by xmx77** [comment] 2023-09-17 18:09
> > Not work with me, untiy Unity version: 2021.3.29. I try to change to :com.google.android.gms:play-services-ads:[22.3.0] And to com.google.android.gms:play-services-ads:[22.4.0] both of them not work.
> 
> I can try to help you, what other SDK and mediations do you have in the game? Also, delete all the resolved libraries and check for the remaining ones to exist in the main AndroidManifest.xml.

I have those 
- Firebase sdk 
- facebook SDK 
- Unity ADS 
And the issue it was 
`Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/mahmoudabualamrien/.gradle/caches/transforms-2/files-2.1/b786d6b8050a9adf09aae2d746c9c69e/com.google.android.gms.play-services-ads-lite-22.4.0/AndroidManifest.xml:48:5-117: AAPT: error: unexpected element <property> found in <manifest><application>.`

**Comment by dcosmin-97** [comment] 2023-09-17 18:33
> > > Not work with me, untiy Unity version: 2021.3.29. I try to change to :com.google.android.gms:play-services-ads:[22.3.0] And to com.google.android.gms:play-services-ads:[22.4.0] both of them not work.
> > 
> > 
> > I can try to help you, what other SDK and mediations do you have in the game? Also, delete all the resolved libraries and check for the remaining ones to exist in the main AndroidManifest.xml.
> 
> Unity version: 2021.3.30f1 Google Mobile Ads Unity plugin version: v8.5.2 Platform: Android - Unity Editor
> 
> I have those SDKs :
> 
>     * Firebase sdk
> 
>     * facebook SDK
> 
>     * Unity ADS
> 
> 
> And the issue it was `Execution failed for task ':launcher:processReleaseResources'.
> 
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> > Android resource linking failed
> > /Users/dddddd/.gradle/caches/transforms-2/files-2.1/b786d6b8050a9adf09aae2d746c9c69e/com.google.android.gms.play-services-ads-lite-22.4.0/AndroidManifest.xml:48:5-117: AAPT: error: unexpected element  found in .`

Well, I know that Unity ADS has some issues when you resolve. I have opened a separate issue for it.
If you set this to "com.google.android.gms:play-services-ads:[22.3.0]", you should not have com.google.android.gms.play-services-ads-lite-22.4.0 
Make sure everything is deleted when you press delete resolved, it may have issues

**Comment by xmx77** [comment] 2023-09-17 19:13
ok it's work , 
I don't understand you mean change "com.google.android.gms:play-services-ads:[22.3.0]" with Brackets 
i just change like this "com.google.android.gms:play-services-ads:22.3.0"
----
Anyway thank you for help

**Comment by xmx77** [comment] 2023-09-17 19:14
> > > > Not work with me, untiy Unity version: 2021.3.29. I try to change to :com.google.android.gms:play-services-ads:[22.3.0] And to com.google.android.gms:play-services-ads:[22.4.0] both of them not work.
> > > 
> > > 
> > > I can try to help you, what other SDK and mediations do you have in the game? Also, delete all the resolved libraries and check for the remaining ones to exist in the main AndroidManifest.xml.
> > 
> > 
> > Unity version: 2021.3.30f1 Google Mobile Ads Unity plugin version: v8.5.2 Platform: Android - Unity Editor
> > I have those SDKs :
> > ```
> > * Firebase sdk
> > 
> > * facebook SDK
> > 
> > * Unity ADS
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And the issue it was `Execution failed for task ':launcher:processReleaseResources'.
> > > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> > > Android resource linking failed
> > > /Users/dddddd/.gradle/caches/transforms-2/files-2.1/b786d6b8050a9adf09aae2d746c9c69e/com.google.android.gms.play-services-ads-lite-22.4.0/AndroidManifest.xml:48:5-117: AAPT: error: unexpected element  found in .`
> 
> Well, I know that Unity ADS has some issues when you resolve. I have opened a separate issue for it. If you set this to "com.google.android.gms:play-services-ads:[22.3.0]", you should not have com.google.android.gms.play-services-ads-lite-22.4.0 Make sure everything is deleted when you press delete resolved, it may have issues

ok it's work , 
I don't understand you mean change "com.google.android.gms:play-services-ads:[22.3.0]" with Brackets 
i just change like this "com.google.android.gms:play-services-ads:22.3.0"
----
Anyway thank you for help

**Comment by NVentimiglia** [comment] 2023-09-18 17:59
Glad it is working, we are still looking into this issue.

**Comment by GodzillaDev** [comment] 2023-09-19 14:54
Hi, I'm facing this issue as well, however after deleting the libraries in the error logs we still see the following error:
`21:21:09  1: Task failed with an exception.
21:21:09  -----------
21:21:09  * What went wrong:
21:21:09  Execution failed for task ':launcher:processReleaseResources'.
21:21:09  > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
21:21:09     > Android resource linking failed
21:21:09       C:\Users\clientdev\.gradle\caches\transforms-3\2d92465aff1ea491d8332c9499aa2cb9\transformed\jetified-com.google.android.gms.play-services-ads-lite-22.4.0\AndroidManifest.xml:48:5-117: AAPT: error: unexpected element <property> found in <manifest><application>.
21:21:09           
21:21:09  
21:21:09  * Try:
21:21:09  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
21:21:09  ==============================================================================
21:21:09  
21:21:09  2: Task failed with an exception.
21:21:09  -----------
21:21:09  * What went wrong:
21:21:09  Execution failed for task ':launcher:bundleReleaseResources'.
21:21:09  > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
21:21:09     > Android resource linking failed
21:21:09       C:\workspace\Temp\gradleOut\launcher\build\intermediates\bundle_manifest\release\bundle-manifest\AndroidManifest.xml:532: AAPT: error: unexpected element <property> found in <manifest><application>.`

Could it have something to do with other sdks depending on that specific version of play-services-ads-lite-22.4.0? E.g AppsFlyer  forcing it to revert to that version of play-services?

**Comment by qbit86** [comment] 2023-09-21 13:16
@NVentimiglia > _Confirmed the issue_
@NVentimiglia > _we are still looking into this issue._

I'm also facing this AAPT failure after updating AppLovin mediation adapters in Unity project.
Please let us know when you fix this!
![image](https://github.com/googleads/googleads-mobile-unity/assets/880168/242f60f9-4320-41e3-8e0e-8f6916862230)
```
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/…/AndroidManifest.xml:622: AAPT: error: unexpected element <property> found in <manifest><application>.
```

**Comment by BlackDemonZyT** [comment] 2023-09-21 15:39
I have the same issue also, help please:

`[pram:03.512][err] * What went wrong:
[pram:03.512][err] Execution failed for task ':launcher:processDebugResources'.
[pram:03.512][err] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[pram:03.512][err]    > Android resource linking failed
[pram:03.512][err]      C:\Users\black\.gradle\caches\transforms-2\files-2.1\057b562dece9137b8f32755026740bcc\com.google.android.gms.play-services-ads-lite-22.4.0\AndroidManifest.xml:48:5-117: AAPT: error: unexpected element <property> found in <manifest><application>.
`

**Comment by NVentimiglia** [comment] 2023-09-27 23:27
Thanks for the update, we are still looking into this issue and hope to solve this soon.

**Comment by NVentimiglia** [comment] 2023-09-29 17:46
No ETA at the moment, but I have flagged this issue as high priority.

**Comment by dcosmin-97** [comment] 2023-09-30 20:33
Changes to androidPackage spec="com.google.android.gms:play-services-ads:[22.3.0]" does not work anymore.
Has anyone find a temporary fix for this?

**Comment by chakaramba** [comment] 2023-10-04 12:40
We're using Applovin MAX plugin for unity, version 5.1.4
And recently, after updating Google AdMob integration from `android_22.0.0.2_ios_10.4.0.0` to `android_22.4.0.0_ios_10.11.0.0` (alongside with other mediations, but that seem to not matter), we've encountered issue with android builds failing with the following log: 
```
Execution failed for task ':launcher:processReleaseResources'.
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Android resource linking failed
%path%/jetified-facebook-core-16.2.0/AndroidManifest.xml:36:13-37: AAPT: error: unexpected element <property> found in <manifest><application>.
```
Note: iOS builds were fine.


After a quite painful investigation through sdk and mediations changelogs and testing different changes on their own, it appeared that updating Google ads mediation network was the cause. After that, we've found this issue about the latest 22.4.0 release for Android Google ads and corresponding 22.4.0.0 update for Google Ads Android mediation in Applovin MAX.

So, as a workaround to preserve latest changes in iOS mediation and still have near-to-latest changes on Android, we've manually edited corresponding mediation dependencies file `Assets/MaxSdk/Mediation/Google/Editor/Dependencies.xml` to have latest version iOS pod and android package specified as `[22.3.0.0]`:

```
<androidPackage spec="com.applovin.mediation:google-adapter:[22.3.0.0]" />
<iosPod name="AppLovinMediationGoogleAdapter" version="10.11.0.0" />
```

**Comment by dcosmin-97** [comment] 2023-10-04 12:44
> We're using Applovin MAX plugin for unity, version 5.1.4 And recently, after updating Google AdMob integration from `android_22.0.0.2_ios_10.4.0.0` to `android_22.4.0.0_ios_10.11.0.0` (alongside with other mediations, but that seem to not matter), we've encountered issue with android builds failing with the following log:
> 
> ```
> Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> Android resource linking failed
> %path%/jetified-facebook-core-16.2.0/AndroidManifest.xml:36:13-37: AAPT: error: unexpected element <property> found in <manifest><application>.
> ```
> 
> Note: iOS builds were fine.
> 
> After a quite painful investigation through sdk and mediations changelogs and testing different changes on their own, it appeared that updating Google ads mediation network was the cause. After that, we've found this issue about the latest 22.4.0 release for Android Google ads and corresponding 22.4.0.0 update for Google Ads Android mediation in Applovin MAX.
> 
> So, as a workaround to preserve latest changes in iOS mediation and still have near-to-latest changes on Android, we've manually edited corresponding mediation dependencies file `Assets/MaxSdk/Mediation/Google/Editor/Dependencies.xml` to have latest version iOS pod and android package specified as `[22.3.0.0]`:
> 
> ```
> <androidPackage spec="com.applovin.mediation:google-adapter:[22.3.0.0]" />
> <iosPod name="AppLovinMediationGoogleAdapter" version="10.11.0.0" />
> ```
> 
> Useful links:
> 
>     * Mediation changelog: [iOS](https://github.com/AppLovin/AppLovin-MAX-SDK-iOS/blob/master/Google/CHANGELOG.md)/[Android](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/master/Google/CHANGELOG.md)
> 
>     * SDK changelog: [iOS](https://developers.google.com/admob/ios/rel-notes)/[Android](https://developers.google.com/admob/android/rel-notes)

Have you tried a different Gradle / Gradle plugin other than the default one from Unity? I think this might be the cause.
I will try this approach today.

**Comment by ivancy2001** [comment] 2023-10-06 03:52
hi, the following works for me with AppLovin sdk version 11.11.3, Admob mediation version 22.4.0 / Admob sdk version 8.5.2
1. upgrading unity gradle to 6.7.1
2. under Assets/Plugin/Android/baseProjectTemplate.gradle - set dependencies classpath: com.android.tools.build:gradle:4.2.1

**Comment by BrushkouMatvey** [comment] 2023-10-14 19:18
> hi, the following works for me with Unity 2021.3.27f1, AppLovin sdk version 11.11.3, Admob mediation version 22.4.0 / Admob sdk version 8.5.2
> 
> 1. upgrading unity gradle to 6.7.1
> 2. under Assets/Plugin/Android/baseProjectTemplate.gradle - set dependencies classpath: com.android.tools.build:gradle:4.2.1

how to update unity Gradle to 6.7.1?

**Comment by BrushkouMatvey** [comment] 2023-10-14 19:28
> > Have you tried a different Gradle / Gradle plugin other than the default one from Unity? I think this might be the cause.
> > I will try this approach today.
> 
> @dcosmin-97, no, just skipped the "broken" 22.4.0 version by sticking to the previous 22.3.0 until the fix will come

what is the version of AppLovin MAX SDK?

**Comment by chakaramba** [comment] 2023-10-16 11:21
@BrushkouMatvey, MAX SDK v11.11.3, same as it was for Plugin v 5.11.3
![image](https://github.com/googleads/googleads-mobile-unity/assets/31999358/e6e0cb18-4058-400c-b93e-957473a36b98)

Though, this version is still off the changelog for whatever the reason :/ 
 https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases

**Comment by ivancy2001** [comment] 2023-10-24 08:30
> > hi, the following works for me with Unity 2021.3.27f1, AppLovin sdk version 11.11.3, Admob mediation version 22.4.0 / Admob sdk version 8.5.2
> > 
> > 1. upgrading unity gradle to 6.7.1
> > 2. under Assets/Plugin/Android/baseProjectTemplate.gradle - set dependencies classpath: com.android.tools.build:gradle:4.2.1
> 
> how to update unity Gradle to 6.7.1?

download from https://gradle.org/releases/
change the gradle folder setting in unity preferences

**Comment by juanblasco** [comment] 2023-10-24 09:10
> > > hi, the following works for me with Unity 2021.3.27f1, AppLovin sdk version 11.11.3, Admob mediation version 22.4.0 / Admob sdk version 8.5.2
> > > 
> > > 1. upgrading unity gradle to 6.7.1
> > > 2. under Assets/Plugin/Android/baseProjectTemplate.gradle - set dependencies classpath: com.android.tools.build:gradle:4.2.1
> > 
> > 
> > how to update unity Gradle to 6.7.1?
> 
> download from https://gradle.org/releases/ change the gradle folder setting in unity preferences

Gonna try your approach, but I don't know how to do the step 2 and why is it necessary, could you explain please?

Thanks in advance

**Comment by juanblasco** [comment] 2023-10-24 10:48
I was able to upgrade grade and got a succesful build but when I tried to upgrade admob I got the same issue

**Comment by NVentimiglia** [comment] 2023-10-25 00:54
This is a known issue and we are working on a fix.

As a work around you can hard code the maximum version of the google mobile ads Android sdk in the `GoogleMobileAdsDependencies.xml` file.

```
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.android.gms:play-services-ads:[22.3.0]">
      <repositories>
        <repository>https://maven.google.com/</repository>
      </repositories>
    </androidPackage>
  </androidPackages>

  <iosPods>
    <iosPod name="Google-Mobile-Ads-SDK" version="~> 10.9">
      <sources>
        <source>https://github.com/CocoaPods/Specs</source>
      </sources>
    </iosPod>
  </iosPods>
</dependencies>
```

**Comment by ericleich** [comment] 2023-10-30 23:53
We published some documentation at https://developers.google.com/admob/unity/gradle with details on how to upgrade Gradle. For folks still having issues, we'd appreciate feedback on whether these steps work for you.

**Comment by SCastanedaMunoz** [comment] 2023-11-02 17:53
> We published some documentation at https://developers.google.com/admob/unity/gradle with details on how to upgrade Gradle. For folks still having issues, we'd appreciate feedback on whether these steps work for you.

Hey, I have noticed the documentation fix states that this should be applied when using target API 33 or higher, this seems incorrect as you should be able to build without issues when targeting API 33. (I have corroborated this with older versions such as 2020.3.37f1).

Is this fix/requirement something that will be required for future versions, let's say 22.5.0? 🤔 

The proposed fix also does not seem compatible with 2020.3.37f1. From our end we have documented on a video all the require steps to Export as an Android Studio project and upgrade to Gradle higher versions (tested with 8.1.2), using the AGP Upgrade tool. This seems to be the only way to build for API 34 on 2020.3+.

**Comment by batteredhedgehog** [comment] 2023-11-08 20:32
why is this closed? Pinning a dependency is a workaround, not a fix.

**Comment by NVentimiglia** [comment] 2023-11-18 00:05
Hello everyone,

We have [launched v8.6.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/v8.6.0) of the Google Mobile Ads for Unity Plugin. This is an important patch release that resolves compatibility issues between older AGP version 4.0.1(Unity editors below 2022.3) and Android GMA SDKv 22.4 and above. 

Previously, we have published[ this workaround](https://developers.google.com/admob/unity/gradle) instructing you on how to upgrade Unity's Gradle installation. While this option is still recommended, this additional step is no longer required with and after v8.6.0 of the Plugin

In Google Mobile Ads Settings you will see two new options; **"Enable kotlix.coroutines packaging options."** and **"Remove property tag from GMA Android SDK."**. Make sure both of these options are enabled and your build should work as expected.

![image](https://github.com/googleads/googleads-mobile-unity/assets/125889/9028b373-c3eb-4a20-8e7d-52c0b133c84e)

Lastly, if you see any issues with this release, please report the problem here, and I will be happy to help you out.

Nick

**Comment by thanhtoan88** [comment] 2023-11-25 04:43
WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 34

This Android Gradle plugin (7.3.1) was tested up to compileSdk = 33

This warning can be suppressed by adding
    android.suppressUnsupportedCompileSdk=34
to this project's gradle.properties

**Comment by kushG** [comment] 2023-11-29 18:20
Hey @NVentimiglia I'm running into this https://github.com/googleads/googleads-mobile-unity/issues/3042. Any insights ?

**Comment by shefich** [comment] 2023-12-15 18:47
I used gradle 6.7.1 and custom baseProjectTemplate as described in the workaround.
It gives me error upon build:
`A failure occurred while executing com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnable See the Console for details.`
How can I fix this?

**Comment by NVentimiglia** [comment] 2023-12-15 18:50
Another work around is to use EDM4U dependency resolution instead of Custom Main Gradle Template and
Custom Gradle Properties Template. We are looking into a solution.

**Comment by shefich** [comment] 2023-12-15 18:57
I'm using custom templates in my project cause of other libraries. Also I use EDM4U and update resolution every time after adding new sdk. But I still have the error described above.
Unity 2021.3.33
Google Mobile Ads Unity Plugin v8.6.0

**Comment by shefich** [comment] 2023-12-15 19:11
BTW it works in Unity 2022.3.x (building for Android SDK 34 with Admob 8.6.0)

**Comment by NVentimiglia** [comment] 2024-01-12 02:20
Closing this issue as fixed.

Please feel free to open a new issue if you run into gradle problems.

**Closed by NVentimiglia** 2024-01-12 02:20 UTC
Labels: P1

**Comment by shefich** [comment] 2024-01-12 13:16
It doesn't fixed. I tried it now and still have this error upon build on Unity 2021.3.34:
`FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':launcher:bundleReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.Aapt2ProcessResourcesRunnable
   > AAPT2 aapt2-4.2.1-7147631-windows Daemon #0: Unexpected error during link, attempting to stop daemon.
     This should not happen under normal circumstances, please file an issue if it does.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > AAPT2 aapt2-4.2.1-7147631-windows Daemon #1: Unexpected error during link, attempting to stop daemon.
     This should not happen under normal circumstances, please file an issue if it does.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
* Get more help at https://help.gradle.org
BUILD FAILED in 41s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)`

**Comment by DungDajHjep** [comment] 2024-04-20 09:40
> hi, the following works for me with Unity 2021.3.27f1, AppLovin sdk version 11.11.3, Admob mediation version 22.4.0 / Admob sdk version 8.5.2
> 
> 1. upgrading unity gradle to 6.7.1
> 2. under Assets/Plugin/Android/baseProjectTemplate.gradle - set dependencies classpath: com.android.tools.build:gradle:4.2.1

Thanks so much !
