### ISSUE TITLE
3.9.0: Banner position stuck at top?

### ISSUE THREAD

**Issue by xxPillsxx** [googleads/googleads-mobile-unity#572] opened 2017-11-22 15:23 UTC
I recently updated to 3.9.0 cause I heard it should fix some incorrect ad positions, but now on my android app, my banner ad is stuck at the top position. I can position it left, middle and right but it's always on top. Tried deleting everything related to the plugin in the project and reimporting but same result, tried clean install, reimport all, still same result. I have not tested real ads with any iOS devices yet.
This only happens to real ads, test banners are still positioned correctly.
Edit: Tried different banner types, same thing. However, the center position does work and so does custom positioning.

**Comment by rampara** [comment] 2017-11-22 20:01
@xxPillsxx there shouldn't be any change in behavior between test and real ads. I'm having trouble reproducing the issue on my end. Attached an image below were a banner was correctly positioned in the bottom left of the screen. 

![image](https://user-images.githubusercontent.com/11047881/33147516-db3d60ce-cf7c-11e7-9540-b90f378b4c6c.png)

If you can provide a Unity project that reproduces the problem, I can investigate further.

**Comment by xxPillsxx** [comment] 2017-11-23 00:43
I created a fresh new project and tried importing the 3.9.0 and everything worked fine, I copied all the admob files from the new project to my production project but nothing changed. How can I make a clean install of admob again? I tried deleting every admob file I could find (including meta files) and copying the fresh install again, but to no avail.

**Comment by rampara** [comment] 2017-11-28 19:57
@xxPillsxx still having trouble reproducing the issue on my end. Updating the plugin shouldn't require any steps beyond importing the updated Unity package into your project. I tried creating a test app with v3.8.0 of the plugin and then updating 3.9.0. Everything works as expected for me.

**Comment by BrianOSH** [comment] 2017-12-02 15:02
I can reproduce this in my apps. If I create a banner view and request a banner ad to appear at the bottom of the screen. Then BEFORE the ad appears make a call to Application.OpenURL. Wait for about 10 seconds then press the back button to return from the browser to my app. The banner ad is positioned at the top of the screen every time.

**Comment by flashwade03** [comment] 2017-12-04 00:36
I'm using version 3.9.0.
I have tested at Android6, Andorid5, Android7.
In case of Android6, banner is positioned at top always. But the other versions, banner is positioned correctly.

**Comment by rampara** [comment] 2017-12-04 19:05
@flashwade03  just did a quick test with the latest version of this plugin (3.9.0) and a Samsung S7 running Android 6 and was unable to repro this issue. Can you link me to a test project that I can use to reproduce the issue.

**Comment by flashwade03** [comment] 2017-12-04 23:14
@rampara I just tested with LG G4, Lenovo tablet devices. (android version 6). Because my projects is our company projects, I can not share with you sorry.

**Comment by rampara** [comment] 2017-12-06 16:29
Having trouble reproducing on this on my end but keeping the issue open while it's being investigated.

**Comment by sjvc** [comment] 2017-12-15 16:35
I'm having this issue too. I have an horizontal banner at the bottom, but in an Acer Iconia Tab 8 it appears on top

**Comment by flashwade03** [comment] 2017-12-18 02:37
@sjvc Hi, all.
This is my a my solution. I wish this code help you.

Banner.java
`private void showPopUpWindow() {
        View anchorView = mUnityPlayerActivity.getWindow().getDecorView().getRootView();

        if (this.mPositionCode == PluginUtils.POSITION_CUSTOM) {
            // Android Nougat has a PopUpWindow bug gravity doesn't position views as expected.
            // Using offset values as a workaround. On certain devices (ie. Samsung S8) calls to
            // update() cause the PopUpWindow to be rendered at the top of the screen. Using
            // showAsDropDown() instead of showAtLocation() (when possible) avoids this issue.
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                mPopupWindow.showAsDropDown(anchorView,
                        (int) PluginUtils.convertDpToPixel(mHorizontalOffset),
                        -anchorView.getHeight()
                                + (int) PluginUtils.convertDpToPixel(mVerticalOffset));
            } else {
                mPopupWindow.showAtLocation(
                        anchorView, Gravity.NO_GRAVITY,
                        (int) PluginUtils.convertDpToPixel(mHorizontalOffset),
                        (int) PluginUtils.convertDpToPixel(mVerticalOffset));
            }
        } else {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                int adViewWidth = mAdView.getAdSize().getWidthInPixels(mUnityPlayerActivity);
                int adViewHeight = mAdView.getAdSize().getHeightInPixels(mUnityPlayerActivity);

                mPopupWindow.showAsDropDown(anchorView,
                        PluginUtils.getHorizontalOffsetForPositionCode(mPositionCode, adViewWidth,
                                anchorView.getWidth()),
                        PluginUtils.getVerticalOffsetForPositionCode(mPositionCode, adViewHeight,
                                anchorView.getHeight()));
            } else {
                mPopupWindow.showAtLocation(anchorView,
                        PluginUtils.getLayoutGravityForPositionCode(mPositionCode), 0, 0);
            }
        }
    }
`

**Comment by rampara** [comment] 2017-12-18 19:17
@flashwade03 @sjvc the latest version of the plugin (v.3.10.0) contains an updated banner positioning implementation. Can you try this version of the plugin to see if your issue persists?

**Comment by BrianOSH** [comment] 2017-12-18 21:59
My banners still appear at the top of the screen when using my test program.

On 18 Dec 2017, at 19:17, rampara <notifications@github.com<mailto:notifications@github.com>> wrote:


@flashwade03<https://github.com/flashwade03> @sjvc<https://github.com/sjvc> the latest version of the plugin (v.3.10.0) contains an updated banner positioning implementation. Can you try this version of the plugin to see if your issue persists?

**Comment by flashwade03** [comment] 2017-12-19 05:10
@rampara Hi. I tested new version of plugins, but problem exist currently.
And When I tested in iPhone X(ios11+), Same problem was occured.

**Comment by sjvc** [comment] 2017-12-19 07:23
@rampara with version 3.9.0 only happened 1 time (banner was on top). After it happened, I closed the app, opened again, and then it worked everytime (banner was at the bottom). It's weird, but it happened. I'm testing v3.10.0 right now.

**Comment by sjvc** [comment] 2017-12-19 22:24
@rampara it happened again using v3.10.0. It only happened first time, and can't reproduce it again. But it happened.

**Comment by rampara** [comment] 2018-01-03 21:37
@flashwade03 I'm unable to reproduce this issue on iOS at all. Can you provide me with a Unity project that reproduces the issue?

@sjvc are you only experiencing this issue on certain Android devices or across all devices?

**Comment by sjvc** [comment] 2018-01-03 21:48
I've tested it on several devices, but I'm only able to reproduce this
issue with an Acer Iconia Tab 8. And I've tested it several times on the
Acer tablet, but only two times the banner was shown at top. The other
times it was shown correctly (at bottom).

**Comment by rampara** [comment] 2018-01-03 21:56
@sjvc without being able to reproduce the issue I won't be able to troubleshoot further. Let me know if you run into the issue on any other devices.

**Comment by rotter** [comment] 2018-04-02 20:39
Quick comment which might be helpful:

I've had in the past (1-2 years ago) problems with some specific Samsung devices regarding their orientation and the returned Screen.Width and Screen.Height. They would for example be in Portrait mode but would return swapped Width and Height values, this would mess up lots of things including our AdMob banner positioning, and I dont blame AdMob on that.

I'm only pointing out so you can check and report that to see if it's the same problem: Portrait with larger Width than Height (or obviously Landscape with larger Height).

**Comment by rampara** [comment] 2018-04-04 19:26
@rotter swapped height and width values seem like they would result in offset banners rather than banners that are locked to the top position. Is there something within the implementation of this plugin that pushed you towards that being the cause of the issue?

**Comment by rotter** [comment] 2018-04-05 00:38
@rampara no, it was just a long shot as I remembered a positioning issue I faced years ago. Might not be related, you can ignore it if you don't think it's related (probably isn't as I re-read now). And if I recall correctly indeed it didnt position the banner on the wrong end, but would shift it half-way outside of the screen due to centering using the wrong value (1920 instead of 1080 for example)

**Comment by rampara** [comment] 2018-04-05 18:25
Will continue to keep this issue open until I'm able to get my hands on a device that reproduces the issue.

**Comment by rampara** [comment] 2018-04-12 21:50
Was finally able to reproduce the issue on my end. Putting together a workaround that should be pushed out shortly.

**Comment by sjvc** [comment] 2018-04-12 21:52
That's good news! Thanks!

**Comment by shlapkoff** [comment] 2018-05-24 09:57
I reproduce this issue on Nexus 5 with Android 6.0.1.
Plugin version: 0.9.50.

When I see interstitial ad, bottom banner goin to top position and after close interstitial bottom banner goin to bottom position. But sometimes the bottom banner remains at the top.

**Comment by rampara** [comment] 2018-05-24 23:44
@shlapkoff are you also experiencing this issue on the latest version of the plugin (v3.13.1) ?

**Comment by shlapkoff** [comment] 2018-05-30 10:39
@rampara hi, yes, it's behavior fixed in latest version of plugin.

**Comment by rampara** [comment] 2018-07-24 19:54
Closing this issue as it seems to have been resolved on the latest version of this plugin.

**Closed by rampara** 2018-07-24 19:54 UTC
Labels: P2, plugin bug
