### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.google.android.chimera.Fragment" 

### ISSUE THREAD

**Issue by sharklab** [googleads/googleads-mobile-unity#365] opened 2017-03-13 19:19 UTC
I'm not able to make Rewarded video working, anyone have this same issue?

`Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.chimera.Fragment" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/0000000f/DynamiteModulesA_GmsCore_prodmnc_xxhdpi_release.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/0000000f/n/armeabi-v7a, /data/user_de/0/com.google.android.gms/app_chimera/m/0000000f/n/armeabi, /system/lib, /vendor/lib]]
03-13 20:18:06.876 I:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
03-13 20:18:06.876 I:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
03-13 20:18:06.876 I:     at java.lang.Class bzi.loadClass(java.lang.String, boolean) (:com.google.android.gms:34)
03-13 20:18:06.876 I:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
03-13 20:18:06.876 I:     at java.lang.Class dalvik.system.DexFile.defineClassNative(java.lang.String, java.lang.ClassLoader, java.lang.Object, dalvik.system.DexFile) (DexFile.java:-2)
03-13 20:18:06.876 I:     at java.lang.Class dalvik.system.DexFile.defineClass(java.lang.String, java.lang.ClassLoader, java.lang.Object, dalvik.system.DexFile, java.util.List) (DexFile.java:299)
03-13 20:18:06.876 I:     at java.lang.Class dalvik.system.DexFile.loadClassBinaryName(java.lang.String, java.lang.ClassLoader, java.util.List) (DexFile.java:292)
03-13 20:18:06.876 I:     at java.lang.Class dalvik.system.DexPathList.findClass(java.lang.String, java.util.List) (DexPathList.java:418)
03-13 20:18:06.876 I:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:54)
03-13 20:18:06.876 I:     at java.lang.Class bzi.loadClass(java.lang.String, boolean) (:com.google.android.gms:28)
03-13 20:18:06.876 I:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
03-13 20:18:06.876 I:     at void ht.h() (:com.google.android.gms.DynamiteModulesA:619)
03-13 20:18:06.876 I:     at ht ht.a(android.content.Context, java.lang.String, java.lang.String, boolean) (:com.google.android.gms.DynamiteModulesA:2195)
03-13 20:18:06.876 I:     at ht hk.b(android.content.Context, boolean) (:com.google.android.gms.DynamiteModulesA:131)
03-13 20:18:06.876 I:     at void hk.a(android.content.Context, boolean) (:com.google.android.gms.DynamiteModulesA:91)
03-13 20:18:06.876 I:     at hl hl.a(java.lang.String, android.content.Context, boolean) (:com.google.android.gms.DynamiteModulesA:80)
03-13 20:18:06.876 I:     at void com.google.android.gms.ads.internal.ad.run() (:com.google.android.gms.DynamiteModulesA:6183)
03-13 20:18:06.876 I:     at java.lang.Object com.google.android.gms.ads.internal.util.ab.call() (:com.google.android.gms.DynamiteModulesA:1055)
03-13 20:18:06.876 I:     at void com.google.android.gms.ads.internal.util.ac.run() (:com.google.android.gms.DynamiteModulesA:75)
03-13 20:18:06.876 I:     at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:428)
03-13 20:18:06.877 I:     at void java.util.concurrent.FutureTask.run() (FutureTask.java:237)
03-13 20:18:06.877 I:     at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1133)
03-13 20:18:06.877 I:     at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:607)
03-13 20:18:06.877 I:     at void java.lang.Thread.run() (Thread.java:761)`

**Comment by rampara** [comment] 2017-03-13 20:26
Can you check if the `JarResolver` library successfully copied the required Google Play services and Google Mobile Ads dependencies into the `Assets/Plugins/Android` directory of your Unity project? Can you post the contents of this directory? If you don't see the Play services AARs in this directory, you can manually force the resolution of these dependencies by selecting `Assets->Google Play Services->Resolve Client Jars` in the Unity editor.

**Comment by daneric** [comment] 2017-03-17 05:59
I have same problem. I found the aar files under the Assets/Plugins/Android directory and I did Assets->Google Play Services->Resolve Client Jars in the Unity editor also. But problem already exists.

**Comment by rampara** [comment] 2017-03-20 21:44
@daneric is the class that cannot be found `com.google.android.chimera.Fragment` for you as well?

**Comment by jseparovic** [comment] 2017-04-13 08:58
I just started getting this same error using GoogleApiClient with android 7.

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.chimera.Fragment" on path: DexPathList.

Seems to just happen after installing the latest update, same code worked on my phone a few days ago

**Comment by matie** [comment] 2017-04-26 12:36
Hi, anyone already a solution? Yes rampara, also com.google.android.chimera.Fragment not found.

**Comment by rampara** [comment] 2017-04-27 05:32
@matie Did the JarResolver library add the Google Play Services dependencies to the `Plugins/Assets/Android` directory of your Unity project? If not, you can run dependency resolution manually by selecting `Assets > Play Services Resolver > Android Resolver > Resolve Client Jars` in the Unity editor.

**Comment by rampara** [comment] 2017-05-31 17:56
Closing this issue due to non-response. If this issue persists for you, please re-open it.

**Closed by rampara** 2017-05-31 17:56 UTC
Labels: support question
