### ISSUE TITLE
Unity app crashes immediately after launch (Firebase Database + Admob)

### ISSUE THREAD

**Issue by u3556571** [googleads/googleads-mobile-unity#975] opened 2019-07-24 00:11 UTC
I was building my game using **FirebaseDatabase** and **Admob** together. Everything was fine when I run it in **Unity**. But when I build and run it on my mobile, the app just crashed immediately after launch, even before the Unity logo is shown. I know there is a lot of similar problems between Firebase and Admob. I tried many of the solutions but it seems that they don't fit my case as the app still crashes. So hopefully someone can help me out. I really appreciate that:)
- Unity 2018.3.5f1
- Google Mobile Ads Unity Plugin v3.18.1
- Firebase Unity SDK 6.2.1

I've build a test project so that the problem will occur:
1. Import .net4 Firebase Database package (the resolving android dependencies dialog automatically shows up)
2. Imort Admob Plugin package (a warning about different GUID show up in the import package dialog, and these errors show up AFTER importing:)
> Assembly 'Assets/Firebase/Editor/Firebase.Editor.dll' will not be loaded due to errors:
Unable to resolve reference 'Google.VersionHandlerImpl'. Is the assembly missing or incompatible with the current platform?
Unable to resolve reference 'Google.JarResolver'. Is the assembly missing or incompatible with the current platform?
Unable to resolve reference 'Google.IOSResolver'. Is the assembly missing or incompatible with the current platform?

3. Set up the Google AdMob ID for Android only
4. Put the google-services json in the root of the Assets folder
5. Now build and run on my mobile the app will just crashes right after launch

I really hope someone can have a solution on this!!

**Comment by AsifNaeem1** [comment] 2019-07-24 16:50
I am facing same problem on some devices. App crash on launch. Using Unity 2018.3 and firebase analytics 6.2

**Comment by stowy** [comment] 2019-07-24 22:15
Thanks for the feedback.

Please provide the crash log for us to begin investigating.

**Comment by AsifNaeem1** [comment] 2019-07-25 10:02
@stowy  I am attaching crash log, But I have no idea what is this explaining


07-25 14:51:42.437: E/HSM_BG(1554): NormalTrafficAnalysis:alert byte = 0, so return
07-25 14:51:42.441: E/AndroidRuntime(28879): FATAL EXCEPTION: main
07-25 14:51:42.441: E/AndroidRuntime(28879): Process: com.sl.impossibletrack.monstertruckstunts.rampstuntracing.stuntdriving, PID: 28879
07-25 14:51:42.441: E/AndroidRuntime(28879): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at com.facebook.ads.internal.ac.a(SourceFile:79)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at com.facebook.ads.internal.u.a(SourceFile:79)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at com.facebook.ads.internal.be.a(SourceFile:121)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at com.facebook.ads.internal.u.a(SourceFile:124)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at com.facebook.ads.internal.bq.a(SourceFile:1106)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at com.facebook.ads.internal.bn.a(SourceFile:1350)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at com.facebook.ads.internal.bn$2.run(SourceFile:294)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at android.os.Handler.handleCallback(Handler.java:907)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at android.os.Looper.loop(Looper.java:216)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at android.app.ActivityThread.main(ActivityThread.java:7593)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at java.lang.reflect.Method.invoke(Native Method)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
07-25 14:51:42.441: E/AndroidRuntime(28879): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.LocalBroadcastManager" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.sl.impossibletrack.monstertruckstunts.rampstuntracing.stuntdriving-14rG7adz6LIlmo2ekwLcCA==/base.apk"],nativeLibraryDirectories=[/data/app/com.sl.impossibletrack.monstertruckstunts.rampstuntracing.stuntdriving-14rG7adz6LIlmo2ekwLcCA==/lib/arm, /data/app/com.sl.impossibletrack.monstertruckstunts.rampstuntracing.stuntdriving-14rG7adz6LIlmo2ekwLcCA==/base.apk!/lib/armeabi-v7a, /system/lib, /product/lib]]
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-25 14:51:42.441: E/AndroidRuntime(28879): 	... 14 more
07-25 14:51:42.445: E/ActivityManager(1274): The same pid with last one, do not add dropbox and clear mLastCrashedPid. mLastAppCrashedPid==28879
07-25 14:51:42.451: W/ActivityManager(1274):   finishTopCrashedActivityLocked Force finishing activity com.sl.impossibletrack.monstertruckstunts.rampstuntracing.stuntdriving/com.unity3d.player.UnityPlayerActivity
07-25 14:51:42.464: I/StatusBarDisable(1274): setFlags what=0 which=1 pkg=Window{57bbe2 u0 com.sl.impossibletrack.monstertruckstunts.rampstuntracing.stuntdriving/com.unity3d.player.UnityPlayerActivity}
07-25 14:51:42.469: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.495: I/ActivityManager(1274): get AppResource
07-25 14:51:42.504: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.505: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.522: I/chatty(703): uid=0(root) RFD_TASK2 identical 5 lines
07-25 14:51:42.522: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.527: D/asd_primary_out(569): L[0],R[0], continus 20 times!
07-25 14:51:42.550: E/AwareLog(1783): SPKSchedFeature: Uid has been sent, ignore.
07-25 14:51:42.557: I/Process(28879): Sending signal. PID: 28879 SIG: 9
07-25 14:51:42.563: I/AppManager(1783): removeProcessDependency pid:28879
07-25 14:51:42.575: E/AwareLog(1783): GameSdkConfigReader: GameSdkLog: idNameMap: null
07-25 14:51:42.577: I/BoosterSwitchP(1709): notifyUidState do nothing
07-25 14:51:42.577: I/DeepNoDisturbP(1709): notifyUidState
07-25 14:51:42.577: I/BrowserChrP(1709): notifyUidState
07-25 14:51:42.584: D/HiDATA_ContentAware(1274): mForegroundAppPackageName: com.huawei.android.launcher ,score: 0
07-25 14:51:42.589: E/dubaid(678): [DubaiUtils.h] parseMessage# Failed to find second tag: uid=
07-25 14:51:42.590: E/dubaid(678): [SystemHandler.cpp] parsePartialWakelockAcquiredMessage# Failed to parse count: lock=34652739 tag=IntentOp:.common.broadcast.BackgroundBroadcastReceiverSupport$GmsReceiverIntentOperation count=0
07-25 14:51:42.590: E/dubaid(678): [SystemHandler.cpp] onPartialWakelockAcquireMessage# Failed to parse message
07-25 14:51:42.597: D/HiDATA(1274): onForegroundAppWifiSleepChange: config:false, sleeptime:-1,type: 301, appname:com.huawei.android.launcher
07-25 14:51:42.623: E/dubaid(678): [SystemHandler.cpp] onPartialWakelockReleaseMessage# Already released, lock: 34652739
07-25 14:51:42.629: E/dubaid(678): [DubaiUtils.h] parseMessage# Failed to find second tag: uid=
07-25 14:51:42.631: E/dubaid(678): [SystemHandler.cpp] parsePartialWakelockAcquiredMessage# Failed to parse count: lock=75050518 tag=IntentOp:.common.broadcast.BackgroundBroadcastReceiverSupport$PersistentReceiverIntentOperation count=0
07-25 14:51:42.631: E/dubaid(678): [SystemHandler.cpp] onPartialWakelockAcquireMessage# Failed to parse message
07-25 14:51:42.633: D/MSSArbitrager(1274): setGameForeground:false
07-25 14:51:42.633: D/HiDATA(1274): APP type: 301 appName= com.huawei.android.launcher
07-25 14:51:42.634: D/HiDATA(1274): no game, APP_TYPE_GAME, appName =com.huawei.android.launcher
07-25 14:51:42.639: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.646: I/HwNetworkPolicy(1274): onTransact, code = 203
07-25 14:51:42.644: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.646: I/NetworkPolicy(1274): updateRuleForRestrictBackgroundUL(10176): isForeground=true, isBlacklisted=false, isWhitelisted=false, isRestrictedByAdmin=false, oldRule=0 (NONE), newRule=2 (TEMPORARY_ALLOW_METERED), newUidRules=66 (REJECT_ALL|TEMPORARY_ALLOW_METERED), oldUidRules=64 (REJECT_ALL), mRestrictBackground=true
07-25 14:51:42.647: I/HwNetworkPolicyManager(1554): getHwUidPolicy uid = 10068 policy = 0
07-25 14:51:42.647: D/NetdConnector(1274): SND -> {19460 bandwidth addniceapps 10176}
07-25 14:51:42.648: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.650: I/chatty(703): uid=0(root) RFD_TASK2 identical 1 line
07-25 14:51:42.653: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.655: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.658: D/NetdConnector(1274): RCV <- {200 19460 Bandwidth command succeeeded}
07-25 14:51:42.659: D/NetdConnector(1274): RCV <- {200 19460 Bandwidth command succeeeded}
07-25 14:51:42.659: I/HwAudioService(1274): now type = 9,reportForegroundAppType = 301,pkg = null,systemload = 9mVoipOptimizeInGameModefalse
07-25 14:51:42.661: D/NetdConnector(1274): SND -> {19461 firewall set_uid_rule standby 10176 allow}
07-25 14:51:42.662: E/dubaid(678): [SystemHandler.cpp] onPartialWakelockReleaseMessage# Already released, lock: 75050518
07-25 14:51:42.670: D/NetdConnector(1274): RCV <- {200 19461 Firewall command succeeded}
07-25 14:51:42.672: I/NetworkPolicy(1274): updateRulesForPowerRestrictionsUL(10176), isIdle: true, mRestrictPower: false, mDeviceIdleMode: false, isForeground=true, isWhitelisted=false, oldRule=64 (REJECT_ALL), newRule=32 (ALLOW_ALL), newUidRules=34 (ALLOW_ALL|TEMPORARY_ALLOW_METERED), oldUidRules=66 (REJECT_ALL|TEMPORARY_ALLOW_METERED), mRestrictBackground=true
07-25 14:51:42.675: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.675: I/NetworkPolicy(1274): updateRuleForRestrictBackgroundUL(10068): isForeground=true, isBlacklisted=false, isWhitelisted=false, isRestrictedByAdmin=false, oldRule=0 (NONE), newRule=2 (TEMPORARY_ALLOW_METERED), newUidRules=2 (TEMPORARY_ALLOW_METERED), oldUidRules=0 (NONE), mRestrictBackground=true
07-25 14:51:42.675: I/NetworkPolicy(1274): [ 07-25 14:51:42.675   703:25544 D/         ]
07-25 14:51:42.675: I/NetworkPolicy(1274): External::GetAppType Begin
07-25 14:51:42.676: D/NetdConnector(1274): SND -> {19462 bandwidth addniceapps 10068}
07-25 14:51:42.676: D/NetdConnector(1274): [ 07-25 14:51:42.679   703:25544 D/         ]
07-25 14:51:42.676: D/NetdConnector(1274): External::GetAppType End
07-25 14:51:42.680: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.680: I/chatty(703): uid=0(root) RFD_TASK3 identical 3 lines
07-25 14:51:42.680: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.682: I/TrafficMonitor(1274): update:rxPkts:425,txPkts:396,rxBytes:471925,txBytes:42829
07-25 14:51:42.682: I/TrafficMonitor(1274): no expired. level:5
07-25 14:51:42.682: I/TrafficMonitor(1274): gettimer:interval=2000
07-25 14:51:42.682: I/TrafficMonitor(1274): during_ms:2002,period_ms:2000
07-25 14:51:42.683: I/TrafficMonitor(1274): count:385,rx_sum:425,tx_sum:396,rxBytes:471925,during_ms:2002,rx_speed:235726.77322677325,tx_speed:21393.106893106895,rto:1.0732323232323233
07-25 14:51:42.684: D/NetdConnector(1274): RCV <- {200 19462 Bandwidth command succeeeded}
07-25 14:51:42.684: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.685: D/WorkSource(2142): Insert in WorkSource{} @ 0 uid 10019 name com.google.android.gms
07-25 14:51:42.685: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.687: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.688: I/NetworkPolicy(1274): updateRuleForRestrictBackgroundUL(10033): isForeground=true, isBlacklisted=false, isWhitelisted=false, isRestrictedByAdmin=false, oldRule=0 (NONE), newRule=2 (TEMPORARY_ALLOW_METERED), newUidRules=2 (TEMPORARY_ALLOW_METERED), oldUidRules=0 (NONE), mRestrictBackground=true
07-25 14:51:42.689: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.689: D/NetdConnector(1274): SND -> {19463 bandwidth addniceapps 10033}
07-25 14:51:42.697: D/NetdConnector(1274): RCV <- {200 19463 Bandwidth command succeeeded}
07-25 14:51:42.699: I/chatty(703): uid=0(root) RFD_TASK3 identical 8 lines
07-25 14:51:42.700: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.701: D/WorkSource(2142): Insert in WorkSource{} @ 0 uid 10019 name com.google.android.gms
07-25 14:51:42.701: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.706: I/chatty(703): uid=0(root) RFD_TASK3 identical 4 lines
07-25 14:51:42.707: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.707: D/WorkSource(2142): Insert in WorkSource{} @ 0 uid 10019 name com.google.android.gms
07-25 14:51:42.708: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.709: I/AudioTrackShared(591): server obtain null buf part1:0 rear:292576 front:292576 mFrameCount:4096
07-25 14:51:42.710: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.718: I/chatty(703): uid=0(root) RFD_TASK3 identical 7 lines
07-25 14:51:42.719: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.721: D/WorkSource(2142): Insert in WorkSource{} @ 0 uid 10019 name com.google.android.gms
07-25 14:51:42.723: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.746: I/chatty(703): uid=0(root) RFD_TASK3 identical 14 lines
07-25 14:51:42.747: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.748: D/WorkSource(2142): Insert in WorkSource{} @ 0 uid 10019 name com.google.android.gms
07-25 14:51:42.749: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.760: I/chatty(703): uid=0(root) RFD_TASK3 identical 6 lines
07-25 14:51:42.761: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.762: W/InputDispatcher(1274): channel '57bbe2 com.sl.impossibletrack.monstertruckstunts.rampstuntracing.stuntdriving/com.unity3d.player.UnityPlayerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-25 14:51:42.762: E/InputDispatcher(1274): channel '57bbe2 com.sl.impossibletrack.monstertruckstunts.rampstuntracing.stuntdriving/com.unity3d.player.UnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-25 14:51:42.763: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.764: E/iMonitor(703): FaultDetect: DUMPTOOL_PRINTF return.
07-25 14:51:42.765: I/Zygote(529): Process 28879 exited due to signal (9)
07-25 14:51:42.765: D/ConnectivityService(1274): ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=1557, [ Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND Uid: 10399] ], android.os.BinderProxy@78e69f0)

**Comment by stowy** [comment] 2019-07-25 22:50
You appear to have libraries referring to android support libraries.

You need to ensure that all dependencies are jetified so that they all
refer to androidx support libraries.

This is done using the play services resolve android settings menu (see
attached screenshot). Go to 'Assets' -> 'Play Services Resolver' ->
'Android Resolver' -> 'Settings' and select 'Use Jetifier'.

**Closed** 2019-08-02 22:43 UTC
