### ISSUE TITLE
Unity 5.1.4f1 + Google Mobile Ads 3.0.3 + Android Dev Build = Crash

### ISSUE THREAD

**Issue by liszto** [googleads/googleads-mobile-unity#194] opened 2016-03-24 14:07 UTC
Hello,
when we tried to generate an apk in development build with Admob plugin we have a crash during our game initialization. Here is the crash log :

> 03-24 15:04:33.015: E/AndroidRuntime(6516): FATAL EXCEPTION: main
03-24 15:04:33.015: E/AndroidRuntime(6516): Process: com.bigpoint.hocuspuzzle, PID: 6516
03-24 15:04:33.015: E/AndroidRuntime(6516): java.lang.Error: FATAL EXCEPTION [main]
03-24 15:04:33.015: E/AndroidRuntime(6516): Unity version     : 5.1.4f1
03-24 15:04:33.015: E/AndroidRuntime(6516): Device model      : htc Nexus 9
03-24 15:04:33.015: E/AndroidRuntime(6516): Device fingerprint: google/volantis/flounder:6.0.1/MMB29V/2554798:user/release-keys
03-24 15:04:33.015: E/AndroidRuntime(6516): Caused by: java.lang.NullPointerException: storage == null
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at java.util.Arrays$ArrayList.<init>(Arrays.java:38)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at java.util.Arrays.asList(Arrays.java:155)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at com.unity3d.player.ReflectionHelper$1.invoke(Unknown Source)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at $Proxy3.onAdLoaded(Unknown Source)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at com.google.unity.ads.Interstitial$1$1.onAdLoaded(Interstitial.java:72)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at com.google.android.gms.ads.internal.client.zzc.onAdLoaded(Unknown Source)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at com.google.android.gms.ads.internal.client.zzq$zza.onTransact(Unknown Source)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at android.os.Binder.transact(Binder.java:387)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at com.google.android.gms.ads.internal.client.o$a$a.c(:com.google.android.gms.alldynamite:152)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at com.google.android.gms.ads.internal.a.o(:com.google.android.gms.alldynamite:771)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at com.google.android.gms.ads.internal.l.o(:com.google.android.gms.alldynamite:386)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at com.google.android.gms.ads.internal.a.b(:com.google.android.gms.alldynamite:405)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at com.google.android.gms.ads.internal.b.b(:com.google.android.gms.alldynamite:149)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at maps.at.a.a(:com.google.android.gms.alldynamite:125)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at maps.at.a.a(:com.google.android.gms.alldynamite:91)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at maps.bi.c.e(:com.google.android.gms.alldynamite:398)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at maps.bi.c.onPageFinished(:com.google.android.gms.alldynamite:374)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:524)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:188)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at android.os.Looper.loop(Looper.java:148)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at java.lang.reflect.Method.invoke(Native Method)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-24 15:04:33.015: E/AndroidRuntime(6516): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

We tried on other Android device and it crashed too.
If we remove the development build and create a "release" build there is no issue.

**Comment by liszto** [comment] 2016-03-31 08:54
Any news from devs ?

**Comment by rampara** [comment] 2016-04-01 17:53
Using the latest version of Unity and our sample application, I'm able to build and run development builds. Are you able to reproduce this issue on our sample application?

**Comment by rampara** [comment] 2016-08-17 17:46
Closing issue due to non-response. If this issue persists, please re-open.

**Closed by rampara** 2016-08-17 17:46 UTC
Labels: support question
