### ISSUE TITLE
Initialize callback issue

### ISSUE THREAD

**Issue by jeffalee** [googleads/googleads-mobile-unity#984] opened 2019-07-31 17:58 UTC
I followed the [Getting Started](https://developers.google.com/admob/unity/start) guide, where they give the following example for initializing the SDK.

`MobileAds.Initialize(initStatus => { });`

They also state the following:
> If you are using mediation, you may wish to wait until the callback occurs before loading ads, as this will ensure that all mediation adapters are initialized.

I am using mediation so I decided to request my first ad inside the callback like this:

`MobileAds.Initialize(initStatus => { RequestAd(); });`

But nothing happens. Is that not supposed to work? Or is the callback never called?

**Comment by stowy** [comment] 2019-08-02 23:24
Is this iOS or Android? Can you please confirm what versions you are using?

**Comment by evanlancaster** [comment] 2019-08-02 23:29
Doesn't work for me either. plugin inits as expected but no callback received on android device. Haven't tested on iOS device yet. Unity 2018.3.13 and mobile ads 3.18.2.

**Comment by scorp2007** [comment] 2019-08-05 02:29
same

Unity 2019.1.7f1
Android
Google Mobile Ads Unity Plugin v3.18.2
Resolver 1.2.124

**Comment by stowy** [comment] 2019-08-05 23:33
This works for me in testing (unity version 2019.1.11f1). Two things to make sure of:

1 - That jar resolver successfully resolves the play-services ads dependency.
2 - That you have followed the [getting started guide](https://developers.google.com/admob/unity/start#set_your_admob_app_id) and correctly configured the AdMob App ID for Android. Test this one to check a valid App ID works - `ca-app-pub-3940256099942544~3347511713`.

If those two things are correctly configured, please attach a zip file with ADB logs from a run where this occurs.

**Comment by jeffalee** [comment] 2019-08-06 09:37
For me the real issue was #982, initialization was failing. Updating the jar resolver to the latest version fixed this issue. But if I'm correct, the callback isn't called in the editor (v3.18.2), which made me think that was the issue.

Apologies for the confusion.

**Comment by stowy** [comment] 2019-08-08 22:48
I'm going to close this as an implementation / dependencies resolution issue, I think initialize is working as intended.

**Closed by stowy** 2019-08-08 22:48 UTC
