### ISSUE TITLE
[UNITY] Crash game Android when finisish reward video Vungle via Admob Mediation?

### ISSUE THREAD

**Issue by ForestJungle** [googleads/googleads-mobile-unity#325] opened 2016-12-22 09:13 UTC
Hello Everyone.I'm having a big problems.I use reward admob with Unity ads and Vungle Ads.After Video finish Unity ads does work but Vunlge is not.
When I click X button to turn off Vungle ads then Game crash.Can anyone suggestion for me? Thanks a lot! :)

**Comment by rampara** [comment] 2017-01-06 23:00
Is your issue the when closing a Vungle mediated rewarded video ad you're experiencing a crash? If so, what platform are you deploying your Unity app to (Android or iOS)? Do you see any output in logcat or in the Xcode console that might indicate the cause of the error? Are you using the latest versions of the Vungle SDK and adapter?

**Comment by rampara** [comment] 2017-03-11 22:22
Closing this issue due to non-response. Please reopen if this issue persists for you.

**Closed by rampara** 2017-03-11 22:22 UTC
Labels: support question
