### ISSUE TITLE
Admob Causing ANR when closing Ads 

### ISSUE THREAD

**Issue by AjayC-Bsw** [googleads/googleads-mobile-unity#1914] opened 2022-01-28 14:00 UTC
<img width="439" alt="Screenshot 2022-01-28 at 7 31 55 PM" src="https://user-images.githubusercontent.com/71251740/151560000-2c753d50-ebb9-4964-bdfa-4d31c28406ca.png">

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.30f1
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: _____ Android
  * Platform OS version: _____ ( Android 11 )
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: IronSrc(v7.1.8.0), Facebook(v6.5.1.1), Unity(v3.7.5.0), InMobi (9.2.0.0)

### [REQUIRED] Step 2: Describe the problem

We are getting a Random ANR at firebase crashlytics and we are not able to repro it.

```
#### Root Blocking

Binder:18236_F (native): tid=6 systid=29723
#00 pc 0x9c7c8 libc.so 
#01 pc 0x5a87c libc.so 
#02 pc 0x7c55c base.apk!libconscrypt_gmscore_jni.so 
#03 pc 0x7ca00 base.apk!libconscrypt_gmscore_jni.so 
#04 pc 0x75464 base.apk!libconscrypt_gmscore_jni.so 
       at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_read(Native method)
       at com.google.android.gms.org.conscrypt.NativeSsl.read(:com.google.android.gms@214815039@21.48.15 (150408-414534850):3)
       at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@214815039@21.48.15 (150408-414534850):6)
       at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
       at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
       at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
       at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
       at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
       at android.media.MediaHTTPConnection.readAt(MediaHTTPConnection.java:404)
       at android.media.MediaHTTPConnection.native_readAt(Native method)
       at android.media.MediaHTTPConnection.readAt(MediaHTTPConnection.java:390)
       at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:143)
       at android.os.Binder.execTransactInternal(Binder.java:1174)
       at android.os.Binder.execTransact(Binder.java:1126)

#### Triggered ANR: -

main (unknown): tid=1 systid=18236
       at android.media.MediaHTTPConnection.disconnect(MediaHTTPConnection.java:172)
       at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:132)
       at android.os.Binder.execTransactInternal(Binder.java:1174)
       at android.os.Binder.execTransact(Binder.java:1126)
       at android.media.MediaPlayer._release(Native method)
       at android.media.MediaPlayer.release(MediaPlayer.java:2121)
       at android.widget.VideoView.stopPlayback(VideoView.java:365)
       at com.unity3d.services.ads.adunit.VideoPlayerHandler.destroy(VideoPlayerHandler.java:38)
       at com.unity3d.services.ads.adunit.VideoPlayerHandler.onPause(VideoPlayerHandler.java:74)
       at com.unity3d.services.ads.adunit.AdUnitActivity.onPause(AdUnitActivity.java:219)
       at android.app.Activity.performPause(Activity.java:8271)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5039)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5000)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4951)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2207)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:268)
       at android.app.ActivityThread.main(ActivityThread.java:8067)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

#### Steps to reproduce:

Unable to Repro.

### More Info :- We are getting strict policy violation at Google play. Well Can this okhttp version be the cause ?
```
com.squareup.okhttp3:okhttp:3.12.1   from dependency Graph
```

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at okhttp3.internal.platform.OptionalMethod.getPublicMethod(OptionalMethod.java:164)
	at okhttp3.internal.platform.OptionalMethod.getMethod(OptionalMethod.java:149)
	at okhttp3.internal.platform.OptionalMethod.invokeOptional(OptionalMethod.java:66)
	at okhttp3.internal.platform.OptionalMethod.invokeOptionalWithoutCheckedException(OptionalMethod.java:86)
	at okhttp3.internal.platform.AndroidPlatform.configureTlsExtensions(AndroidPlatform.java:123)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:314)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/net/Socket;->impl:Ljava/net/SocketImpl;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.google.android.gms.org.conscrypt.Platform.getFileDescriptor(:com.google.android.gms@213918046@21.39.18 (150400-407637301):1)
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@213918046@21.39.18 (150400-407637301):6)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
	at com.android.okhttp.okio.RealBufferedSource.exhausted(RealBufferedSource.java:61)
	at com.android.okhttp.internal.io.RealConnection.isHealthy(RealConnection.java:365)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:139)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
	at com.google.android.gms.internal.firebase-auth-api.zzvb.zza(com.google.firebase:firebase-auth@@21.0.1:10)
	at com.google.android.gms.internal.firebase-auth-api.zzul.zzg(com.google.firebase:firebase-auth@@21.0.1:4)
	at com.google.android.gms.internal.firebase-auth-api.zzpt.zzO(com.google.firebase:firebase-auth@@21.0.1:5)
	at com.google.android.gms.internal.firebase-auth-api.zzpt.zzb(com.google.firebase:firebase-auth@@21.0.1:1)
	at com.google.android.gms.internal.firebase-auth-api.zzpn.zzb(com.google.firebase:firebase-auth@@21.0.1:7)
	at com.google.android.gms.internal.firebase-auth-api.zzvb.zza(com.google.firebase:firebase-auth@@21.0.1:25)
	at com.google.android.gms.internal.firebase-auth-api.zzul.zzn(com.google.firebase:firebase-auth@@21.0.1:4)
	at com.google.android.gms.internal.firebase-auth-api.zzpt.zzz(com.google.firebase:firebase-auth@@21.0.1:3)
	at com.google.android.gms.internal.firebase-auth-api.zztp.zzu(com.google.firebase:firebase-auth@@21.0.1:4)
	at com.google.android.gms.internal.firebase-auth-api.zzrz.zzd(com.google.firebase:firebase-auth@@21.0.1:3)
	at com.google.android.gms.internal.firebase-auth-api.zzry.accept(Unknown Source:6)
	at com.google.android.gms.common.api.internal.zacr.doExecute(com.google.android.gms:play-services-base@@17.6.0:1)
	at com.google.android.gms.common.api.internal.zag.zaf(com.google.android.gms:play-services-base@@17.6.0:1)
	at com.google.android.gms.common.api.internal.zabl.zaG(com.google.android.gms:play-services-base@@17.6.0:2)
	at com.google.android.gms.common.api.internal.zabl.zaF(com.google.android.gms:play-services-base@@17.6.0:5)
	at com.google.android.gms.common.api.internal.zabl.zad(com.google.android.gms:play-services-base@@17.6.0:3)
	at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(com.google.android.gms:play-services-base@@17.6.0:64)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by NVentimiglia** [comment] 2022-01-29 01:07
Thanks for the report, I will take a look.

**Comment by alex-blastproofgames** [comment] 2022-02-15 11:51
I work with people that worked in google, and they're tell me you guys have been passing these AdMob bugs around and nobody wants to fix them because Google is not promoting people for fixing bugs.
Is that true @NVentimiglia ?

**Comment by kungshinhean** [comment] 2022-03-06 11:46
Oh, they finally update the version, but did they fix this issue thought?

https://github.com/googleads/googleads-mobile-unity/releases/tag/v7.0.0

**Comment by brzaknemanja** [comment] 2022-03-11 19:01
Can anyone confirm that latest version fixed these ANR?

**Comment by lan-indiez** [comment] 2022-03-13 08:38
Hey @NVentimiglia @AjayC-Bsw 
I can reproduce it here - https://github.com/googleads/googleads-mobile-unity/issues/1825#issuecomment-1066052804

Hope it will help to find the solution

P.s: sorry for not commenting on this post

**Comment by lan-indiez** [comment] 2022-03-14 05:18
hi @NVentimiglia 

As I've tested again, I didn't receive any ANR report with AdMob Ads so I guessed the ANR just only happened with some ads specific.

And I guess this bug relates to WebView Library version on the user device, you can take more investigation in this case

**Comment by lan-indiez** [comment] 2022-03-24 02:41
Hi @sandeepFC 

I have not had a test like that, as my knowledge, AppLovin MAX get more ANR than ironSource or AdMob Mediation, you can try to switch to ironSource mediation with the newest SDK version 7.2.1.1 - that I saw them have some fixing ANR bugs

I've not tested yet but will do soon

**Comment by sandeepFC** [comment] 2022-03-24 05:17
Hey! @lan-indiez 
Thanks for the insights!
![image_2022_03_23T11_25_37_854Z](https://user-images.githubusercontent.com/96594076/159847221-bad84244-4411-41c6-8e5a-a1b83dffdf68.png)

**Check this out...Something to look into further. I am in the process to switching one of our games from Admob mediation to Ironsource completely and test.**

**Comment by wallaby3** [comment] 2022-03-25 20:36
Yes, it's worse than even this. If you look at the Google Group, some developers are having real issues and no one at Google will help them. If you depend on Admob for your revenue, you're in real danger. It's time to diversify.

**Comment by KarahanOnarlar** [comment] 2022-04-01 21:29
For those who are considering changing the mediation system: 

We published our game in October 2021(only with Admob Mediation). By the end of November, our ANR rate exceeded 4%. As a result, our rankings and downloads dropped drastically and we lost our momentum. Because of this, we had to completely abandon Admob. We switched to Ironsource Mediation and our ANR rate dropped below 1% from the first month and below the threshold after the second month. Now our rankings are starting to return to normal and our daily downloads have increased nearly eightfold. However, the ad revenue is about 35% lower than Admob. 

We're happy for now, but it would be great to have the issue resolved and to be able to use Admob again...

**Comment by romannotroman** [comment] 2022-04-06 07:40
What is the state of the issue? More than half a year Admob team promises to implement a fix and still no results

**Comment by shefich** [comment] 2022-07-28 10:26
I have the same situation.
Tried unity 2019, 2020.3.34, 2020.3.35, 2020.3.36 - no luck.

**Comment by kunny** [comment] 2023-02-06 15:02
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.

**Closed by kunny** 2023-02-06 15:02 UTC
Labels: wontfix, P2

**Comment by shefich** [comment] 2023-07-10 20:32
@kunny  Tell me if this stacktrace is usefull for determining the cause:

```
main (native):tid=1 systid=7450 
#00 pc 0xd7374 libc.so (__ioctl + 4) (BuildId: ddfcb9d4fd7d4d5ecb9d226c1e8e24dd)
#01 pc 0x92f34 libc.so (ioctl + 152) (BuildId: ddfcb9d4fd7d4d5ecb9d226c1e8e24dd)
#02 pc 0x45840 libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 288) (BuildId: a874823f4b8316d2b8316797d5c4e32e)
#03 pc 0x469f4 libbinder.so (android::IPCThreadState::waitForResponse(android::Parcel*, int*) + 60) (BuildId: a874823f4b8316d2b8316797d5c4e32e)
#04 pc 0x46744 libbinder.so (android::IPCThreadState::transact(int, unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 216) (BuildId: a874823f4b8316d2b8316797d5c4e32e)
#05 pc 0x3e8ac libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 192) (BuildId: a874823f4b8316d2b8316797d5c4e32e)
#06 pc 0x5cf4c libmedia.so (android::BpMediaPlayer::disconnect() + 280) (BuildId: f03cb339c913017976025a56bdd51458)
#07 pc 0x4b7f0 libmedia.so (android::MediaPlayer::disconnect() + 276) (BuildId: f03cb339c913017976025a56bdd51458)
#08 pc 0x72750 libmedia_jni.so (android_media_MediaPlayer_release(_JNIEnv*, _jobject*) + 152) (BuildId: 484087a1f6b93166adb8c342ff5f8abd)
       at android.media.MediaPlayer._release(Native method)
       at android.media.MediaPlayer.release(MediaPlayer.java:2433)
       at android.widget.VideoView.stopPlayback(VideoView.java:365)
       at com.unity3d.services.ads.adunit.VideoPlayerHandler.destroy(VideoPlayerHandler.java:38)
       at com.unity3d.services.ads.adunit.AdUnitActivity.setViews(AdUnitActivity.java:382)
       at com.unity3d.services.ads.api.AdUnit$1.run(AdUnit.java:171)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by shefich** [comment] 2023-07-10 20:34
Also this and this:https://github.com/googleads/googleads-mobile-unity/issues/2024 can be connected

**Comment by kungshinhean** [comment] 2023-07-11 04:23
@shefich and @KarahanOnarlar since this is being awhile d, are we still the same situation? 

One of our studio games that use Admob has an unusually high ANR rate. Are we the only ones that experience this?

**Comment by shefich** [comment] 2023-07-11 10:04
@kungshinhean yeah, I have these ANRs now. Admob for unity 8.3.0.

**Comment by shefich** [comment] 2023-07-11 16:39
@kungshinhean I also started new (the same) therad here: https://github.com/googleads/googleads-mobile-unity/issues/2819
as proposed by @kunny
