### ISSUE TITLE
Cocoapods Error

### ISSUE THREAD

**Issue by ozbra** [googleads/googleads-mobile-unity#315] opened 2016-11-30 01:21 UTC
Having the same issue with cocoapods on ios build. I think, I managed to work around but seeing this on console and not being able to use cocoapods a bit annoying. My pods version is 1.1.1.

Some extra information, in the export folder, I can see pod file but there isn't any .xcworkspace file. Because of there is a pod file, I installed that pod file and get the framework inside of the project, although because of missing .xcworkspace file, I needed to use .xcodeproj file and add framework manually there. I am not sure should I do anything else manually. 

  I am adding whole error message in the console below.

> Error running cocoapods. Please ensure you have at least version  1.0.0.  You can install cocoapods with the Ruby gem package manager:
>  > sudo gem install -n /usr/local/bin cocoapods
>  > pod setup
> UnityEngine.Debug:LogError(Object)
> Google.IOSResolver:Log(String, Boolean, LogLevel)
> Google.IOSResolver:OnPostProcessInstallPods(BuildTarget, String)
> UnityEditor.HostView:OnGUI()

**Comment by rampara** [comment] 2016-12-01 21:44
Where do you have the pod command installed?

**Comment by rampara** [comment] 2016-12-07 00:47
Marking as duplicate of #289

**Closed by rampara** 2016-12-07 00:47 UTC
Labels: support question

**Comment by sam-mckay** [comment] 2016-12-08 08:56
@ozbra see this link for a fix to cocoapods https://groups.google.com/forum/#!topic/google-admob-ads-sdk/55COuO1SH2M
