### ISSUE TITLE
Unity Cloud Build Error

### ISSUE THREAD

**Issue by nikhiljolly** [googleads/googleads-mobile-unity#369] opened 2017-03-16 11:16 UTC
Hi,
I am facing an issue when using Unity Cloud Build. I am able to make manual builds successfully without any errors.

Getting these errors both in iOS and Droid builds:

[Unity] Assets/GoogleMobileAds/Editor/AdMobDependencies.cs(53,28): error CS0103: The name `Google' does not exist in the current context
[Unity] Assets/GoogleMobileAds/Editor/AdMobDependencies.cs(58,9): error CS0103: The name `Google' does not exist in the current context

Kindly let me know if there's anyway I can resolve this issue.

Regards,
Nikhil

PS: The issue is similar to https://github.com/googleads/googleads-mobile-unity/issues/349, however I was unable to comment there due to some reason.

**Comment by rampara** [comment] 2017-03-20 21:58
Currently, the JarResolver library does not support Unity Cloud builds, but we are working to fill that gap in functionality. Look for an update on this soon. Closing as duplicate of #333.

**Closed** 2017-03-20 21:59 UTC
Labels: blocked
