### ISSUE TITLE
Rewardbasead callbacks not working help

### ISSUE THREAD

**Issue by martythegreat** [googleads/googleads-mobile-unity#464] opened 2017-07-16 13:43 UTC
I have a  playad button that after the videoad plays it will revive the player, I tried implementing rewarded ads but thecall backs seem to be not working

**Comment by rampara** [comment] 2017-07-17 19:24
@martythegreat are you running into this issue on iOS or Android? Have you tried reproducing this issue in the HelloWorld sample app from this repo?

**Comment by oc2pcoj** [comment] 2017-07-19 19:55
https://gamedev.stackexchange.com/questions/141040/unity-admob-plugin-rewarding-the-user-on-the-main-thread

**Comment by rampara** [comment] 2017-07-20 18:18
@martythegreat if the issue you're running into is the same one described in link from @oc2pcoj, you may also find this [blog post](http://googleadsdeveloper.blogspot.com/2016/04/handling-android-ad-events-in-unity.html) useful.

**Comment by rampara** [comment] 2017-09-26 21:13
Closing this issue due to its age and non response from original poster.

**Closed by rampara** 2017-09-26 21:13 UTC
Labels: support question
