### ISSUE TITLE
Close "X" button not showing occasionally for iOS interstitial ads

### ISSUE THREAD

**Issue by iMagesBlues** [googleads/googleads-mobile-unity#294] opened 2016-10-21 06:12 UTC

**Comment by rampara** [comment] 2016-10-21 21:43
If you could capture a Charles log for an ad request where you're able to replicate this behavior, it would help greatly in finding the cause.

**Comment by iMagesBlues** [comment] 2016-10-26 15:41
Hi Rampara,
Thank you for your quick response. While I am quite unfamiliar on how to capture Charles logs, however I can send you logs directly from XCode's console with the replicated behaviour. Is this something you can also use to investigate the issue?
Best regards,Miguel  

    On Saturday, October 22, 2016 5:43 AM, rampara <notifications@github.com> wrote:
 

 If you could capture a Charles log for an ad request where you're able to replicate this behavior, it would help greatly in finding the cause. —

**Comment by rampara** [comment] 2016-10-27 00:55
XCode logs won't be very useful if the issue is specific to the particular creative. When you run into the issue is it with the same creative? Are you able to reproduce the issue with test ads?

**Comment by rampara** [comment] 2017-01-23 22:10
Closing this issue due to non-response. Please re-open if this issue persists for you.

**Closed by rampara** 2017-01-23 22:10 UTC
Labels: MAD SDK issue
