### ISSUE TITLE
java.lang.Error $Proxy8.onAdLoaded

### ISSUE THREAD

**Issue by shahzad77** [googleads/googleads-mobile-unity#843] opened 2019-02-07 12:49 UTC
java.lang.Error: FATAL EXCEPTION [Thread-43]
Unity version     : 2018.3.0f2
Device model      : vivo vivo 1714
Device fingerprint: vivo/1714/1714:7.0/NRD90M/1545036514:user/release-keys
Caused by
  at com.unity3d.player.ReflectionHelper.nativeProxyInvoke (Native Method)
  at com.unity3d.player.ReflectionHelper.a (Unknown Source)
  at com.unity3d.player.ReflectionHelper$1.invoke (Unknown Source)
  at java.lang.reflect.Proxy.invoke (Proxy.java:813)
  at $Proxy8.onAdLoaded (Unknown Source)
  at com.google.unity.ads.Banner$3$1.run (Banner.java:176)
  at java.lang.Thread.run (Thread.java:761)

**Comment by arpaplus** [comment] 2019-02-20 09:38
Confirmed, many crashes on Unity 2018.3.3.f1.

**Comment by 3583Bytes** [comment] 2019-02-27 01:30
I am getting same errors after upgrading Unity to 2018.3.3

**Comment by matie** [comment] 2019-04-06 07:07
Lately upgraded to 2018.3.9. Latest google mobile ads and facing these errors as well. Seems to be a mediation issue with unity ads. Any progress or solutions?

**Comment by arpaplus** [comment] 2019-04-07 03:27
**Aurimas-Cernius (Unity Technologies)**: Fix for this issue will be shipped with Unity 2018.3.12f1.

**Comment by Zohaib-Saleem** [comment] 2019-05-06 06:31
this issue is fixed in unity 2018.3.13

**Comment by UragayalaDeepika** [comment] 2019-06-28 15:36
Closing this. Feel free to comment if you need any help on this. We will reopen the issue.

**Closed by UragayalaDeepika** 2019-06-28 15:36 UTC
