### ISSUE TITLE
Can't build for Android after upgrading to 3.7.0

### ISSUE THREAD

**Issue by edscodeblenders** [googleads/googleads-mobile-unity#510] opened 2017-09-19 14:12 UTC
I was using Admob for Unity plug-in version 3.6.3 without any problem. After upgrading to 3.7.0, I'm getting the following error:

CommandInvokationFailure: Unable to convert classes into dex format.
C:\Program Files\Java\jdk1.8.0_92\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/MyUserName/AppData/Local/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzut;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzuu;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzuv;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzuw;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzux;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzuy;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzuz;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzva;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzvb;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:613)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at SDKMain.main(SDKMain.java:130)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:605)
	... 9 more
]
stdout[
processing archive C:\MyGame\Temp\StagingArea\android-libraries\GoogleAIDL\libs\.\classes.jar...
processing com/android/vending/billing/BuildConfig.class...
processing com/android/vending/billing/IInAppBillingService.class...
processing com/android/vending/billing/IInAppBillingService$Stub.class...
processing com/android/vending/billing/IInAppBillingService$Stub$Proxy.class...
processing archive C:\MyGame\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\libs\.\unity-plugin-library.jar...
processing com/google/unity/BuildConfig.class...
processing com/google/unity/ads/AdNetworkExtras.class...
processing com/google/unity/ads/Banner.class...
processing com/google/unity/ads/Banner$1.class...
processing com/google/unity/ads/Banner$2.class...
processing com/google/unity/ads/Banner$3.class...
processing com/google/unity/ads/Banner$4.class...
processing com/google/unity/ads/Banner$5.class...
processing com/google/unity/ads/Banner$6.class...
processing com/google/unity/ads/Banner$7.class...
processing com/google/unity/ads/CustomNativeAd.class...
processing com/google/unity/ads/CustomNativeAd$1.class...
processing com/google/unity/ads/CustomNativeAd$2.class...
processing com/google/unity/ads/Interstitial.class...
processing com/google/unity/ads/Interstitial$1.class...
processing com/google/unity/ads/Interstitial$1$1.class...
processing com/google/unity/ads/Interstitial$2.class...
processing com/google/unity/ads/Interstitial$3.class...
processing com/google/unity/ads/NativeAdLoader.class...
processing com/google/unity/ads/NativeAdLoader$1.class...
processing com/google/unity/ads/NativeAdLoader$2.class...
processing com/google/unity/ads/NativeAdLoader$3.class...
processing com/google/unity/ads/NativeAdLoader$3$1.class...
processing com/google/unity/ads/NativeAdLoader$3$2.class...
processing com/google/unity/ads/NativeAdLoader$3$3.class...
processing com/google/unity/ads/NativeAdLoader$4.class...
processing com/google/unity/ads/NativeExpressAd.class...
processing com/google/unity/ads/NativeExpressAd$1.class...
processing com/google/unity/ads/NativeExpressAd$2.class...
processing com/google/unity/ads/NativeExpressAd$3.class...
processing com/google/unity/ads/NativeExpressAd$4.class...
processing com/google/unity/ads/NativeExpressAd$5.class...
processing com/google/unity/ads/NativeExpressAd$6.class...
processing com/google/unity/ads/NativeExpressAd$7.class...
processing com/google/unity/ads/NativeExpressAd$8.class...
processing com/google/unity/ads/PluginUtils.class...
processing com/google/unity/ads/RewardBasedVideo.class...
processing com/google/unity/ads/RewardBasedVideo$1.class...
processing com/google/unity/ads/RewardBasedVideo$1$1.class...
processing com/google/unity/ads/RewardBasedVideo$2.class...
processing com/google/unity/ads/RewardBasedVideo$3.class...
processing com/google/unity/ads/UnityAdListener.class...
processing com/google/unity/ads/UnityAdLoaderListener.class...
processing com/google/unity/ads/UnityRewardBasedVideoAdListener.class...
processing archive C:\MyGame\Temp\StagingArea\android-libraries\GooglePlay\libs\.\classes.jar...
processing com/unity/purchasing/googleplay/ActivityLauncher.class...
processing com/unity/purchasing/googleplay/BillingServiceManager.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$2.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$2.class...
processing com/unity/purchasing/googleplay/BillingServiceProcessor.class...
processing com/unity/purchasing/googleplay/BuildConfig.class...
processing com/unity/purchasing/googleplay/Consts.class...
processing com/unity/purchasing/googleplay/Consts$PurchaseState.class...
processing com/unity/purchasing/googleplay/Consts$ResponseCode.class...
processing com/unity/purchasing/googleplay/GooglePlayBillingUnAvailableException.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$1.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$2.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$3.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$4.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$5.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$6.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$7.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$Features.class...
processing com/unity/purchasing/googleplay/IActivityLauncher.class...
processing com/unity/purchasing/googleplay/IBillingServiceManager.class...
processing com/unity/purchasing/googleplay/IabException.class...
processing com/unity/purchasing/googleplay/IabHelper.class...
processing com/unity/purchasing/googleplay/IabHelper$1.class...
processing com/unity/purchasing/googleplay/IabHelper$2.class...
processing com/unity/purchasing/googleplay/IabHelper$2$1.class...
processing com/unity/purchasing/googleplay/IabHelper$3.class...
processing com/unity/purchasing/googleplay/IabHelper$4.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeMultiFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabPurchaseFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabSetupFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$QueryInventoryFinishedListener.class...
processing com/unity/purchasing/googleplay/IabResult.class...
processing com/unity/purchasing/googleplay/Inventory.class...
processing com/unity/purchasing/googleplay/Purchase.class...
processing com/unity/purchasing/googleplay/PurchaseActivity.class...
processing com/unity/purchasing/googleplay/PurchaseFailedEvent.class...
processing com/unity/purchasing/googleplay/SkuDetails.class...
processing com/unity/purchasing/googleplay/VRPurchaseActivity.class...
processing archive C:\MyGame\Temp\StagingArea\android-libraries\MainLibProj\libs\.\play-games-plugin-support.jar...
processing com/google/games/bridge/BuildConfig.class...
processing com/google/games/bridge/NativeBridgeActivity.class...
processing com/google/games/bridge/TokenFragment.class...
processing com/google/games/bridge/TokenFragment$1.class...
processing com/google/games/bridge/TokenFragment$2.class...
processing com/google/games/bridge/TokenFragment$TokenRequest.class...
processing com/google/games/bridge/TokenPendingResult.class...
processing com/google/games/bridge/TokenResult.class...
processing archive C:\MyGame\Temp\StagingArea\android-libraries\ShortcutBadger-1.1.5\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource me/
ignored resource me/leolin/
ignored resource me/leolin/shortcutbadger/
processing me/leolin/shortcutbadger/Badger.class...
processing me/leolin/shortcutbadger/BuildConfig.class...
processing me/leolin/shortcutbadger/ShortcutBadgeException.class...
processing me/leolin/shortcutbadger/ShortcutBadger.class...
ignored resource me/leolin/shortcutbadger/impl/
processing me/leolin/shortcutbadger/impl/AdwHomeBadger.class...
processing me/leolin/shortcutbadger/impl/ApexHomeBadger.class...
processing me/leolin/shortcutbadger/impl/AsusHomeLauncher.class...
processing me/leolin/shortcutbadger/impl/DefaultBadger.class...
processing me/leolin/shortcutbadger/impl/LGHomeBadger.class...
processing me/leolin/shortcutbadger/impl/NewHtcHomeBadger.class...
processing me/leolin/shortcutbadger/impl/NovaHomeBadger.class...
processing me/leolin/shortcutbadger/impl/SamsungHomeBadger.class...
processing me/leolin/shortcutbadger/impl/SolidHomeBadger.class...
processing me/leolin/shortcutbadger/impl/SonyHomeBadger.class...
processing me/leolin/shortcutbadger/impl/XiaomiHomeBadger.class...
ignored resource me/leolin/shortcutbadger/util/
processing me/leolin/shortcutbadger/util/BroadcastHelper.class...
processing me/leolin/shortcutbadger/util/CloseHelper.class...
processing archive C:\MyGame\Temp\StagingArea\android-libraries\common\libs\.\classes.jar...
processing com/unity/purchasing/BuildConfig.class...
processing com/unity/purchasing/common/DelayedHandler.class...
processing com/unity/purchasing/common/IDelayedExecutor.class...
processing com/unity/purchasing/common/INativeStore.class...
processing com/unity/purchasing/common/IStore.class...
processing com/unity/purchasing/common/IStoreCallback.class...
processing com/unity/purchasing/common/IUnityCallback.class...
processing com/unity/purchasing/common/InitializationFailureReason.class...
processing com/unity/purchasing/common/ProductDefinition.class...
processing com/unity/purchasing/common/ProductDescription.class...
processing com/unity/purchasing/common/ProductMetadata.class...
processing com/unity/purchasing/common/ProductType.class...
processing com/unity/purchasing/common/PurchaseFailedEvent.class...
processing com/unity/purchasing/common/PurchaseFailureDescription.class...
processing com/unity/purchasing/common/PurchaseFailureReason.class...
processing com/unity/purchasing/common/SaneJSONObject.class...
processing com/unity/purchasing/common/StoreDeserializer.class...
processing com/unity/purchasing/common/UnityPurchasing.class...
processing archive C:\MyGame\Temp\StagingArea\android-libraries\play-services-ads-11.2.2\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/ads/
ignored resource com/google/android/gms/ads/internal/
processing com/google/android/gms/ads/internal/ClientApi.class...
ignored resource com/google/android/gms/ads/internal/js/
processing com/google/android/gms/ads/internal/js/JavascriptEngineFactory.class...
processing com/google/android/gms/ads/internal/js/JavascriptEngineFactory$JSEngineSettableFuture.class...
processing com/google/android/gms/ads/internal/js/zza.class...
processing com/google/android/gms/ads/internal/js/zzaa.class...
processing com/google/android/gms/ads/internal/js/zzab.class...
processing com/google/android/gms/ads/internal/js/zzac.class...
processing com/google/android/gms/ads/internal/js/zzad.class...
processing com/google/android/gms/ads/internal/js/zzae.class...
processing com/google/android/gms/ads/internal/js/zzaf.class...
processing com/google/android/gms/ads/internal/js/zzag.class...
processing com/google/android/gms/ads/internal/js/zzah.class...
processing com/google/android/gms/ads/internal/js/zzai.class...
processing com/google/android/gms/ads/internal/js/zzaj.class...
processing com/google/android/gms/ads/internal/js/zzak.class...
processing com/google/android/gms/ads/internal/js/zzb.class...
processing com/google/android/gms/ads/internal/js/zzc.class...
processing com/google/android/gms/ads/internal/js/zzd.class...
processing com/google/android/gms/ads/internal/js/zze.class...
processing com/google/android/gms/ads/internal/js/zzf.class...
processing com/google/android/gms/ads/internal/js/zzg.class...
processing com/google/android/gms/ads/internal/js/zzh.class...
processing com/google/android/gms/ads/internal/js/zzi.class...
processing com/google/android/gms/ads/internal/js/zzj.class...
processing com/google/android/gms/ads/internal/js/zzk.class...
processing com/google/android/gms/ads/internal/js/zzl.class...
processing com/google/android/gms/ads/internal/js/zzm.class...
processing com/google/android/gms/ads/internal/js/zzn.class...
processing com/google/android/gms/ads/internal/js/zzo.class...
processing com/google/android/gms/ads/internal/js/zzp.class...
processing com/google/android/gms/ads/internal/js/zzq.class...
processing com/google/android/gms/ads/internal/js/zzr.class...
processing com/google/android/gms/ads/internal/js/zzs.class...
processing com/google/android/gms/ads/internal/js/zzt.class...
processing com/google/android/gms/ads/internal/js/zzu.class...
processing com/google/android/gms/ads/internal/js/zzv.class...
processing com/google/android/gms/ads/internal/js/zzw.class...
processing com/google/android/gms/ads/internal/js/zzx.class...
processing com/google/android/gms/ads/internal/js/zzy.class...
processing com/google/android/gms/ads/internal/js/zzz.class...
ignored resource com/google/android/gms/ads/internal/overlay/
processing com/google/android/gms/ads/internal/overlay/AdOverlayInfoParcel.class...
processing com/google/android/gms/ads/internal/overlay/zza.class...
processing com/google/android/gms/ads/internal/overlay/zzaa.class...
processing com/google/android/gms/ads/internal/overlay/zzab.class...
processing com/google/android/gms/ads/internal/overlay/zzac.class...
processing com/google/android/gms/ads/internal/overlay/zzad.class...
processing com/google/android/gms/ads/internal/overlay/zzae.class...
processing com/google/android/gms/ads/internal/overlay/zzaf.class...
processing com/google/android/gms/ads/internal/overlay/zzag.class...
processing com/google/android/gms/ads/internal/overlay/zzaj.class...
processing com/google/android/gms/ads/internal/overlay/zzak.class...
processing com/google/android/gms/ads/internal/overlay/zzal.class...
processing com/google/android/gms/ads/internal/overlay/zzam.class...
processing com/google/android/gms/ads/internal/overlay/zzan.class...
processing com/google/android/gms/ads/internal/overlay/zzao.class...
processing com/google/android/gms/ads/internal/overlay/zzap.class...
processing com/google/android/gms/ads/internal/overlay/zzaq.class...
processing com/google/androi<message truncated>

Any idea of what could be happening here? I'm also using Google Play Games and the Unity IAP plug-in.

Any hint will be greatly appreciated!

Thanks,

**Comment by wenderRondonia** [comment] 2017-09-20 16:13
same problem here using GPGS and UnityIAP and Facebook SDK

**Comment by rampara** [comment] 2017-09-20 18:34
@edscodeblenders @edscodeblenders can you post the contents of the `Assets/Plugins/Android` directory of your Unity project?

**Comment by edscodeblenders** [comment] 2017-09-20 19:08
Sure, here are all the files and folders in that folder:
08/09/2017  20:28             1.850 AndroidManifest.xml
26/07/2017  17:35               178 AndroidManifest.xml.meta
18/09/2017  17:12            11.156 common-1.0.0.jar
18/09/2017  17:12               628 common-1.0.0.jar.meta
18/09/2017  13:29    <DIR>          GoogleMobileAdsPlugin
12/07/2017  21:47               327 GoogleMobileAdsPlugin.meta
17/08/2017  09:54    <DIR>          libs
07/06/2017  18:44               191 libs.meta
14/09/2017  20:18         1.453.562 play-games-plugin-support.aar
14/09/2017  20:18               441 play-games-plugin-support.aar.meta
18/09/2017  17:12         1.017.715 play-services-ads-11.2.2.aar
18/09/2017  17:12               628 play-services-ads-11.2.2.aar.meta
18/09/2017  17:12           286.669 play-services-ads-lite-11.2.2.aar
18/09/2017  17:12               628 play-services-ads-lite-11.2.2.aar.meta
18/09/2017  17:12            76.646 play-services-auth-10.2.6.aar
18/09/2017  17:12               628 play-services-auth-10.2.6.aar.meta
18/09/2017  17:12            57.725 play-services-auth-base-10.2.6.aar
18/09/2017  17:12               628 play-services-auth-base-10.2.6.aar.meta
18/09/2017  17:12           415.499 play-services-base-11.2.2.aar
18/09/2017  17:12               628 play-services-base-11.2.2.aar.meta
18/09/2017  17:12           361.088 play-services-basement-11.2.2.aar
18/09/2017  17:12               628 play-services-basement-11.2.2.aar.meta
18/09/2017  17:12           361.510 play-services-drive-10.2.6.aar
18/09/2017  17:12               628 play-services-drive-10.2.6.aar.meta
18/09/2017  17:12           559.542 play-services-games-10.2.6.aar
18/09/2017  17:12               628 play-services-games-10.2.6.aar.meta
18/09/2017  17:12            20.943 play-services-gass-11.2.2.aar
18/09/2017  17:12               628 play-services-gass-11.2.2.aar.meta
18/09/2017  17:12            81.125 play-services-gcm-11.2.2.aar
18/09/2017  17:12               628 play-services-gcm-11.2.2.aar.meta
18/09/2017  17:12            16.200 play-services-iid-11.2.2.aar
18/09/2017  17:12               628 play-services-iid-11.2.2.aar.meta
18/09/2017  17:12           231.422 play-services-nearby-10.2.6.aar
18/09/2017  17:12               628 play-services-nearby-10.2.6.aar.meta
18/09/2017  17:12            29.604 play-services-tasks-11.2.2.aar
18/09/2017  17:12               628 play-services-tasks-11.2.2.aar.meta
18/09/2017  17:12             9.603 runtime-1.0.0.aar
18/09/2017  17:12               628 runtime-1.0.0.aar.meta
06/05/2017  15:53            19.339 ShortcutBadger-1.1.5.aar
06/05/2017  15:53               459 ShortcutBadger-1.1.5.aar.meta
18/09/2017  17:12            24.712 support-annotations-26.1.0.jar
18/09/2017  17:12               628 support-annotations-26.1.0.jar.meta
18/09/2017  17:12           636.333 support-compat-26.1.0.aar
18/09/2017  17:12               628 support-compat-26.1.0.aar.meta
18/09/2017  17:12           233.096 support-core-ui-26.1.0.aar
18/09/2017  17:12               628 support-core-ui-26.1.0.aar.meta
18/09/2017  17:12            87.151 support-core-utils-26.1.0.aar
18/09/2017  17:12               628 support-core-utils-26.1.0.aar.meta
18/09/2017  17:12           164.608 support-fragment-26.1.0.aar
18/09/2017  17:12               628 support-fragment-26.1.0.aar.meta
18/09/2017  17:12           311.842 support-media-compat-26.1.0.aar
18/09/2017  17:12               628 support-media-compat-26.1.0.aar.meta
18/09/2017  17:12             3.087 support-v4-26.1.0.aar
18/09/2017  17:12               628 support-v4-26.1.0.aar.meta
06/05/2017  15:53            27.025 utnotifications.aar
06/05/2017  15:53               459 utnotifications.aar.meta
23/08/2017  12:15    <DIR>          UTNotificationsRes
23/08/2017  12:15               631 UTNotificationsRes.meta

Thanks in advance for your help!

**Comment by rampara** [comment] 2017-09-20 22:42
@edscodeblenders looks like the issue you're running into is caused by conflicted versions of Play Services AARs being included in your project (10.2.6 and 11.2.2). Can you try forcing dependency resolution by selecting `Assets -> Play Services Resolver -> Android Resolver -> Force Resolve` in the Unity Editor. If that doesn't resolve the issue you may have to update the dependency declarations to be the same version (11.2.2) in files located under `Assets/Firebase/Editor` until the Play Services Resolver library is updated to resolve this issue.

**Comment by duchanhleo** [comment] 2017-09-21 08:19
Hi, I get same issue. There are anyway to fix it manually?

**Comment by duchanhleo** [comment] 2017-09-21 08:35
I fixed by update dependencies file. Open GoogleMobileAdsDependencies.xml from path Assets\GoogleMobileAds\Editor\GoogleMobileAdsDependencies.xml. Change "com.google.android.gms:play-services-ads:11.2.2" to "com.google.android.gms:play-services-ads:11.2.0"

**Comment by rampara** [comment] 2017-09-21 19:03
@duchanhleo mentioned, updating the dependency declarations from different Unity plugins to not conflict should serve as a workaround until the Play Services Resolver library is updated to resolve the issue.

**Comment by czater** [comment] 2017-09-22 07:20
I have the same problem... @duchanhleo method doesn't work for me

**Comment by rampara** [comment] 2017-09-22 17:32
@czater have you manually updated all your dependency declarations to the the same version and then done a force resolution?

**Comment by infernova** [comment] 2017-09-23 18:32
@edscodeblenders @wenderRondonia @czater, as mentioned by @rampara, the issue seems to be due to a mismatch of dependency versions so you will need to go to Assets/GooglePlayGames/Editor/GPGSDependencies.xml and change all the package versions from 10+ to 11.2.2. If you have Firebase installed as well, you will need to ensure the Firebase package versions are the same as well by going to Assets/Firebase/Editor/*Deps.cs and edit the version number for everything except the Unity specific packages (which has a version number of 4.1.0/4.0.3).

If you don't see the GPGSDependencies.xml file, you might need to update to the latest version of GPGS (version 0.9.41) but that in itself requires its own set of bugfixes as detailed by the issue thread on the GPGS GitHub found at https://github.com/playgameservices/play-games-plugin-for-unity/issues/1913

**Comment by wenderRondonia** [comment] 2017-09-26 13:41
solved it thanks @infernova

**Comment by rampara** [comment] 2017-09-27 00:16
This issue has been resolved in the version of Play Services Resolver included in the latest release of this plugin (v3.7.1).

**Closed by rampara** 2017-09-27 00:16 UTC
Labels: support question
