### ISSUE TITLE
Ads overlaid on top of each other?

### ISSUE THREAD

**Issue by KhmerRun** [googleads/googleads-mobile-unity#619] opened 2018-02-18 09:11 UTC
Hello,

I just update admob today to 3.11.1. Doing some test and feel weird on the display.

<img width="960" alt="screenshot_2018-02-18-12-01-42-227_admob" src="https://user-images.githubusercontent.com/33341948/36350177-3ac8330a-14c6-11e8-9482-cd5f9f8bd26f.png">

First the ads show the top one (facebook). After navigating here and there in the app, it showed another one and the back order. Tested using smartbanner.

Regards,

**Comment by rampara** [comment] 2018-02-20 18:31
@KhmerRun are you requesting and displaying multiple banner ads?

**Comment by KhmerRun** [comment] 2018-02-20 22:57
@rampara 
Hi, I didn't intend to request multiple banner. But I didn't know what s wrong it displayed on top of each other. Possibly the ads request multiple times on the code? Correction, I didn't use SmartBanner.

Here is my request banner code, and it is called in Awake()

	```
private void RequestBanner()
	{
		AdSize adSize = new AdSize(320, 50);
		
		if (Screen.width < 500) {
			adSize = new AdSize(320, 50);
		} else if (Screen.width >= 500 & Screen.width < 728)
		{
			adSize = new AdSize(468, 60);
		} else if (Screen.width >= 728)
		{
			adSize = new AdSize(468, 60);
		}
		
		BannerView bannerView = new BannerView(adUnitId, adSize, AdPosition.Bottom);
		AdRequest request = new AdRequest.Builder()
			.AddTestDevice(AdRequest.TestDeviceSimulator)       // Simulator.
			.AddTestDevice("XXXX")  // My test device.
			.Build();
	
		// Load the banner with the request.
		bannerView.LoadAd(request);
	}
```

**Comment by rampara** [comment] 2018-03-01 01:14
@KhmerRun can you provide me with a test project that reproduces this issue? It would help with getting to the bottom of the cause of the issue.

**Comment by rampara** [comment] 2018-04-04 18:37
Closing due to non-response.

**Closed by rampara** 2018-04-04 18:37 UTC
Labels: P2, support question
