### ISSUE TITLE
No valid name for platform: 11 in Unity 5.5

### ISSUE THREAD

**Issue by Aenyhm** [googleads/googleads-mobile-unity#342] opened 2017-01-26 11:17 UTC
Hi,

I have the following error in Unity 5.5.1:

![capture d ecran 2017-01-26 a 09 55 05](https://cloud.githubusercontent.com/assets/825466/22329362/40c1ca3c-e3c1-11e6-850e-6c12ca9cd880.png)

I have tested with versions 3.1.3 and 3.2.0 of the plugin.

**Comment by rampara** [comment] 2017-01-28 00:05
Which platform are you attempting to build for when you run into this issue?

**Comment by Aenyhm** [comment] 2017-01-28 08:47
Any platform I use (Android, iOS, WebGL).

When I change code and I go back to Unity, the modal sometimes appears after the Editor refreshed.

It seems to be linked to PlayServicesResolver.

**Comment by rampara** [comment] 2017-02-03 21:45
I'm having trouble reproducing this issue. Using Unity 5.5.1f1, I'm able to successfully build the sample app included in this repo and deploy to Android. Can you try importing this plugin into a clean Unity app (such as our sample app) and test if your issue is still reproducible?

**Comment by bence98** [comment] 2017-02-07 19:44
I can confirm this bug. Using version 3.2.0 with Unity v5.5.1xf1. Happens to an _empty_ project as soon as I import the unitypackage. Attempting to open that project again then results in the same message.

**Comment by rampara** [comment] 2017-02-07 22:23
It's really strange that I can't reproduce this. Which OS is the machine you are developing on using?

**Comment by bence98** [comment] 2017-02-08 05:26
Linux (Kubuntu 16.04 LTS)

**Comment by rampara** [comment] 2017-03-22 18:03
@bence98 are you still experiencing this issue with the latest version of the plugin?

**Comment by bence98** [comment] 2017-03-22 19:46
@rampara Indeed I am. (AdMob 3.3.0, Unity still 5.5.1xf1)

**Comment by rampara** [comment] 2017-03-23 01:44
Running Unity 5.5.1xf1 on Ubuntu with the latest version of the plugin I'm still unable to repro this issue. The crash seems to be coming from the call to [GetCompatibleWithPlatform](https://docs.unity3d.com/ScriptReference/PluginImporter.GetCompatibleWithPlatform.html) as explained [here](https://github.com/googlesamples/unity-jar-resolver/blob/891ff13730b10a9ccb7df234a5fcc55b9e023df8/source/VersionHandler/src/VersionHandler.cs#L181). I would recommend opening an issue on the [JarResolver](https://github.com/googlesamples/unity-jar-resolver) issue tracker.

**Comment by bence98** [comment] 2017-03-23 21:17
According to them, it has been fixed. Is the latest JarResolver (1.2.14.0) in AdMob v3.3.0?

**Comment by rampara** [comment] 2017-03-23 21:32
Ah, the version in the latest release is slightly older. If you build this plugin from source it will pull in the latest version of version of JarResolver for you.

**Comment by rampara** [comment] 2017-05-08 20:13
Closing this issue has as using an updated version of JarResolver seems to have resolved it.

**Closed by rampara** 2017-05-08 20:13 UTC
Labels: support question
