### ISSUE TITLE
`Utils' does not contain a definition for `CheckInitialization'

### ISSUE THREAD

**Issue by waht123msn** [googleads/googleads-mobile-unity#757] opened 2018-09-05 03:09 UTC
when I update to 3.15.1,the unity show the error: Assets/GoogleMobileAds/Api/AdLoader.cs(48,19): error CS0117: `Utils' does not contain a definition for `CheckInitialization',and Assets/GoogleMobileAds/Api/CustomNativeTemplateAd.cs(53,26): error CS0117: `Utils' does not contain a definition for `GetTexture2DFromByteArray'

**Comment by rampara** [comment] 2018-09-06 22:38
@waht123msn @natereese does seem like a namespace issue. I would ensure your project is not defining a different `Utils` class. Closing as a duplicate of #259.

**Closed** 2018-09-06 22:39 UTC
Labels: P2, duplicate, support question
