### ISSUE TITLE
Destroy() does not work properly

### ISSUE THREAD

**Issue by Supereor** [googleads/googleads-mobile-unity#736] opened 2018-07-27 16:14 UTC
In my game "Night of the Red Cubes: Crimson Tide", banner ads are supposed to show up upon opening the Game Mode menu and every time you die, but go away when you select a game mode or restart the game.  However, for whatever reason, ads sometimes persist after the player starts a new game and after the player restarts.  It happens in this video(in addition to the ads not loading initially, which also doesn't happen consistently): https://youtu.be/QjBvvhL8x0c?t=21s

When I test it on my device, it works about 70% of the time.  I have the ad code set up so that it is attached to a single GameObject that persists across scenes with the code DontDestroyOnLoad(this); and
        if (FindObjectsOfType(GetType()).Length > 1)
        {
            Destroy(gameObject);
        }
, and ads are called and destroyed when the buttons for opening the menu and restarting the game are pressed, or when the player dies.  Am I trying to request ads too quickly?  Is the game not tracking them internally, so it can't tell when to destroy them or what to destroy?  Does anyone know?

**Comment by Seanm07** [comment] 2018-09-18 11:18
I had this same issue with the latest version 3.15.1 of plugin.

However I was **ONLY** able to reproduce it on my S7 Edge on Android 8. We've tested other android 8 devices as well as a few other random devices and the issue would not happen. But even after reboots, app re-installs etc it would always happen on the S7 Edge.

The game would start and we loaded and showed a smart banner at the bottom of the menus, after clicking through the menus to enter the game a loading screen would appear and here we would destroy the banner and load a new smart banner at the top of the screen (as older versions of the plugin did not have the .SetPosition(..) function)

During gameplay the smart banner is displayed at the top of the screen and on the pause menu it was destroyed and moved to the bottom of the screen.

Like Supereor said about 70% of the time one of these banners would not get destroyed and would be stuck on the screen and the top/bottom ads would overlap other ads in the same position too.

There were 2 things I changed to fix this in my game:
- Before calling .Destroy() on the banner call .Hide() (This fixed the issue mostly but if I spam called .Show() .Hide() .Destroy() and .LoadAd(..) very fast it would still leave me with a phantom ad, could be fixed by limiting the user ability to spam the things e.g cooldown between pausing/unpausing though)
- As the latest version of googleads has .SetPosition(..) use that, it means the banner doesn't need to be destroyed or reloaded at all to be moved.

**Comment by rampara** [comment] 2018-10-26 17:37
@Supereor @Seanm07 were you able to reproduce this issue on any device other than an S7 Edge?

**Closed as completed** 2019-01-23 03:42 UTC
Labels: Support, P2

**Comment by Seanm07** [comment] 2019-01-23 10:19
Sorry for missing the original reply. Just thought I would update this with some extra info found over the last few months.

I was able to replicate the issue on a Samsung Tab S and a HTC Nexus 9 both updated to the latest available versions of android on them. It seems to be related to moving a smart banner from the top to the bottom of the screen and would happen if I simply destroyed the smart banner then created the other smart banner.

This has happened between pause screens and gameplay (where there's a smart banner at the top of the screen ingame and at the bottom of the screen in the pause menu) there's no scene change, the only thing being done was setting the timescale to 0, enabling the pause screen gameobject, destroying the smart banner at the top of the screen, requesting a new one at the bottom of the screen and showing it.

However as the new version of the plugin has the SetPosition functionality, the old method of destroying and re-creating the banners is no longer needed (and the issue doesn't happen when smart banners are moved with SetPosition)

Also note that I have only ever had this issue happen with smart banners and also only had it happen when destroying a smart banner in one position and recreating another smart banner in a new position. I've never seen it happen when using a different banner type.
