### ISSUE TITLE
ADS does not work on iOS (SDK tried to perform a networking task before being initialized) 

### ISSUE THREAD

**Issue by DmytroSobko** [googleads/googleads-mobile-unity#1542] opened 2021-01-06 08:53 UTC
Admob does not work for iOS, the same code works just fine for Android.
I'm currently using v5.3.0 of this plugin, which was tested with the iOS SDK 7.63.0.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.1.16
  * Google Mobile Ads Unity plugin version: 5.3.0
  * Platform: iOS
  * Platform OS version:  iOS 14

#### Steps to reproduce:
- add 5.3.0 Admob plugin version;
- make the build for iOS;
- see messages like in the screenshot

![1](https://user-images.githubusercontent.com/47760062/103748331-a3a10300-500c-11eb-9204-85b27dede50f.jpg)

**Comment by memento3525** [comment] 2021-01-06 12:34
Same here.
An ad was called after 'MobileAds.Initialize' callback.
My app is also a game already being serviced by Android, and I'm expanding my platform to iOS.
Test Unit ID used.

UnityVersion : 2019.4.17f1
Google Mobile Ads Unity plugin version : 5.4.0
PlatformVersion : ios14 / Ipad Air (3gen)

**Comment by zhouruikevin** [comment] 2021-01-06 15:40
Same Here. IOS Platform

**Comment by zhouruikevin** [comment] 2021-01-07 06:38
Soveld!   Add a framework. 
![image](https://user-images.githubusercontent.com/8570632/103859928-dbd04080-50f5-11eb-86a9-ee2dae85397e.png)

**Comment by DmytroSobko** [comment] 2021-01-07 13:29
> Soveld! Add a framework.
> ![image](https://user-images.githubusercontent.com/8570632/103859928-dbd04080-50f5-11eb-86a9-ee2dae85397e.png)

Hmm,I don't have such a framework. Where did you find it?

**Comment by DmytroSobko** [comment] 2021-01-25 10:51
Adding this to the podfile fixed the issue
use_frameworks! :linkage => :static

**Comment by kuharev** [comment] 2021-03-01 10:21
use_frameworks! :linkage => :static

Didn't help me :(

**Comment by kuharev** [comment] 2021-03-01 10:47
> Adding this to the podfile fixed the issue
> use_frameworks! :linkage => :static

Can you explain more?

**Comment by KingKlauz** [comment] 2021-03-01 13:10
I am having the same issue on iOS as well. I am currently using admob v5.4.0 and am testing it on iPhone 12 running iOS 14.4. I already have the Pods_Unity_iPhone.framework: 

![Screenshot 2021-03-01 at 9 00 51 PM](https://user-images.githubusercontent.com/39686786/109501309-6455d680-7ad2-11eb-86e5-8f281cb38358.png)

Adding the "use_frameworks! :linkage => :static" to the pod file does not appear fix the issue for me either. Hope somebody will be able to help us out with this issue.

**Comment by pixeption** [comment] 2021-03-09 14:47
> Adding this to the podfile fixed the issue
> use_frameworks! :linkage => :static

Works for me. Unity 2019.4.20f1, Mopub 5.16.1 and Admob 7.69.0

**Comment by jayaram9877** [comment] 2021-03-17 12:09
> I am having the same issue on iOS as well. I am currently using admob v5.4.0 and am testing it on iPhone 12 running iOS 14.4. I already have the Pods_Unity_iPhone.framework:
> 
> ![Screenshot 2021-03-01 at 9 00 51 PM](https://user-images.githubusercontent.com/39686786/109501309-6455d680-7ad2-11eb-86e5-8f281cb38358.png)
> 
> Adding the "use_frameworks! :linkage => :static" to the pod file does not appear fix the issue for me either. Hope somebody will be able to help us out with this issue.
> 
> ![Screenshot 2021-03-02 at 4 30 05 PM](https://user-images.githubusercontent.com/39686786/109620204-94ee4c80-7b74-11eb-8581-b45c034e6105.png)

Did you somehow found the solution?

**Comment by JoS84** [comment] 2021-03-21 04:56
Same issue here.
before it worked well when i used

'Google-Mobile-Ads-SDK', '~>7.68'
'GoogleMobileAdsMediationUnity', '3.4.2.1'

It's OK but.

it issue appears when I add
'GoogleMobileAdsMediationFacebook', '6.2.1.0'

**Comment by KingKlauz** [comment] 2021-03-21 05:19
> > I am having the same issue on iOS as well. I am currently using admob v5.4.0 and am testing it on iPhone 12 running iOS 14.4. I already have the Pods_Unity_iPhone.framework:
> > ![Screenshot 2021-03-01 at 9 00 51 PM](https://user-images.githubusercontent.com/39686786/109501309-6455d680-7ad2-11eb-86e5-8f281cb38358.png)
> > Adding the "use_frameworks! :linkage => :static" to the pod file does not appear fix the issue for me either. Hope somebody will be able to help us out with this issue.
> > ![Screenshot 2021-03-02 at 4 30 05 PM](https://user-images.githubusercontent.com/39686786/109620204-94ee4c80-7b74-11eb-8581-b45c034e6105.png)
> 
> Did you somehow solve the issue?

Not exactly. But I was integrating some other 3rd party SDKs into my project afterwards and the issue went away. I do notice that my podlike is much different after integrating these other 3rd party SDKs. Though ads do appear now on iOS, they introduce another issue where all audios get muted after a rewarded ad is loaded. There is already a thread about this on this GitHub as well. So it's just 1 issue after another honestly.

My altered pod file:

![Screenshot 2021-03-21 at 1 00 53 PM](https://user-images.githubusercontent.com/39686786/111894697-c9ed1100-8a47-11eb-9809-971554329f45.png)

**Comment by glodos** [comment] 2021-03-23 14:04
Since the pod file is regenerated on each build you might want to have the following settings in iOS Resolver:

<img width="398" alt="Screenshot 2021-03-23 at 14 57 32" src="https://user-images.githubusercontent.com/2659001/112158955-f2f8d780-8be8-11eb-9196-496dbdb9bcc1.png">


This gives me the same pod flie as above and the issue is no longer present.

**Comment by KingKlauz** [comment] 2021-03-24 04:08
> Since the pod file is regenerated on each build you might want to have the following settings in iOS Resolver:
> This gives me the same pod flie as above and the issue is no longer present.


Ouh! Thank you for the tip!

**Comment by egorovsa** [comment] 2021-04-01 19:32
> Since the pod file is regenerated on each build you might want to have the following settings in iOS Resolver:
> This gives me the same pod flie as above and the issue is no longer present.
OMG! WORKS NOW!!!!

**Comment by NagasumukhHD** [comment] 2021-05-04 04:22
Hey I am still facing this issue. I tried the above mentioned solutions but no luck. Did anyone find any solution?

**Comment by ang713** [comment] 2021-05-20 14:42
adding UnityFramework.framework fixed my issue
<img width="701" alt="Screenshot 2021-05-20 at 8 40 50 PM" src="https://user-images.githubusercontent.com/39689638/118998985-b6a8e400-b9ab-11eb-84bf-8b59bac183cb.png">

**Comment by victorcui** [comment] 2021-05-20 22:54
@ang713  same here

**Comment by chaors** [comment] 2021-07-13 09:06
hello  anybody, I use the same method in iOS14 and it is no problem, but iOS13 is still problematic, and it is no problem to connect to the Xcode real machine for debugging, but not after archive and installation.

**Comment by chaors** [comment] 2021-07-14 07:11
> I am having the same issue on iOS as well. I am currently using admob v5.4.0 and am testing it on iPhone 12 running iOS 14.4. I already have the Pods_Unity_iPhone.framework:
> 
> ![Screenshot 2021-03-01 at 9 00 51 PM](https://user-images.githubusercontent.com/39686786/109501309-6455d680-7ad2-11eb-86e5-8f281cb38358.png)
> 
> Adding the "use_frameworks! :linkage => :static" to the pod file does not appear fix the issue for me either. Hope somebody will be able to help us out with this issue.
> 
> ![Screenshot 2021-03-02 at 4 30 05 PM](https://user-images.githubusercontent.com/39686786/109620204-94ee4c80-7b74-11eb-8581-b45c034e6105.png)

me too 😿😿

**Comment by NVentimiglia** [comment] 2023-01-26 23:06
Closing this issue as obsolete and not replicated on the most recent version. If you still have issues, please reopen.

**Closed by NVentimiglia** 2023-01-26 23:06 UTC
