### ISSUE TITLE
java.lang.Error  $Proxy12.onAdLoaded

### ISSUE THREAD

**Issue by UnityKR** [googleads/googleads-mobile-unity#841] opened 2019-02-07 07:39 UTC
Device summary:
* LGE LM-V409N
* Android 8.1

Software summary:
* Unity 2018.3.3f1
* Resolver play-services-resolver_v1.2.98.0
* GooglePlayGamesPlugin_v0.9.58

Error Log
java.lang.Error: FATAL EXCEPTION [Thread-217]
Unity version     : 2018.3.3f1
Device model      : LGE LM-V409N
Device fingerprint: lge/judypn_lao_com/judypn:8.1.0/OPM1.171019.026/1900911449a5b.Plus.FGN:user/release-keys
Caused by
  at com.unity3d.player.ReflectionHelper.nativeProxyInvoke (Native Method)
  at com.unity3d.player.ReflectionHelper.a (Unknown Source)
  at com.unity3d.player.ReflectionHelper$1.invoke (Unknown Source:6)
  at java.lang.reflect.Proxy.invoke (Proxy.java:913)
  at $Proxy12.onAdLoaded (Unknown Source)
  at com.google.unity.ads.Interstitial$1$1$1.run (Interstitial.java:75)
  at java.lang.Thread.run (Thread.java:764)

**Comment by UragayalaDeepika** [comment] 2019-07-31 15:47
@UnityKR Closing this for now. Feel free to comment here so that we can reopen and reinvestigate this issue if it is still reproducible with the latest version.

**Closed by UragayalaDeepika** 2019-07-31 15:47 UTC

**Comment by tienhagioi** [comment] 2021-04-29 07:21
Same issue 
OS : Android 4 ( 80% ) , 5 (4%) , 8 (11%) ,9,10
Software summary:
* Unity 2020.3.1
* Play-services-resolver_v1.2.164
* Firebase 7.1.0
* Google Mobile Ads Unity Plugin v5.4.0
Caused by : 
com.unity3d.player.ReflectionHelper.nativeProxyInvoke
com.unity3d.player.ReflectionHelper.a
com.unity3d.player.ReflectionHelper$1.invoke
$Proxy12.onAdLoaded
com.google.unity.ads.Banner$3$1.run (Banner.java:165)
java.lang.Thread.run (Thread.java:841)
