### ISSUE TITLE
Video Rewarded Getting Called Twice After Reloading The Scene

### ISSUE THREAD

**Issue by 1exip** [googleads/googleads-mobile-unity#759] opened 2018-09-10 19:46 UTC
I have tried reimporting the plugin, reinstalling the jdk and the sdk. Nothing works, Video Rewarded and Video Closed gets called twice

**Comment by rampara** [comment] 2018-10-03 01:15
@1exip I'm having trouble reproducing this behavior. Can you provide a test project that demonstrates this issue?

**Comment by rampara** [comment] 2019-01-23 03:43
Closing due to non-response.

**Closed by rampara** 2019-01-23 03:43 UTC
Labels: P2, support question
