### ISSUE TITLE
crashes app on startup every 5-7 times. on iOS 8

### ISSUE THREAD

**Issue by lgrogin** [googleads/googleads-mobile-unity#140] opened 2015-12-01 08:14 UTC
tested on iphone 4 , ipad mini and iphone 6 with iOS8.
It crashes app on startup every 5-7 times. 
Removing the Googlemobileads framework fixes the crashes

**Comment by rampara** [comment] 2015-12-07 22:41
Can you provide additional details on the crash @lgrogin ? Are you able to reproduce the error in our sample app?

- Ram

**Comment by lgrogin** [comment] 2015-12-08 14:16
@rampara 
I was able to reproduce the above issue with your sample app
in the call stack of the crash I can see
[GADApplication runEarlyActivities]
[GADDevice cacheStaticParameters]

I did this with iPhone 4S running iOS 7.0.2

**Comment by rampara** [comment] 2016-10-10 21:23
Closing this issue due to its age and it being specific to the Google Mobile Ads SDK and not this plugin. GMA SDK issues can be reported at our [product forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).

**Closed by rampara** 2016-10-10 21:23 UTC
