### ISSUE TITLE
Banner looks wierd on Samsung Galaxy s10

### ISSUE THREAD

**Issue by Jazzgazer** [googleads/googleads-mobile-unity#890] opened 2019-04-23 01:46 UTC
![admob banner issue](https://user-images.githubusercontent.com/7954950/56545894-f0804400-65b3-11e9-89ef-519a18aeb0dd.jpg)

I tested bannerView on Galaxy S10. It looks like in wrong position. 

**Using codes are below.**
(bannerView = new BannerView(bannerUnitID, AdSize.Banner, AdPosition.Top);

Please check plugin on brand new phones. 
thanks.

**Comment by stowy** [comment] 2019-05-16 18:49
Please try [version 3.17.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/3.17.0).

**Comment by stowy** [comment] 2019-07-03 22:13
Hi, I am unable to reproduce this on a samsung S8 using Android version
7.0, and Pixel 3 using Android 9.

Does it reproduce on any other devices? I don't have access to a Galaxy
S10. Haven't been able to repro in an emulator either.

**Comment by UragayalaDeepika** [comment] 2019-10-10 21:04
@Jazzgazer We are closing this issue. Please comment here if you are able to reproduce the issue with the latest plugin so that we can take a look.

**Closed by UragayalaDeepika** 2019-10-10 21:04 UTC
