### ISSUE TITLE
When I update to v3.12.0, game sound muted after interstitial closed

### ISSUE THREAD

**Issue by daneric** [googleads/googleads-mobile-unity#633] opened 2018-03-17 13:16 UTC
sound also muted after rewarded video closed.
There is error log in xcode when intersititial closed:
[avas] AVAudioSession.mm:1177:-[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

**Comment by rampara** [comment] 2018-03-19 17:42
@daneric can you provide a Unity test project that reproduces this behavior?

**Comment by anightinseoul** [comment] 2018-04-06 07:50
1. play music using Music App
2. Start unity game.
3. Show Rewarded video and close.
=> The music is played automatically but game sound isn't played.

**Comment by rampara** [comment] 2018-07-25 18:19
@anightinseoul will investigate and follow up once I have more information on this issue.

**Comment by rampara** [comment] 2019-01-23 03:55
Closing due to non-response.

**Closed by rampara** 2019-01-23 03:55 UTC
Labels: P3, support question
