### ISSUE TITLE
Ios Build Error

### ISSUE THREAD

**Issue by gokhanci** [googleads/googleads-mobile-unity#355] opened 2017-02-27 05:54 UTC
Win32Exception: ApplicationName='gem', CommandLine='environment', CurrentDirectory='C:\Users\Gokhan\Desktop\Games\JU-PU'
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()

OS Windows 10, Unity version 5.5.2

@rampara

**Comment by DEKAGATO** [comment] 2017-03-09 03:29
Did you get solution for this ? i also up to Admob ver 3.3.0 but nothing change

**Comment by rampara** [comment] 2017-03-22 18:35
Closing as duplicate of #350.

**Closed by rampara** 2017-03-22 18:35 UTC
