### ISSUE TITLE
GetTexture2DFromByteArray'

### ISSUE THREAD

**Issue by srikanthch888** [googleads/googleads-mobile-unity#348] opened 2017-02-12 14:25 UTC
GetTexture2DFromByteArray'

**Comment by srikanthch888** [comment] 2017-02-12 14:26
When I import asset in unity  it get's error
"GetTexture2DFromByteArray'"

**Comment by rampara** [comment] 2017-02-13 20:29
Are you using the latest version of the plugin? Have you modified the plugin in any way? Are you able to reproduce this error in an empty Unity project?

**Comment by kujo87** [comment] 2017-02-13 20:31
Do you have your own class somewhere called Utils that isn't in its own namespace? I had this issue, and so had to add in Common.Utils.GetTexture2DFromByteArray to the CustomNativeTemplate class to make it pass

**Comment by rampara** [comment] 2017-02-13 20:34
+1 to @kujo87's comment.

**Comment by rampara** [comment] 2017-03-20 21:42
Closing this issue due to non-response. If this issue persists for you, please re-open it.

**Closed by rampara** 2017-03-20 21:42 UTC
Labels: support question
