### ISSUE TITLE
Loading of Rewarded Video Ads With TestDevices fails

### ISSUE THREAD

**Issue by Mario185** [googleads/googleads-mobile-unity#371] opened 2017-03-17 13:34 UTC
Hi,
I want to use the new Rewarded Video ads.
But how can I test them? 
When I add TestDevices to the AdRequest loading of the ad fails with the message "Internal Error". Without TestDevices everything seems to work fine.

So this would fail and wold trigger the OnAdFailedToLoad event:
`var adRequest = new AdRequest.Builder().AddTestDevice("[DEVICE ID GOES HERE]").Build();
RewardBasedVideoAd.Instance.LoadAd(adRequest, c_rewardedVideoAdID);`

With banner ads the TestDevices work just fine.

Am I doing something wrong or are TestDevices just not supported for rewarded video ads?

**Comment by rampara** [comment] 2017-03-20 21:30
Currently, when your device is set as a test device, AdMob will fail to serve any rewarded video ads to your device. You can expect this issue to be addressed soon. For the time being, to test rewarded video ads you can remove the test device option and use the test ad units listed below as a workaround.

Android - ca-app-pub-3940256099942544/5224354917
iOS - ca-app-pub-3940256099942544/1712485313

**Comment by rampara** [comment] 2017-03-20 21:30
closing as duplicate of #374.

**Closed by rampara** 2017-03-20 21:30 UTC
Labels: support question
