### ISSUE TITLE
Callbacks not being called

### ISSUE THREAD

**Issue by gilbertoalexsantos** [googleads/googleads-mobile-unity#452] opened 2017-06-24 23:30 UTC
Environment:

Unity version:            5.6.2f1
Googleads version:   3.5.0 (last version)
Device:                       Android
Project:                      My personal project and the googleads sample projects

Description:

Everything is working fine... Except the callbacks (OnAdLoaded, OnAdFailedToLoad, ...) that aren't being called.

I've tested with the SampleProject without modifying one line of code.

Any tips guys?

**Comment by rampara** [comment] 2017-06-26 20:23
@gilbertoalexsantos are you running into this issue on Android or on iOS?

**Comment by gilbertoalexsantos** [comment] 2017-06-26 22:13
On Android.

**Comment by rampara** [comment] 2017-06-26 23:47
@gilbertoalexsantos when running the sample project from the repo you see no output in logcat under the `Unity` tag corresponding to ad events?

**Comment by gilbertoalexsantos** [comment] 2017-06-26 23:53
I see no output on Unity Debug.Log.

I have a plugin that has the option to visualize Unity Debug.Logs on runtime for debug purposes (SRDebugger).

I put some Debug.Log on the class InterstitialAd too (to make sure wasn't problem on my part). I put on these callbacks: this.client.OnAdLoaded, ...

I didn't try to see the logs on logcat. Do you want me to try it? I'm a bit busy right now, but I can try it later and I'll update the thread here.

**Comment by rampara** [comment] 2017-06-27 20:02
I can you try a project where you're not using SRDebugger just to try isolate where the issue is coming from.

**Comment by Pacifist94** [comment] 2017-06-28 22:08
Man, I got the same issue, The callbacks are not working, 
In my case when it triggers the  HandleOnAdRewarded method (or any other) it only works on the very first time ... after requesting a second ad, I complete viewing the ad succesfully , but no RewardEvent is trigger this time..

**Comment by rampara** [comment] 2017-06-29 18:29
@Pacifist94 replied to you in #448.

**Comment by Pacifist94** [comment] 2017-07-03 10:29
Thanks my issue was resolved it was an error on my end....

**Comment by rampara** [comment] 2017-07-05 18:25
@Pacifist94 glad to hear your issue was resolved.

**Comment by rampara** [comment] 2017-08-04 20:00
Closing issue due to non-response from the original poster. Please reopen if the issue persists for you.

**Closed by rampara** 2017-08-04 20:00 UTC
Labels: support question
