### ISSUE TITLE
Banner not showing on Android device

### ISSUE THREAD

**Issue by douduck08** [googleads/googleads-mobile-unity#437] opened 2017-06-05 12:01 UTC
I used version 3.5.0 of the plugin and Unity 5.5.3f1 to build an apk.
But after installing, banner didn't show in app when I had sent request for miniutes.

In logcat, I got following message:
- app does not have the required permissions to get location

and
- No fill from ad server
- Failed to load ad: 3

Btw, also no banner was showed when I add AddTestDevice to AdRequest.
Did I miss any setting?

**Comment by rampara** [comment] 2017-06-05 14:48
@douduck08 are you able to reproduce this issue with the sample app included in this repo?

**Comment by douduck08** [comment] 2017-06-06 11:38
I used my Ad Unit Id in the the sample HelloWorld in this repo, then it worked.

My app have joined "Designed for Families", and the plan suggested me add more information in ad request. However I can't use the setting in this plugin, maybe here is the problem?

Ref: https://support.google.com/admob/answer/6223431

**Comment by rampara** [comment] 2017-06-07 16:02
Our [developer docs](https://developers.google.com/admob/unity/start#ad_request_targeting) document how to add targeting information such as child-directed treatment.

**Comment by rampara** [comment] 2017-07-13 21:08
Closing issue due to it's age. Please re-open if this issue persists for you.

**Closed by rampara** 2017-07-13 21:08 UTC
Labels: support question

**Comment by ArmandCloud** [comment] 2017-08-26 17:18
I am having the same error.
Only with android build. Ios has no problems showing ads.
So i removed this lines from my code and make a test build.
`.AddExtra("is_designed_for_families", "true")
 .TagForChildDirectedTreatment(true)`
Again i have the same error. And cant see test ads.

08-26 20:14:05.747 1836-1836/com.fauna.koskukulikos I/Ads: This request is sent from a test device.
08-26 20:14:06.127 1836-1847/com.fauna.koskukulikos I/Ads: No fill from ad server.
08-26 20:14:06.127 1836-1836/com.fauna.koskukulikos W/Ads: Failed to load ad: 3

And also ;
Some times i have Error Code : 0

**Comment by douduck08** [comment] 2017-08-27 02:10
I have solved this issue on my app.

I removed my app from the "Designed for Families" plan, and the ads showed.
The reason I guessed is google cannot provide enough content with the limit of "Designed for Families".

**Comment by ArmandCloud** [comment] 2017-08-27 11:24
Thank you @douduck08 ,
I removed .AddExtra("is_designed_for_families", "true") from request.
I change Designed for families age group to mixed audience .
Now i can see the test ads.
Best Regards,
