### ISSUE TITLE
plugin 5.4.0 crashed the app by newing an instance of abstract com.google.android.gms.ads.rewarded.RewardedAd class

### ISSUE THREAD

**Issue by swswggg** [googleads/googleads-mobile-unity#1591] opened 2021-04-10 19:15 UTC
Using 2020.3.3f1, import AdMob unity plugin 5.4.0, also Android Resolver resolved forcefully.
still get the following message and app crashed.
it seems that UnityRewardedAd tried to new an abstract com.google.android.gms.ads.rewarded.RewardedAd instance. Any workaround?

2021-04-11 02:35:05.115 10922-10922/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.moonriver.divination, PID: 10922
    java.lang.InstantiationError: com.google.android.gms.ads.rewarded.RewardedAd
        at com.google.unity.ads.UnityRewardedAd$1.run(UnityRewardedAd.java:53)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7551)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by swswggg** [comment] 2021-04-10 19:22
sry for misunderstanding. it seems that UnityRewardedAd tried to new a abstract com.google.android.gms.ads.rewarded.RewardedAd instance. Any workaround?

**Comment by ali-pjx** [comment] 2021-04-11 06:12
I have the exact same problem the game crashes with:
FATAL EXCEPTION: main

Error AndroidRuntime java.lang.InstantiationError: com.google.android.gms.ads.rewarded.RewardedAd
Error AndroidRuntime 	at com.google.unity.ads.UnityRewardedAd$1.run(UnityRewardedAd.java:53)
Error AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:883)
Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:100)
Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:237)
Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:7948)
Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

**Comment by saeedasadsh** [comment] 2021-04-11 06:15
same here. game crash after unity splash screen with fatal exception

**Comment by ivan7012** [comment] 2021-04-11 06:24
we have the same issue in our company games and no one can watch ads anymore
java.lang.InstantiationError: com.google.android.gms.ads.rewarded.RewardedAd

**Comment by zero0sight** [comment] 2021-04-11 06:32
I ran into same thing. please inform me if you find any solution...

**Comment by swswggg** [comment] 2021-04-11 12:16
solved. It is basically a package versioning problem. admob unity 5.4.0 uses play-service 19.5.0 and old google package managers have a bug on solving it, always grab the latest play-service 20.0.0. Donot use and delete other google package managers included in other unitypackages. Just use the one included in admob unity 5.4.0. 
(https://user-images.githubusercontent.com/19384188/114303841-b3941b80-9b02-11eb-91bf-0967f945e694.png)

**Comment by ali-pjx** [comment] 2021-04-11 12:21
> solved. It is basically a package versioning problem. admob unity 5.4.0 uses play-service 19.5.0 and old google package managers have a bug on solving it, always grab the latest play-service 20.0.0. Donot use and delete other google package managers included in other unitypackages. Just use the one included in admob unity 5.4.0.
> (https://user-images.githubusercontent.com/19384188/114303841-b3941b80-9b02-11eb-91bf-0967f945e694.png)

Its interesting, this problem only happens when I force resolve the android packages and it switches to 20.0.0, So before this problem was produced, the package was set to com.google.android.gms.play-services-ads-19.5.0 and everything was fine but when it decides to use com.google.android.gms.play-services-ads-20.0.0 this crash comes up.

**Comment by swswggg** [comment] 2021-04-11 13:28
> > solved. It is basically a package versioning problem. admob unity 5.4.0 uses play-service 19.5.0 and old google package managers have a bug on solving it, always grab the latest play-service 20.0.0. Donot use and delete other google package managers included in other unitypackages. Just use the one included in admob unity 5.4.0.
> > (https://user-images.githubusercontent.com/19384188/114303841-b3941b80-9b02-11eb-91bf-0967f945e694.png)
> 
> Its interesting, this problem only happens when I force resolve the android packages and it switches to 20.0.0, So before this problem was produced, the package was set to com.google.android.gms.play-services-ads-19.5.0 and everything was fine but when it decides to use com.google.android.gms.play-services-ads-20.0.0 this crash comes up.

the new package manager changed its located path that we are not familiar with, not Assets->Play Services Resolver->Android Resolver->Force Resolve, in this case, wrong old package manager might be used, said old one imported with FB Audience network. As mentioned at last post, deleting other google package managers located in your unity project helps to avoid such a misuse,

**Comment by ali-pjx** [comment] 2021-04-11 13:36
> > > solved. It is basically a package versioning problem. admob unity 5.4.0 uses play-service 19.5.0 and old google package managers have a bug on solving it, always grab the latest play-service 20.0.0. Donot use and delete other google package managers included in other unitypackages. Just use the one included in admob unity 5.4.0.
> > > (https://user-images.githubusercontent.com/19384188/114303841-b3941b80-9b02-11eb-91bf-0967f945e694.png)
> > 
> > 
> > Its interesting, this problem only happens when I force resolve the android packages and it switches to 20.0.0, So before this problem was produced, the package was set to com.google.android.gms.play-services-ads-19.5.0 and everything was fine but when it decides to use com.google.android.gms.play-services-ads-20.0.0 this crash comes up.
> 
> the new package manager changed its located path that we are not familiar with, not Assets->Play Services Resolver->Android Resolver->Force Resolve, in this case, wrong old package manager might be used, said old one imported with FB Audience network. As mentioned at last post, deleting other google package managers located in your unity project helps to avoid such a misuse,

Not sure that I understood what you are trying to say, but I am using External dependency manager that is included in the GMS package itself, and I'm 100% sure that its on of the mediations that changes gms ads version from 19.5 to 20 and produces this crashes. However, I've been challenging with this problem since last week and for some reason one of these packages is trying to use the 20th version of GMS ads. Also, when I was looking at maven repository which is the main google repository for such packages, I have checked that version 20 is neither associated to firebase nor to any other related api's such as Unity .... 

So I'm not absolutely sure how they decided to upgrade to version 20, but we are losing revenue every single day with such problem.

**Comment by ivan7012** [comment] 2021-04-11 13:53
> solved. It is basically a package versioning problem. admob unity 5.4.0 uses play-service 19.5.0 and old google package managers have a bug on solving it, always grab the latest play-service 20.0.0. Donot use and delete other google package managers included in other unitypackages. Just use the one included in admob unity 5.4.0.
> (https://user-images.githubusercontent.com/19384188/114303841-b3941b80-9b02-11eb-91bf-0967f945e694.png)

I have done as you said (force resolving and checking packages version) and the issue is still there. The crash happens when ever I try to request for a new rewarded video ad. The play-service plugin version is 20.0.0

**Comment by swswggg** [comment] 2021-04-11 14:51
> > solved. It is basically a package versioning problem. admob unity 5.4.0 uses play-service 19.5.0 and old google package managers have a bug on solving it, always grab the latest play-service 20.0.0. Donot use and delete other google package managers included in other unitypackages. Just use the one included in admob unity 5.4.0.
> > (https://user-images.githubusercontent.com/19384188/114303841-b3941b80-9b02-11eb-91bf-0967f945e694.png)
> 
> I have done as you said (force resolving and checking packages version) and the issue is still there. The crash happens when ever I try to request for a new rewarded video ad. The play-service plugin version is 20.0.0

i think the simplest solution is replace these play services by hand, if you just had this problem only. 
Also, remove the package manager to stop it from resolving wrong version automatically.

**Comment by ali-pjx** [comment] 2021-04-11 14:55
> > > solved. It is basically a package versioning problem. admob unity 5.4.0 uses play-service 19.5.0 and old google package managers have a bug on solving it, always grab the latest play-service 20.0.0. Donot use and delete other google package managers included in other unitypackages. Just use the one included in admob unity 5.4.0.
> > > (https://user-images.githubusercontent.com/19384188/114303841-b3941b80-9b02-11eb-91bf-0967f945e694.png)
> > 
> > 
> > I have done as you said (force resolving and checking packages version) and the issue is still there. The crash happens when ever I try to request for a new rewarded video ad. The play-service plugin version is 20.0.0
> 
> i think the simplest solution is replace these play services by hand, if you just had this problem only.
> Also, remove the package manager to stop it from resolving wrong version automatically.

Could you please mention what you have done exactly that you stopped this issue? 

Also, are you sure deleting package manager would not mess up the dependencies and other required stuff?

**Comment by swswggg** [comment] 2021-04-11 15:58
> > > > solved. It is basically a package versioning problem. admob unity 5.4.0 uses play-service 19.5.0 and old google package managers have a bug on solving it, always grab the latest play-service 20.0.0. Donot use and delete other google package managers included in other unitypackages. Just use the one included in admob unity 5.4.0.
> > > > (https://user-images.githubusercontent.com/19384188/114303841-b3941b80-9b02-11eb-91bf-0967f945e694.png)
> > > 
> > > 
> > > I have done as you said (force resolving and checking packages version) and the issue is still there. The crash happens when ever I try to request for a new rewarded video ad. The play-service plugin version is 20.0.0
> > 
> > 
> > i think the simplest solution is replace these play services by hand, if you just had this problem only.
> > Also, remove the package manager to stop it from resolving wrong version automatically.
> 
> Could you please mention what you have done exactly that you stopped this issue?
> 
> Also, are you sure deleting package manager would not mess up the dependencies and other required stuff?

Firstly answer the deleting package manager question, i think package manager is a help tool(plugin) for you to download the right version libs into your unity project. it reads all prepared xxxxxDependencies.xmls(by other plugins what need) in your project, resolves conflicts and downloads them all. If you remove package manager, you just lose the automatic resolving function, not making your project broken.
Anyway, BACKUP YOUR PROJECTS BEFORE you do somethings what you never done BEFORE.  

the way i imported admob is as following pics shown:
![new package manager(1)](https://user-images.githubusercontent.com/19384188/114310664-12b35980-9b1e-11eb-8a32-f03f5df2d290.png)
after importing, admob's google package asked me dialogs,
i just first click "enabled" at upper dialog, then await its doing jobs.
when it finished, i just click the "text area" right below the "After" Label, then click "Add selected Registries".

![new package manager(2)](https://user-images.githubusercontent.com/19384188/114310970-6b372680-9b1f-11eb-8e2d-ed858e2cd6b8.png)
ok, google want you to upgrade, then i click "Apply".

![new package manager(3)](https://user-images.githubusercontent.com/19384188/114311060-cf59ea80-9b1f-11eb-85f5-2beecf54b61f.png)
you will see the the folder "External Dependency Manager" underneath Asset folder went down the below of folder "Packages".

you done.

And the errata is here.
once you get this done, then you import another plugin(ex. FB Audiencd Network) include another old package manager without excluding the old one.
your manager might go mad and give you wrong version libs.
![new package manager(4)](https://user-images.githubusercontent.com/19384188/114311416-3b891e00-9b21-11eb-882a-27b13bd9af47.png)
as shown in this pic, you got additional old package manager "PlayServiceResolver" in Asset folder, and wrong libs in Plugins/Android folder.

**Comment by swswggg** [comment] 2021-04-11 16:04
in this situation, remove the whole related plugins, including uninstalling/deleting all package managers, then import all again with cautions. this works for me. 

Anyway, BACKUP YOUR PROJECTS BEFORE you do somethings what you never done BEFORE.

**Comment by swswggg** [comment] 2021-04-11 16:11
Besides package manager, the supreme ultra solution is copy corresponding libs to your Plugins/Android from maven repository by your own hands. It is an try-and-error to "guess" what libs your plugin(s) need and annoyingly crazy.

i done this before google package manager shows up.

**Comment by DacNV95** [comment] 2021-04-22 02:28
Hello, today I encountered this problem. After finding out t has determined the cause of the conflict between Facebook Audience Network v6.2.1 (requires play-service 20.0.0 to use bidding feature with admob) vs Admob v5.4.0 (requires play- service 19.5.0), while play-service 20.0.0 removed many reward functions so this error was generated.
While waiting for google to release the update to support play-service 20.0.0, you can use the following: in the build settings, check the custom build gradle (unity 2018.4) then resolve again, t used still see normal ads without errors.

**Comment by mdobele** [comment] 2021-04-23 05:05
> After finding out t has determined the cause of the conflict between Facebook Audience Network v6.2.1 (requires play-service 20.0.0 to use bidding feature with admob) vs Admob v5.4.0 (requires play- service 19.5.0)

Does Facebook require play-services 20 for bidding??   We've been using FB Open Bidding for several months now, including the latest 6.2.1.0 version against play-services-19.7.0 without any issues. 

We recently ran into this threads issue after we attempted to update Firebase to the latest, since they are removing support for the Unity Package Manager. 

We tried using both the External Dependency Managers included with latest Firebase as well as Admob 5.4.0 but both resolved to v20.  In the end we simply had to manually downgrade the play-services ads files back to our previous 19.7.0 to get both Firebase and Admob working correctly again. 

I'm guessing this won't be resolved until Admob release a new version that also supports v20, so recommend you avoid updating Firebase to latest unless you have to.

**Comment by ali-pjx** [comment] 2021-04-24 05:44
> > After finding out t has determined the cause of the conflict between Facebook Audience Network v6.2.1 (requires play-service 20.0.0 to use bidding feature with admob) vs Admob v5.4.0 (requires play- service 19.5.0)
> 
> Does Facebook require play-services 20 for bidding?? We've been using FB Open Bidding for several months now, including the latest 6.2.1.0 version against play-services-19.7.0 without any issues.
> 
> We recently ran into this threads issue after we attempted to update Firebase to the latest, since they are removing support for the Unity Package Manager.
> 
> We tried using both the External Dependency Managers included with latest Firebase as well as Admob 5.4.0 but both resolved to v20. In the end we simply had to manually downgrade the play-services ads files back to our previous 19.7.0 to get both Firebase and Admob working correctly again.
> 
> I'm guessing this won't be resolved until Admob release a new version that also supports v20, so recommend you avoid updating Firebase to latest unless you have to.

Yes, both admob latest version and some of mediations from admob are forcing to use v20. 
However, This is pretty awkward since this problem is causing users almost three weeks, and not only there is not any answers from official support but also it is being reproduced every single day.

**Comment by ali-pjx** [comment] 2021-04-24 05:44
> > > > > solved. It is basically a package versioning problem. admob unity 5.4.0 uses play-service 19.5.0 and old google package managers have a bug on solving it, always grab the latest play-service 20.0.0. Donot use and delete other google package managers included in other unitypackages. Just use the one included in admob unity 5.4.0.
> > > > > (https://user-images.githubusercontent.com/19384188/114303841-b3941b80-9b02-11eb-91bf-0967f945e694.png)
> > > > 
> > > > 
> > > > I have done as you said (force resolving and checking packages version) and the issue is still there. The crash happens when ever I try to request for a new rewarded video ad. The play-service plugin version is 20.0.0
> > > 
> > > 
> > > i think the simplest solution is replace these play services by hand, if you just had this problem only.
> > > Also, remove the package manager to stop it from resolving wrong version automatically.
> > 
> > 
> > Could you please mention what you have done exactly that you stopped this issue?
> > Also, are you sure deleting package manager would not mess up the dependencies and other required stuff?
> 
> Firstly answer the deleting package manager question, i think package manager is a help tool(plugin) for you to download the right version libs into your unity project. it reads all prepared xxxxxDependencies.xmls(by other plugins what need) in your project, resolves conflicts and downloads them all. If you remove package manager, you just lose the automatic resolving function, not making your project broken.
> Anyway, BACKUP YOUR PROJECTS BEFORE you do somethings what you never done BEFORE.
> 
> the way i imported admob is as following pics shown:
> ![new package manager(1)](https://user-images.githubusercontent.com/19384188/114310664-12b35980-9b1e-11eb-8a32-f03f5df2d290.png)
> after importing, admob's google package asked me dialogs,
> i just first click "enabled" at upper dialog, then await its doing jobs.
> when it finished, i just click the "text area" right below the "After" Label, then click "Add selected Registries".
> 
> ![new package manager(2)](https://user-images.githubusercontent.com/19384188/114310970-6b372680-9b1f-11eb-8e2d-ed858e2cd6b8.png)
> ok, google want you to upgrade, then i click "Apply".
> 
> ![new package manager(3)](https://user-images.githubusercontent.com/19384188/114311060-cf59ea80-9b1f-11eb-85f5-2beecf54b61f.png)
> you will see the the folder "External Dependency Manager" underneath Asset folder went down the below of folder "Packages".
> 
> you done.
> 
> **And the errata is here. once you get this done, then you import another plugin(ex. FB Audiencd Network) include another old package manager without excluding the old one. your manager might go mad and give you wrong version libs.**
> ![new package manager(4)](https://user-images.githubusercontent.com/19384188/114311416-3b891e00-9b21-11eb-882a-27b13bd9af47.png)
> as shown in this pic, you got additional old package manager "PlayServiceResolver" in Asset folder, and wrong libs in Plugins/Android folder.

Thank you so much.

**Comment by DacNV95** [comment] 2021-04-26 02:14
> > > > > > solved. It is basically a package versioning problem. admob unity 5.4.0 uses play-service 19.5.0 and old google package managers have a bug on solving it, always grab the latest play-service 20.0.0. Donot use and delete other google package managers included in other unitypackages. Just use the one included in admob unity 5.4.0.
> > > > > > (https://user-images.githubusercontent.com/19384188/114303841-b3941b80-9b02-11eb-91bf-0967f945e694.png)
> > > > > 
> > > > > 
> > > > > I have done as you said (force resolving and checking packages version) and the issue is still there. The crash happens when ever I try to request for a new rewarded video ad. The play-service plugin version is 20.0.0
> > > > 
> > > > 
> > > > i think the simplest solution is replace these play services by hand, if you just had this problem only.
> > > > Also, remove the package manager to stop it from resolving wrong version automatically.
> > > 
> > > 
> > > Could you please mention what you have done exactly that you stopped this issue?
> > > Also, are you sure deleting package manager would not mess up the dependencies and other required stuff?
> > 
> > 
> > Firstly answer the deleting package manager question, i think package manager is a help tool(plugin) for you to download the right version libs into your unity project. it reads all prepared xxxxxDependencies.xmls(by other plugins what need) in your project, resolves conflicts and downloads them all. If you remove package manager, you just lose the automatic resolving function, not making your project broken.
> > Anyway, BACKUP YOUR PROJECTS BEFORE you do somethings what you never done BEFORE.
> > the way i imported admob is as following pics shown:
> > ![new package manager(1)](https://user-images.githubusercontent.com/19384188/114310664-12b35980-9b1e-11eb-8a32-f03f5df2d290.png)
> > after importing, admob's google package asked me dialogs,
> > i just first click "enabled" at upper dialog, then await its doing jobs.
> > when it finished, i just click the "text area" right below the "After" Label, then click "Add selected Registries".
> > ![new package manager(2)](https://user-images.githubusercontent.com/19384188/114310970-6b372680-9b1f-11eb-8e2d-ed858e2cd6b8.png)
> > ok, google want you to upgrade, then i click "Apply".
> > ![new package manager(3)](https://user-images.githubusercontent.com/19384188/114311060-cf59ea80-9b1f-11eb-85f5-2beecf54b61f.png)
> > you will see the the folder "External Dependency Manager" underneath Asset folder went down the below of folder "Packages".
> > you done.
> > **And the errata is here. once you get this done, then you import another plugin(ex. FB Audiencd Network) include another old package manager without excluding the old one. your manager might go mad and give you wrong version libs.**
> > ![new package manager(4)](https://user-images.githubusercontent.com/19384188/114311416-3b891e00-9b21-11eb-882a-27b13bd9af47.png)
> > as shown in this pic, you got additional old package manager "PlayServiceResolver" in Asset folder, and wrong libs in Plugins/Android folder.
> 
> Thank you so much.

You just need to check the custom main gradle, the libraries will be configured by you in the gradle file, not needing to depend on PlayServiceResolver to automatically resolve for you.
![ads2](https://user-images.githubusercontent.com/54349466/116020050-bac53880-a66f-11eb-8efe-a0f010acbdb0.PNG)
![ads1](https://user-images.githubusercontent.com/54349466/116020055-bbf66580-a66f-11eb-8d3c-441a16bf9780.PNG)

**Comment by jasons-codes** [comment] 2021-04-26 06:25
In my project, many build errors appear when applying mainTemplate.gradle.

I think the goal of Unity is simplicity.

However, it seems that the more temporary settings are applied in Unity to avoid SDK issues, the more complex it is than using Android Studio and there are too many build errors. Like twisted spaghetti.

**Comment by jasons-codes** [comment] 2021-04-26 10:31
I want to use com.google.android.gms.play-services-ads-19.5.0.

So I put com.google.android.gms.play-services-ads-20.0.0 in the trash and tried to build with com.google.android.gms.play-services-ads-19.5.0.

The result is that at build time, the External Dependency Manager regenerates com.google.android.gms.play-services-ads-20.0.0 and generates a build error.

The best thing is to solve the dependency problem automatically by the External Dependency Manager, but it doesn't work as it should now.

It's hopeless. My production Unity project has a lot of SDKs installed and the dependencies are complex, so putting in a custom gradle is quite an adventure, and modifying one keeps causing problems elsewhere.

When will this issue be officially resolved?

Currently, the combination of GoogleMobileAds-v5.4.0.unitypackage + audience-network-unity-sdk-6.3.0.unitypackage is 100% buggy. At this point in time, it seems likely that many developers who have updated to the latest version to apply mediation and FB open tenders may face the problem.

Therefore, I hope that it will be resolved as soon as possible.

**Comment by TarmoJussila** [comment] 2021-04-26 15:22
Any updates on this? We're facing the same problem. Have you had any luck with downgrading the Facebook Audience Network, or this that unadvisable?

**Comment by mdobele** [comment] 2021-04-27 02:01
We're using latest FB Adapter which gave us v6.2.0.1 of their SDK along with Admob 5.4.0.  We manually downgraded the required play-services files to the 19.7.0 version (Since 20 doesn't work) and are able to build / get adverts fine with them.  We've had no issues with our Open Bidding setup on either.  Using Unity 2020.2.1f1 at the moment.  

![AdmobFiles](https://user-images.githubusercontent.com/46547272/116173346-bff9b480-a74f-11eb-84f8-adefa0e8fa40.PNG)

**Comment by jasons-codes** [comment] 2021-04-27 04:09
I don't solve the problem.

The plugins in use are as follows.
![image](https://user-images.githubusercontent.com/46530730/116183783-862dab80-a759-11eb-9616-e2deeeaf7f69.png)

I prepared com.google.android.gms.play-services-ads-19.7.0 in advance and installed it in the Assets/Plugins/Android folder.
![image](https://user-images.githubusercontent.com/46530730/116183793-8b8af600-a759-11eb-944d-8927c8680841.png)
![image](https://user-images.githubusercontent.com/46530730/116183794-8e85e680-a759-11eb-9c75-132067d35b63.png)

The dependencies are also as follows.
![image](https://user-images.githubusercontent.com/46530730/116183821-9ba2d580-a759-11eb-973c-450150d0d395.png)
![image](https://user-images.githubusercontent.com/46530730/116183873-b70de080-a759-11eb-9a02-b7b6b66ff2eb.png)
![image](https://user-images.githubusercontent.com/46530730/116183807-96458b00-a759-11eb-987d-4279af92a79c.png)

The actual result is that instead of com.facebook.android.audience-network-sdk-6.2.0, com.facebook.android.audience-network-sdk-6.4.0 is installed, and the play-services-ads libraries are duplicated.
![image](https://user-images.githubusercontent.com/46530730/116183905-c7be5680-a759-11eb-8456-1af16d517244.png)

**Comment by jasons-codes** [comment] 2021-04-27 10:20
Even if I tried with audience-network-unity-sdk-6.2.1.unitypackage, the problem was the same.

Next, I turned off the'Enable Resolution On Build' option in the Android setting of the External Dependency Manager, and then placed the play-services-ads library in the Assets/Plugins/Android folder without duplicates. (Try both versions 19.7.0 and 19.5.0)

Finally, AdMob ad loading succeeded, but the mediation test suite crashes. (Crash both versions 19.7.0 and 19.5.0)

I am worried if it can be applied to my service project as it is.

**Comment by aceloq** [comment] 2021-04-27 11:11
Same Problem. I think Google Mobile Ads Unity Plugin should be updated and compatible with Play-Services-20.0.0 version.

https://groups.google.com/g/google-admob-ads-sdk/c/auTJZ7dWdZs/m/GuqGEb_EAgAJ

**Comment by mohammaddabiri** [comment] 2021-04-27 11:27
I believe unity support for 20.0.0 will be coming soon. Since we currently only use rewarded ads we ended up reworking the `RewardedAdClient` to target the new API ourselves to get around the issue.

**Comment by aceloq** [comment] 2021-04-27 11:48
> I believe unity support for 20.0.0 will be coming soon. Since we currently only use rewarded ads we ended up reworking the `RewardedAdClient` to target the new API ourselves to get around the issue.

I'm afraid not. They don't think there is such a problem

**Comment by TarmoJussila** [comment] 2021-04-27 14:03
We were able to work around this issue by using the tips by @mdobele. So manually downgrading play services .aar files to 19.7.0 instead of 20.0.0. Also had to disable "Auto resolve on build" feature to avoid automatically resolving back to 20.0.0.

For us the 20.0.0 files with AdMob 5.4.0 totally crashed the app when attempting to initialize RewardedAd:s. So hopefully this will be resolved in an upcoming AdMob update, so we can use the resolve feature again.

**Comment by adbourdages** [comment] 2021-04-27 17:51
Similarly to others, I was able to get the game working again by disabling "auto-resolve on build" (don't forget to save, the button is not visible without scrolling). Then I restored the following files from source control to replace the 20.0.0 version in the Plugin/Android folder:
- com.google.android.gms.play-services-gass-19.8.0.aar
- com.google.android.gms.play-services-ads-19.8.0.aar
- com.google.android.gms.play-services-ads-base-19.8.0.aar
- com.google.android.gms.play-services-ads-lite-19.8.0.aar

Those 4 files were enough to prevent the crash and still get admod ads, admob mediation, facebook ads and play games services to work.

**Comment by jasons-codes** [comment] 2021-04-28 14:01
AdMob works unless it is com.google.android.gms.play-services-ads-20.0.0.aar.

But in my case, when I run the Mediation Test suite, I get this crash.
- java.lang.IllegalStateException: MobileAds.initialize() must be called prior to getting initialization status.
![image](https://user-images.githubusercontent.com/46530730/116414202-3d6a1580-a873-11eb-93d5-dda1596d6735.png)

The plugin I used is:
- GoogleMobileAds-v5.4.0.unitypackage
- GoogleMobileAdsMediationTestSuite.unitypackage
- GoogleMobileAdsFacebookMediation-3.2.0.zip/GoogleMobileAdsFacebookMediation.unitypackage
- (And firebase 7.0.2)
![image](https://user-images.githubusercontent.com/46530730/116411449-b156ee80-a870-11eb-87ed-5a76d300fed3.png)
![image](https://user-images.githubusercontent.com/46530730/116411550-c9c70900-a870-11eb-8efe-11602dc0fd56.png)


If I remove GoogleMobileAdsFacebookMediation-3.2.0 and run Mediation Test Suite with the combination below, then it works.
- GoogleMobileAds-v5.4.0.unitypackage
- GoogleMobileAdsMediationTestSuite.unitypackage
- (And firebase 7.0.2)

The result is as follows because the FAN plug-in is missing.
![image](https://user-images.githubusercontent.com/46530730/116416308-32b08000-a875-11eb-94ad-75a6706b2357.png)
![image](https://user-images.githubusercontent.com/46530730/116416254-29bfae80-a875-11eb-84c4-2366e63ecc3f.png)

The point is that when importing GoogleMobileAdsFacebookMediation-3.2.0 in GoogleMobileAds-v5.4.0 environment, Mediation Test Suite does not work. I don't know why.

Additionally, the build process also becomes spaghetti at this time.
It is required to remove com.google.android.gms.play-services-ads-20.0.0.aar created by External Dependency Manager and place one of the following 3 versions in the Assets/Plugins/Android folder.

- play-services-ads-19.5.0
![image](https://user-images.githubusercontent.com/46530730/116413188-5a521900-a872-11eb-9d53-d333df46640b.png)
![image](https://user-images.githubusercontent.com/46530730/116413842-eebc7b80-a872-11eb-8115-64881c7ff986.png)

- play-services-ads-19.7.0
![image](https://user-images.githubusercontent.com/46530730/116413363-81a8e600-a872-11eb-93a1-e64b2fa9d997.png)
![image](https://user-images.githubusercontent.com/46530730/116413706-d5b3ca80-a872-11eb-9dea-a9923d00f1d8.png)

- play-services-ads-19.8.0
![image](https://user-images.githubusercontent.com/46530730/116413469-9b4a2d80-a872-11eb-9046-b53543ca3e65.png)
![image](https://user-images.githubusercontent.com/46530730/116413546-b5840b80-a872-11eb-9c23-f8bf55965560.png)

I've tested all of these, but they all get crashes in the Mediation Test Suite.

And in my case, the External Dependency Manager creates com.facebook.android.audience-network-sdk-6.3.0 and com.google.ads.mediation.facebook-6.3.0.1.

**Comment by y0rshl** [comment] 2021-05-06 15:45
Same issue here. Resolver adds services-ads-20.0 and it isn't compatible with 5.4.0.
Adding 19.8 manually fixes the issue. Fixing this should be a top priority of Admob so continue bumping this until someone from Admob officialy responds.

**Comment by ali-pjx** [comment] 2021-05-15 10:54
@y0rshl @adbourdages @mohammaddabiri @TarmoJussila @aceloq 

Seems like this issue is reproduced again but now with gms version **20.1**. When I saw the update, I thought that finally, they have decided to update the gms in order to finish this madness. But it seems like AdMob does not care a bit about their customers. 

We are being forced to change our mobile advertising platform when this issue is not being handled by AdMob.

**Comment by ericleich** [comment] 2021-06-24 21:51
The Unity plugin version 6.0.0 has been updated for Google Mobile Ads Android SDK 20.x.x and Google Mobile Ads iOS SDK 8.x.x. I recommend getting 6.0.1 at this point.

**Closed by ericleich** 2021-06-24 21:51 UTC

**Comment by mohammadmahdi123** [comment] 2022-03-12 10:50
I get this error when requesting a rewarded video then crashing.
It is initialized successfully.

Unity: 2019.4
Platform: Android
GoogleMobileAds-native.unitypackage: Latest
Google Mobile Games: 0.10.12, 0.10.14

2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime java.lang.InstantiationError: com.google.android.gms.ads.rewarded.RewardedAd
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at com.google.unity.ads.UnityRewardedAd$1.run(UnityRewardedAd.java:53)
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:808)
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:101)
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:166)
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:7529)
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
2022/03/11 21:44:42.128 19921 19921 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

MainTemplate.gradle

dependencies {
    implementation 'ir.tapsell.plus:tapsell-plus-sdk-unity:2.1.6'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
// Android Resolver Dependencies Start
    implementation 'com.google.ads.mediation:chartboost:8.3.0.0' // Assets/GoogleMobileAds/Editor/ChartboostMediationDependencies.xml:8
    implementation 'com.google.ads.mediation:vungle:6.10.3.0' // Assets/GoogleMobileAds/Editor/VungleMediationDependencies.xml:8
    implementation 'com.google.android.gms:play-services-ads:18.3.0' // Assets/PlayServicesResolver/Editor/DeemaunityDependencies.xml:7
    implementation 'com.google.android.gms:play-services-ads:19.5.0' // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
    implementation 'com.google.android.gms:play-services-base:17.6.0' // Assets/Firebase/Editor/AppDependencies.xml:17
    implementation 'com.google.code.gson:gson:2.8.5' // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:13
    implementation 'com.google.firebase:firebase-analytics:19.0.0' // Assets/Firebase/Editor/MessagingDependencies.xml:15
    implementation 'com.google.firebase:firebase-analytics-unity:8.0.0' // Assets/Firebase/Editor/AnalyticsDependencies.xml:18
    implementation 'com.google.firebase:firebase-app-unity:8.0.0' // Assets/Firebase/Editor/AppDependencies.xml:22
    implementation 'com.google.firebase:firebase-common:20.0.0' // Assets/Firebase/Editor/AppDependencies.xml:13
    implementation 'com.google.firebase:firebase-messaging:22.0.0' // Assets/Firebase/Editor/MessagingDependencies.xml:13
    implementation 'com.google.firebase:firebase-messaging-unity:8.0.0' // Assets/Firebase/Editor/MessagingDependencies.xml:20
    implementation 'com.google.games:gpgs-plugin-support:0.10.12' // Assets/GooglePlayGames/Editor/GooglePlayGamesPluginDependencies.xml:11
    implementation 'com.squareup.okhttp3:okhttp:3.12.0' // Assets/PlayServicesResolver/Editor/DeemaunityDependencies.xml:9
    implementation 'com.squareup.okio:okio:2.4.1' // Assets/PlayServicesResolver/Editor/DeemaunityDependencies.xml:11
// Android Resolver Dependencies End
**DEPS**}
