### ISSUE TITLE
Version 3.14.0 does not import .aar files

### ISSUE THREAD

**Issue by RafaelC2** [googleads/googleads-mobile-unity#735] opened 2018-07-27 13:47 UTC
Versions 3.15.0 and 3.13.1 work well here, but for some reason version 3.14.0 does not seem to be importing .aar files.

**Comment by rampara** [comment] 2018-07-27 17:39
@RafaelC2 might be due to a bug for with a specific version of Play Services Resolver included in v3.14.0. However, I'm not able to reproduce the issue. Closing the issue as it doesn't seem to be a problem in the latest release of the plugin. Please re-open if it is.

**Closed** 2018-07-27 17:40 UTC
Labels: P2, support question
