### ISSUE TITLE
Crash while adding AdColonyMediationExtras

### ISSUE THREAD

**Issue by OniTheC4t** [googleads/googleads-mobile-unity#739] opened 2018-07-31 08:50 UTC
The app crash on android when calling RewardBasedVideoAdClient.LoadAd with AdColonyMediationExtras and GDPR parameters.

GoogleMobileAdsAdColonyMediation-1.0.2
Google Mobile Ads Unity Plugin v3.15.0

> 07-30 13:51:01.786: E/CRASH(19517): backtrace:
07-30 13:51:02.006: E/CRASH(19517): 	#00  pc 00011464  /system/lib/libc.so (strlen+83)
07-30 13:51:02.006: E/CRASH(19517): 	#01  pc 00120f3c  /data/app/com.WhatWapp.BeloteLeDefi-1/lib/arm/libunity.so
07-30 13:51:02.006: E/CRASH(19517): 	#02  pc 00126c48  /data/app/com.WhatWapp.BeloteLeDefi-1/lib/arm/libunity.so
07-30 13:51:02.006: E/CRASH(19517): 	#03  pc 0000e024   ( (wrapper managed-to-native) UnityEngine.AndroidJNI:CallStringMethod (intptr,intptr,UnityEngine.jvalue[]) + 0x4c (0x9da14fd8 0x9da15068) [0xaff38ee0 - Unity Root Domain]+57380)
07-30 13:51:02.006: E/CRASH(19517): 	#04  il ........  at (wrapper managed-to-native) UnityEngine.AndroidJNI.CallStringMethod (intptr,intptr,UnityEngine.jvalue[]) <0xffffffff>
07-30 13:51:02.006: E/CRASH(19517): 	#05  il 0000002c  at UnityEngine.AndroidJNISafe.CallStringMethod (intptr,intptr,UnityEngine.jvalue[]) <0x0002c>
07-30 13:51:02.006: E/CRASH(19517): 	#06  il 0000042b  at UnityEngine.AndroidJavaObject._Call<object> (string,object[]) <0x0042b>
07-30 13:51:02.006: E/CRASH(19517): 	#07  il 0000003b  at UnityEngine.AndroidJavaObject.Call<object> (string,object[]) <0x0003b>
07-30 13:51:02.006: E/CRASH(19517): 	#08  il 00000b53  at GoogleMobileAds.Android.Utils.GetAdRequestJavaObject (GoogleMobileAds.Api.AdRequest) <0x00b53>
07-30 13:51:02.006: E/CRASH(19517): 	#09  il 00000047  at GoogleMobileAds.Android.RewardBasedVideoAdClient.LoadAd (GoogleMobileAds.Api.AdRequest,string) <0x00047>
07-30 13:51:02.006: E/CRASH(19517): 	#10  il 0000003f  at GoogleMobileAds.Api.RewardBasedVideoAd.LoadAd (GoogleMobileAds.Api.AdRequest,string) <0x0003f>

**Comment by rampara** [comment] 2018-07-31 22:44
Assigning to joshuajplagonera to investigate.

**Comment by AC002** [comment] 2018-08-20 06:07
Same problem here but with Vungle, sadly it needs mediation extras to even work.

**Comment by Check2016** [comment] 2018-08-29 12:39
I got the same error in Unity 2018.2.5f1 when adding Vungle extras. I found out that this likely is a Unity3d bug caused by an AndroidJavaObject call that returns null (In the plugin probably: GoogleMobileAds.Android.Utils line: 189 with a call to map.put)
Unity Issue: https://issuetracker.unity3d.com/issues/android-application-crashes-when-native-function-returns-null
They say it is fixed "in a future release".

**Comment by rampara** [comment] 2018-08-31 19:38
This issue should be resolved on the latest version of this plugin (3.15.1).

**Closed by rampara** 2018-08-31 19:38 UTC
Labels: P2, plugin bug
