### ISSUE TITLE
AdMob smart banner not centered

### ISSUE THREAD

**Issue by Mitnainartinarian** [googleads/googleads-mobile-unity#744] opened 2018-08-13 18:53 UTC
My smart banners are not properly centered on one of my test devices. It's a Galaxy S6 (SM-G920W8) running Android 6.0.1. I'm using Unity 2018.1.6f1. The attached screenshot shows an example. On my other devices they are properly centered. They are a Galaxy S6 with Android 5.1.1 and a Galaxy S7 with Android 7.0.0 (I no longer have the S7, but it was working fine in the past). This is a problem I've had a while including on previous version of the AdMob SDK, but haven't had time to look into it until now.

![screenshot_20180813-135307](https://user-images.githubusercontent.com/19413426/44048725-382a49f2-9f00-11e8-95df-2023ccec785d.png)

I'm creating the banner ad like below:

`new BannerView(unitId, AdSize.SmartBanner, AdPosition.Top);`

I've also tried it in portrait orientation and have the same problem, and both test and non-test ads are not centered. If I make the position AdPosition.Bottom I have the same problem.

I'm using AdMob Unity SDK 3.15.0.

**Comment by rampara** [comment] 2018-09-06 22:47
Closing as duplicate of #749.

**Closed by rampara** 2018-09-06 22:47 UTC
