### ISSUE TITLE
Crash native ads express on IOS when have no internet connection

### ISSUE THREAD

**Issue by longvannguyendx** [googleads/googleads-mobile-unity#278] opened 2016-09-29 08:38 UTC
Game is broken when I'm using the native ad express with have no internet connection. 
Note: 
 -I'm using the latest version (Plugin version 3.0.7, Sdk for iOS 7.11.0).
 -This bug occurs on IOS only, I also tested on android and It's woking ok.

I attached the log, please see log for more detail. (I also attached my implement , please focus into  LoadNativeAd function which I implemented)
[Admob.txt](https://github.com/googleads/googleads-mobile-unity/files/500145/Admob.txt)

[Log.pdf](https://github.com/googleads/googleads-mobile-unity/files/500121/Log.pdf)

**Comment by rampara** [comment] 2016-10-05 23:17
I'm having trouble reproducing this error with in both airplane mode and on a simulated wifi network with impaired connectivity. I'm also not seeing anything that ties crash log you posted to this plugin or the GMA SDK. It also seems like you're integrating Unity Ads in your application. Are you able to reproduce the crash on the stripped on [sample application](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) from this repo?

**Comment by at-longnv** [comment] 2016-10-31 08:04
I tested again, and this issue still occurs. Please turn off wifi, (Note: If wifi is on but can not connect internet --> this bug don't occur.), after that, launch game and you will see this issue.

**Comment by at-longnv** [comment] 2016-11-04 02:34
Hi
     Did you check this issue and any update for this?
Thanks.

**Comment by rampara** [comment] 2016-11-04 21:42
Still am unable to reproduce this crash in the following scenarios:

- Airplane mode on
- Airplane mode off, wifi off

Are you able to reproduce the crash in this [native express sample app](https://github.com/googleads/googleads-mobile-ios-examples/tree/master/Objective-C/admob/NativeExpressExample)?

**Comment by at-longnv** [comment] 2016-11-05 06:10
Hello,
    
   I found the reason for this issue.
   You have to register for native ad events. , if no, when you launch  the game without wifi, your app will be crashed.
I tested with native express sample app:
Step 1:  skip register for native ad events.
 // Register for ad events.
//        this.nativeExpressAdView.OnAdLoaded += this.HandleNativeExpressAdLoaded;
//        this.nativeExpressAdView.OnAdFailedToLoad += this.HandleNativeExpresseAdFailedToLoad;
//        this.nativeExpressAdView.OnAdLoaded += this.HandleNativeExpressAdOpened;
//        this.nativeExpressAdView.OnAdClosed += this.HandleNativeExpressAdClosed;
//        this.nativeExpressAdView.OnAdLeavingApplication += this.HandleNativeExpressAdLeftApplication;
Step 2: Build and run ios project.
Step 3: Touch on "Request Native Express Ad" ==> Your app will be crashed.
![untitled](https://cloud.githubusercontent.com/assets/16132364/20028049/469a7150-a359-11e6-9660-ba5bddad9e12.png)
Thanks.

**Comment by rampara** [comment] 2016-11-07 19:45
@at-longnv is this issue still present for you on v3.1.1 of the plugin?

**Comment by rampara** [comment] 2016-11-07 21:16
Was able to finally reproduce this issue. Will be pushing a fix shortly.

**Comment by rampara** [comment] 2016-11-08 00:04
This issue has been fixed in the latest version of the plugin (3.1.2).

**Closed by rampara** 2016-11-08 00:04 UTC
Labels: support question
