### ISSUE TITLE
OnAdClosed and OnAdRewarded are sometimes called twice in a row.

### ISSUE THREAD

**Issue by icyh4mmer** [googleads/googleads-mobile-unity#396] opened 2017-04-10 09:06 UTC
Sometimes it happens that OnAdClosed and OnAdRewarded events are called twice in a row. Is this a plugin bug or am I missing something?

**Comment by rampara** [comment] 2017-04-10 18:26
The ad events should only be invoked once for an single ad. Is this issue consistently reproducible for you? Are you deploying to Android or iOS? Which version of the GMA SDK are you using?

**Comment by icyh4mmer** [comment] 2017-04-11 08:40
We haven't find a way to reproduce ti yet, it happens mabe once or twice every 100 video watches. We are only deploying to android atm. Regarding the version, is there any way I could check that up? I'd guess that I've updated this plugin around 2 months ago and I didn't see any fix regarding that in the latest commits.

**Comment by rampara** [comment] 2017-04-11 18:13
The version of the plugin can be found in the `AdRequest` class, located at `Assets/GoogleMobileAds/Api` of your Unity project. The version of the Android GMA Ads SDK can be determined by looking in the `Assets/Plugins/Android` directory of your Unity project to see which version of Play Services AARs are being used. iOS builds should be pulling in the latest version of the iOS GMA SDK via Cocoapods when generating the Xcode project from Unity.

Also, are you using mediation for rewarded video as well or are all ads strictly from AdMob?

**Comment by icyh4mmer** [comment] 2017-04-13 08:16
Version in AdRequest class: Version = "3.2.0"
AAR version: 10.0.1

I am using mediation for rewarded video; Unity, Vungle, Chartboost, Applovin and default AdMob.

**Comment by rampara** [comment] 2017-04-14 00:32
@icyh4mmer Narrowing down which ad network returned the ad which is causing the issue for you would help figure out the cause of the issue.

**Comment by icyh4mmer** [comment] 2017-04-14 16:58
If I manage to reproduce the issue on specific provider I'll let you know.

**Comment by rampara** [comment] 2017-04-14 23:08
@icyh4mmer I'm having trouble reproducing the issue on my end so I'll wait till you get back to me.

**Comment by rampara** [comment] 2017-05-31 17:55
Closing this issue due to non-response. If this issue persists for you, please re-open it.

**Closed by rampara** 2017-05-31 17:55 UTC
Labels: support question
