### ISSUE TITLE
AdMob fails when setting Managed Stripped Level to medium or high.

### ISSUE THREAD

**Issue by ColorTwist** [googleads/googleads-mobile-unity#832] opened 2019-01-19 15:03 UTC
While all other plugins work fine, like FireBase, Facebook SDK, etc.
It does work when setting "Managed Stripped level " too low or disabled.
I am a bit size fanatic, it would be nice to have it work with higher stripping level as many other plugins does.
Note that I use Unity 2018.3.2f
Stripping did work with AdMob with 2018.2.18, but in 2018.2 it was a bit different (you do not select low, medium, or high, but methods)

The line that fails is:
   `MobileAds.Initialize(appId);`

With the error: _

> "NullReferenceException: Object reference not set to an instance of an object"

_

**Comment by rampara** [comment] 2019-01-23 03:08
@ColorTwist this may be due to reflection used in this plugin. Does using the [Preserve attribute](https://docs.unity3d.com/Manual/ManagedCodeStripping.html)
 for the GMA Unity plugin classes resolve the issue?

**Comment by ColorTwist** [comment] 2019-01-23 06:36
Thanks for the reply.

I read about Preserve Attributes from the link you provided. 
Was not totally certain how to use it with GMA plugin.

I placed the following before unity `Start()` where I initialize GMA `MobileAds.Initialize(appId);` which fails.

```
  [UnityEngine.Scripting.Preserve]
    public void Start()
    {
 //Code
  MobileAds.Initialize(appId);
 //Code
}
```

Still the same error.

**Comment by rampara** [comment] 2019-01-23 21:17
Can you try inserting `[type: Preserve]` at the top of GMA classes?

**Comment by RolandSzep** [comment] 2019-02-11 15:33
I am experiencing the same issue. I will try out your advice when I have some time.

**Comment by ColorTwist** [comment] 2019-02-12 13:19
From what I tried it did not work, but maybe I missed something.
@RolandSzep Please try it also & update.

**Comment by junedmmn** [comment] 2019-02-13 14:39
I am setting stripping level to Low. It gives Size approximately equal to highest stripping level for my project.

**Comment by ColorTwist** [comment] 2019-02-26 06:21
Tried 
```
  [type: Preserve]
    public class MobileAds
    {
//code
}
```

Still getting:

>  NullReferenceException: Object reference not set to an instance of an object
> 02-26 08:09:34.131  4431  4515 E Unity   :   at GoogleMobileAds.Api.MobileAds.GetMobileAdsClient () [0x00016] in <7e1d88abf8084941a4370ec2fc9ebe72>:0
> 02-26 08:09:34.131  4431  4515 E Unity   :   at GoogleMobileAds.Api.MobileAds..cctor () [0x00000] in <7e1d88abf8084941a4370ec2fc9ebe72>:0
> 02-26 08:09:34.131  4431  4515 E Unity   : Rethrow as TypeInitializationException: The type initializer for 'GoogleMobileAds.Api.MobileAds' threw an exception.
> 02-26 08:09:34.131  4431  4515 E Unity   :   at AdMobController.InitAdMob () [0x0001b] in <7e1d88abf8084941a4370ec2fc9ebe72>:0
> 02-26 08:09:34.131  4431  4515 E Unity   :   at AdMobController.Start () [0x00000] in <7e1d88abf8084941a4370ec2fc9ebe72>:0


Where exactly to place the `Preserve`?

**Comment by UragayalaDeepika** [comment] 2019-10-10 20:37
@ColorTwist Hello, 

Do you still have this issue with the latest plugin? Can you please let us know?

**Comment by ColorTwist** [comment] 2019-10-11 08:21
It seems to be solved! It is supposed to be solved, right?
Tested on:
Unity: 2019.1.11
AdMob: v4.0.0
Stripping level: Medium and High

**Comment by UragayalaDeepika** [comment] 2019-10-15 18:32
@ColorTwist Glad to hear that. We are closing this thread as the issue seems to be resolved with the latest plugin.

**Closed by UragayalaDeepika** 2019-10-15 18:32 UTC
Labels: P2, support question

**Comment by Arrnav** [comment] 2019-10-20 15:29
The issue is still not resolved for me when using the early access SDK because I'm using Adaptive banner ads.

This is where I obtained the SDK from - https://developers.google.com/admob/unity/early-access/adaptive-banners

Unity: 2019.2.9f1, Android
AdMob: Early Access SDK obtained from above guide link (I assume this should be updated as much as the v4.0.0?)
Stripping level: Medium or High

Adding Preserve attribute to any GMA related class does nothing. Still throws the null reference error.

Turning down to "Low" stripping level is not an option as the minor reduction in size matters to me.

Please help.
