### ISSUE TITLE
Rewarded Video Ad showing test video ad on second time in Unity Plugin 

### ISSUE THREAD

**Issue by Brijesh-kumar-Vaishya** [googleads/googleads-mobile-unity#684] opened 2018-06-04 05:53 UTC
Hello Connections

In my unity project is used admob rewareded video ad for showing add two time (different ad with same adUnitId).

First time it works fine but second time it shows test rewarded video ad.

issue is showing test ad on second time.

Thanks 
Brijesh Kumar Vaishya

**Comment by rampara** [comment] 2018-06-25 10:37
@Brijesh-kumar-Vaishya are you experiencing this issue on Android or iOS? Are you able to consistently reproduce the issue? Are you registering your device as a test device?

**Comment by rampara** [comment] 2018-09-06 22:43
Closing issue due to non-response.

**Closed by rampara** 2018-09-06 22:43 UTC
Labels: P2, support question
