### ISSUE TITLE
Interstitial Ad "Timed out waiting for WebView to finish loading."

### ISSUE THREAD

**Issue by drostar** [googleads/googleads-mobile-unity#184] opened 2016-03-11 15:32 UTC
I'm using the latest version of this plugin and sample test program (3.0.2) to test interstitial ads on a Nexus 7 (2012). The android program was built using Unity 5.3.3p1. At first loading and displaying ads works fine. But if I leave the device sleep for a while with the app loaded (a few hours, or maybe overnight for good measure), when I come back, interstitial ads won't load and instead just spit out this error in logcat. Below is the relevant logs. The "Interstitial is not ready yet" message is from me clicking the "Show Interstitial" button on screen. If I kill the app and open it again, interstitial ads work again (for a while).

03-11 09:14:20.928: D/DynamitePackage(27018): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
03-11 09:14:21.158: I/Ads(27018): Starting ad request.
03-11 09:14:21.618: I/ConfigService(21505): onCreate
03-11 09:14:23.068: D/dalvikvm(21520): GC_CONCURRENT freed 1136K, 13% free 10837K/12432K, paused 10ms+7ms, total 99ms
03-11 09:14:23.068: D/dalvikvm(21520): WAIT_FOR_CONCURRENT_GC blocked 36ms
03-11 09:14:23.068: E/DataBuffer(21520): Internal data leak within a DataBuffer object detected!  Be sure to explicitly call release() on all DataBuffer extending objects when you are done with them. (internal object: com.google.android.gms.common.data.DataHolder@423e7860)
03-11 09:14:26.708: I/ConfigService(21505): onDestroy
03-11 09:14:34.648: I/Unity(27018): Interstitial is not ready yet.
03-11 09:14:34.648: I/Unity(27018): UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
03-11 09:14:34.648: I/Unity(27018): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
03-11 09:14:34.648: I/Unity(27018): UnityEngine.Logger:Log(LogType, Object)
03-11 09:14:34.648: I/Unity(27018): UnityEngine.Debug:Log(Object)
03-11 09:14:34.648: I/Unity(27018): UnityEngine.MonoBehaviour:print(Object) (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineMonoBehaviourBindings.gen.cs:106)
03-11 09:14:34.648: I/Unity(27018): GoogleMobileAdsDemoScript:ShowInterstitial() (at C:\Users\Matthew\Documents\Unity Projects\External\AdMob Intersitital Bug Repro\Assets\Example\GoogleMobileAdsDemoScript.cs:225)
03-11 09:14:34.648: I/Unity(27018): GoogleMobileAdsDemoScript:OnGUI() (at C:\Users\Matthew\Documents\Unity Projects\External\AdMob Intersitital Bug Repro\Assets\Example\GoogleMobileAdsDemoScript.cs:122)
03-11 09:14:34.648: I/Unity(27018):  
03-11 09:14:34.648: I/Unity(27018): (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineMonoBehaviourBindings.gen.cs Line: 106)
03-11 09:15:14.678: D/dalvikvm(27018): GC_FOR_ALLOC freed 499K, 7% free 8401K/8992K, paused 139ms, total 140ms
03-11 09:15:23.348: E/Ads(27018): Timed out waiting for WebView to finish loading.
03-11 09:15:23.408: E/Ads(27018): JS: Uncaught ReferenceError: AFMA_ReceiveMessage is not defined (null:1)
03-11 09:15:23.408: E/Web Console(27018): Uncaught ReferenceError: AFMA_ReceiveMessage is not defined at null:1

**Comment by rampara** [comment] 2016-03-15 18:33
Can you elaborate on the steps to reproduce this error?

1. Request interstitial
2. Display interstitial
3. Leave app open overnight.
4. Request interstitial.
5. Requests fail (?)

If the above is correct, can you provide the error reason provided in the onAdFailedToLoad callback. A Charles log of the ad request that fails would also be helpful.

**Comment by drostar** [comment] 2016-03-15 20:12
Yes, those are the steps. But onAdFailedToLoad isn't even being called when it fails. And to clarify "3. Leave app open" means the app seems to just need to remain in memory. I can be minimized the app first and then turn off the screen or I can leave the app in the foreground when I turn off the screen. I should also note that the app is being built with "Development Build" checked off in Unity build settings.

It may actually be a bug in Unity because I don't seem to have this problem when I build with Unity 5.2.4f1. I'll see if I can get a Charles log of it happening.

**Comment by drostar** [comment] 2016-03-16 15:41
A couple more pieces of information:
The Nexus 7 (2012) which I used to produce this error is running Android 4.3.
I also tested on a Nexus 4 running Android 5.1 and can't seem to reproduce the error on it.
So you need just the right combination of device, Android and Unity.

**Comment by drostar** [comment] 2016-03-29 01:34
@rampara Were you able to reproduce this issue?

**Comment by tacohead75** [comment] 2016-05-01 18:44
Did you find out anything more about this problem? I have the same issue with Android 4.2.2 on a Galaxy S4. I do not use Unity in my app.

**Comment by rampara** [comment] 2016-10-10 21:44
@tacohead75 this issue tracker is specific to issues with the Google Mobile Ads Unity plugin. @drostar I'm having trouble reproducing this issue. Does it still persist for you with the latest version of the GMA SDK and plugin?

**Comment by rampara** [comment] 2016-11-30 00:57
Closing this issue due to it's age and non-response. If this issue persists for you, please re-open the issue.

**Closed by rampara** 2016-11-30 00:57 UTC
Labels: support question
