### ISSUE TITLE
Admob rewarded video is restarting Game after finishes on Android.

### ISSUE THREAD

**Issue by TheMostWonderful** [googleads/googleads-mobile-unity#453] opened 2017-06-28 02:42 UTC
Hi all, I have issue with rewarded video with android devices, as soon as rewarded video ends application is getting restarted, it is not happening in ios devices. Can somebody help, below is my code:

using System.Collections;
using System.Collections.Generic;
using System;
using UnityEngine;
using GoogleMobileAds;
using GoogleMobileAds.Api;

public class AdManager : MonoBehaviour {
	
	private GameOver gameOver;
	public RewardBasedVideoAd rewardBasedVideoAd;
	private InterstitialAd fullAdmob;
	//bool isWatched = false;
	private bool rewardBasedEventHandlersSet = false;
	public int scoreAmount = 100;
	// Use this for initialization

	void Start () {
		

		//gameOver = FindObjectOfType<GameOver> ();
		LoadRewardBasedAd ();
		RequestFull ();
	}
	
	// Update is called once per frame
	void Update () {
		
	}

	public void LoadRewardBasedAd (){
		#if UNITY_EDITOR
		string adUnitId = "unused";
		#elif UNITY_ANDROID
		//Production
		//string adUnitId = "ca-app-pub-5630039207485482/7766431653";
		//Test
		string adUnitId = "ca-app-pub-3940256099942544/5224354917";
		#elif UNITY_IPHONE
		string adUnitId = "ca-app-pub-5630039207485482/3674309254";
		#else
		string adUnitId = "unexpected_platform";
		#endif

		rewardBasedVideoAd = RewardBasedVideoAd.Instance;

		//Production
		AdRequest adRequest = new AdRequest.Builder ().Build ();

		//Test
		//AdRequest adRequest = new AdRequest.Builder()
		//.AddTestDevice(AdRequest.TestDeviceSimulator)       // Simulator.
		//.AddTestDevice("c78b1468accb7ee846fa4f8e61bde0ff")  // My test device.
		//.Build();

		//Load ad
		//rewardBasedVideoAd.LoadAd (new AdRequest.Builder ().Build (), adUnitId);
		rewardBasedVideoAd.LoadAd(adRequest, adUnitId);

		if (!rewardBasedEventHandlersSet) {
		rewardBasedVideoAd.OnAdLoaded += HandleOnAdLoaded;
		rewardBasedVideoAd.OnAdFailedToLoad += HandleOnAdFailedToLoad;
		rewardBasedVideoAd.OnAdOpening += HandleOnAdOpening;
		rewardBasedVideoAd.OnAdStarted += HandleOnAdStarted;
		// is closed.
		rewardBasedVideoAd.OnAdClosed += HandleOnAdClosed;
		// has rewarded the user.
		rewardBasedVideoAd.OnAdRewarded += HandleOnAdRewarded;
		// is leaving the application.
		rewardBasedVideoAd.OnAdLeavingApplication += HandleOnAdLeavingApplication;
		rewardBasedEventHandlersSet = true;
		}
	}

		void RequestFull(){
		//Production
		//string idFull = "ca-app-pub-5630039207485482/7545348452";
		//Test
		string idFull = "ca-app-pub-3940256099942544/1033173712";
		fullAdmob = new InterstitialAd (idFull);
		AdRequest adRequest = new AdRequest.Builder ().Build ();
		fullAdmob.LoadAd (adRequest);
		}

		public void HandleOnAdLoaded(object sender, EventArgs args){

		}
		public void HandleOnAdFailedToLoad(object sender, AdFailedToLoadEventArgs args){
		LoadRewardBasedAd ();
		}
		public void HandleOnAdOpening(object sender, EventArgs args){

		}
		public void HandleOnAdStarted(object sender, EventArgs args){

		}
		public void HandleOnAdRewarded (object sender, Reward args){
		LevelManager refs = GameObject.Find ("LevelManager").GetComponent<LevelManager> ();
		refs.IncreaseScore (scoreAmount);

		}
		public void HandleOnAdClosed(object sender, EventArgs args){
		LoadRewardBasedAd ();

		}
		public void HandleOnAdLeavingApplication (object sender,EventArgs args){

		}

		public void ShowRewardBasedAd (){
		if (rewardBasedVideoAd.IsLoaded ()) {
			rewardBasedVideoAd.Show ();

		} else {
			LoadRewardBasedAd ();
		}
	}
		public void ShowFullAds(){
		if (fullAdmob.IsLoaded ()) {
			fullAdmob.Show ();
			RequestFull ();
			}  else {
				RequestFull ();
			}
		}

}

**Comment by rampara** [comment] 2017-06-29 18:30
@TheMostWonderful do you see stack traces in logcat that may indicate what caused the app to restart?

**Comment by TheMostWonderful** [comment] 2017-07-01 00:27
I never user logcat, so I am not sure about it, I am new Unity developer.

**Comment by rampara** [comment] 2017-07-01 00:44
The [Android dev docs](https://developer.android.com/studio/debug/am-logcat.html) provide a pretty good overview of how to use logcat.

**Comment by rampara** [comment] 2017-08-16 00:43
Closing issue due to non-response. Please re-open if this issue persists for you.

**Comment by Akashbhatt111** [comment] 2017-10-02 08:03
please open this issue it happen me too
game restart after admob reward ad finished

**Comment by rampara** [comment] 2017-10-03 18:28
@Akashbhatt111 can you provide logs from the crash?

**Comment by Akashbhatt111** [comment] 2017-10-04 10:26
there is nothing in my logcat that is seems to be cause i think no error at all

**Comment by rampara** [comment] 2017-10-04 17:35
@Akashbhatt111 your app crashes and restarts without any content in logcat indicating the reason for the crash?

**Comment by Akashbhatt111** [comment] 2017-10-06 07:20
it is working fine in development build but in release mode it restart after the rewarded ads finished

**Comment by Akashbhatt111** [comment] 2017-10-06 07:20
i use chartboost and unity as a mediation network

**Comment by Akashbhatt111** [comment] 2017-10-06 08:06
[log.txt](https://github.com/googleads/googleads-mobile-unity/files/1361991/log.txt)
here is my logcat

**Comment by rampara** [comment] 2017-10-12 22:41
@Akashbhatt111 Is this crash consistently reproducible for you? Can you reproduce it with the [HelloWorld sample app](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) from this repo?

**Comment by rampara** [comment] 2017-11-15 02:21
Closing due to non-response.

**Closed by rampara** 2017-11-15 02:21 UTC
Labels: support question

**Comment by c301** [comment] 2017-12-24 08:55
Here is logs, hope it will helps. Looks like android 4.1 affected
[logcat.txt](https://github.com/googleads/googleads-mobile-unity/files/1584699/logcat.txt)

**Comment by rampara** [comment] 2017-12-27 22:10
@c301 a log that isn't filtered to just Unity tag would be more helpful.

**Comment by aurnut** [comment] 2018-04-11 12:58
Hello @rampara I have the same issue.
I'm using Unity 2017.3.1p4 with Google Mobile Ads 3.12.0 and mediation. I also use Proguard within Unity. The crash happens at the end of an Admob video and is rare on some phones and 100% on others. And it happened to me that a phone with the crash happening rarely became a 100%. Here is the error in the log: 

```
D/AndroidRuntime(27843): Shutting down VM

E/AndroidRuntime(27843): FATAL EXCEPTION: main

E/AndroidRuntime(27843): Process: com.xxx.xxx, PID: 27843

E/AndroidRuntime(27843): java.lang.Error: FATAL EXCEPTION [main]

E/AndroidRuntime(27843): Unity version     : 2017.3.1p4

E/AndroidRuntime(27843): Device model      : asus ASUS_Z00AD

E/AndroidRuntime(27843): Device fingerprint: asus/WW_Z00A/Z00A:5.0/LRX21V/2.20.40.206_20170627_2131_user:user/release-keys

E/AndroidRuntime(27843): 

E/AndroidRuntime(27843): Caused by: java.lang.AbstractMethodError: abstract method "void com.google.android.gms.ads.reward.RewardedVideoAdListener.onRewardedVideoCompleted()"

E/AndroidRuntime(27843): 	at com.google.android.gms.internal.zzafh.onRewardedVideoCompleted(Unknown Source)

E/AndroidRuntime(27843): 	at com.google.android.gms.internal.zzafd.onTransact(Unknown Source)

E/AndroidRuntime(27843): 	at android.os.Binder.transact(Binder.java:380)

E/AndroidRuntime(27843): 	at ht.b(:com.google.android.gms.dynamite_dynamitemodulesa@12521013@12.5.21 (020700-189987672):20)

E/AndroidRuntime(27843): 	at com.google.android.gms.ads.internal.reward.client.l.f(:com.google.android.gms.dynamite_dynamitemodulesa@12521013@12.5.21 (020700-189987672):27)

E/AndroidRuntime(27843): 	at com.google.android.gms.ads.internal.a.u(:com.google.android.gms.dynamite_dynamitemodulesa@12521013@12.5.21 (020700-189987672):471)

E/AndroidRuntime(27843): 	at com.google.android.gms.ads.internal.reward.d.f_(:com.google.android.gms.dynamite_dynamitemodulesa@12521013@12.5.21 (020700-189987672):87)

E/AndroidRuntime(27843): 	at com.google.android.gms.ads.internal.reward.mediation.h.h(:com.google.android.gms.dynamite_dynamitemodulesa@12521013@12.5.21 (020700-189987672):37)

E/AndroidRuntime(27843): 	at com.google.android.gms.ads.internal.reward.client.n.f(:com.google.android.gms.dynamite_dynamitemodulesa@12521013@12.5.21 (020700-189987672):96)

E/AndroidRuntime(27843): 	at com.google.android.gms.ads.internal.a.u(:com.google.android.gms.dynamite_dynamitemodulesa@12521013@12.5.21 (020700-189987672):471)

E/AndroidRuntime(27843): 	at com.google.android.gms.ads.internal.ak.Z(:com.google.android.gms.dynamite_dynamitemodulesa@12521013@12.5.21 (020700-189987672):277)

E/AndroidRuntime(27843): 	at com.google.android.gms.ads.internal.gmsg.am.a(:com.google.android.gms.dynamite_dynamitemodulesa@12521013@12.5.21 (020700-189987672):28)

E/AndroidRuntime(27843): 	at com.google.android.gms.ads.internal.webview.j.b(:com.google.android.gms.dynamite_dynamitemodulesa@12521013@12.5.21 (020700-189987672):356)

E/AndroidRuntime(27843): 	at com.google.android.gms.ads.internal.webview.ab.run(Unknown Source)

E/AndroidRuntime(27843): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(27843): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(27843): 	at com.google.android.gms.ads.internal.util.f.dispatchMessage(:com.google.android.gms.dynamite_dynamitemodulesa@12521013@12.5.21 (020700-189987672):9)

E/AndroidRuntime(27843): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(27843): 	at android.app.ActivityThread.main(ActivityThread.java:5264)

E/AndroidRuntime(27843): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(27843): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(27843): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)

E/AndroidRuntime(27843): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)

W/ActivityManager(  646):   Force finishing activity com.xxx.xxx/com.google.android.gms.ads.AdActivity
```

**Comment by ebrahim--hsh** [comment] 2019-02-24 10:29
I use Invoke to put some delays to call whatever I need to do, It works for me like a charm.

**Comment by Thaina** [comment] 2020-10-20 05:27
My app in unity 2020.1.9f1 with GoogleMobileAds-v5.3.0 still face this issue

I would try the above suggestion but I think admob SDK should handle this in SDK itself

**Comment by Thaina** [comment] 2020-10-20 09:30
I have wrap every `RewardedAd`'s event with `MobileAdsEventExecutor.ExecuteInUpdate` and it seem the problem are not persist anymore

Should this SDK consider calling every event in update by default?
