### ISSUE TITLE
Is this a common bug? How i Fix ?

### ISSUE THREAD

**Issue by Vinicioslc** [googleads/googleads-mobile-unity#324] opened 2016-12-21 00:46 UTC
Is this a common bug? Where can I fix it? I never got into an error, so extensive... :sweat: 
Error appears inside editor...
![screenshot_1](https://cloud.githubusercontent.com/assets/10997022/21373428/112fd7e6-c706-11e6-9e77-4f0c4477199e.png)

**Comment by Vinicioslc** [comment] 2016-12-23 22:14
Forbiden this guys im so dumb im using now admob plugin

**Comment by rampara** [comment] 2017-01-06 23:06
Are you using the latest version of this plugin? The error is are running into is caused by the [JarResolver](https://github.com/googlesamples/unity-jar-resolver) library being unable to locate the firebase unity dependency on your machine. If you were not prompted to do so by the JarResolver library, you should ensure this dependency is downloaded and available on your machine.

**Comment by rampara** [comment] 2017-01-23 22:23
Closing this issue due to non-response. Please re-open if this issue persists for you.

**Closed by rampara** 2017-01-23 22:23 UTC
Labels: support question
