### ISSUE TITLE
Admob ios interstitial no close button

### ISSUE THREAD

**Issue by hkk007** [googleads/googleads-mobile-unity#122] opened 2015-09-10 13:45 UTC
I have added a admob interstitial for my game fruit castle. In this game when game over i show admob interstitial and it does not show close button on ad to the user in some phones only. For example iphone 6.
here user stuck at ad and can not close it. please help me .

my game on app store link:
https://itunes.apple.com/us/app/fruit-castle/id1033802354?ls=1&mt=8

**Comment by hkk007** [comment] 2015-09-10 14:54
I Used admob Unity plugin

**Comment by aaronboothuk** [comment] 2015-11-03 00:35
I am also getting the same Issue in multiple apps with the unity plugin 2 different versions. Latest seen 7.5.2

**Comment by rampara** [comment] 2015-11-03 01:38
To help debug the issue, could you provide more information.

- Is this issue present on test ads as well as live ads?
- On what platform are you seeing the issue?
- Is the issue reproducible?

A charles log for an ad request where you see the issue would also be helpful.


- Ram

**Comment by hkk007** [comment] 2015-11-03 08:49
it seen only some iphones. i use iphone 4s and it shows close button in my phone. but some users complained that it doesnt shows close button.
you can check my game fruit castle.
https://itunes.apple.com/us/app/fruit-castle/id1033802354?ls=1&mt=8

**Comment by rampara** [comment] 2015-11-03 19:53
@hkk007 I installed the application you linked above but am unable to reproduce the issue. Without additional information, I cannot debug further.

**Comment by ericleich** [comment] 2015-11-04 02:27
Please take a screenshot if you see this come up for you. Since it happens only occasionally, my guess is there could be a bug in a particular interstitial ad creative. This wouldn't be the Unity plugin's fault and the plugin can't work around it, but is certainly feedback we can forward on if we can scope it to a particular ad.

**Comment by hkk007** [comment] 2015-11-04 06:04
k i will post screen shot when i see it again

**Comment by aaronboothuk** [comment] 2015-11-04 06:07
Two Examples here which were caught my apple app review on an iPAD using IOS 9.1
![temp pcwviohn](https://cloud.githubusercontent.com/assets/15621456/10930841/cb73b4b2-82f4-11e5-8b91-bd213f1f7583.png)
![temp fjrojiyb](https://cloud.githubusercontent.com/assets/15621456/10930842/cda13926-82f4-11e5-8d8f-908e23c228cb.png)

**Comment by aaronboothuk** [comment] 2015-11-04 06:16
Another instance this time IOS 9.02
![temp uihnlisn](https://cloud.githubusercontent.com/assets/15621456/10931012/3efe03aa-82f6-11e5-8750-72d1ca4b4928.png)

**Comment by gferrari** [comment] 2015-11-04 17:06
I have same problem with android. They user can't get the close button because is hidden by status bar. (I this is a similar issue)

The game is: https://play.google.com/store/apps/details?id=com.Neurocreativa.CthulhuVirtualPet

Thanks!

![screenshot_2015-11-04-14-44-52](https://cloud.githubusercontent.com/assets/675596/10945631/15947e0c-82fd-11e5-8e73-e4a43604bdc5.jpg)

**Comment by rampara** [comment] 2015-11-04 18:33
@gferrari In my tests, when an interstitial is first shown the status bar is hidden. Swiping down from the top of the screen will result in the close button being covered by the status bar (as shown in the screenshot you attached). However, waiting a few seconds will allow the status bar to hide and the interstitial can be closed. Are you seeing different behavior?

@aaronboothuk I am working with the ad serving team to investigate why those ads are missing a close button and will follow up when I have more information. 
 
- Ram

**Comment by rampara** [comment] 2015-12-18 17:00
@gferrari , @aaronboothuk @hkk007 is this issue still present for you?

**Comment by rampara** [comment] 2016-01-04 17:21
Closing issue due to non-response. If this issue persists, please re-open.

- Ram

**Closed by rampara** 2016-01-04 17:21 UTC
