### ISSUE TITLE
Banner above hidden navigation bar although immersive mode (Sony Z3 tablet)

### ISSUE THREAD

**Issue by matie** [googleads/googleads-mobile-unity#447] opened 2017-06-13 19:35 UTC
Although the Android navigation bar is hidden, the banner will be placed as if the app is not running in immersive mode. So, the app is able to use to full screen, but the banner thinks the navigation bar is still there, so it places it over our own menu bar. 

We've done an upgrade lately to 3.5.0 (Running on Unity 5.6.1f1). After this upgrade of google ads the problem occurs (landscape), but only on our Sony Z3 compact tablet (model SGP611). I've tested it on about 25 different devices which differ as much as possible from each other. 

When setting Screen.fullScreen  to false (switch off immersive mode), it works perfectly, the bar will be put at the same position as in immersive mode, but with the unwanted navigation bar.

It really seems to be a bug in the plugin.

At this moment I'm grabbing the model number and disable banners on these devices. 

Could you have a look at this?

Mathijs.

**Comment by rampara** [comment] 2017-06-13 20:30
Seems to be the same issue as #430. Haven't been able to get my hands on a Z3 compact or a Z3 compact tablet and unable to repro on other Sony devices. Tried a Sony Xperia E3 and that renders fine.

![image](https://user-images.githubusercontent.com/11047881/27102744-3b761a56-503b-11e7-9554-6796f9e36165.png)

Will follow up once I'm able to get one of two devices reported in this and the linked issue.

**Comment by matie** [comment] 2017-06-14 08:46
Hi, We also have a Xperia Z2 Phone. This one works like a charm. So, indeed, it somehow seems device specific. The Z3 is running Android 5.1.1 (latest firmware). The Z2 is currently running 6.0.1. There is an update available, will check that one as well.

**Comment by rampara** [comment] 2017-06-14 17:30
@matie thanks for the additional information.

**Comment by rchallenger** [comment] 2017-07-31 09:06
HI, I've also experienced that on latest versions. Only v 3.1.3 works fine. The issue was when application in portrait orientation with hidden nav_bar, immersive mode turned on and visible banner 320x50, showed interstitial. When we are showing interstitial ads - small banner is hidden to avid 2 ads present on the screen (designed for families program demands), especially when content of interstitial had transparent background. So we catch interstitial closed event and show small banner again. The problem is that if you close interstitial with help of close button on the content or Esc_button on nav_bar, unity activity resumes and nav_bar stays visible for some time (transparent). At this very moment banner becomes visible and positions above the nav_bar. As the bar minimizes banner goes to its initial place (bottom-center). This behavior is not acceptable, cause it is not in compliance with Admob program policies (designed for families: ADS AND CONTENT OVERLAP).

**Comment by rchallenger** [comment] 2017-07-31 09:08
Forgot to mention that I ran it on Moto Z Play, Android 7.0

**Comment by rampara** [comment] 2017-08-03 22:19
@matie I was able to get my hands on a Z3 running Android 5.1.1 but I'm still unable to reproduce the issue on the device with the latest version of the plugin. Attached a screenshot below.

![screencap](https://user-images.githubusercontent.com/11047881/28946150-51e35452-785e-11e7-8ae9-2b6c3931d2a5.png)

**Comment by rampara** [comment] 2017-08-03 22:20
@rchallenger can you provide me with a test app to reproduce the issue you mention. It would help me investigate.

**Comment by rchallenger** [comment] 2017-08-04 06:43
Here are test applications, using [3.6.1](https://drive.google.com/file/d/0B6u2VDj2GWUkc255bGxDOWxmSm8/view?usp=sharing) and [3.6.2](https://drive.google.com/file/d/0B6u2VDj2GWUkSWRHdFRKTER2dlU/view?usp=sharing) plugin version. Both behave in the same manner.

Here is a [video record](https://drive.google.com/open?id=0B6u2VDj2GWUkWFZZRGZMXzhmbkk) of what is really happening.

Here is a log file.
[Ads_test_log.txt](https://github.com/googleads/googleads-mobile-unity/files/1199437/Ads_test_log.txt)

**Comment by rampara** [comment] 2017-08-07 20:22
@rchallenger This does seem like a Moto specific issue where when returning to the Unity activity (from the interstitial ad), there is a delay before re-entering immersive mode. Are you able to reproduce the issue on any other device?

And the reason you're not seeing this behavior on plugin version 3.1.3 or earlier is because as of v.3.2.0, the implementation to display banner and native express ads changed to be compatible with Unity 5.6+.

**Comment by rampara** [comment] 2017-11-15 02:16
Closing as this is a Moto specific issue not caused by this plugin.

**Closed by rampara** 2017-11-15 02:16 UTC
Labels: plugin bug
