### ISSUE TITLE
Crash on application start with Firebase

### ISSUE THREAD

**Issue by Synivar** [googleads/googleads-mobile-unity#866] opened 2019-03-01 02:33 UTC
Using GoogleMobileAds v3.15.1 and Firebase for Unity SDK v5.1.0. Everything was working fine before integrating the Google Ads plugin but now I'm getting an immediate crash when opening the application. Before anyone asks, I did follow the setup guide (https://developers.google.com/admob/unity/start) but it appears there are incompatibility issues with Firebase.

In case it's relevant I also added the AdColony mediation adapter plugin for Unity (v1.0.3) from here: https://developers.google.com/admob/unity/mediation/adcolony

Crash log:

`03-03 12:22:03.372 18123-18123/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.Company.Game, PID: 18123
    java.lang.NoSuchMethodError: No static method com_google_firebase_components_ComponentRuntime$$Lambda$1_lambda$new$0(Lcom/google/firebase/components/ComponentRuntime;Lcom/google/firebase/components/Component;)Ljava/lang/Object; in class Lcom/google/firebase/components/ComponentRuntime; or its super classes (declaration of 'com.google.firebase.components.ComponentRuntime' appears in /data/app/com.hasbro.riskbigscreen-2/base.apk:classes2.dex)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source)
        at com.google.firebase.components.Lazy.get(Unknown Source)
        at com.google.firebase.components.AbstractComponentContainer.get(Unknown Source)
        at com.google.firebase.components.ComponentRuntime.get(Unknown Source)
        at com.google.firebase.FirebaseApp.<init>(Unknown Source)
        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5905)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5497)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5436)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6171)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)`

Additionally hitting "Resolve" on the library resolver results in this warning which may be related:

`Some conflicting dependencies were found.
The following dependency versions were modified:
com.android.support:appcompat-v7:25.3.1 --> com.android.support:appcompat-v7:26.1.0
com.android.support:cardview-v7:25.3.1 --> com.android.support:cardview-v7:26.1.0
com.android.support:customtabs:25.3.1 --> com.android.support:customtabs:26.1.0
com.android.support:design:25.3.1 --> com.android.support:design:26.1.0
com.android.support:recyclerview-v7:25.3.1 --> com.android.support:recyclerview-v7:26.1.0
com.android.support:support-v13:25.3.1 --> com.android.support:support-v13:26.1.0
com.android.support:support-v4:25.3.1 --> com.android.support:support-v4:26.1.0
com.google.android.gms:play-services-ads:15.0.1 --> com.google.android.gms:play-services-ads:+
com.google.android.gms:play-services-analytics:9.2.0 --> com.google.android.gms:play-services-analytics:+
com.google.android.gms:play-services-analytics:11.4.2 --> com.google.android.gms:play-services-analytics:+
com.google.android.gms:play-services-auth:11.4.2 --> com.google.android.gms:play-services-auth:+
com.google.android.gms:play-services-auth-base:11.4.2 --> com.google.android.gms:play-services-auth-base:+
com.google.android.gms:play-services-games:11.4.2 --> com.google.android.gms:play-services-games:+
com.google.android.gms:play-services-gcm:11.4.2 --> com.google.android.gms:play-services-gcm:+
com.google.android.gms:play-services-plus:11.4.2 --> com.google.android.gms:play-services-plus:+
com.google.android.gms:play-services-plus-license:11.4.2 --> com.google.android.gms:play-services-plus-license:11+
com.google.firebase:firebase-common:16.0.4 --> com.google.firebase:firebase-common:+
com.google.firebase:firebase-core:16.0.6 --> com.google.firebase:firebase-core:+
com.google.firebase:firebase-messaging:17.3.4 --> com.google.firebase:firebase-messaging:+
com.google.games:gpgs-plugin-support:0.9.50 --> com.google.games:gpgs-plugin-support:+`

**Comment by ctykaya** [comment] 2019-03-09 07:53
Same issue for me. Admob with firebase doesn't work together. Crash on start.

**Comment by yantian001** [comment] 2019-03-13 08:16
Same issue for me ,i also edit android manifest following guide ,don't use for me .

**Comment by Heru6664** [comment] 2019-04-04 14:53
any update on this?
i got same problem

**Comment by stowy** [comment] 2019-04-04 17:11
Can you confirm if this issue occurs with the 3.16 GoogleMobileAds plugin?

**Comment by yantian001** [comment] 2019-04-08 06:44
@stowy Yes,I have confirmed also have same issue with 3.16

**Comment by yantian001** [comment] 2019-04-08 07:31
@stowy I also update the firebase unity sdk to 5.6.1 .fixed !

**Comment by Heru6664** [comment] 2019-04-08 08:03
i fixed it following the docs here 
https://rnfirebase.io/docs/v5.x.x/troubleshooting/android#NoSuchMethodError:-No-static-method-(run-time-error)

**Comment by stowy** [comment] 2019-04-08 15:53
@Heru6664 did you have to change any settings of did just updating versions resolve the issue?

**Comment by Heru6664** [comment] 2019-04-08 16:02
> @Heru6664 did you have to change any settings of did just updating versions resolve the issue?

i updating any settings, after i updating of google play service versions. i following this, as the docs said :

https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f

**Comment by stowy** [comment] 2019-04-08 17:36
Can you share what your final configuration looks like?

**Comment by UragayalaDeepika** [comment] 2019-10-10 20:46
@Heru6664  Are you still able to reproduce the issue? Closing this thread for now. Please comment and let us know so that we can reopen the issue and assist you further.

**Closed by UragayalaDeepika** 2019-10-10 20:46 UTC
