### ISSUE TITLE
New commit made everything worse?

### ISSUE THREAD

**Issue by tommyzat** [googleads/googleads-mobile-unity#320] opened 2016-12-09 21:11 UTC
Hello, since the new commit on 3.1.3 NOTHING works now. Banners don't appear, and input controls are completely ignored. Why?

**Comment by rampara** [comment] 2016-12-10 00:38
Are you seeing this issue on Android or on iOS? Do you see any output in logcat or the Xcode console that may indicate the cause of the issue?

**Comment by rampara** [comment] 2017-01-17 18:40
Closing issue due to non-response. If this issue persists for you please re-open.

**Closed by rampara** 2017-01-17 18:40 UTC
Labels: support question
