### ISSUE TITLE
Plugin incompatible with firebase in unity

### ISSUE THREAD

**Issue by rafante** [googleads/googleads-mobile-unity#708] opened 2018-07-04 10:37 UTC
In unity, If you add for instance firebase auth or real time database, and also add the admob plugin. They conflict about some dll, and If you proceed It seems it will work because in editor It shows no problem but If you build the app on Android, the app crashes when you call the RequestBanner () method more especifically in the new BannerView([...]) command. Please fix this issue because I really need to mix both admob and firebase.

**Comment by rampara** [comment] 2018-07-10 21:30
Closing as duplicate of #695.

**Closed** 2018-07-10 21:30 UTC
Labels: P2, plugin bug
