### ISSUE TITLE
Admob ads not working in Unity 5.3.5p7 personal

### ISSUE THREAD

**Issue by zeeshanarif53** [googleads/googleads-mobile-unity#252] opened 2016-07-17 13:17 UTC
Hi,

I'm using this unity plugin but i'm not able to receive ads. When i build the code for IOS and run it on using Xcode on iphone below will happen. I call the below function 

    private static InterstitialAd interstitial;
    public void RequestInterstitial()
    {
     
       string adUnitId = "inter_admob_id";
      
        // Create an interstitial.
        interstitial = new InterstitialAd(adUnitId);
        // Load an interstitial ad.
				
        interstitial.LoadAd(createAdRequest());
    }

But i receive this error in xcode logs (This error is on the line  interstitial = new InterstitialAd(adUnitId);) 

NotSupportedException: To marshal a managed method, please add an attribute named 'MonoPInvokeCallback' to the method definition.
  at GoogleMobileAds.iOS.Externs.GADUSetInterstitialCallbacks (IntPtr interstitial, GoogleMobileAds.iOS.GADUInterstitialDidReceiveAdCallback adReceivedCallback, GoogleMobileAds.iOS.GADUInterstitialDidFailToReceiveAdWithErrorCallback adFailedCallback, GoogleMobileAds.iOS.GADUInterstitialWillPresentScreenCallback willPresentCallback, GoogleMobileAds.iOS.GADUInterstitialDidDismissScreenCallback didDismissCallback, GoogleMobileAds.iOS.GADUInterstitialWillLeaveApplicationCallback willLeaveCallback) [0x00000] in <filename unknown>:0 
  at GoogleMobileAds.Api.InterstitialAd..ctor (System.String adUnitId) [0x00000] in <filename unknown>:0 

Please help me out

**Comment by rampara** [comment] 2016-07-18 18:37
I'm having trouble reproducing this error. Have you modified the plugin code? If not, can you link to a test app where you're able to reproduce the error. It would help me investigate into the cause of the issue.

**Comment by rampara** [comment] 2016-10-10 21:41
Closing this issue to due it's age and non-response. Please re-open if this issue persists for you.

**Closed by rampara** 2016-10-10 21:41 UTC
Labels: support question
