### ISSUE TITLE
v7.0.0 removes permissions from the main manifest

### ISSUE THREAD

**Issue by MayisGM** [googleads/googleads-mobile-unity#2001] opened 2022-03-29 15:28 UTC
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.23
  * Google Mobile Ads Unity plugin version: 7.0.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Android 9 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: No specific devices
  * Mediation ad networks used, and their versions: All mediations has the latest versions

#### Steps to reproduce:

Add this permission to the main AndroidManifest.xml file for example:

<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

After building the project which includes Google Mobile Ads SDK version 7.0.0 the permission will be removed from the main manifest. The reason of this happening is AndroidManifest.xml file inside googlemobileads-unity.aar, which looks like this:

<?xml version="1.0" encoding="utf-8"?>

#### Relevant Code:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.google.unity.ads" >

    <uses-permission
        android:name="android.permission.READ_PHONE_STATE"
        tools:node="remove" />
    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        tools:node="remove" />
    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE"
        tools:node="remove" />
    <uses-permission android:name="android.permission.INTERNET" />

</manifest>
```
Please let us know how to temporarily solve this issue, or please release fixed version as soon as possible.

**Comment by PokerDawg** [comment] 2022-04-01 12:58
I think I found a temporary solution to this. 
.aar files are basically .zip files, so open `Assets/Plugins/Android/googlemobileads-unity.aar` with whatever archive software you have (I'm using 7zip) and extract its contents. Edit the `AndroidManifest.xml` file by deleting the lines that remove permissions. It should look like this:
```
<?xml version="1.0" encoding="utf-8"?>
<!--
This Google Mobile Ads plugin library manifest will get merged with your
application's manifest, adding the necessary metadata
required for displaying ads.
-->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.google.unity.ads" >

    <uses-permission android:name="android.permission.INTERNET" />

</manifest>
```
Now take all the files and zip them back up. Rename the archive to `googlemobileads-unity.aar` (no .zip extension) and replace it in your Unity project. I'm not sure it's necessary, but I restarted the editor and force resolved with EDM. 
We're using a plugin to save pictures to the user's gallery, and it's working again after I modified the .aar. From the limited time we've had with this solution, we didn't find any problems with the ads or anything else. Regardless, we're hoping for a fix to be released soon.

**Comment by MayisGM** [comment] 2022-04-01 14:37
> I think I found a temporary solution to this. .aar files are basically .zip files, so open `Assets/Plugins/Android/googlemobileads-unity.aar` with whatever archive software you have (I'm using 7zip) and extract its contents. Edit the `AndroidManifest.xml` file by deleting the lines that remove permissions. It should look like this:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> 
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     xmlns:tools="http://schemas.android.com/tools"
>     package="com.google.unity.ads" >
> 
>     <uses-permission android:name="android.permission.INTERNET" />
> 
> </manifest>
> ```
> 
> Now take all the files and zip them back up. Rename the archive to `googlemobileads-unity.aar` (no .zip extension) and replace it in your Unity project. I'm not sure it's necessary, but I restarted the editor and force resolved with EDM. We're using a plugin to save pictures to the user's gallery, and it's working again after I modified the .aar. From the limited time we've had with this solution, we didn't find any problems with the ads or anything else. Regardless, we're hoping for a fix to be released soon.

Thank you for sharing your temporary solution. I tried described solution too, and that worked, but as I was not sure this solution will not harm other components of Google Mobile Ads Unity SDK I decided to use SDK version 6.1.2, because it doesn't have this issue. Let's wait for the official fix of this issue.

**Comment by stickylabdev** [comment] 2022-04-02 17:34
i wondering where to put AD_ID permission

**Comment by MayisGM** [comment] 2022-04-03 11:58
> i wondering where to put AD_ID permission

As I know you just need to add this to permissions section in main AndroidManifest.xml:

<uses-permission android:name="com.google.android.gms.permission.AD_ID"/>

**Comment by stickylabdev** [comment] 2022-04-03 13:37
I need the exact line, I'm afraid I put it in wrong line

Pada tanggal Min, 3 Apr 2022 18.58, MayisGM ***@***.***>
menulis:

**Comment by NVentimiglia** [comment] 2022-04-08 06:36
Thank you for the report. 

This will be fixed in the next release.

**Comment by Nyankoo** [comment] 2022-04-15 23:18
@NVentimiglia Any ETA for the next release?

**Comment by ericleich** [comment] 2022-04-15 23:47
@stickylabdev  For adding the AD_ID permission, it should be added automatically by the play-services-ads dependency if [using version 20.4.0 or higher](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml#L3) per the [Android release notes](https://developers.google.com/admob/android/rel-notes#20.4.0). Unity plugin v7.0.0 looks to be distributed with 20.6.0, meaning you shouldn't have to add the permission manually.

**Comment by stickylabdev** [comment] 2022-04-16 01:43
> @stickylabdev For adding the AD_ID permission, it should be added automatically by the play-services-ads dependency if [using version 20.4.0 or higher](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml#L3) per the [Android release notes](https://developers.google.com/admob/android/rel-notes#20.4.0). Unity plugin v7.0.0 looks to be distributed with 20.6.0, meaning you shouldn't have to add the permission manually.

The problem is this https://github.com/googleads/googleads-mobile-unity/issues/2000#issue-1182655588

**Closed** 2022-05-24 15:26 UTC
Labels: P1
