### ISSUE TITLE
Cannot play reward video ad: java.lang.IllegalStateException: Top bit not zero

### ISSUE THREAD

**Issue by hnim** [googleads/googleads-mobile-unity#1508] opened 2020-11-23 08:09 UTC
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.13f1
  * Google Mobile Ads Unity plugin version: 5.4.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: 7.1.2 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: LDPlayer
  * Mediation ad networks used, and their versions: _____

#### Everytime I open game then this log appears and I cannot play reward video ad:

java.lang.IllegalStateException: Top bit not zero: -1571240360
        at com.google.android.gms.ads.exoplayer3.util.i.i(:com.google.android.gms.policy_ads_fdr_dynamite@204102000@204102000000.334548305.334548305:2)
        at com.google.android.gms.ads.exoplayer3.extractor.mp4.p.a(:com.google.android.gms.policy_ads_fdr_dynamite@204102000@204102000000.334548305.334548305:23)
        at com.google.android.gms.ads.exoplayer3.upstream.n.run(:com.google.android.gms.policy_ads_fdr_dynamite@204102000@204102000000.334548305.334548305:7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
2020-11-23 14:59:16.499 29363-29825/com.redantz.game.monsterswar E/ExoPlayerImplInternal: Source error.
    com.google.android.gms.ads.exoplayer3.upstream.o: Unexpected IllegalStateException: Top bit not zero: -1571240360
        at com.google.android.gms.ads.exoplayer3.upstream.n.run(:com.google.android.gms.policy_ads_fdr_dynamite@204102000@204102000000.334548305.334548305:20)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.IllegalStateException: Top bit not zero: -1571240360
        at com.google.android.gms.ads.exoplayer3.util.i.i(:com.google.android.gms.policy_ads_fdr_dynamite@204102000@204102000000.334548305.334548305:2)
        at com.google.android.gms.ads.exoplayer3.extractor.mp4.p.a(:com.google.android.gms.policy_ads_fdr_dynamite@204102000@204102000000.334548305.334548305:23)
        at com.google.android.gms.ads.exoplayer3.upstream.n.run(:com.google.android.gms.policy_ads_fdr_dynamite@204102000@204102000000.334548305.334548305:7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761)

**Comment by wanxiaobing** [comment] 2021-06-16 08:52
> ### [REQUIRED] Step 1: Describe your environment
> * Unity version: 2019.4.13f1
> * Google Mobile Ads Unity plugin version: 5.4.0
> * Platform: Android (iOS, Android, Unity Editor)
> * Platform OS version: 7.1.2 (eg iOS 10, Android 9)
> * Any specific devices issue occurs on: LDPlayer
> * Mediation ad networks used, and their versions: _____
> 
> ### [REQUIRED] Step 2: Describe the problem
> #### Everytime I open game then this log appears and I cannot play reward video ad:
> java.lang.IllegalStateException: Top bit not zero: -1571240360
> at com.google.android.gms.ads.exoplayer3.util.i.i(:com.google.android.gms.policy_ads_fdr_dynamite@204102000@204102000000.334548305.334548305:2)
> at com.google.android.gms.ads.exoplayer3.extractor.mp4.p.a(:com.google.android.gms.policy_ads_fdr_dynamite@204102000@204102000000.334548305.334548305:23)
> at com.google.android.gms.ads.exoplayer3.upstream.n.run(:com.google.android.gms.policy_ads_fdr_dynamite@204102000@204102000000.334548305.334548305:7)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
> at java.lang.Thread.run(Thread.java:761)
> 2020-11-23 14:59:16.499 29363-29825/com.redantz.game.monsterswar E/ExoPlayerImplInternal: Source error.
> com.google.android.gms.ads.exoplayer3.upstream.o: Unexpected IllegalStateException: Top bit not zero: -1571240360
> at com.google.android.gms.ads.exoplayer3.upstream.n.run(:com.google.android.gms.policy_ads_fdr_dynamite@204102000@204102000000.334548305.334548305:20)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
> at java.lang.Thread.run(Thread.java:761)
> Caused by: java.lang.IllegalStateException: Top bit not zero: -1571240360
> at com.google.android.gms.ads.exoplayer3.util.i.i(:com.google.android.gms.policy_ads_fdr_dynamite@204102000@204102000000.334548305.334548305:2)
> at com.google.android.gms.ads.exoplayer3.extractor.mp4.p.a(:com.google.android.gms.policy_ads_fdr_dynamite@204102000@204102000000.334548305.334548305:23)
> at com.google.android.gms.ads.exoplayer3.upstream.n.run(:com.google.android.gms.policy_ads_fdr_dynamite@204102000@204102000000.334548305.334548305:7)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
> at java.lang.Thread.run(Thread.java:761)

**Comment by wanxiaobing** [comment] 2021-06-16 08:54
Fatal Exception: java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2018.4.23f1
Device model      : samsung SM-A515F
Device fingerprint: samsung/a51nsser/a51:11/RP1A.200720.012/A515FXXU4DUB1:user/release-keys

Caused by java.util.NoSuchElementException
       at java.util.ArrayDeque.removeFirst(ArrayDeque.java:270)
       at abb.b(:com.google.android.gms.policy_ads_fdr_dynamite@211512000@211512000057.367949677.367949677:4)
       at fy.n(:com.google.android.gms.policy_ads_fdr_dynamite@211512000@211512000057.367949677.367949677:60)
       at gt.run(:10)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by kunny** [comment] 2023-01-09 14:28
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones.

Thanks for your contribution again!

**Closed by kunny** 2023-01-09 14:28 UTC
