### ISSUE TITLE
Multiple Crashes on Nexus 5 Running Android 5.1.1

### ISSUE THREAD

**Issue by Nomo-HSH** [googleads/googleads-mobile-unity#137] opened 2015-11-25 23:32 UTC
Hi there. I'm currently encountering two separate crashes while testing Google Mobile Ads on my Nexus 5 running Android 5.1.1 built against version 2.3.1 of your Unity3d plugin. My game is running in Unity3d 5.2.3f1. It is worth noting that neither of these issues occur when running the exact same APK of my game on my Nexus 7 running Android 4.4.4 (also interstitial ads display without issue). The first issue pertains to building and running "development builds" as defined by the toggle in the Unity3d build settings window. Developments builds will crash during the initial load into my game during which interstitial ads are loaded using Google Mobile Ads. See the log file named dev_build_crash_log.txt. When running non-development builds (development build toggle disabled in build settings), interstitial ads that do not include embedded videos will load and display without issue. However, if the interstitial ad includes a video then the game will crash within 1-2 seconds of playback of the video. See the log file named video_interstitial_crash_log.text. Upon reviewing other issues that have been posted I explored the possibility that the issue could have something to do with the functionality in my game that runs upon receiving events from InterstitialAd class instances given it sounds as though those events are not triggered from the main thread. Unfortunately, moving the actual handling logic of these events to the Update method of a Mono Behaviour did not have any effect on either crashes. I look forward to insight on these issues. Thanks.

[dev_build_crash_log.txt](https://github.com/googleads/googleads-mobile-unity/files/44473/dev_build_crash_log.txt)
[video_interstitial_crash_log.txt](https://github.com/googleads/googleads-mobile-unity/files/44474/video_interstitial_crash_log.txt)

**Comment by rampara** [comment] 2015-12-18 16:52
The dev build crash seems similar to the issue posted [here](https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/game-engines/_ZJT6W_4ADw) and seems related to invalid initialization of an ArrayList. 

However, I am unable to reproduce this issue or your video crash. Are you able to reproduce this issue in a Unity project with just this plugin (as it seems you are using many other plugins as well)?  

- Ram

**Comment by rampara** [comment] 2016-08-16 18:41
Closing issue due to non-response. If this issue persists, please re-open.

**Closed by rampara** 2016-08-16 18:41 UTC
