### ISSUE TITLE
problem with AddPosition.Top on Android

### ISSUE THREAD

**Issue by VincentBaillet** [googleads/googleads-mobile-unity#794] opened 2018-10-28 12:21 UTC
I've spent much time trying to display banners with adposition.top on  Android device, and here is the result i get on all (3) my android devices:
![screenshot_20181028-123743-2](https://user-images.githubusercontent.com/11924925/47615656-b4ab6c80-dab1-11e8-8c11-a2de4e22b785.png)
The banner does not appear at the top of the screen, but under what looks like the "status bar zone". Also, the banner is cut horizontally in the middle.
It looks like issue #792, except that there is no notches on my phones.

I've tried to play with SetPosition(X,Y) in order to understand what's happening: it looks like the banner is always cut if the Y position is located within the "status bar". 

2 questions:
-Is there a way to display the Banner at the top of the screen, without being cut ?
-I suppose this version of the plugin is a bit buggy on positionning banners. Is there an old version of the plugin that work on all banner positions and on all devices ?

Thanks.
     Vincent

**Comment by asarazan** [comment] 2018-11-01 22:29
I'm also seeing this, but it only seems to manifest after the app resumes from background (e.g. the native share flow will trigger it).

My current hack is to wait for app resume, hide the banner, wait 1 second, and re-show the banner. Seems to work most of the time.

**Comment by asarazan** [comment] 2018-11-01 22:35
One thing that might be relevant: I believe my Admob aar version has been forced to 17.0.0, due to Firebase's dependency requirements (this also caused an insta-crash, as Unity suddenly demanded that my app id be included in my AndroidManifest).

I suspect an incompatibility with the latest Admob aar may to be blame here.

**Comment by asarazan** [comment] 2018-11-01 22:44
Here's a video of the repro in my app: https://photos.app.goo.gl/te4ueqvy4Fn9PCbx6

Interestingly, it didn't push down the banner this time, just the app contents. I have confirmed that the shifting goes away _if and only if_ the banner is hidden/disabled.

**Comment by VincentBaillet** [comment] 2018-11-08 21:21
thanks very much asarazan, i've tried to hide the banner and display it again, i also tried to follow your advice about the app resuming from background... I also removed and reinstalled all my packages, following step by step the instructions... and i still have the banner cut horizontally.
Maybe my 3 android phones have a compatibility problem with admob, maybe there is a compatibility problem with other packages... Anyway, i can not solve this problem.
I've spend too much time on this issue. So I've switched another banner provider, which worked within minutes.

**Comment by itayganor** [comment] 2018-11-11 22:59
> thanks very much asarazan, i've tried to hide the banner and display it again, i also tried to follow your advice about the app resuming from background... I also removed and reinstalled all my packages, following step by step the instructions... and i still have the banner cut horizontally.
> Maybe my 3 android phones have a compatibility problem with admob, maybe there is a compatibility problem with other packages... Anyway, i can not solve this problem.
> I've spend too much time on this issue. So I've switched another banner provider, which worked within minutes.

May you please name the other banner provider?

**Comment by rampara** [comment] 2019-01-23 04:13
@VincentBaillet @itayganor @asarazan is this reproducible with the `HelloWorld` sample app included in this repo?

**Comment by VincentBaillet** [comment] 2019-01-24 17:35
@rampara @itayganor @asarazan I've stopped trying some time ago, I've spent too much time on these banners that behaved differently on several devices. The best way I've found to display admob banners was to use another package and to use mediation for admob
hope you will be able to solve this issue: it's a bit strange to use Mopub plugin to display admob ads.

**Comment by rubelmusicwould8374** [comment] 2019-02-04 05:56
My New App http://app.appsgeyser.com/8460172/Rubel%20Musicwould
**
_Rubel_Musicwould_8460172 .apk
****
Banner Ads
ca-app-pub-7689122978757670/1062649510
Interstitial Ads
ca-app-pub-7689122978757670/5822530919
Please Settings Admob Adjust Enable System

**Comment by stowy** [comment] 2019-05-16 18:50
Please try [version 3.17.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/3.17.0).

**Comment by UragayalaDeepika** [comment] 2019-06-18 15:37
@VincentBaillet @itayganor Can you please try with the latest verison of the plugin and let us know?

**Comment by UragayalaDeepika** [comment] 2019-07-31 15:23
Closing this for now. Feel free to comment here so that we can reinvestigate this issue if it is still reproducible with the latest version.

**Closed by UragayalaDeepika** 2019-07-31 15:23 UTC
Labels: P2, plugin bug
