### ISSUE TITLE
Banner Ad is dropping frame rate of game

### ISSUE THREAD

**Issue by vibas** [googleads/googleads-mobile-unity#132] opened 2015-11-10 05:52 UTC
I have integrated google admob package in my game. For interstitial Ad game is working fine. But while game play I am showing the Banner Ad which is disturbing game FPS. The game play was smooth before I integrated Admob. But now I am facing heavy lag in game play. Please help.

**Comment by rampara** [comment] 2016-02-03 04:54
In the latest release of this plugin (v3.0.0), our sample application was updated to include a frame rate indicator. Are you seeing a drop in frame rate while displaying a banner application? If so, can you provide additional information on the type of device you're seeing this behavior on?

- Ram

**Comment by rampara** [comment] 2016-12-06 00:34
duplicate of #236

**Closed** 2016-12-06 00:34 UTC
Labels: duplicate, plugin bug
