### ISSUE TITLE
iOS rewarded video closed and rewarded callbacks are not called

### ISSUE THREAD

**Issue by quyenlt4488** [googleads/googleads-mobile-unity#238] opened 2016-06-21 06:54 UTC
I integrated Unity ads, Vungle and AdColony as admob rewarded video ads. The video is loaded and shown well but the rewardedAds.**OnAdRewarded** and rewardedAds.**OnAdClosed** are not called. So I cannot reward users.
    I have checked all rewardedAds callbacks, just rewardedAds.**OnAdOpening** and rewardedAds.**OnAdStarted** are called.
   One more issue, when rewarded video is playing, game is still running. Could I make the game pause when the video is playing ?
   Could you help me to fix these problems.
Thanks in advance.

**Comment by rampara** [comment] 2016-06-24 21:24
Using our [sample application](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld), I was able to request and display rewarded video ads from Vungle and received all call backs as expected. Can you provide a link to a test app (our sample app would be a good choice), where you're able to reproduce the error? It would help in tracking down what's causing the issue.

**Comment by rampara** [comment] 2016-08-17 17:50
Closing issue due to non-response. If this issue persists, please re-open.

**Closed by rampara** 2016-08-17 17:50 UTC
Labels: support question

**Comment by sarthakz9** [comment] 2018-07-17 15:05
@rampara This is how you can reproduce this error for Admob unity.
1. make 2 scenes, say A and B.
2. you can go from scene A to scene B and vice versa.
3. All you rewarded video ad logics and callbacks should be written in script present in scene B.
4. now, when you will go to scene B for the first time your callbacks will be init. for the first time and everything will work fine.
5. go back from scene B to scene A and them back to scene B.
6. this time you rewarded video callback will be setup for the second time. you will see that most of the callbacks in this script are not called as expected.

I think the singleton behavior of admob rewarded video ads is causing the issue and callbacks when initialized the 2nd time are not working correctly. 

7. Also when you close the game and do the same thing again. The callbacks will work again for the first time you are in scene B.
