### ISSUE TITLE
iOS library duplicated errors with plugin version 7.3.1

### ISSUE THREAD

**Issue by AllanRW** [googleads/googleads-mobile-unity#2482] opened 2023-01-12 20:37 UTC
Getting library duplicates on plugin version 7.3.1, reverting to 7.3.0 fixes the issue.

  * Unity version: 2021.3.16f1
  * Google Mobile Ads Unity plugin version: 7.3.1
  * Platform: iOS
  * Platform OS version: iOS 16

**Comment by MadFishGamesOfficial** [comment] 2023-01-14 21:36
I managed to successfully build the project by freezing the version of Google-Mobile-Ads-SDK to 9.13.

The problem:

`GoogleMobileAdsDependencies.xml` file contains this line `<iosPod name="Google-Mobile-Ads-SDK" version="~> 9.11">`

Optimistic operator (`~>`) makes it so that package with the greatest version will be included.

This issue was introduced in version 9.14, thus if you were to try to build the project today, You will have Google-Mobile-Ads-SDK version 9.14 (The problematic version).

The solution:

Open the `GoogleMobileAdsDependencies.xml` and replace the version from `"~> 9.11"` to `"9.13"` (Removing the optimistic operator).

**Comment by joaoborks** [comment] 2023-01-17 17:32
Possible duplicate of #2450

**Comment by NVentimiglia** [comment] 2023-01-18 01:25
This is fixed in [7.4.0](https://github.com/googleads/googleads-mobile-unity/releases/tag/v7.4.0)

**Closed by NVentimiglia** 2023-01-18 01:25 UTC
