### ISSUE TITLE
Force landscape / portrait

### ISSUE THREAD

**Issue by bruno-ian** [googleads/googleads-mobile-unity#246] opened 2016-07-03 05:23 UTC
Hi, i'm having a problem with Admob ads.

Currently the app supports portrait and lanscape (Unity settings/player is configured to autorotate) but when it is in landscape mode, ads are shown in portrait.

If the app is configured to support only landscape mode, ads are shown in correctly (landscape mode) ... but i want to use both modes.

There is a way around it?

Thnx!

**Comment by rampara** [comment] 2016-07-06 18:27
Are you seeing this issue on Android or iOS?

**Comment by bruno-ian** [comment] 2016-07-08 17:16
I saw this on two different Android devices.
Didnt tried iOS yet...
thnx.

**Comment by bruno-ian** [comment] 2016-07-14 02:23
Any way of fixing it?

**Comment by rampara** [comment] 2016-07-15 22:39
I'm having trouble reproducing this issue. I'm able to request a display a banner in one orientation, and then rotate without any problems. I've attached a video of the behavior I'm seeing with the sample application from this repository. 

[BannerRotate.zip](https://github.com/googleads/googleads-mobile-unity/files/366939/BannerRotate.zip)

**Comment by bruno-ian** [comment] 2016-07-28 03:09
Sorry, maybe I am expressing myself wrongly and have omited to say that it is with interstitials.

The app is configured to autorotate in Unity, but if it is in landscape mode when is going to display an instertitial rotates to portrait (and stays that way while is displaying it) then it goes back to landscape. 

Which for me is weird and incorrect... 
Maybe this is the correct behaviour and I'm wrong.

Thank you!

**Comment by rampara** [comment] 2016-08-16 18:38
The expected behavior of interstitials is to have the same orientation of that of the device at ad request time (not the orientation of the device when the ad is shown). Is this not the behavior you're seeing?

**Comment by rampara** [comment] 2016-11-30 00:56
Closing this issue due to it's age and non-response. If this issue persists for you, please re-open the issue.

**Closed** 2016-11-30 00:56 UTC
Labels: support question
