### ISSUE TITLE
Conflict between Vungle Plugin and Google mobile Ads?

### ISSUE THREAD

**Issue by ForestJungle** [googleads/googleads-mobile-unity#309] opened 2016-11-19 07:02 UTC
Hi everyone.I'm having a problem that I can't fix.When I import google mobiles ads in Plugin will generate 2 files play-services-ads-9.8.0 ,play-services-ads-lites-9.8.0 and some others.I continue import Vungle Plugins then I can't build on android.It show error "Unable to convert classes into dex the format".
I found that it conflict between 2 files above with "project" files in Plugins/Vungle_lib/project.If I delete 2 this files or "project" files in Vungle_lib and then I can build but can't show Ads Admob or video Vungle..Plz fixed it for me.Thank you so much.

**Comment by rampara** [comment] 2016-11-30 00:53
The conflict is caused by the inclusion of Google Play services in Vungle's Unity plugin. When importing the Vungle Unity package, don't include the `google-play-services_lib` directory.

**Comment by ForestJungle** [comment] 2016-12-22 09:14
Hello Everyone.I'm having a big problems.I use reward admob with Unity ads and Vungle Ads.After Video finish Unity ads does work but Vunlge is not.
When I click X button to turn off Vungle ads then Game crash.Can anyone suggestion for me? Thanks a lot! :)

**Comment by rampara** [comment] 2017-01-06 23:02
Closing this issue as your original issue seems to have been resolved and your latest comment is a duplicate of #325.

**Closed by rampara** 2017-01-06 23:02 UTC
Labels: support question
