### ISSUE TITLE
iOS Pod install : unable to read the license file for the spec UnityAds

### ISSUE THREAD

**Issue by alaslipknot** [googleads/googleads-mobile-unity#654] opened 2018-04-11 15:24 UTC
Hi, 

am getting this error when i do : 
`pod install --repo-update`

Error:

`[i] Unable to read the license file `/Users/ala/Desktop/CS1/Pods/UnityAds/LICENSE` for the spec `UnityAds (2.2.0)``

Here is the content of my pod file : 

```
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Unity-iPhone' do
pod 'GoogleMobileAdsMediationUnity', '2.2.0.0'
pod 'GoogleMobileAdsMediationVungle', '5.3.0.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
end

```

And here is the full output after doing **pod install** : 

```
Updating local specs repositories
  $ /usr/bin/git -C /Users/ala/.cocoapods/repos/master fetch origin --progress
  remote: Counting objects: 36, done.        
  remote: Compressing objects: 100% (36/36), done.        
  remote: Total 36 (delta 24), reused 0 (delta 0), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     f03814ae6d4..d2db3a2e1eb  master     -> origin/master
  $ /usr/bin/git -C /Users/ala/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/ala/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at d2db3a2e1eb [Add] FlexibleDiff 0.0.5

CocoaPods 1.5.0 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.5.0

  $ /usr/bin/git -C /Users/ala/.cocoapods/repos/master fetch origin --progress
  $ /usr/bin/git -C /Users/ala/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/ala/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at d2db3a2e1eb [Add] FlexibleDiff 0.0.5

CocoaPods 1.5.0 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.5.0

Analyzing dependencies
Downloading dependencies
Using Google-Mobile-Ads-SDK (7.29.0)
Using GoogleMobileAdsMediationUnity (2.2.0.0)
Using GoogleMobileAdsMediationVungle (5.3.0.0)
Using UnityAds (2.2.0)
Using VungleSDK-iOS (5.3.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 5 total pods installed.

[!] Unable to read the license file `/Users/ala/Desktop/CS1/Pods/UnityAds/LICENSE` for the spec `UnityAds (2.2.0)`

[!] Unable to read the license file `/Users/ala/Desktop/CS1/Pods/UnityAds/LICENSE` for the spec `UnityAds (2.2.0)`

```

any help please ?

thanks

**Comment by rampara** [comment] 2018-04-11 19:52
@alaslipknot can you try generating a new Xcode project from Unity instead of appending to the existing one that is causing this issue?

**Comment by alaslipknot** [comment] 2018-04-12 20:29
@rampara  yes tried that, still the same, i had to go back to the perversion version of GoogleMobileAdsMediationUnity, now am using 2.1 instead of 2.2 and the problem is gone, however this is related to my other post and even when this issue gone, unityAds callback are still not working.

**Comment by rampara** [comment] 2018-06-25 11:00
@alaslipknot is this issue still present for you with the latest UnityAds dependencies?

**Comment by rampara** [comment] 2018-07-20 20:53
Closing as not reproducible.

**Closed by rampara** 2018-07-20 20:53 UTC
Labels: P2, support question

**Comment by Izzyjm** [comment] 2019-08-01 18:58
I got this after Installing GoogleMobileAdsMediationUnity (3.1.0.0)

![Screen Shot 2019-08-01 at 1 56 37 PM](https://user-images.githubusercontent.com/24462583/62319771-5c503380-b464-11e9-8e56-21902d53c21c.png)

**Comment by wimbledon** [comment] 2019-08-18 14:36
I got the same warning message after pod installing `UnityAds` 3.2.0
![image](https://user-images.githubusercontent.com/3291853/63225921-af551500-c1de-11e9-8676-523b6ecddee4.png)

**Comment by stowy** [comment] 2019-08-19 23:57
Hi, this looks like an issue with 'UnityAds' and not with the Google Mobile
Ads SDK or Unity Ads mediation adapter.

Refer
https://github.com/CocoaPods/Specs/blob/master/Specs/2/e/8/UnityAds/3.2.0/UnityAds.podspec.json
.
- it doesn't appear that there is a LICENSE file in the linked zip file,
however I don't know for certain that that is where cocoapods is looking
for it.

**Comment by tegant** [comment] 2019-10-13 16:20
same here: 
```[!] Unable to read the license file `LICENSE` for the spec UnityAds (3.2.0)```

**Comment by wimbledon** [comment] 2019-10-13 16:32
Same issue with 3.3.0
`[!] Unable to read the license file `LICENSE` for the spec `UnityAds (3.3.0)``
