### ISSUE TITLE
Banner ad position changes after viewing interstitial ad.

### ISSUE THREAD

**Issue by greedvan** [googleads/googleads-mobile-unity#629] opened 2018-03-14 08:23 UTC
This error occurred on LG G Pro2 smartphone

tested the sample in the hello world.

I changed the position of the banner ad from top to bottom.
208line.
 this.bannerView = new BannerView(adUnitId, AdSize.SmartBanner, AdPosition.Bottom);

Then run the app, Follow the actions below

1. touch Request Banner button.
2. touch Request Interstitial button.
3. touch Show Interstitial button.

The position of the banner ad changes to the top.

When viewing an interstitial ad, the softkey is visible, and when the interstitial is closed, the softkey disappears and the position of the banner ad changes

**Comment by kobyle69** [comment] 2018-03-14 08:26
That's my hack to solve it: (just force it to the bottom every 5 secs)

private BannerView m_Banner;
public void Update()
{
	m_TimePassed += Time.deltaTime;
	if (m_TimePassed > 5)
	{
		m_Banner.SetPosition(AdPosition.Bottom);

		m_TimePassed = 0;
	}
}

**Comment by rampara** [comment] 2018-03-14 18:24
@greedvan @kobyle69 is this issue reproducible across all devices for you or only certain ones?

**Comment by greedvan** [comment] 2018-03-15 01:04
I tested on only one device.

This issue has not been resolved by processing the command to change the location of banner ads in the 'HandleOnAdClosed' event of interstitials.

public void HandleOnAdClosed(object sender, EventArgs args)
{
    bannerView.SetPosition(AdPosition.Bottom); //fail
}

**Comment by rampara** [comment] 2018-03-16 17:13
@greedvan using the latest version of the plugin and a variety of devices I'm unable to reproduce the issue. Linking a [video](https://drive.google.com/file/d/1ibkbWOrooZZlDKrZdXxjwpkzXY4NMALu/view?usp=sharing) to the behavior I'm seeing.

**Comment by BrianOSH** [comment] 2018-03-19 10:42
This also happens on my Hipstreet Electron 8" tablet.
![img_0366](https://user-images.githubusercontent.com/13030197/37591045-244d053a-2b62-11e8-93b3-1fa0a1641037.jpg)

**Comment by rampara** [comment] 2018-03-20 22:01
@BrianOSH I don't have access to that particular device. Were you able to replicate the issue on any other devices?

**Comment by BrianOSH** [comment] 2018-04-04 09:47
Hi
  Here is my temporary solution to this problem.

// called as a coroutine.
IEnumerator OnApplicationPause(bool pauseStatus)
{
        // check for application resume.
	if(pauseStatus == false)
	{
                // a small delay seems to be need here.
		yield return new WaitForSeconds(2);

                // reposition banner.
		bannerView.SetPosition(AdPosition.Bottom);
	}
}

If the banner also start in the wrong place. Try this code.

void Start()
{
        // create banner view, then reposition it after 10 seconds.
        Invoke("PositionBanner", 10);
}

public void PositionBanner()
{
	bannerView.SetPosition(AdPosition.Bottom);
}

**Comment by rampara** [comment] 2018-04-04 19:26
Continuing to keep this issue open until I can find I device that reproduces the issue.

**Comment by fzdravko** [comment] 2018-04-08 20:31
I have this problem too. It happens when I load Rewarded Video and then cancel it, banner ad change position from bottom to top. I have multiple devices and this happens only on one - Motorola Moto G (XT1032) - Android v5.1.

**Comment by rampara** [comment] 2018-04-12 22:10
Was finally able to reproduce the issue on my end. Putting together a workaround that should be pushed out shortly.

**Comment by rotter** [comment] 2018-04-19 03:42
As I mentioned on another related issue, a user of mine emailed today saying that after a Google update that she had yesterday it started working.

But then a few hours later she emailed again and said that only on the first few ads it worked, then after a while it stopped working again.

I cant try it as Im out of town, I will try on next Monday and write back.

**Comment by rampara** [comment] 2018-04-19 17:13
Will keep the issue open until the fix is verified.

**Comment by rotter** [comment] 2018-04-23 19:27
I have just tried and on the first 2 rewarded videos the banner was OK (bottom), then after the 3rd rewarded video the banner moved to the top.

Some comments:

I didnt update the AdMob SDK bundled on the game, I was expecting that the update would already be on the device due to the automatic updates on Google modules, if I should have downloaded the newest SDK let me know and I will re-test
But I dont know which version of the AdMob SDK is running on the device, I dont know how to check. Google play services version on the device is 12.5.29
I'm not 100% sure but I think it was the same banner during the whole test, so the problem didnt happen during a banner switch

**Comment by gammlstudio** [comment] 2018-04-28 20:00
I have the same problem when showing an interstital or a video ad the banner ad jumps from the bottom to the top. Banner ad position change also occures when minimizing the app and then returning to it. When the banner is shown on the bottom, then to the top and vice versa. At the moment I have used only Huawei P6 for testing, so not sure if this happens on other devices.
Does the hiding and delaying the show of a banner work for a quick fix?

**Comment by rotter** [comment] 2018-04-28 20:45
@gammlstudio this problem only happens on Android 5.0/5.1 it seems, and no workaround was posted here yet from what I can tell

**Comment by gammlstudio** [comment] 2018-04-28 21:58
@rotter Thank you for your replay and yes, my testing device runs on 5.1.1. Hopefully the bug gets fixed in the future though.

**Comment by rampara** [comment] 2018-05-02 21:09
@gammlstudio @rotter I've linked a video where I attempted to reproduce the issue on a Moto G running Android 5.1. Prior to v3.13.1 of this plugin, I was able to reproduce the issue but am no longer able to. Are you performing different steps that what I've done in the video?

https://drive.google.com/file/d/1nd08sYZ47iwTtD9m8pVFxLE-haYmgHd8/view?usp=sharing

**Comment by rotter** [comment] 2018-05-02 21:14
Hi @rampara . As I mentioned I didnt update the packaged AdMob on the APK plugin to test, so if AdMob v3.13.1 isnt bundled in GPS 12.5.29 then I was testing with the old AdMob plugin (and therefore you can ignore my last message from a few days ago).

**Comment by rampara** [comment] 2018-05-02 21:16
@rotter the fix for this issue was included with the plugin itself and not the Google Mobile Ads SDK.

**Comment by rotter** [comment] 2018-05-02 21:27
So that means my players won't get a fix until automatically via Google Play Services, and I have to download the new plugin and roll out an update with the new plugin... correct?

If the answer is "yes" then you can ignore my message from 9 days ago, as I didnt download the plugin and rebuilt, I mis-thought the fix was rolled out automatically via GPS.

**Comment by rampara** [comment] 2018-07-24 19:55
Closing this issue as it should no longer be present on the latest version of this plugin.

**Closed by rampara** 2018-07-24 19:55 UTC
Labels: P2, plugin bug
