### ISSUE TITLE
Some ads look weird, not sure if this is related to the ad or if its a bug

### ISSUE THREAD

**Issue by dweebster666** [googleads/googleads-mobile-unity#217] opened 2016-05-08 13:00 UTC
Hi!

I've been using this integration for some time and it works great but I've noticed that certain ads looks strange. It seems like the content within the ad is not loading to 100% and causing it to display a sort of error message. 

See the image below
![image](https://cloud.githubusercontent.com/assets/19251017/15097923/67449120-152d-11e6-8830-dada50a9511d.png)

The message is in Swedish probably because the device is in Swedish but in the ad it says " [ 1 ] New object". This seems more like an error message to me rather than a real ad. 

Does that error message mean anything to you?

**Comment by rampara** [comment] 2016-05-13 21:29
Are you able to easily reproduce this error? If so, can you provide a Charles log of an ad request where you see this error? It would help me investigate.

**Comment by rampara** [comment] 2016-08-16 18:43
Closing issue due to non-response. If this issue persists, please re-open.

**Closed by rampara** 2016-08-16 18:43 UTC
Labels: support question
