### ISSUE TITLE
Latest version of  Google Mobile Ads SDK 

### ISSUE THREAD

**Issue by ChaserKnight** [googleads/googleads-mobile-unity#831] opened 2019-01-18 18:53 UTC
I am using the latest version of this plugin (v3.15.1) and Unity 2018.3 on macOS.
And when I make a build and run it on device, there is a message in the XCode about updating to the latest "Google Mobile Ads SDK", it says I am using (7.25.0) and there is a url for the release notes (https://developers.google.com/admob/ios/rel-notes) and the release notes shows that (7.25.0) is from 2017 which is very old and current version is (7.37.0) so why do I have an old SDK while using the latest version of this googleads-mobile-unity plugin? Am I missing something, I am using cocoapods as it says on Unity console after making a build. So do I need to install the latest "Google Mobile Ads SDK" using cocoapods, if yes then how do I install it using cocoapods. 

I found a command called:
`pod install --repo-update`
but running it in the terminal says "-bash: pod: command not found".

Please help, I can see the ads and AdMob is working fine but I want to know if I should update to the latest "Google Mobile Ads SDK" as the XCode console says.

**Comment by rampara** [comment] 2019-01-23 03:11
@ChaserKnight even when you create a new Xcode project, the latest version of the GMA SDK is not pulled in? [Installing Cocoapods](https://guides.cocoapods.org/using/getting-started.html) on your machine should allow you to run the `pod install --repo-update
` command.

**Comment by ChaserKnight** [comment] 2019-01-23 07:50
As I build from Unity, it generates a new Xcode project everytime, and cocoapods is already installed on my Mac. Is there a specific process for running this repo update command? I just open terminal then paste and run the command and it shows the "-bash: pod: command not found" error. I am not very familiar with terminal commands. Do I have to switch to some directory before running the update command?

**Comment by rampara** [comment] 2019-01-23 21:14
@ChaserKnight you may have installed Cocoapods in a location that's not referenced in your bash Path. How did you install Cocoapods originally?

**Comment by ChaserKnight** [comment] 2019-01-23 21:54
@rampara When I first imported the AdMob plugin into Unity, it installed Cocoapods automatically, it was installed through Unity by the plugin. Can you please tell me how can I reference it in the bash path?

**Comment by rampara** [comment] 2019-01-23 21:59
@ChaserKnight looks like Cocoapods should be installed in the standard location by the plugin. Can you try running `sudo gem install cocoapods` in your temerinal just to be sure.

**Comment by ChaserKnight** [comment] 2019-01-24 07:21
@rampara My Cocoapods install directory is "/Users/ChaserKnight/.gem/ruby/2.0.0".
And I tried running the sudo gem install command you mentioned but it gave the following error:
`ERROR:  Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/latest_specs.4.8.gz)`

**Comment by ChaserKnight** [comment] 2019-01-24 07:37
@rampara One more thing is I have  macOS Sierra (v10.12.6), can that be a problem? Do I need to upgrade to latest macOS for this?

**Comment by rubelmusicwould8374** [comment] 2019-02-04 05:55
My New App http://app.appsgeyser.com/8460172/Rubel%20Musicwould
**
_Rubel_Musicwould_8460172 .apk
****
Banner Ads
ca-app-pub-7689122978757670/1062649510
Interstitial Ads
ca-app-pub-7689122978757670/5822530919
please Sir Activate Settings Admob Account Adjust-App

**Comment by UragayalaDeepika** [comment] 2019-07-31 15:25
Closing this for now. Feel free to comment here so that we can reinvestigate this issue if it is still reproducible with the latest version.

**Closed by UragayalaDeepika** 2019-07-31 15:25 UTC
Labels: P2, support question
