### ISSUE TITLE
Moving file failed issue

### ISSUE THREAD

**Issue by minjisong7334** [googleads/googleads-mobile-unity#569] opened 2017-11-21 07:32 UTC
Hi, I'm using Unity 5.6.1 and building Android with Internal(default) option and getting this error message. 

"Moving Temp/StagingArea/android-libraries/play-services-ads-license-11.6.0/classes.jar to Temp/StagingArea/android-libraries/play-services-ads-license-11.6.0/libs/classes.jar: No such file or directory" 

Added the most recent version of GoogleMobileAds.unitypackage. 
I checked that when I build it with Gradel there is no issue.
Does version 3.9.0 support Internal(default) building option?

**Comment by cwadoud** [comment] 2017-11-26 07:30
Same problem 😓

**Comment by rampara** [comment] 2017-11-28 19:43
@minjisong7334 @cwadoud I'm having trouble reproducing this error. Can you post the contents of the `Assets/Plugins/Android` directory of your Unity project?

**Comment by tanapp** [comment] 2017-12-10 18:09
Same problem.
Reproducing the error is simple. Just add the google play game plugin

**Comment by tanapp** [comment] 2017-12-10 23:07
How I solved the issue:
I moved (to save) and deleted the "gpgs-plugin-support" folder (Assets\GooglePlayGames\Editor\m2repository\com\google\games\gpgs-plugin-support\0.9.42\)
I ran Android Resolver > Force Resolve =>I got an error
I put back the folder in its place and ran Force Resolve again. And it worked.

**Comment by rampara** [comment] 2017-12-11 19:48
@tanapp based on the folder/ files you had to remove, it seems your error is caused by the Google Play Games plugin and not this one.

**Comment by tanapp** [comment] 2017-12-11 20:04
@rampara,
Well, as mentioned in my first post, I said to install google play games plugin to reproduce the issue. This is how I got this issue.
I guess Google Play Games and GoogleAds have some conflict and I'm giving the way I made it work.
Anyway, are we obliged to prohibit ourself from using Google Play Games if we want to use GoogeAds ?

**Comment by rampara** [comment] 2017-12-15 00:57
@tanapp @minjisong7334 wasn't able to repro this problem. Started with the Helloworld sample app from this repo, imported the latest version of this plugin, imported the latest version of the Google Play Games plugin, force resolved dependencies and built with the internal build system. Using the steps I outlined, I was able to successfully create an Android build.

**Comment by rampara** [comment] 2018-01-30 23:19
Closing as I was unable to reproduce the issue. Please re-open if the issue persists for you.

**Closed by rampara** 2018-01-30 23:19 UTC
Labels: P2, support question

**Comment by tanapp** [comment] 2018-03-28 12:34
Wow.
I can reproduce the problem all the time with every new project.
I wished I could say "can't see the problem, so there is no problem" and get all my problems solved just by saying it.

**Comment by rchallenger** [comment] 2018-03-28 14:18
Something similar to your issue occured with GAD and resolver.
Solution was reducing the file name length by shortening depth of project location.
Try placing your Assets folder at the root of your drive.

**Comment by tanapp** [comment] 2018-03-28 14:58
Thx @rchallenger.
I had always find a way to solve this issue, as mentioned before.
The main problem is that every version of this google ads project have the same issue. Just look at the issues list. So instead of finding a solution, we have an "I can't see it so it doesn't exist" answer. Too bad.
