### ISSUE TITLE
Sometimes, fail to load banner and other error

### ISSUE THREAD

**Issue by Youngchangoon** [googleads/googleads-mobile-unity#470] opened 2017-07-31 06:44 UTC
![image uploaded from ios](https://user-images.githubusercontent.com/10609257/28765671-ee757278-7606-11e7-822d-e7415cf4cabd.jpeg)

Right now, we have critical issue in our app wth ADMOB.
Sometimes, the banner in the game fail to lad Ads and shows strange codes(check attached files).
Because of this issue, we can NOT provide our Ads to users.
Also, want to know what is problem on this issues.

Please, if you have any idea just let us know as soon as possible.

Thank you.

**Comment by rampara** [comment] 2017-07-31 16:54
@Youngchangoon can you provide a Charles log for an ad request that experiences the issue you're describing.

**Comment by Youngchangoon** [comment] 2017-08-03 08:16
@rampara I can't capture this error during debug Charles..

This error was once on Android device real testing.

I have one question.
This error has occurred before?

**Comment by rampara** [comment] 2017-08-03 21:46
@Youngchangoon I'm unable to reproduce the error. If you are able to reproduce it, a Charles log would help investigate.

**Comment by rampara** [comment] 2017-09-26 21:16
Closing this issue due to non-response.

**Closed by rampara** 2017-09-26 21:16 UTC
Labels: support question
