### ISSUE TITLE
AdMob causes a crash on iOS when calling LoadAdError.ToString() on main thread

### ISSUE THREAD

**Issue by aroman** [googleads/googleads-mobile-unity#1658] opened 2021-06-18 20:49 UTC
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.12f1
  * Google Mobile Ads Unity plugin version: 6.0.0 
  * Platform: iOS 
  * Platform OS version: 14.6
  * Any specific devices issue occurs on: all devices
  * Mediation ad networks used, and their versions: none

#### Steps to reproduce:

1. Disconnect the phone from the internet (so as to trigger a Load Error)
2. in `rewardedAd.OnAdFailedToLoad` callback handler, call `LoadAdError.ToString()` which is provided via `AdFailedToLoadEventArgs args`, from the main thread. I've included sample code below.
3. App crashes

#### Code sample

```cs
var rewardedAd = new RewardedAd(adUnitId);
rewardedAd.OnAdFailedToLoad += (o, args) => {
// this does NOT crash
var adErrorString = args.LoadAdError.ToString();
  MobileAdsEventExecutor.ExecuteInUpdate(() =>
  {
      // this line crashes
      var adErrorStringInner = args.LoadAdError.ToString();
  });
}
```

#### Stacktrace

here is a stacktrace demonstrating the issue originating in [GADUInterface.m:767](https://github.com/googleads/googleads-mobile-unity/blob/219bc85e7e82bbd04d89c5bfedd235bab43e2324/source/plugin/Assets/Plugins/iOS/GADUInterface.m#L767)

```
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000d8a9ecb0e9b0 -> 0x00000029ecb0e9b0 (possible pointer authentication failure)
VM Region Info: 0x29ecb0e9b0 is in 0x1000000000-0x7000000000;  bytes after start: 111345199536  bytes before end: 300971660879
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)      fc0000000-1000000000 [  1.0G] ---/--- SM=NUL  ...(unallocated)
--->  GPU Carveout (reserved) 1000000000-7000000000 [384.0G] ---/--- SM=NUL  ...(unallocated)
      UNUSED SPACE AT END

Triggered by Thread:  0

Thread 0 name:
Thread 0 Crashed:
0   libobjc.A.dylib               	0x00000001a9ce71e0 objc_msgSend + 32
1   UnityFramework                	0x0000000106fa3a2c 0x105f14000 + 17365548
2   UnityFramework                	0x0000000108005df0 Externs_GADUGetAdErrorDescription_m42A11399A030A982610D6CA81E960AF3BB6AD3FF + 4 (GoogleMobileAds.iOS.cpp:7806)
3   UnityFramework                	0x0000000108005df0 LoadAdErrorClient_ToString_m49AE69319FBC410CE10FECD63873C5B5F41CA119 + 20 (GoogleMobileAds.iOS.cpp:10102)
4   UnityFramework                	0x000000010858de2c Invoke + 16 (mscorlib15.cpp:47)
5   UnityFramework                	0x000000010858de2c StringBuilder_AppendFormatHelper_m1AC42B5BFE6A5D5A48D6BC2E0B299E163CF7B857 + 1572 (mscorlib15.cpp:35136)
6   UnityFramework                	0x000000010858d52c String_FormatHelper_mF468B62759AD66A7FB75DCC196BCFB402DD4CA19 + 100 (mscorlib15.cpp:27402)
7   UnityFramework                	0x00000001085829c8 String_Format_mB3D38E5238C3164DB4D7D29339D9E225A4496D17 + 64 (mscorlib15.cpp:27193)
8   UnityFramework                	0x0000000107037a18 U3CU3Ec__DisplayClass27_0_U3COnAdFailedToLoadU3Eb__0_m3CF464822FBC497E68DC4A034DFC45AB91644679 + 104 (Assembly-CSharp4.cpp:9841)
9   UnityFramework                	0x00000001084eb720 Action_Invoke_m3FFA5BE3D64F0FF8E1E1CB6F953913FADB5EB89E + 276
10  UnityFramework                	0x0000000107ffe9f4 MobileAdsEventExecutor_Update_m744E5546FD4841F0D152535462BBAC94A3930ED4 + 532 (GoogleMobileAds.Common.cpp:1465)
11  UnityFramework                	0x00000001060a6488 RuntimeInvoker_TrueVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5(void (*)(), MethodInfo const*, void*, void**) + 20 (Il2CppInvokerTable.cpp:161679)
12  UnityFramework                	0x0000000106f0dd24 0x105f14000 + 16751908
13  UnityFramework                	0x00000001067d0344 scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool) + 112
14  UnityFramework                	0x00000001067dbdf8 0x105f14000 + 9207288
15  UnityFramework                	0x00000001067e7dbc 0x105f14000 + 9256380
16  UnityFramework                	0x000000010663f7b8 0x105f14000 + 7518136
17  UnityFramework                	0x0000000106702b00 0x105f14000 + 8317696
18  UnityFramework                	0x0000000106702b40 0x105f14000 + 8317760
19  UnityFramework                	0x0000000106702e08 0x105f14000 + 8318472
20  UnityFramework                	0x0000000106aba768 UnityPlayerLoopImpl(bool) + 112

```

**Comment by bab202** [comment] 2021-07-09 11:14
Thanks man, my app has crash free decrease from 100% to 60% and I cannot reproduce the problem until I see your reported issue. Turn off the internet and bam, cannot believe this sdk make your app crash without internet, so sad :((. But still thank to you so much because report the issue.

**Comment by fightaway** [comment] 2021-09-18 06:28
The same issue with you!

**Comment by yerfdogj** [comment] 2021-10-20 05:22
This issue still exists in v6.1.2.

**Comment by keepup** [comment] 2021-12-21 03:38
#1693

**Comment by ChaserKnight** [comment] 2022-02-06 17:32
I am also facing this issue, using v6.1.2, is there any update on this?

**Comment by NVentimiglia** [comment] 2022-04-08 06:54
This will be fixed in the next release.

**Closed by NVentimiglia** 2022-04-08 06:54 UTC
