### ISSUE TITLE
iOS LatencyMillis value is wrong

### ISSUE THREAD

**Issue by chengwenpo** [googleads/googleads-mobile-unity#2801] opened 2023-06-29 05:28 UTC
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.26f1
  * Google Mobile Ads Unity plugin version: 8.2.0
  * Platform: iOS
  * Platform OS version: iOS 15.4.1
  * Any specific devices issue occurs on: any ios device
  * Mediation ad networks used, and their versions: Google-Mobile-Ads-SDK 10.5.0

### [REQUIRED] Step 2: Describe the problem

LatencyMillis from Platforms/iOS/AdapterResponseInfoClient.cs return wrong value, such as -9.22337e+18

#### Steps to reproduce:

1.Open unity sample project HelloWorld
2.Add log to print LatencyMillis 
3.Build iOS project
4.Build and run xcode project in iOS device

#### Relevant Code:

```
AdRequest adRequest = new AdRequest();
RewardedAd.Load(adUnitId, adRequest,(RewardedAd ad, LoadAdError error) =>
{
    ...
    var adapterResponses = ad.GetResponseInfo().GetLoadedAdapterResponseInfo();
    var latencyMillis = adapterResponses?.LatencyMillis ?? 0;
    Debug.Log($"HandleOnAdLoaded: latency:{latencyMillis} info:{ad.GetResponseInfo()}");
});
```

**Comment by chengwenpo** [comment] 2023-06-29 06:24
latency type cast  cause this result

in file Plugins/iOS/GADUInterface.m 
latency is casted from double to long
```
const long GADUAdapterResponseInfoLatency(GADUTypeAdapterResponseInfoRef adapterResponseInfo) {
  GADAdNetworkResponseInfo *info = (__bridge GADAdNetworkResponseInfo *)adapterResponseInfo;
  return (long)[NSNumber numberWithLong:info.latency];
}
```
in file Platforms/iOS/AdapterResponseInfoClient.cs
latency is cast from long to double,and then convert to long
```
        public long LatencyMillis
        {
            get
            {
                double latency = Externs.GADUAdapterResponseInfoLatency(_adapterResponseInfoPtr);
                return Convert.ToInt64(latency * 1000);
            }
        }
```

**Comment by NVentimiglia** [comment] 2023-06-29 19:53
@chengwenpo 

Confirmed the issue with incorrect Latency on iOS.  I will push for a fix.

**Comment by chengwenpo** [comment] 2023-07-17 04:32
!!!The lasted update did not fix latency value.!!!

In file Plugins/iOS/GADUInterface.m, the type of info.latency is double, just return the original double value.
```
const double GADUAdapterResponseInfoLatency(GADUTypeAdapterResponseInfoRef adapterResponseInfo) {
  GADAdNetworkResponseInfo *info = (__bridge GADAdNetworkResponseInfo *)adapterResponseInfo;
  // return (long)[NSNumber numberWithLong:info.latency];
  return info.latency;
}
```
In file Platforms/iOS/Externs.cs, change the return value to double.
```
        internal static extern double GADUAdapterResponseInfoLatency(
            IntPtr adapterResponseInfoRef);
```
In file Platforms/iOS/AdapterResponseInfoClient.cs, declare latency as double.
```
        public long LatencyMillis
        {
            get
            {
                double latency = Externs.GADUAdapterResponseInfoLatency(_adapterResponseInfoPtr);
                return Convert.ToInt64(latency * 1000);
            }
        }
```
Those change will fix the incorrect latency value.

**Comment by NVentimiglia** [comment] 2023-07-18 22:40
Thank you @chengwenpo 

We will take another look.

**Comment by GreedyBM** [comment] 2024-03-22 05:42
Hi, I'm getting a null reference exception for the same API on IOS. 

Unity version: 2022.3.21f1 (but occurs when using other editor versions as well)
Google Mobile Ads Unity plugin version: 8.2.0.0
Platform OS version: iOS 17.0.3
Xcode version: 15.3
Any specific devices issue occurs on: any ios device

`public long LatencyMillis => _client.get_LatencyMillis ();`

 _client  could be the cause of the issue

**Comment by NVentimiglia** [comment] 2024-03-22 21:12
Thanks,

We are looking into this now.

**Comment by NVentimiglia** [comment] 2024-06-25 23:11
Fixed in latest.

**Closed by NVentimiglia** 2024-06-25 23:11 UTC
Labels: P2, Plugin
