### ISSUE TITLE
Mopub interstitial OnAdClosed event has delay 10s.

### ISSUE THREAD

**Issue by ikitae** [googleads/googleads-mobile-unity#798] opened 2018-11-02 05:33 UTC
Mopub interstitial OnAdClosed event has delay 10s.

**Comment by rampara** [comment] 2018-12-05 21:35
@ikitae is this problem still reproducible for you with the latest version of the MoPub mediation support package.

**Comment by rampara** [comment] 2019-01-23 03:50
Closing due to non-response.

**Closed by rampara** 2019-01-23 03:50 UTC
Labels: P2, support question
