### ISSUE TITLE
Game crashes after Unity splash screen in Android

### ISSUE THREAD

**Issue by zodlanier** [googleads/googleads-mobile-unity#169] opened 2016-02-15 06:02 UTC
I added only the basic code from the AdMob tutorial page for smart banners inside the default awake function, along with the id.

Here it is:
#if UNITY_ANDROID
			string adUnitId = "ca-app-pub-******************/************";
			#elif UNITY_IPHONE
			string adUnitId = "ca-app-pub-******************/************";
			#else
			string adUnitId = "unexpected_platform";
			#endif

			// Create a 320x50 banner at the top of the screen.
			BannerView bannerView = new BannerView(adUnitId, AdSize.Banner, AdPosition.Top);
			// Create an empty ad request.
			AdRequest request = new AdRequest.Builder().Build();
			// Load the banner with the request.
			bannerView.LoadAd(request);

It does build to the device but crashes every single time after the unity splash screen. Strangely, no error log.

**Comment by rampara** [comment] 2016-02-16 19:28
Is there nothing in logcat that can point towards what is causing the crash?

**Comment by zodlanier** [comment] 2016-02-17 02:26
Hi, thanks for replying.Sad, i couldn't save my comment in github.
If i run it in Unity Editor, in the console it says that:>Created DummyClient>Dummy CreateBannerView>Dummy LoadAd 
However, if i build and run it in Android, there is nothing in the console and it crashed every time after the unity splash screen showed up. Alternatively, if i command out the requestBanner() function, there is no crash. Thanks @rampara. I am not sure what causes this crash since i follow the exact instruction shown here.
|   |
|   |  |   |   |   |   |   |
| Game Developers: Ads Best PracticesThis guide discusses best practices for integrating banner and interstitial adsinto games using the Google Mobile Ads SDK.  |
|  |
| View on developers.google.com | Preview by Yahoo |
|  |
|   |


 

    On Wednesday, February 17, 2016 2:29 AM, rampara <notifications@github.com> wrote:
 

 Is there nothing in logcat that can point towards what is causing the crash?—

**Comment by rampara** [comment] 2016-02-17 21:10
Can you check logcat for the cause of the crash instead of the Unity console.

**Comment by zodlanier** [comment] 2016-02-18 03:03
well i think this is it. runtime error inside the logcat:
E/AndroidRuntime(15469): Caused by: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 8487000 but found 7571000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" /> 

    On Thursday, February 18, 2016 4:10 AM, rampara <notifications@github.com> wrote:
 

 Can you check logcat for the cause of the crash instead of the Unity console.—

**Comment by rampara** [comment] 2016-02-18 21:41
Did you modify the Android manifest file for the Google Mobile Ads Unity plugin? Or are you including any other plugins with an Android manifest that has an invalid google_play_services_version declaration?

**Comment by zodlanier** [comment] 2016-02-19 02:03
Yes i did modify the Android manifest file and also the version.xml. The last time, i included the google-play-game-services plugin. Now that it is unused and the latest plugin is already compatible, i removed it and changed everything back to the original state with only Google Mobile Ads Unity plugin. Thank you. 

    On Friday, February 19, 2016 4:41 AM, rampara <notifications@github.com> wrote:
 

 Did you modify the Android manifest file for the Google Mobile Ads Unity plugin? Or are you including any other plugins with an Android manifest that has an invalid google_play_services_version declaration?—

**Comment by rampara** [comment] 2016-02-19 19:05
If you can link to a project where you can replicate this problem it can help me investigate further.

**Comment by rampara** [comment] 2016-08-16 18:46
Closing issue due to non-response. If this issue persists, please re-open.

**Closed by rampara** 2016-08-16 18:46 UTC
Labels: support question
