### ISSUE TITLE
When apps is on runtime, application is shot down.

### ISSUE THREAD

**Issue by sptkjs** [googleads/googleads-mobile-unity#881] opened 2019-03-28 02:35 UTC
Hi, I have issue relative admob plugin on android 9.
I use unity 2017.4.24f1, and import admob plugin v3.16, also play games plugin v0.9.62.

I modified AndroidManifest.xml about meta-data.

However, some Android 9 devices is crashed.

I remain the report sample error:
java.lang.Error: FATAL EXCEPTION [Thread-44]
Unity version     : 2017.4.24f1
Device model      : samsung SM-G950F
Device fingerprint: samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXS4DSC2:user/release-keys
Caused by
1.  at jq.b (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):3)
2.  at jp.a (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):3)
3.  at jr.a (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):19)
4.  at com.google.android.gms.ads.internal.util.ar.a (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):15)
5.  at iu.a (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):20)
6.  at iu.run (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):8)

Caused by: java.lang.ClassNotFoundException: 
1.  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:134)
2.  at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
3.  at ad.loadClass (com.google.android.gms.dynamite_dynamiteloader@15090083@15.0.90 (100408-231259764):4)
4.  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)

**Comment by cgvmlg85** [comment] 2019-04-03 12:08
Hi,
Same problem here with Android 9:
Samsung Galaxy S8 (dreamlte), Android 9
Informe 1

java.lang.Error: FATAL EXCEPTION [Thread-14]
Unity version     : 2017.4.3f1
Device model      : samsung SM-G950F
Device fingerprint: samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXS4DSC2:user/release-keys
Caused by
  at jq.b (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):3)
  at jp.a (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):3)
  at jr.a (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):19)
  at com.google.android.gms.ads.internal.util.ar.a (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):15)
  at iu.a (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):20)
  at iu.run (com.google.android.gms.dynamite_adsdynamite@15090083@15.0.90 (100408-231259764):8)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:134)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
  at ad.loadClass (com.google.android.gms.dynamite_dynamiteloader@15090083@15.0.90 (100408-231259764):4)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)

**Comment by eleguni** [comment] 2019-04-06 16:06
I have the same problem
unity version is 2018.2.11f1
on runtime it crashes

**Comment by Andre2553** [comment] 2019-04-07 19:16
I have the same problem

**Comment by stowy** [comment] 2019-04-08 17:33
Does it have a message saying which class was not found? Something like:

```
Caused by java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads...." on path: DexPathList[...
```

**Comment by sptkjs** [comment] 2019-04-09 00:37
@stowy No. It doesn't have any messages that "Class Not Found".

**Comment by s4relok** [comment] 2019-04-15 09:18
Same problem, lot of affected users in the last month.

Sony Xperia XZ1 (G8342), Android 9

java.lang.Error: FATAL EXCEPTION [Thread-276]
Unity version     : 2017.4.23f1
Device model      : Sony G8342
Device fingerprint: Sony/G8342/G8342:9/47.2.A.10.28/1345156320:user/release-keys
Caused by
  at lt.b (com.google.android.gms.policy_ads_fdr_dynamite@30004@30004.238272502.238272502:2)
  at ls.a (com.google.android.gms.policy_ads_fdr_dynamite@30004@30004.238272502.238272502:1)
  at lu.a (com.google.android.gms.policy_ads_fdr_dynamite@30004@30004.238272502.238272502:18)
  at com.google.android.gms.ads.internal.util.ar.a (com.google.android.gms.policy_ads_fdr_dynamite@30004@30004.238272502.238272502:10)
  at kx.a (com.google.android.gms.policy_ads_fdr_dynamite@30004@30004.238272502.238272502:7)
  at kx.run (com.google.android.gms.policy_ads_fdr_dynamite@30004@30004.238272502.238272502:2)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:134)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
  at ac.loadClass (com.google.android.gms.dynamite_dynamiteloader@16089083@16.0.89 (100408-239467275):4)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)

**Comment by keyserjaya** [comment] 2019-04-16 19:02
Go to AndroidManifest.xml (located in: Assets/Plugins/Android/GoogleMobileAdsPlugin)

Replace "[ADMOB APPLICATION ID]" to our "Admob appId" we are good to go!
No more crash on runtime.

Good luck ;)

**Comment by JanOrsuliak** [comment] 2019-04-17 15:45
> 
> 
> Go to AndroidManifest.xml (located in: Assets/Plugins/Android/GoogleMobileAdsPlugin)
> 
> Replace "[ADMOB APPLICATION ID]" to our "Admob appId" we are good to go!
> No more crash on runtime.
> 
> Good luck ;)
> 
> This issue is same as #848

sadly thats not true ... yes crash will uccur in case of unassigned app id but 

there are crashes like this 

java.lang.Error: FATAL EXCEPTION [Thread-220]
Unity version     : 2018.3.3f1
Device model      : samsung SM-G950F
Device fingerprint: samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXU4DSBA:user/release-keys
Caused by
 
  at lt.b (com.google.android.gms.policy_ads_fdr_dynamite@30004@30004.238272502.238272502:2) 
  at ls.a (com.google.android.gms.policy_ads_fdr_dynamite@30004@30004.238272502.238272502:1) 
  at lu.a (com.google.android.gms.policy_ads_fdr_dynamite@30004@30004.238272502.238272502:18) 
  at com.google.android.gms.ads.internal.util.ar.a (com.google.android.gms.policy_ads_fdr_dynamite@30004@30004.238272502.238272502:10) 
  at kx.a (com.google.android.gms.policy_ads_fdr_dynamite@30004@30004.238272502.238272502:7) 
  at kx.run (com.google.android.gms.policy_ads_fdr_dynamite@30004@30004.238272502.238272502:2)
Caused by: java.lang.ClassNotFoundException:  
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:134) 
  at java.lang.ClassLoader.loadClass (ClassLoader.java:379) 
  at ac.loadClass (com.google.android.gms.dynamite_dynamiteloader@16089083@16.0.89 (100408-239467275):4) 
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)

which affect only small amount off Android 9 user base

**Comment by s4relok** [comment] 2019-04-21 08:37
> temporary fix is lower target api in unity from 28 to 27 which brings another problems but solves this one

And what another problems it brings?

**Comment by stowy** [comment] 2019-04-22 17:31
I believe this is related to https://developer.android.com/about/versions/pie/android-9.0-changes-28#apache-p.

A fix if this is the case would be to add the following to the AndroidManifest.xml:
```xml
<uses-library android:name="org.apache.http.legacy" android:required="false"/>
```

**Comment by stowy** [comment] 2019-05-16 18:58
Should be fixed in v3.17.0

**Closed by stowy** 2019-05-16 18:58 UTC

**Comment by hardapps1692** [comment] 2019-07-05 14:10
> I believe this is related to https://developer.android.com/about/versions/pie/android-9.0-changes-28#apache-p.
> 
> A fix if this is the case would be to add the following to the AndroidManifest.xml:
> 
> ```
> <uses-library android:name="org.apache.http.legacy" android:required="false"/>
> ```

This not working. App Still crashing with the same error.

**Comment by stowy** [comment] 2019-07-11 22:19
There has been a new android and unity release this week, 3.18.1, please try with the latest version.
