### ISSUE TITLE
 Exception caught while getting parental controls.

### ISSUE THREAD

**Issue by augustli2009** [googleads/googleads-mobile-unity#296] opened 2016-10-22 07:38 UTC
I'm keeping get this error....Anyone know what is this....thanks..

10-22 15:24:10.912  5870  5870 I Ads     : Starting ad request.
10-22 15:24:10.912  5870  5870 I Ads     : Use AdRequest.Builder.addTestDevice("************_hidden**_***************") to get test ads on this device.
10-22 15:24:13.386 30600  6088 W Ads     : Exception caught while getting parental controls.
10-22 15:24:13.386 30600  6088 W Ads     : java.util.concurrent.TimeoutException: CallbackFuture timed out.
10-22 15:24:13.386 30600  6088 W Ads     :  at com.google.android.gms.ads.internal.util.future.a.get(:com.google.android.gms:154)
10-22 15:24:13.386 30600  6088 W Ads     :  at com.google.android.gms.ads.internal.request.service.c.b(:com.google.android.gms:394)
10-22 15:24:13.386 30600  6088 W Ads     :  at com.google.android.gms.ads.internal.request.service.c.a(:com.google.android.gms:230)
10-22 15:24:13.386 30600  6088 W Ads     :  at com.google.android.gms.ads.internal.request.service.c.a(:com.google.android.gms:602)
10-22 15:24:13.386 30600  6088 W Ads     :  at com.google.android.gms.ads.internal.request.service.j.run(:com.google.android.gms:617)
10-22 15:24:13.386 30600  6088 W Ads     :  at com.google.android.gms.ads.internal.util.x.call(:com.google.android.gms:1055)
10-22 15:24:13.386 30600  6088 W Ads     :  at com.google.android.gms.ads.internal.util.y.run(:com.google.android.gms:75)
10-22 15:24:13.386 30600  6088 W Ads     :  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
10-22 15:24:13.386 30600  6088 W Ads     :  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-22 15:24:13.386 30600  6088 W Ads     :  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-22 15:24:13.386 30600  6088 W Ads     :  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-22 15:24:13.386 30600  6088 W Ads     :  at java.lang.Thread.run(Thread.java:833)

**Comment by rampara** [comment] 2016-10-27 00:04
@augustli2009 can you provide the steps to reproduce this error? Are you seeing this behavior for all ad requests?

**Comment by augustli2009** [comment] 2016-10-27 02:16
ye... the ad appears after I used vpn, but this error still exists.
I am in china..maybe it is the network issue, or maybe it is just because there is no google play service in my cellphone (because of the green wall, we can't visit google play,,,so all chinese android cellphones does not have google play service).

Github is also blocked.... but not everyday... I am using vpn now, hahahah

**Comment by rampara** [comment] 2016-11-05 00:24
@augustli2009 the warning you are seeing is likely caused by Google Play Services not being present on the device you're running your Unity application on (making parental control settings inaccessible). Closing this issue as you're able to request and display ads without issue.

**Closed by rampara** 2016-11-05 00:24 UTC
Labels: support question
