### ISSUE TITLE
Bottom banner cut by the navigation bar on Xperia SOL26

### ISSUE THREAD

**Issue by ValentinUsedREKTItsSuperEffective** [googleads/googleads-mobile-unity#576] opened 2017-11-29 03:28 UTC
Hello, I'm having trouble at displaying abmob banners. The banners are cut on an area corresponding to the bottom navigation bar instead of being overlay. This problem appear after I upgraded admob unity plugin from version 3.7.1 to 3.9.0. (I got another problem with the version 3.7.1:
https://groups.google.com/forum/#!topic/google-admob-ads-sdk/pTxy5x2GSxg)

Btw, banner are correctly displayed and overlayed by the navigation bar when using the plugin 3.1.2 .

【Game engine】
Unity 5.6.3f1

【Unity Admob plugin】
Google Mobile Ads Unity Plugin v3.9.0

【Device】
Android 5.0.2 Sony Xperia SOV26

【Code Unity C#】
BannerView _bannerView;

public void InitBanner() {
	_bannerView = new BannerView(AdConstants.ADMOB_BANNER_UNIT_ID, AdSize.Banner, AdPosition.Bottom);

	var request = new AdRequest.Builder().AddTestDevice("").Build();
	_bannerView.LoadAd(request);
}

Here is a screenshot of the bottom part of the phone, banner became a thin line:
![screenshot_2017-11-29-11-58-23](https://user-images.githubusercontent.com/20621210/33356357-61400a1e-d4ff-11e7-9822-d922c32e1e13.png)

Sorry for my poor English.

**Comment by nmtuhin** [comment] 2017-11-29 12:27
Currently, i am also facing the same problem. This is happening when Admob SDK and firebase messaging SDK are using together. 

Unity 5.6.3 p2
Admob plugin 3.9.0
Firebase Cloud Messaging SDK 
Without firebase cloud messaging SDK bottom had no problem.

![device-2017-11-29-212000](https://user-images.githubusercontent.com/5388162/33375059-fd2336b2-d54b-11e7-9d9f-2e0aacfdbfc4.png)
Here is screenshot

**Comment by nmtuhin** [comment] 2017-11-29 13:02
My Problem was solved by setting full-screen theme in the manifest file created by firebase SDK.
The problem was AdMob banner hide by the Navigation bar when the theme was not full screen.
Here is current capture
![device-2017-11-29-220200](https://user-images.githubusercontent.com/5388162/33376421-f62677f2-d550-11e7-9f51-2b372603be04.png)

**Comment by leoHN** [comment] 2017-11-30 00:17
Hi, I got same issue on Sony Z3 plus. Cleaning Project/Library and Project/Temp work for me. You can try it

**Comment by ValentinUsedREKTItsSuperEffective** [comment] 2017-11-30 02:42
@leoHN Nice try ^^ Thanks you but the problem remain after deleting Library and Temp project. 
@nmtuhin I think you are pointing the problem as no fullscreen theme appear in the manifest generated by Unity.

**Comment by nmtuhin** [comment] 2017-11-30 03:22
@ValentinUsedREKTItsSuperEffective 
For my case Yes because firebase overrides unity manifest but no theme was set.Unity set then set default device theme on the fly.
Here is how unity apply theme in android
https://blogs.unity3d.com/2015/07/16/android-themes-in-unity/
If I use only AdMob SDK there was no problem but if I add firebase messaging SDK problem occurred.
I am not fully confident about my explanation Need to study more.

**Comment by ValentinUsedREKTItsSuperEffective** [comment] 2017-11-30 04:58
It works after I updated Android SDK through Android Studio. 
There was certainly some incompatibility between the previously installed Android SDK and the latest AdMob unity plugins as it work well with the old 3.1.2 plugin. I didn't need to change android's Theme in the manifest.

Thanks you guys! Hope this will help other people.

**Comment by leoHN** [comment] 2017-11-30 07:09
@ValentinUsedREKTItsSuperEffective  did you imported Facebook Sdk into this project?

**Comment by ValentinUsedREKTItsSuperEffective** [comment] 2017-11-30 07:23
@leoHN We use Facebook Audience Network only. Do you think it might have any relation ?

--------

I skirt the problem by simply call the banner's show method after the navigation bar  hide. The problem occurred while Imobile text ads were display.

public class IMobileText : MonoBehaviour {

        public ReactiveProperty<bool> textDisplayed;

	void Start () {
		textDisplayed = new ReactiveProperty<bool> (false);
		IMobileSdkAdsUnityPlugin.addObserver (gameObject.name);
		IMobileSdkAdsUnityPlugin.registerFullScreen(
			IMOBILE_PUBLISHER_ID, 
			IMOBILE_MEDIA_ID, 
			IMOBILE_TEXT_UNIT_ID
		);
		IMobileSdkAdsUnityPlugin.start(IMOBILE_TEXT_UNIT_ID);
	}
		
	public void Show() {
		textDisplayed.Value = true;

		IMobileSdkAdsUnityPlugin.show(IMOBILE_TEXT_UNIT_ID);
	}

	void imobileSdkAdsSpotDidClose (string value) {
		textDisplayed.Value = false;
	}
}


Then control the banner show/hide using

`
showBanner = canShowBanner
			.CombineLatest (imobileText.textDisplayed, (canShowBanner, showText) => canShowBanner && !showText)
			.DistinctUntilChanged ()
			.StartWith (false)
			.ToReactiveProperty ();
`

ReactiveProperty<T> is part UniRx plugin.

**Comment by leoHN** [comment] 2017-11-30 07:29
I don't think so. I am getting same issue on once project. I am still trying to find what made the issue

**Comment by leoHN** [comment] 2017-11-30 07:29
it looks like the cause come from Manifest file

**Comment by leoHN** [comment] 2017-11-30 07:34
![image](https://user-images.githubusercontent.com/20719577/33419075-6b2db936-d5db-11e7-8944-7f85cd645a4d.png)
I make there changes to fix that issue. I don't know what line has resolved bug exactly.

**Comment by ValentinUsedREKTItsSuperEffective** [comment] 2017-11-30 07:40
In the activity, android:theme were added. This probably solved your bug.
I'm far from mastering android manifests.. ^^'

**Comment by leoHN** [comment] 2017-11-30 08:26
I fixed the issue by re-generating manifest by facebook sdk tool. But I still don't understand the cause of bug.

**Comment by leoHN** [comment] 2017-11-30 09:13
Hey @ValentinUsedREKTItsSuperEffective. Try to add `android:theme="@style/UnityThemeSelector"` to activity like this. `<activity android:name="com.unity3d.player.UnityPlayerNativeActivity" android:label="@string/app_name" android:theme="@style/UnityThemeSelector">`

**Comment by ValentinUsedREKTItsSuperEffective** [comment] 2017-12-27 07:06
Thank you guys for your answers.

I just installed the unity plugin GoogleMobileAds 3.10.0 and it seems that this problem has been solved. Can others people try it too ?

**Comment by rampara** [comment] 2018-01-09 18:58
@leoHN @nmtuhin following up to see if this is still an issue for you with this plugin.

**Comment by rampara** [comment] 2018-01-30 23:19
Closing due to non-response. Please re-open if this issue persists for you.

**Closed by rampara** 2018-01-30 23:19 UTC
Labels: P3, plugin bug
