### ISSUE TITLE
Admob 3.0.3 issue on Unity 5.3.2

### ISSUE THREAD

**Issue by mliitfall** [googleads/googleads-mobile-unity#186] opened 2016-03-16 05:32 UTC
After transferring the package, got some error :

Assets/GoogleMobileAds/Common/DummyClient.cs(29,22):
error CS0309: The type `Reward' must be convertible to `System.EventArgs' in order to use it as parameter `TEventArgs' in the generic type or method `System.EventHandler<TEventArgs>'

Assets/GoogleMobileAds/Common/IRewardBasedVideoAdClient.cs(32,15): 
error CS0309: The type `Reward' must be convertible to `System.EventArgs' in order to use it as parameter `TEventArgs' in the generic type or method `System.EventHandler<TEventArgs>'

Assets/GoogleMobileAds/Platforms/Android/RewardBasedVideoAdClient.cs(35,22):
error CS0309: The type `Reward' must be convertible to `System.EventArgs' in order to use it as parameter `TEventArgs' in the generic type or method `System.EventHandler<TEventArgs>'

Anyone can fix this?

**Comment by rampara** [comment] 2016-03-18 22:19
I'm having trouble reproducing this error. Have you modified the plugin so that Reward is no longer subclass of EventArgs?

**Comment by mliitfall** [comment] 2016-03-19 03:11
I have not modified the plugin, just unselected iOS package. Actually it does not show the error when first time transferred, while i am transferred googleplayservice plugin, it show that error.

**Comment by rampara** [comment] 2016-03-22 23:49
I'm not sure what you mean when you say you "transferred" the package. I'm able to build an Android APK without any errors using our [sample project]() and latest plugin release. Can you provide a link to a Unity project where you can reproduce the issue? This would help me investigate further.

**Comment by Samad313** [comment] 2016-04-21 08:18
I am having the exact same issue, @rampara  did you find the solution of it?

**Comment by rampara** [comment] 2016-04-22 17:52
@mliitfall Can you provide a link to a Unity project where you can reproduce the issue? A stripped down project such as our [sample project](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) would work best.

**Comment by aliakbo** [comment] 2016-05-17 18:53
This came up for me and the issue was I simply had a Reward class in my project and they were conflicting.

**Comment by rampara** [comment] 2016-08-16 18:44
Closing issue due to non-response. If this issue persists, please re-open.

**Closed by rampara** 2016-08-16 18:44 UTC
Labels: support question
