### ISSUE TITLE
3.10.0 banner has wrong position

### ISSUE THREAD

**Issue by SnnYsf** [googleads/googleads-mobile-unity#592] opened 2017-12-27 10:04 UTC
Why this error can not be fixed.
the bottom banner always on the top

Device: POP 4 6" 4G android (POP4-6_4G)
OS: Android 6.0
1080 × 1920
(DPI) :480
manufacturer: Alcatel
Only portrait screen used

**Comment by SnnYsf** [comment] 2017-12-28 11:53
Device:     One_E8 (htc_mecul_emea)
OS: Android 6.0
1080 × 1920
(DPI) :480
manufacturer: HTC

**Comment by rampara** [comment] 2017-12-28 18:31
@SnnYsf I don't have access to either of the devices you mentioned and am unable to reproduce the issue a wide variety of devices I tested with. Are you experiencing the issue on any other devices?

**Comment by SnnYsf** [comment] 2017-12-28 20:33
@rampara 
Only two users complained.
I wrote device information.
I will information you if there are new devices problem.

**Comment by arcv** [comment] 2018-01-02 17:21
I have the same issue. In my case, it is not always on the top.

Device: Samsung Note 4 (Android 6.0), Only portrait screen
Unity 5.6.4p3

**Comment by SnnYsf** [comment] 2018-01-03 00:35
bu problem android 6.0 çzel sanırım oguz

2018-01-02 20:21 GMT+03:00 Oguz <notifications@github.com>:

**Comment by arcv** [comment] 2018-01-03 09:36
Öyle görünüyor. 3.8.0 paketini kurdum, sorun ortadan kalktı gibi duruyor. 3.9.0 paketinde de aynı sorun var.

**Comment by SnnYsf** [comment] 2018-01-03 20:17
3.8.0 da sorunlu ondada başka cihazlarda sorun cıkıyor  3.7 sanırım o hariç hepsinde aynı problemler var.

**Comment by rampara** [comment] 2018-01-03 21:48
@arcv can you test with v3.10.0 of the plugin. I don't have access to a Note 4 running Android 6.0 but tested without issue on a Note 4 running Android 4.4. Also testing on a Samsung S7 running Android 6.0 and the banner is positioned correctly.

**Comment by rampara** [comment] 2018-01-05 20:32
@rampara will continue to investigate further once you're able to provide other devices the issue can be reproduced on.

**Comment by kobyle69** [comment] 2018-01-06 21:00
Confirmed this is reproducing on:
iPhone 7 (11.2.1)
iPhone 6 Plus (11.0.1)
When using SmartBanner 
using Unity 2017.1.2f1 (64-bit) + 7.27 SDK

**Comment by wazzion** [comment] 2018-01-08 16:06
I have the same issue. In my case, bottom banner is not always on the top.

Device 1: Nexus 5 (Android 5.0.1), Only portrait screen
Unity 5.6.1f1
Plugin version : 3.10

**Comment by stowy** [comment] 2018-01-08 17:28
@kobyle69 this issue is for Android banners. Have you noticed problems with positioning of the smart banner on iOS? Which version of the Unity plugin were you using? Can you please create a separate issue for the iOS smart banner problem and describe steps to reproduce, including which version of the Unity plugin (or alternatively ensure you are using the latest version).

**Comment by arcv** [comment] 2018-01-09 15:39
@rampara I was able to test on Zenfone 3 (Z012S, Android 7.0) and there was no issue about banner.

**Comment by rampara** [comment] 2018-02-01 22:42
Closing as duplicate of #572.

**Closed by rampara** 2018-02-01 22:42 UTC
Labels: P2, plugin bug
