### ISSUE TITLE
Can't add Banner Ads/Native as child of game Object or UI object

### ISSUE THREAD

**Issue by phamhphuc** [googleads/googleads-mobile-unity#383] opened 2017-03-28 01:34 UTC
As the native ads or banner ads in android native, when we initialize the ads, we can add parent of the ads but not in unity. I really want it so it will like it a part of my game for native ads

Do we have solution somewhere?

**Comment by rampara** [comment] 2017-03-29 00:30
As the ad objects in this plugin are not instances  of `GameObject`, they cannot be added as children to other `GameObject` objects. What functionality requires you to have the ad objects be children of other `GameObject` objects?

**Comment by phamhphuc** [comment] 2017-03-29 00:34
I want to implement the native ads in game like this:

The panel with 4 boxes in unity UI, 3 first boxes is 3 upgrade boxes and the 4th box is native ads. In this case I think user will think this ads is a part of the game.

**Comment by rampara** [comment] 2017-03-29 17:50
Currently, this plugin does not support ad assets that are Unity textures but we are looking into support of such a feature. Closing as duplicate of #146.

**Closed by rampara** 2017-03-29 17:50 UTC
Labels: support question
