### ISSUE TITLE
Game restart after reward ads finished 

### ISSUE THREAD

**Issue by Akashbhatt111** [googleads/googleads-mobile-unity#527] opened 2017-10-04 09:03 UTC
Game restart as soon as reward ad complete in unity admob.
i used chartboost and unity for mediation reward video.
even test ads behaves like this...
nothing is shown in logcat that i seems as cause of this...

**Comment by rampara** [comment] 2017-10-04 17:36
Closing as duplicate of #453.

**Closed by rampara** 2017-10-04 17:36 UTC
