### ISSUE TITLE
[GoogleMobileAds v3.3.0] Bottom banner is showing with a padding

### ISSUE THREAD

**Issue by duchanhleo** [googleads/googleads-mobile-unity#364] opened 2017-03-11 02:36 UTC
Hello,
I just replace v3.3.0 into my sample without any changes. It not show in bottom as below screen.
Are there any new code to show banner at bottom?
![screenshot](https://cloud.githubusercontent.com/assets/20719577/23819761/5a575fcc-063d-11e7-8e1f-a60fa35ce828.png)

**Comment by rampara** [comment] 2017-03-11 20:25
Strange, this issue should have been fixed in the latest version of the plugin (v3.3.0) and is now working correctly for me as shown below. 

![screencap](https://cloud.githubusercontent.com/assets/11047881/23826645/6c3265f8-0655-11e7-8117-8c984ad25002.png)

Can you try a quick test by integrating the plugin into a clean app, such as the sample included in this repo. If this issue still persists for you, can you let me know what device and Android OS version you're able to reproduce the issue on.

**Comment by rampara** [comment] 2017-05-08 20:16
Closing this issue due to non-response. Pleas re-open if this issue persists for you.

**Closed by rampara** 2017-05-08 20:16 UTC
Labels: support question
