### ISSUE TITLE
Smart banner height problem on Galaxy s6

### ISSUE THREAD

**Issue by chooy1210** [googleads/googleads-mobile-unity#443] opened 2017-06-10 14:58 UTC
I use this method for calculate smart banner height.

```
public int CalculateBannerHeight() {
		
		float screenDpi = Screen.dpi;
		if (Screen.height <= 400*Mathf.RoundToInt(screenDpi/160)) {
			return 32*Mathf.RoundToInt(screenDpi/160);
		} else if (Screen.height <= 720*Mathf.RoundToInt(screenDpi/160)) {
			return 50*Mathf.RoundToInt(screenDpi/160);
		} else {
			return 90*Mathf.RoundToInt(screenDpi/160);
		}

	}
```

Other phones that i have got right height but galaxy s6 ad height is long more than calculated value.
Does anyone have the same problem?
I use unity 5.6, admob 3.5.

**Comment by matie** [comment] 2017-06-13 19:06
Yes, this is since a long time. It is still there. We already got issues with it from Admob because of overlapping content. This still hasn't been solved. Hopefully they will have a look at it. It is only at the S6 (we have around 50 devices, also S3, S7 don't show this issue). S8 shows a similar issue as well in portrait mode I believe.

**Comment by rampara** [comment] 2017-06-13 22:00
I'm having trouble reproducing this issue with an S6 Edge. I compared the value returned by @chooy1210's code snippet to an Android call to `getHeight` on the `AdView` Android banner object and values match. 200 pixels in portrait and 128 pixels in landscape. What values do you see?

**Comment by rampara** [comment] 2017-07-14 20:58
Closing due to age of issue. If this issue persists, please re-open issue.

**Closed by rampara** 2017-07-14 20:58 UTC
Labels: support question
