### ISSUE TITLE
Banner Ad goes up above navigation bar after interstitial closed

### ISSUE THREAD

**Issue by rchallenger** [googleads/googleads-mobile-unity#434] opened 2017-06-02 08:28 UTC
As banner Ad created and placed at the bottom of screen it won't change its position if navigation bar will be shown. But as we show interstitial navigation bar appares and banner Ad  immediately goes up above navigation bar, this can cause unwanted content overlap. Application works in Portrait orientation. Built using Unity3D 5.3.4 and GoogleAds 3.5.0
Same trouble happens if we lock/unlock the device, take screenshot.
tested on Moto Z Play, Android 7.0.0.

Here is a video demonstrating that issue

https://drive.google.com/open?id=0B6u2VDj2GWUkcXdpS2dRT1Y3Slk

**Comment by rampara** [comment] 2017-06-02 18:05
It looks like since the interstitial isn't shown in immersive mode, the banner moves up to accommodate for the nav bar before moving to its normal position when re-entering immersive mode. Given how the plugin works, the system visibility flags for the banner shouldn't be changing so I'm not sure how this is happening. I can't seem to reproduce this behavior on Pixels or Nexus devices and don't have access to a Moto Z Play. Are you able to reproduce the issue on any other device?

**Comment by rchallenger** [comment] 2017-06-02 18:51
Actually I didn't try it, but will as soon as possible. In fact this issue
won't happen when I use GoogleAds 3.1.3.
Will write about other devices later.

Regards,
Dan Pavliuk

2 июн. 2017 г. 9:05 ПП пользователь "rampara" <notifications@github.com>
написал:

**Comment by rampara** [comment] 2017-06-05 15:02
Prior to v3.2.0, the plugin used had a different implementation for displaying banners and native express ads. If you're able to reproduce the issue on any other device it would help with getting to the bottom of what's causing it.

**Comment by rampara** [comment] 2017-07-13 21:08
Closing issue due to it's age. Please re-open if this issue persists for you.

**Closed by rampara** 2017-07-13 21:08 UTC
Labels: support question
