### ISSUE TITLE
Googleads 3.5 and Unity iOS Cloudbuild errors

### ISSUE THREAD

**Issue by dawuwu** [googleads/googleads-mobile-unity#446] opened 2017-06-13 06:59 UTC
Hello, I imported GoogleAdmobs 3.5 into my unity 5.6.1(cloud build) project and with Android everything works fine.

But iOS is throwing several errors:

[xcode] /BUILD_PATH/dev/temp.es3Sab/Libraries/Plugins/iOS/GADUNativeCustomTemplateAd.h:3:1: error: use of '@import' when modules are disabled
  [xcode] /BUILD_PATH/dev/temp.es3Sab/Libraries/Plugins/iOS/GADUNativeCustomTemplateAd.h:4:1: error: use of '@import' when modules are disabled
[xcode] /BUILD_PATH/dev/temp.es3Sab/Libraries/Plugins/iOS/GADUNativeCustomTemplateAd.h:14:30: error: unknown type name 'GADNativeCustomTemplateAd'; did you mean 'GADUNativeCustomTemplateAd'?
[xcode] /BUILD_PATH/dev/temp.es3Sab/Libraries/Plugins/iOS/GADUNativeCustomTemplateAd.h:17:29: error: expected a typ

**Comment by dawuwu** [comment] 2017-06-13 20:53
Okay this errors got fixed by importing the ios sdk.

But now I get the error:
module.modulemap:2:19: error: umbrella header 'GoogleMobileAds.h' not found 

and can't find a fix for it

**Comment by rampara** [comment] 2017-06-13 21:02
#333 has workarounds to get Cloud Build working but I'm also working on getting it working out of the box.

**Comment by rampara** [comment] 2017-06-13 21:02
Closing as duplicate of #333.

**Comment by dawuwu** [comment] 2017-06-13 21:18
my issue is not about cocoapods .
Its about:
module.modulemap:2:19: error: umbrella header 'GoogleMobileAds.h' not found

**Comment by rampara** [comment] 2017-06-13 22:04
@dawuwu are you including the GMA framework at the `Assets/Plugins/iOS` directory of your Unity project?

**Comment by dawuwu** [comment] 2017-06-13 22:21
1. Downloaded GMA for iOS from https://developers.google.com/admob/ios/download (Version 7.20)
2. Extracted and moved GoogleMobileAds.framework folder to Assets/Plugins/iOS
3. modified AdMobDependencies.cs like https://github.com/googleads/googleads-mobile-unity/issues/333 suggested
4. implemented XcodeProjectModifer  like https://github.com/googleads/googleads-mobile-unity/issues/333 suggested

**Comment by dawuwu** [comment] 2017-06-14 07:02
https://www.gamekon.com/?p=264
found this information about the issue, can someone confirm that?

**Comment by rampara** [comment] 2017-06-14 19:56
@dawuwu using the steps outlined in #333, I was able to get a Unity Cloud Build working with the sample app included in this repo. You can find the project at https://github.com/rampara/unity-cloud-build-test.

**Comment by rampara** [comment] 2017-06-14 19:59
![screenshot from 2017-06-14 12 59 22](https://user-images.githubusercontent.com/11047881/27152016-5960b7f8-5101-11e7-9d5b-4eb666630629.png)

**Comment by dawuwu** [comment] 2017-06-16 16:46
@rampara 

could you write down all steps you did? and what OS did you use? 

Today I will try a new clean project and your project with UCB

**Comment by rampara** [comment] 2017-06-17 00:12
Here are the steps I followed:

1. Download the [sample app](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) from this repo.
2. Import the GMA Unity plugin.
1. Download the GMA iOS SDK.
2. Extract and copy the framework file for the GMA iOS SDK to the `Assets/Plugins/iOS` directory of the Unity project.
1. Add the `XcodeProjectModifer` class (as outlined in #333) to the Unity project.
1. Edit the `AdMobDependencies.cs` file as outlined in #333.
1. Add the MainScene to the 'Scenes in Build'.
1. Uploaded project to GitHub repository (https://github.com/rampara/unity-cloud-build-test).
1. Started Unity Cloud Build from online Cloud Build console.

The project was created on a Mac OS machine with git used for version control.

**Comment by dawuwu** [comment] 2017-06-17 10:25
Okay, seems like ANY contact of the admob ios sdk with windows breaks it.

Downloaded your project to a windows machine, uploaded to git -> ucb error
Downloaded your project to a macosx machine, uploaded to git -> ucb success

Is there any chance to make the admob ios sdk windows compatible?

**Comment by dawuwu** [comment] 2017-06-19 18:37
@rampara 
sounds great and thanks for your help

**Closed** 2017-06-19 18:37 UTC
Labels: duplicate, plugin bug

**Comment by petersuwara** [comment] 2017-09-24 22:45
Any progress on this ? We're still using workarounds and it's become an ordeal. We may switch back to  just using Jenkins, which allows a rebuild with a workspace and cocoa pods.

All I am seeing is hacks and work arounds ? Anyone from Unity come to a real reliable fix ?

**Comment by rampara** [comment] 2017-09-26 21:26
@petersuwara Have you tried a Unity Cloud build with the latest version of this plugin (not using any of the PostProcessBuild workarounds) ?
