### ISSUE TITLE
java.lang.Error : FATAL EXCEPTION

### ISSUE THREAD

**Issue by adrean1980** [googleads/googleads-mobile-unity#960] opened 2019-07-02 06:42 UTC
hello
i just received this bug from users, the game only crash when install from play store and click open button for first time, but if i open the game after crash, it's works normal. also if i put the apk on device and install it's works normal

that's happen after i upgrade Google Mobile Ads from 3.16 to 3.18

Unity 2018.3.10
Google Mobile Ads Unity Plugin v3.18
Unity Monetization 3.1.0

this bug from users :
Caused by
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3081)
  at android.app.ActivityThread.-wrap18 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1602)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:173)
  at android.app.ActivityThread.main (ActivityThread.java:6523)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:938)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:828)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:380)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3076)

log from my device :
06-30 21:38:35.316 16300 16300 E AndroidRuntime: FATAL EXCEPTION: main
06-30 21:38:35.316 16300 16300 E AndroidRuntime: Process: xxxxxxx PID: 16300
06-30 21:38:35.316 16300 16300 E AndroidRuntime: java.lang.Error: FATAL EXCEPTION [main]
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 
06-30 21:38:35.316 16300 16300 E AndroidRuntime: Caused by: java.lang.RuntimeException: Unable to instantiate receiver com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver" on path: DexPathList[[zip file "/data/app/xxxxxxx/base.apk", zip file "/data/app/xxxxxxx/split_config.arm64_v8a.apk", zip file "/data/app/xxxxxxx/split_config.en.apk", zip file "/data/app/xxxxxxx/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/xxxxxxx/lib/arm64, /data/app/xxxxxxx/base.apk!/lib/arm64-v8a, /data/app/xxxxxxx/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/xxxxxxx/split_config.en.apk!/lib/arm64-v8a, /data/app/xxxxxxx/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3081)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(ActivityThread.java)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1602)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:173)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6523)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver" on path: DexPathList[[zip file "/data/app/xxxxxxx/base.apk", zip file "/data/app/xxxxxxx/split_config.arm64_v8a.apk", zip file "/data/app/xxxxxxx/split_config.en.apk", zip file "/data/app/xxxxxxx/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/xxxxxxx/lib/arm64, /data/app/xxxxxxx/base.apk!/lib/arm64-v8a, /data/app/xxxxxxx/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/xxxxxxx/split_config.en.apk!/lib/arm64-v8a, /data/app/xxxxxxx/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3076)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	... 8 more
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/xxxxxxx/split_config.arm64_v8a.apk
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFileNative(Native Method)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFile(DexFile.java:373)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:113)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:78)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:359)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 		at dalvik.system.DexPathList.makeElements(DexPathList.java:323)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:263)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 		at dalvik.system.DexPathList.<init>(DexPathList.java:126)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 		at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:46)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
06-30 21:38:35.316 16300 16300 E AndroidRuntime: 		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:520)
06-30 21:38:35.317 16300 16300 E AndroidRuntime: 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:553)
06-30 21:38:35.317 16300 16300 E AndroidRuntime: 		at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1925)
06-30 21:38:35.317 16300 16300 E AndroidRuntime: 		at android.app.LoadedApk.getResources(LoadedApk.java:766)
06-30 21:38:35.317 16300 16300 E AndroidRuntime: 		at android.app.ContextImpl.<init>(ContextImpl.java:2074)
06-30 21:38:35.317 16300 16300 E AndroidRuntime: 		at android.app.ContextImpl.createAppContext(ContextImpl.java:2019)
06-30 21:38:35.317 16300 16300 E AndroidRuntime: 		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5617)
06-30 21:38:35.317 16300 16300 E AndroidRuntime: 		at android.app.ActivityThread.-wrap2(ActivityThread.java)
06-30 21:38:35.317 16300 16300 E AndroidRuntime: 		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1577)
06-30 21:38:35.317 16300 16300 E AndroidRuntime: 		... 6 more
06-30 21:38:35.317 16300 16300 E AndroidRuntime: 	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/xxxxxxx/split_config.en.apk

**Comment by stowy** [comment] 2019-07-02 23:09
We have updated our quick start guide integration instructions
<https://developers.google.com/admob/android/quick-start#example_app-level_buildgradle_excerpt>
 and release notes  <https://developers.google.com/admob/android/rel-notes> to
address this issue.

Reproduced here:

To avoid a crash that occurs on first launch after app install from the
play store, this release requires publishers to declare additional
dependencies in their build.gradle:

*com.google.android.gms:play-services-measurement:17.0.0com.google.android.gms:play-services-measurement-sdk:17.0.0*

We will be releasing a fix for this issue next week due to the 4th July
holidays.

**Comment by rotter** [comment] 2019-07-10 15:55
Im having this problem on 3 different games in production

Any deadline for this fix?

**Comment by stowy** [comment] 2019-07-10 16:20
Android version 18.1.0 was released yesterday which automatically includes
these dependencies.

I am working on an update to the plugin for this release which will go out
this week.

**Comment by stowy** [comment] 2019-07-25 21:56
3.18.1 includes fix for this.

**Closed by stowy** 2019-07-25 21:56 UTC
