### ISSUE TITLE
Banner Ad is OK, but RewardBasedAd doesn't show

### ISSUE THREAD

**Issue by DanteAndroid** [googleads/googleads-mobile-unity#377] opened 2017-03-23 07:28 UTC
When I remove the test device option, it prints log warns me that I should add that test option. Of course, I tried the test ad units [here](https://github.com/googleads/googleads-mobile-unity/issues/374), it still does not work.

**Comment by rampara** [comment] 2017-03-23 16:18
@DanteAndroid even with the test option removed you're unable to request test rewarded video ads with the ad units specified it the linked issue?

**Comment by DanteAndroid** [comment] 2017-03-26 12:14
I've tried that, but it only works on bannerAd. The video ad never shows. Sometime internal error, sometime not fill error. I'm gonna crazy. Hope you can help me because it's my work.

**Comment by DanteAndroid** [comment] 2017-03-27 08:58
Any idea?

**Comment by NikolaTotev** [comment] 2017-03-29 15:28
I am having similar problems. Through some debugging with text on screen it says that the rewarded video is loaded but it never shows on screen.

**Comment by rampara** [comment] 2017-03-29 18:37
@DanteAndroid I plugged the ad unit you provided into the [sample application](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) and I'm able to request and display reward based video ads without issue.

@NikolaTotev can you provide the logcat output under the `Ads` tag when you run into this issue?

**Comment by NikolaTotev** [comment] 2017-03-29 20:12
@rampara  the problem is I debugged via on screen text by tracking which function was complete, I cant get any log to work on my emulator or phone :/

**Comment by rampara** [comment] 2017-03-30 01:24
Can you build stripped down sample app (using the sample app from this repo would well) that reproduces the problem and link the APK. I could access the logs myself which would help investigate the cause of the issue.

**Comment by DanteAndroid** [comment] 2017-03-30 01:56
[app-debug.zip](https://github.com/googleads/googleads-mobile-unity/files/880828/app-debug.zip) Change the suffix to `.apk`, If you need the whole demo project, let me know.

**Comment by NikolaTotev** [comment] 2017-03-30 11:51
@rampara I just applied the sample application example, and I put the script on the camera and it still won't work.
Below I posted the link with the scene that is causing trouble, at the moment I am just having problems with showing the ad.
The "Get coins" button is supposed to call the request ad function and show ad functions. But I'm not sure what the problem is. Thanks for the help in advance!
P.S sorry if the code isn't aligned properly, I just got into coding and I'm still learning.

https://github.com/NikolaTotev/-bug-with-rewarded-video-unity

**Comment by NikolaTotev** [comment] 2017-03-31 17:03
Hello @rampara and @DanteAndroid  I am now encountering a problem with interstitial ads as well. I am getting a 
NullReferenceException: Object reference not set to an instance of an object
AdMobScript.ShowIntersitital () (at Assets/Scripts/AdMobScript.cs:76) 
and this is line 76:

 private void ShowIntersitital()
    {
        if (interstitial.IsLoaded()) << line 76 is giving this error.
        {
            interstitial.Show();
        }
    }

**Comment by rampara** [comment] 2017-03-31 20:53
@NikolaTotev in the github repo you linked, you're using the iOS rewarded video test ad unit for both iOS and Android. On Android, you will not be able to successfully load an ad because of this. You should be using the test ad unit `ca-app-pub-3940256099942544/5224354917` for Android.

The interstitial NullReferenceException exception doesn't seem to map to the repo you linked as there's no interstitial code there. Are you running into this exception when running the sample app from this repo as well?

**Comment by NikolaTotev** [comment] 2017-03-31 21:03
@rampara  Ok  I replaced the ad Id with the one you linked and I'm still not getting a video to show. Could it be a problem in unity itself or where the script it placed?

**Comment by rampara** [comment] 2017-03-31 21:27
@NikolaTotev Did the ad successfully load (you received the `OnAdLoaded` event) ? If you received the `OnAdFailedToLoad` event, what was the reason for your failure?

**Comment by rampara** [comment] 2017-03-31 21:29
@DanteAndroid the APK you provided doesn't seem to be a Unity app. This issue tracker only for issues pertaining to this plugin.

**Comment by NikolaTotev** [comment] 2017-04-01 16:21
@rampara  The problem is that the ad is not loading at all, and at the moment I have not figured out the reason.

**Comment by NikolaTotev** [comment] 2017-04-01 17:28
@rampara  @DanteAndroid  Ok I have fixed it so the ad loads but now even though it says that it is showing in reality no video shows up on the screen.

**Comment by DanteAndroid** [comment] 2017-04-05 02:48
@rampara Actually since Unity plugin doesn't work I try to write code in the native app instead. As a result, I encountered **the same errors**. I read lots of articles and see many people meet this problem so I think it's not the code problem. No offense, but I think google's engineers should not make a mistake like this.

**Comment by rampara** [comment] 2017-04-05 04:54
@DanteAndroid this issue tracker is strictly for issues related to the Google Mobile Ads Unity plugin. For other Google Mobile Ads issues you can reach out on the [Google Mobile Ads support forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).

**Comment by rampara** [comment] 2017-04-05 04:55
@NikolaTotev can you link me a stripped down sample project that reproduces the issue you're experiencing. It will help me investigate what the root cause is.

**Comment by NikolaTotev** [comment] 2017-04-05 17:41
@rampara  I did  this is the scene causing problems 
https://github.com/NikolaTotev/-bug-with-rewarded-video-unity

 this is the stripped down version at the moment I'm working on another which will be done tomorrow. I'll send it when I finish

**Comment by rampara** [comment] 2017-04-06 01:22
Will investigate further one you provide a sample app I can build and run.

**Comment by MFGAME** [comment] 2017-04-07 05:40
I also have the same problem, RewardBasedAd can not appear, advertising requests are very many but not get ads.hoping to get help！

**Comment by rampara** [comment] 2017-04-10 18:40
@MFGAME replied to your issue at # #395.

**Comment by rampara** [comment] 2017-05-23 23:23
Closing this issue due to non-response. Please re-open if this issue persists for you.

**Closed by rampara** 2017-05-23 23:23 UTC
Labels: support question
