### ISSUE TITLE
Don't use shared Plugins folder

### ISSUE THREAD

**Issue by kevinfoley** [googleads/googleads-mobile-unity#442] opened 2017-06-09 19:49 UTC
The Google Ads plugin for Unity stores iOS- and Android-specific files in the shared "Plugins" folder in the project root. Since other plugins, including other Google plugins, also write files into the shared "Plugins" folder, it becomes a nightmare to manage and remove any plugins that write to this folder.

All platform-specific files should be stored in a "Plugins" folder _inside_ the GoogleMobileAds folder. See for example the Facebook Unity SDK

**Comment by rampara** [comment] 2017-06-14 20:01
Closing as duplicate of #411.

**Closed** 2017-06-14 20:01 UTC
Labels: duplicate, feature request
