### ISSUE TITLE
Firebase and AdMob in Unity game does not respond 

### ISSUE THREAD

**Issue by ctykaya** [googleads/googleads-mobile-unity#872] opened 2019-03-10 19:10 UTC
I am trying to implement firebase gps and abmob in my game. Firebase and gps works fine but when I import admob game does not respond any user input and freeze. Here is the log. I cannot figure it out what is the problem. Can any one help?

Here is the log file:
https://ufile.io/6snfi

**Comment by dominicdev** [comment] 2019-03-11 03:36
same issue here..also with the google play services..maybe because of the resolver

**Comment by UragayalaDeepika** [comment] 2019-08-01 00:45
@ctykaya Can you please share a minified sample app or code snippets of your implementation if you are able to reproduce the issue with the latest version of the SDK and plugin? 

Closing this for now. Please comment here if you still have this issue so that we can debug further.

**Closed by UragayalaDeepika** 2019-08-01 00:45 UTC
