### ISSUE TITLE
admob banner height issue 

### ISSUE THREAD

**Issue by guyhazi** [googleads/googleads-mobile-unity#734] opened 2018-07-26 15:36 UTC
in galaxy 9s+ show admob banner at bottom.
swipe bottom of screen for bottom navigation bar to pop up.
press the left button to view all open apps.
select the same app.
**banner will raise above the navigation bar and after few seconds/refresh will go down again.
the last stage doesnt happen all the time.

so the banner is higher then expected for few seconds, any idea how to handle this issue?

**Comment by rchallenger** [comment] 2018-07-30 08:01
Try playing with immersive mode. It helped me sometimes

**Comment by rampara** [comment] 2019-01-23 04:08
closing as duplicate of #687.

**Closed** 2019-01-23 04:08 UTC
Labels: P2, duplicate, plugin bug
